# -----------------------------------------------------------------------
# LIENS — KAEL
# -----------------------------------------------------------------------

default kael_link = 0

label KAEL_LINK_INTERACT:

    menu:
        "Passer du temps avec Kael ?"
        "Oui":
            $ choice = True
        "Non":
            $ choice = False

    if not choice:
        if last_room_label:
            jump expression last_room_label
        return

    if kael_link == 0:
        jump kael_link_1
    elif kael_link == 1:
        jump kael_link_2
    elif kael_link == 2:
        jump kael_link_3
    elif kael_link == 3:
        jump kael_link_4
    elif kael_link == 4:
        jump kael_link_5

    if last_room_label:
        jump expression last_room_label
    return

label kael_link_1:

    play music "music/bgm_unsaid_distance.mp3" fadein 1.0
    scene bg_maintenance at adaptive_fullscreen

    $ showP("kael", "neutre", 0.70)
    $ showP("noam", "reflexion", 0.24)

    "Kael est déjà là quand j'arrive."
    "L'atmosphère est stable, mais tendue sous la surface."
    "On prend quelques secondes avant de commencer à parler."
    noam "Tu observes tout avant de parler, pourquoi ?"
    kael "Je préfère comprendre la trajectoire avant d'intervenir."
    noam "Tu crois qu'on peut éviter les conflits ?"
    kael "On peut réduire les dégâts, rarement les empêcher."
    "Le silence revient brièvement, puis repart."
    noam "Tu t'effaces souvent, c'est volontaire ?"
    kael "Oui. Le retrait est parfois une discipline."
    noam "Tu envies les gens qui prennent de la place ?"
    kael "Parfois. Je l'admets sans fierté."
    "Le silence revient brièvement, puis repart."
    noam "Tu regrettes certaines décisions ?"
    kael "Oui. Le regret m'empêche de recommencer la même erreur."
    noam "Tu doutes de toi ?"
    kael "Souvent, mais le doute force la précision."
    "Le silence revient brièvement, puis repart."
    noam "Tu veux protéger qui en priorité ?"
    kael "Ceux qui ne voient pas le choc arriver."
    noam "Tu préfères écouter que convaincre ?"
    kael "Oui. Les silences disent souvent plus que les slogans."
    "Le silence revient brièvement, puis repart."
    noam "Tu observes tout avant de parler, pourquoi ?"
    kael "Je préfère comprendre la trajectoire avant d'intervenir."
    noam "Tu crois qu'on peut éviter les conflits ?"
    kael "On peut réduire les dégâts, rarement les empêcher."
    "Le silence revient brièvement, puis repart."
    noam "Tu t'effaces souvent, c'est volontaire ?"
    kael "Oui. Le retrait est parfois une discipline."
    noam "Tu envies les gens qui prennent de la place ?"
    kael "Parfois. Je l'admets sans fierté."
    "Le silence revient brièvement, puis repart."
    noam "Tu regrettes certaines décisions ?"
    kael "Oui. Le regret m'empêche de recommencer la même erreur."
    noam "Tu doutes de toi ?"
    kael "Souvent, mais le doute force la précision."
    "Le silence revient brièvement, puis repart."
    noam "Tu veux protéger qui en priorité ?"
    kael "Ceux qui ne voient pas le choc arriver."
    noam "Tu préfères écouter que convaincre ?"
    kael "Oui. Les silences disent souvent plus que les slogans."
    "Le silence revient brièvement, puis repart."
    noam "Tu observes tout avant de parler, pourquoi ?"
    kael "Je préfère comprendre la trajectoire avant d'intervenir."
    noam "Tu crois qu'on peut éviter les conflits ?"
    kael "On peut réduire les dégâts, rarement les empêcher."
    "Le silence revient brièvement, puis repart."
    noam "Tu t'effaces souvent, c'est volontaire ?"
    kael "Oui. Le retrait est parfois une discipline."
    noam "Tu envies les gens qui prennent de la place ?"
    kael "Parfois. Je l'admets sans fierté."
    "Le silence revient brièvement, puis repart."
    noam "Tu regrettes certaines décisions ?"
    kael "Oui. Le regret m'empêche de recommencer la même erreur."
    noam "Tu doutes de toi ?"
    kael "Souvent, mais le doute force la précision."
    "Le silence revient brièvement, puis repart."
    noam "Tu veux protéger qui en priorité ?"
    kael "Ceux qui ne voient pas le choc arriver."
    noam "Tu préfères écouter que convaincre ?"
    kael "Oui. Les silences disent souvent plus que les slogans."
    "Le silence revient brièvement, puis repart."
    noam "Tu observes tout avant de parler, pourquoi ?"
    kael "Je préfère comprendre la trajectoire avant d'intervenir."
    noam "Tu crois qu'on peut éviter les conflits ?"
    kael "On peut réduire les dégâts, rarement les empêcher."
    "Le silence revient brièvement, puis repart."
    noam "Tu t'effaces souvent, c'est volontaire ?"
    kael "Oui. Le retrait est parfois une discipline."
    noam "Tu envies les gens qui prennent de la place ?"
    kael "Parfois. Je l'admets sans fierté."
    "Le silence revient brièvement, puis repart."
    noam "Tu regrettes certaines décisions ?"
    kael "Oui. Le regret m'empêche de recommencer la même erreur."
    noam "Tu doutes de toi ?"
    kael "Souvent, mais le doute force la précision."
    "Le silence revient brièvement, puis repart."
    noam "Tu veux protéger qui en priorité ?"
    kael "Ceux qui ne voient pas le choc arriver."
    noam "Tu préfères écouter que convaincre ?"
    kael "Oui. Les silences disent souvent plus que les slogans."
    "Le silence revient brièvement, puis repart."
    noam "Tu observes tout avant de parler, pourquoi ?"
    kael "Je préfère comprendre la trajectoire avant d'intervenir."
    noam "Tu crois qu'on peut éviter les conflits ?"
    kael "On peut réduire les dégâts, rarement les empêcher."
    "Le silence revient brièvement, puis repart."
    noam "Tu t'effaces souvent, c'est volontaire ?"
    kael "Oui. Le retrait est parfois une discipline."
    noam "Tu envies les gens qui prennent de la place ?"
    kael "Parfois. Je l'admets sans fierté."
    "Le silence revient brièvement, puis repart."
    noam "Tu regrettes certaines décisions ?"
    kael "Oui. Le regret m'empêche de recommencer la même erreur."
    noam "Tu doutes de toi ?"
    kael "Souvent, mais le doute force la précision."
    "Le silence revient brièvement, puis repart."
    noam "Tu veux protéger qui en priorité ?"
    kael "Ceux qui ne voient pas le choc arriver."
    noam "Tu préfères écouter que convaincre ?"
    kael "Oui. Les silences disent souvent plus que les slogans."
    "Le silence revient brièvement, puis repart."
    kael "On devrait reprendre cette discussion plus tard."
    noam "D'accord."
    kael "Même dans un temps libre, on apprend des choses utiles."

    $ kael_link = 1

    jump FREE_TIME_END

label kael_link_2:

    play music "music/bgm_quiet_routine.mp3" fadein 1.0
    scene bg_observation at adaptive_fullscreen

    $ showP("kael", "neutre", 0.70)
    $ showP("noam", "reflexion", 0.24)

    "Kael est déjà là quand j'arrive."
    "L'atmosphère est stable, mais tendue sous la surface."
    "On prend quelques secondes avant de commencer à parler."
    noam "Tu observes tout avant de parler, pourquoi ?"
    kael "Je préfère comprendre la trajectoire avant d'intervenir."
    noam "Tu crois qu'on peut éviter les conflits ?"
    kael "On peut réduire les dégâts, rarement les empêcher."
    "Le silence revient brièvement, puis repart."
    noam "Tu t'effaces souvent, c'est volontaire ?"
    kael "Oui. Le retrait est parfois une discipline."
    noam "Tu envies les gens qui prennent de la place ?"
    kael "Parfois. Je l'admets sans fierté."
    "Le silence revient brièvement, puis repart."
    noam "Tu regrettes certaines décisions ?"
    kael "Oui. Le regret m'empêche de recommencer la même erreur."
    noam "Tu doutes de toi ?"
    kael "Souvent, mais le doute force la précision."
    "Le silence revient brièvement, puis repart."
    noam "Tu veux protéger qui en priorité ?"
    kael "Ceux qui ne voient pas le choc arriver."
    noam "Tu préfères écouter que convaincre ?"
    kael "Oui. Les silences disent souvent plus que les slogans."
    "Le silence revient brièvement, puis repart."
    noam "Tu observes tout avant de parler, pourquoi ?"
    kael "Je préfère comprendre la trajectoire avant d'intervenir."
    noam "Tu crois qu'on peut éviter les conflits ?"
    kael "On peut réduire les dégâts, rarement les empêcher."
    "Le silence revient brièvement, puis repart."
    noam "Tu t'effaces souvent, c'est volontaire ?"
    kael "Oui. Le retrait est parfois une discipline."
    noam "Tu envies les gens qui prennent de la place ?"
    kael "Parfois. Je l'admets sans fierté."
    "Le silence revient brièvement, puis repart."
    noam "Tu regrettes certaines décisions ?"
    kael "Oui. Le regret m'empêche de recommencer la même erreur."
    noam "Tu doutes de toi ?"
    kael "Souvent, mais le doute force la précision."
    "Le silence revient brièvement, puis repart."
    noam "Tu veux protéger qui en priorité ?"
    kael "Ceux qui ne voient pas le choc arriver."
    noam "Tu préfères écouter que convaincre ?"
    kael "Oui. Les silences disent souvent plus que les slogans."
    "Le silence revient brièvement, puis repart."
    noam "Tu observes tout avant de parler, pourquoi ?"
    kael "Je préfère comprendre la trajectoire avant d'intervenir."
    noam "Tu crois qu'on peut éviter les conflits ?"
    kael "On peut réduire les dégâts, rarement les empêcher."
    "Le silence revient brièvement, puis repart."
    noam "Tu t'effaces souvent, c'est volontaire ?"
    kael "Oui. Le retrait est parfois une discipline."
    noam "Tu envies les gens qui prennent de la place ?"
    kael "Parfois. Je l'admets sans fierté."
    "Le silence revient brièvement, puis repart."
    noam "Tu regrettes certaines décisions ?"
    kael "Oui. Le regret m'empêche de recommencer la même erreur."
    noam "Tu doutes de toi ?"
    kael "Souvent, mais le doute force la précision."
    "Le silence revient brièvement, puis repart."
    noam "Tu veux protéger qui en priorité ?"
    kael "Ceux qui ne voient pas le choc arriver."
    noam "Tu préfères écouter que convaincre ?"
    kael "Oui. Les silences disent souvent plus que les slogans."
    "Le silence revient brièvement, puis repart."
    noam "Tu observes tout avant de parler, pourquoi ?"
    kael "Je préfère comprendre la trajectoire avant d'intervenir."
    noam "Tu crois qu'on peut éviter les conflits ?"
    kael "On peut réduire les dégâts, rarement les empêcher."
    "Le silence revient brièvement, puis repart."
    noam "Tu t'effaces souvent, c'est volontaire ?"
    kael "Oui. Le retrait est parfois une discipline."
    noam "Tu envies les gens qui prennent de la place ?"
    kael "Parfois. Je l'admets sans fierté."
    "Le silence revient brièvement, puis repart."
    noam "Tu regrettes certaines décisions ?"
    kael "Oui. Le regret m'empêche de recommencer la même erreur."
    noam "Tu doutes de toi ?"
    kael "Souvent, mais le doute force la précision."
    "Le silence revient brièvement, puis repart."
    noam "Tu veux protéger qui en priorité ?"
    kael "Ceux qui ne voient pas le choc arriver."
    noam "Tu préfères écouter que convaincre ?"
    kael "Oui. Les silences disent souvent plus que les slogans."
    "Le silence revient brièvement, puis repart."
    noam "Tu observes tout avant de parler, pourquoi ?"
    kael "Je préfère comprendre la trajectoire avant d'intervenir."
    noam "Tu crois qu'on peut éviter les conflits ?"
    kael "On peut réduire les dégâts, rarement les empêcher."
    "Le silence revient brièvement, puis repart."
    noam "Tu t'effaces souvent, c'est volontaire ?"
    kael "Oui. Le retrait est parfois une discipline."
    noam "Tu envies les gens qui prennent de la place ?"
    kael "Parfois. Je l'admets sans fierté."
    "Le silence revient brièvement, puis repart."
    noam "Tu regrettes certaines décisions ?"
    kael "Oui. Le regret m'empêche de recommencer la même erreur."
    noam "Tu doutes de toi ?"
    kael "Souvent, mais le doute force la précision."
    "Le silence revient brièvement, puis repart."
    noam "Tu veux protéger qui en priorité ?"
    kael "Ceux qui ne voient pas le choc arriver."
    noam "Tu préfères écouter que convaincre ?"
    kael "Oui. Les silences disent souvent plus que les slogans."
    "Le silence revient brièvement, puis repart."
    kael "On devrait reprendre cette discussion plus tard."
    noam "D'accord."
    kael "Même dans un temps libre, on apprend des choses utiles."

    $ kael_link = 2

    jump FREE_TIME_END

label kael_link_3:

    play music "music/bgm_cold_metadata.mp3" fadein 1.0
    scene bg_archive at adaptive_fullscreen

    $ showP("kael", "neutre", 0.70)
    $ showP("noam", "reflexion", 0.24)

    "Kael est déjà là quand j'arrive."
    "L'atmosphère est stable, mais tendue sous la surface."
    "On prend quelques secondes avant de commencer à parler."
    noam "Tu observes tout avant de parler, pourquoi ?"
    kael "Je préfère comprendre la trajectoire avant d'intervenir."
    noam "Tu crois qu'on peut éviter les conflits ?"
    kael "On peut réduire les dégâts, rarement les empêcher."
    "Le silence revient brièvement, puis repart."
    noam "Tu t'effaces souvent, c'est volontaire ?"
    kael "Oui. Le retrait est parfois une discipline."
    noam "Tu envies les gens qui prennent de la place ?"
    kael "Parfois. Je l'admets sans fierté."
    "Le silence revient brièvement, puis repart."
    noam "Tu regrettes certaines décisions ?"
    kael "Oui. Le regret m'empêche de recommencer la même erreur."
    noam "Tu doutes de toi ?"
    kael "Souvent, mais le doute force la précision."
    "Le silence revient brièvement, puis repart."
    noam "Tu veux protéger qui en priorité ?"
    kael "Ceux qui ne voient pas le choc arriver."
    noam "Tu préfères écouter que convaincre ?"
    kael "Oui. Les silences disent souvent plus que les slogans."
    "Le silence revient brièvement, puis repart."
    noam "Tu observes tout avant de parler, pourquoi ?"
    kael "Je préfère comprendre la trajectoire avant d'intervenir."
    noam "Tu crois qu'on peut éviter les conflits ?"
    kael "On peut réduire les dégâts, rarement les empêcher."
    "Le silence revient brièvement, puis repart."
    noam "Tu t'effaces souvent, c'est volontaire ?"
    kael "Oui. Le retrait est parfois une discipline."
    noam "Tu envies les gens qui prennent de la place ?"
    kael "Parfois. Je l'admets sans fierté."
    "Le silence revient brièvement, puis repart."
    noam "Tu regrettes certaines décisions ?"
    kael "Oui. Le regret m'empêche de recommencer la même erreur."
    noam "Tu doutes de toi ?"
    kael "Souvent, mais le doute force la précision."
    "Le silence revient brièvement, puis repart."
    noam "Tu veux protéger qui en priorité ?"
    kael "Ceux qui ne voient pas le choc arriver."
    noam "Tu préfères écouter que convaincre ?"
    kael "Oui. Les silences disent souvent plus que les slogans."
    "Le silence revient brièvement, puis repart."
    noam "Tu observes tout avant de parler, pourquoi ?"
    kael "Je préfère comprendre la trajectoire avant d'intervenir."
    noam "Tu crois qu'on peut éviter les conflits ?"
    kael "On peut réduire les dégâts, rarement les empêcher."
    "Le silence revient brièvement, puis repart."
    noam "Tu t'effaces souvent, c'est volontaire ?"
    kael "Oui. Le retrait est parfois une discipline."
    noam "Tu envies les gens qui prennent de la place ?"
    kael "Parfois. Je l'admets sans fierté."
    "Le silence revient brièvement, puis repart."
    noam "Tu regrettes certaines décisions ?"
    kael "Oui. Le regret m'empêche de recommencer la même erreur."
    noam "Tu doutes de toi ?"
    kael "Souvent, mais le doute force la précision."
    "Le silence revient brièvement, puis repart."
    noam "Tu veux protéger qui en priorité ?"
    kael "Ceux qui ne voient pas le choc arriver."
    noam "Tu préfères écouter que convaincre ?"
    kael "Oui. Les silences disent souvent plus que les slogans."
    "Le silence revient brièvement, puis repart."
    noam "Tu observes tout avant de parler, pourquoi ?"
    kael "Je préfère comprendre la trajectoire avant d'intervenir."
    noam "Tu crois qu'on peut éviter les conflits ?"
    kael "On peut réduire les dégâts, rarement les empêcher."
    "Le silence revient brièvement, puis repart."
    noam "Tu t'effaces souvent, c'est volontaire ?"
    kael "Oui. Le retrait est parfois une discipline."
    noam "Tu envies les gens qui prennent de la place ?"
    kael "Parfois. Je l'admets sans fierté."
    "Le silence revient brièvement, puis repart."
    noam "Tu regrettes certaines décisions ?"
    kael "Oui. Le regret m'empêche de recommencer la même erreur."
    noam "Tu doutes de toi ?"
    kael "Souvent, mais le doute force la précision."
    "Le silence revient brièvement, puis repart."
    noam "Tu veux protéger qui en priorité ?"
    kael "Ceux qui ne voient pas le choc arriver."
    noam "Tu préfères écouter que convaincre ?"
    kael "Oui. Les silences disent souvent plus que les slogans."
    "Le silence revient brièvement, puis repart."
    noam "Tu observes tout avant de parler, pourquoi ?"
    kael "Je préfère comprendre la trajectoire avant d'intervenir."
    noam "Tu crois qu'on peut éviter les conflits ?"
    kael "On peut réduire les dégâts, rarement les empêcher."
    "Le silence revient brièvement, puis repart."
    noam "Tu t'effaces souvent, c'est volontaire ?"
    kael "Oui. Le retrait est parfois une discipline."
    noam "Tu envies les gens qui prennent de la place ?"
    kael "Parfois. Je l'admets sans fierté."
    "Le silence revient brièvement, puis repart."
    noam "Tu regrettes certaines décisions ?"
    kael "Oui. Le regret m'empêche de recommencer la même erreur."
    noam "Tu doutes de toi ?"
    kael "Souvent, mais le doute force la précision."
    "Le silence revient brièvement, puis repart."
    noam "Tu veux protéger qui en priorité ?"
    kael "Ceux qui ne voient pas le choc arriver."
    noam "Tu préfères écouter que convaincre ?"
    kael "Oui. Les silences disent souvent plus que les slogans."
    "Le silence revient brièvement, puis repart."
    kael "On devrait reprendre cette discussion plus tard."
    noam "D'accord."
    kael "Même dans un temps libre, on apprend des choses utiles."

    $ kael_link = 3

    jump FREE_TIME_END

label kael_link_4:

    play music "music/bgm_careful_wanting.mp3" fadein 1.0
    scene bg_repos at adaptive_fullscreen

    $ showP("kael", "neutre", 0.70)
    $ showP("noam", "reflexion", 0.24)

    "Kael est déjà là quand j'arrive."
    "L'atmosphère est stable, mais tendue sous la surface."
    "On prend quelques secondes avant de commencer à parler."
    noam "Tu observes tout avant de parler, pourquoi ?"
    kael "Je préfère comprendre la trajectoire avant d'intervenir."
    noam "Tu crois qu'on peut éviter les conflits ?"
    kael "On peut réduire les dégâts, rarement les empêcher."
    "Le silence revient brièvement, puis repart."
    noam "Tu t'effaces souvent, c'est volontaire ?"
    kael "Oui. Le retrait est parfois une discipline."
    noam "Tu envies les gens qui prennent de la place ?"
    kael "Parfois. Je l'admets sans fierté."
    "Le silence revient brièvement, puis repart."
    noam "Tu regrettes certaines décisions ?"
    kael "Oui. Le regret m'empêche de recommencer la même erreur."
    noam "Tu doutes de toi ?"
    kael "Souvent, mais le doute force la précision."
    "Le silence revient brièvement, puis repart."
    noam "Tu veux protéger qui en priorité ?"
    kael "Ceux qui ne voient pas le choc arriver."
    noam "Tu préfères écouter que convaincre ?"
    kael "Oui. Les silences disent souvent plus que les slogans."
    "Le silence revient brièvement, puis repart."
    noam "Tu observes tout avant de parler, pourquoi ?"
    kael "Je préfère comprendre la trajectoire avant d'intervenir."
    noam "Tu crois qu'on peut éviter les conflits ?"
    kael "On peut réduire les dégâts, rarement les empêcher."
    "Le silence revient brièvement, puis repart."
    noam "Tu t'effaces souvent, c'est volontaire ?"
    kael "Oui. Le retrait est parfois une discipline."
    noam "Tu envies les gens qui prennent de la place ?"
    kael "Parfois. Je l'admets sans fierté."
    "Le silence revient brièvement, puis repart."
    noam "Tu regrettes certaines décisions ?"
    kael "Oui. Le regret m'empêche de recommencer la même erreur."
    noam "Tu doutes de toi ?"
    kael "Souvent, mais le doute force la précision."
    "Le silence revient brièvement, puis repart."
    noam "Tu veux protéger qui en priorité ?"
    kael "Ceux qui ne voient pas le choc arriver."
    noam "Tu préfères écouter que convaincre ?"
    kael "Oui. Les silences disent souvent plus que les slogans."
    "Le silence revient brièvement, puis repart."
    noam "Tu observes tout avant de parler, pourquoi ?"
    kael "Je préfère comprendre la trajectoire avant d'intervenir."
    noam "Tu crois qu'on peut éviter les conflits ?"
    kael "On peut réduire les dégâts, rarement les empêcher."
    "Le silence revient brièvement, puis repart."
    noam "Tu t'effaces souvent, c'est volontaire ?"
    kael "Oui. Le retrait est parfois une discipline."
    noam "Tu envies les gens qui prennent de la place ?"
    kael "Parfois. Je l'admets sans fierté."
    "Le silence revient brièvement, puis repart."
    noam "Tu regrettes certaines décisions ?"
    kael "Oui. Le regret m'empêche de recommencer la même erreur."
    noam "Tu doutes de toi ?"
    kael "Souvent, mais le doute force la précision."
    "Le silence revient brièvement, puis repart."
    noam "Tu veux protéger qui en priorité ?"
    kael "Ceux qui ne voient pas le choc arriver."
    noam "Tu préfères écouter que convaincre ?"
    kael "Oui. Les silences disent souvent plus que les slogans."
    "Le silence revient brièvement, puis repart."
    noam "Tu observes tout avant de parler, pourquoi ?"
    kael "Je préfère comprendre la trajectoire avant d'intervenir."
    noam "Tu crois qu'on peut éviter les conflits ?"
    kael "On peut réduire les dégâts, rarement les empêcher."
    "Le silence revient brièvement, puis repart."
    noam "Tu t'effaces souvent, c'est volontaire ?"
    kael "Oui. Le retrait est parfois une discipline."
    noam "Tu envies les gens qui prennent de la place ?"
    kael "Parfois. Je l'admets sans fierté."
    "Le silence revient brièvement, puis repart."
    noam "Tu regrettes certaines décisions ?"
    kael "Oui. Le regret m'empêche de recommencer la même erreur."
    noam "Tu doutes de toi ?"
    kael "Souvent, mais le doute force la précision."
    "Le silence revient brièvement, puis repart."
    noam "Tu veux protéger qui en priorité ?"
    kael "Ceux qui ne voient pas le choc arriver."
    noam "Tu préfères écouter que convaincre ?"
    kael "Oui. Les silences disent souvent plus que les slogans."
    "Le silence revient brièvement, puis repart."
    noam "Tu observes tout avant de parler, pourquoi ?"
    kael "Je préfère comprendre la trajectoire avant d'intervenir."
    noam "Tu crois qu'on peut éviter les conflits ?"
    kael "On peut réduire les dégâts, rarement les empêcher."
    "Le silence revient brièvement, puis repart."
    noam "Tu t'effaces souvent, c'est volontaire ?"
    kael "Oui. Le retrait est parfois une discipline."
    noam "Tu envies les gens qui prennent de la place ?"
    kael "Parfois. Je l'admets sans fierté."
    "Le silence revient brièvement, puis repart."
    noam "Tu regrettes certaines décisions ?"
    kael "Oui. Le regret m'empêche de recommencer la même erreur."
    noam "Tu doutes de toi ?"
    kael "Souvent, mais le doute force la précision."
    "Le silence revient brièvement, puis repart."
    noam "Tu veux protéger qui en priorité ?"
    kael "Ceux qui ne voient pas le choc arriver."
    noam "Tu préfères écouter que convaincre ?"
    kael "Oui. Les silences disent souvent plus que les slogans."
    "Le silence revient brièvement, puis repart."
    kael "On devrait reprendre cette discussion plus tard."
    noam "D'accord."
    kael "Même dans un temps libre, on apprend des choses utiles."

    $ kael_link = 4

    jump FREE_TIME_END

label kael_link_5:

    play music "music/bgm_quiet_routine.mp3" fadein 1.0
    scene bg_conclave at adaptive_fullscreen

    $ showP("kael", "neutre", 0.70)
    $ showP("noam", "reflexion", 0.24)

    "Kael est déjà là quand j'arrive."
    "L'atmosphère est stable, mais tendue sous la surface."
    "On prend quelques secondes avant de commencer à parler."
    noam "Tu observes tout avant de parler, pourquoi ?"
    kael "Je préfère comprendre la trajectoire avant d'intervenir."
    noam "Tu crois qu'on peut éviter les conflits ?"
    kael "On peut réduire les dégâts, rarement les empêcher."
    "Le silence revient brièvement, puis repart."
    noam "Tu t'effaces souvent, c'est volontaire ?"
    kael "Oui. Le retrait est parfois une discipline."
    noam "Tu envies les gens qui prennent de la place ?"
    kael "Parfois. Je l'admets sans fierté."
    "Le silence revient brièvement, puis repart."
    noam "Tu regrettes certaines décisions ?"
    kael "Oui. Le regret m'empêche de recommencer la même erreur."
    noam "Tu doutes de toi ?"
    kael "Souvent, mais le doute force la précision."
    "Le silence revient brièvement, puis repart."
    noam "Tu veux protéger qui en priorité ?"
    kael "Ceux qui ne voient pas le choc arriver."
    noam "Tu préfères écouter que convaincre ?"
    kael "Oui. Les silences disent souvent plus que les slogans."
    "Le silence revient brièvement, puis repart."
    noam "Tu observes tout avant de parler, pourquoi ?"
    kael "Je préfère comprendre la trajectoire avant d'intervenir."
    noam "Tu crois qu'on peut éviter les conflits ?"
    kael "On peut réduire les dégâts, rarement les empêcher."
    "Le silence revient brièvement, puis repart."
    noam "Tu t'effaces souvent, c'est volontaire ?"
    kael "Oui. Le retrait est parfois une discipline."
    noam "Tu envies les gens qui prennent de la place ?"
    kael "Parfois. Je l'admets sans fierté."
    "Le silence revient brièvement, puis repart."
    noam "Tu regrettes certaines décisions ?"
    kael "Oui. Le regret m'empêche de recommencer la même erreur."
    noam "Tu doutes de toi ?"
    kael "Souvent, mais le doute force la précision."
    "Le silence revient brièvement, puis repart."
    noam "Tu veux protéger qui en priorité ?"
    kael "Ceux qui ne voient pas le choc arriver."
    noam "Tu préfères écouter que convaincre ?"
    kael "Oui. Les silences disent souvent plus que les slogans."
    "Le silence revient brièvement, puis repart."
    noam "Tu observes tout avant de parler, pourquoi ?"
    kael "Je préfère comprendre la trajectoire avant d'intervenir."
    noam "Tu crois qu'on peut éviter les conflits ?"
    kael "On peut réduire les dégâts, rarement les empêcher."
    "Le silence revient brièvement, puis repart."
    noam "Tu t'effaces souvent, c'est volontaire ?"
    kael "Oui. Le retrait est parfois une discipline."
    noam "Tu envies les gens qui prennent de la place ?"
    kael "Parfois. Je l'admets sans fierté."
    "Le silence revient brièvement, puis repart."
    noam "Tu regrettes certaines décisions ?"
    kael "Oui. Le regret m'empêche de recommencer la même erreur."
    noam "Tu doutes de toi ?"
    kael "Souvent, mais le doute force la précision."
    "Le silence revient brièvement, puis repart."
    noam "Tu veux protéger qui en priorité ?"
    kael "Ceux qui ne voient pas le choc arriver."
    noam "Tu préfères écouter que convaincre ?"
    kael "Oui. Les silences disent souvent plus que les slogans."
    "Le silence revient brièvement, puis repart."
    noam "Tu observes tout avant de parler, pourquoi ?"
    kael "Je préfère comprendre la trajectoire avant d'intervenir."
    noam "Tu crois qu'on peut éviter les conflits ?"
    kael "On peut réduire les dégâts, rarement les empêcher."
    "Le silence revient brièvement, puis repart."
    noam "Tu t'effaces souvent, c'est volontaire ?"
    kael "Oui. Le retrait est parfois une discipline."
    noam "Tu envies les gens qui prennent de la place ?"
    kael "Parfois. Je l'admets sans fierté."
    "Le silence revient brièvement, puis repart."
    noam "Tu regrettes certaines décisions ?"
    kael "Oui. Le regret m'empêche de recommencer la même erreur."
    noam "Tu doutes de toi ?"
    kael "Souvent, mais le doute force la précision."
    "Le silence revient brièvement, puis repart."
    noam "Tu veux protéger qui en priorité ?"
    kael "Ceux qui ne voient pas le choc arriver."
    noam "Tu préfères écouter que convaincre ?"
    kael "Oui. Les silences disent souvent plus que les slogans."
    "Le silence revient brièvement, puis repart."
    noam "Tu observes tout avant de parler, pourquoi ?"
    kael "Je préfère comprendre la trajectoire avant d'intervenir."
    noam "Tu crois qu'on peut éviter les conflits ?"
    kael "On peut réduire les dégâts, rarement les empêcher."
    "Le silence revient brièvement, puis repart."
    noam "Tu t'effaces souvent, c'est volontaire ?"
    kael "Oui. Le retrait est parfois une discipline."
    noam "Tu envies les gens qui prennent de la place ?"
    kael "Parfois. Je l'admets sans fierté."
    "Le silence revient brièvement, puis repart."
    noam "Tu regrettes certaines décisions ?"
    kael "Oui. Le regret m'empêche de recommencer la même erreur."
    noam "Tu doutes de toi ?"
    kael "Souvent, mais le doute force la précision."
    "Le silence revient brièvement, puis repart."
    noam "Tu veux protéger qui en priorité ?"
    kael "Ceux qui ne voient pas le choc arriver."
    noam "Tu préfères écouter que convaincre ?"
    kael "Oui. Les silences disent souvent plus que les slogans."
    "Le silence revient brièvement, puis repart."
    kael "On devrait reprendre cette discussion plus tard."
    noam "D'accord."
    kael "Même dans un temps libre, on apprend des choses utiles."

    $ kael_link = 5

    jump FREE_TIME_END

