# -----------------------------------------------------------------------
# LIENS — NYRA
# -----------------------------------------------------------------------

default nyra_link = 0

label NYRA_LINK_INTERACT:

    menu:
        "Passer du temps avec Nyra ?"
        "Oui":
            $ choice = True
        "Non":
            $ choice = False

    if not choice:
        if last_room_label:
            jump expression last_room_label
        return

    if nyra_link == 0:
        jump nyra_link_1
    elif nyra_link == 1:
        jump nyra_link_2
    elif nyra_link == 2:
        jump nyra_link_3
    elif nyra_link == 3:
        jump nyra_link_4
    elif nyra_link == 4:
        jump nyra_link_5

    if last_room_label:
        jump expression last_room_label
    return

label nyra_link_1:

    play music "music/bgm_soft_neon_morning.mp3" fadein 1.0
    scene bg_conclave at adaptive_fullscreen

    $ showP("nyra", "neutre", 0.70)
    $ showP("noam", "reflexion", 0.24)

    "Nyra est déjà là quand j'arrive."
    "L'atmosphère est stable, mais tendue sous la surface."
    "On prend quelques secondes avant de commencer à parler."
    noam "Tu planifies toujours autant ?"
    nyra "Oui. L'improvisation pure est une dette qui finit toujours par tomber."
    noam "Tu vois vraiment tout comme une partie ?"
    nyra "Je vois des rapports de force, puis je choisis mon angle."
    "Le silence revient brièvement, puis repart."
    noam "Tu as peur de perdre ?"
    nyra "Oui. C'est mon moteur et mon défaut."
    noam "Tu fais confiance aux alliances ?"
    nyra "Je fais confiance aux intérêts alignés, jamais aux promesses seules."
    "Le silence revient brièvement, puis repart."
    noam "Tu défends des idées ou des positions ?"
    nyra "Parfois une idée, parfois la meilleure position du moment."
    noam "Tu peux sacrifier quoi pour gagner ?"
    nyra "Le confort, la réputation, parfois même ma place."
    "Le silence revient brièvement, puis repart."
    noam "Tu te reposes quand ?"
    nyra "Quand j'ai sécurisé deux coups d'avance."
    noam "Tu peux lâcher le contrôle ?"
    nyra "Je peux, mais seulement si le risque est cartographié."
    "Le silence revient brièvement, puis repart."
    noam "Tu planifies toujours autant ?"
    nyra "Oui. L'improvisation pure est une dette qui finit toujours par tomber."
    noam "Tu vois vraiment tout comme une partie ?"
    nyra "Je vois des rapports de force, puis je choisis mon angle."
    "Le silence revient brièvement, puis repart."
    noam "Tu as peur de perdre ?"
    nyra "Oui. C'est mon moteur et mon défaut."
    noam "Tu fais confiance aux alliances ?"
    nyra "Je fais confiance aux intérêts alignés, jamais aux promesses seules."
    "Le silence revient brièvement, puis repart."
    noam "Tu défends des idées ou des positions ?"
    nyra "Parfois une idée, parfois la meilleure position du moment."
    noam "Tu peux sacrifier quoi pour gagner ?"
    nyra "Le confort, la réputation, parfois même ma place."
    "Le silence revient brièvement, puis repart."
    noam "Tu te reposes quand ?"
    nyra "Quand j'ai sécurisé deux coups d'avance."
    noam "Tu peux lâcher le contrôle ?"
    nyra "Je peux, mais seulement si le risque est cartographié."
    "Le silence revient brièvement, puis repart."
    noam "Tu planifies toujours autant ?"
    nyra "Oui. L'improvisation pure est une dette qui finit toujours par tomber."
    noam "Tu vois vraiment tout comme une partie ?"
    nyra "Je vois des rapports de force, puis je choisis mon angle."
    "Le silence revient brièvement, puis repart."
    noam "Tu as peur de perdre ?"
    nyra "Oui. C'est mon moteur et mon défaut."
    noam "Tu fais confiance aux alliances ?"
    nyra "Je fais confiance aux intérêts alignés, jamais aux promesses seules."
    "Le silence revient brièvement, puis repart."
    noam "Tu défends des idées ou des positions ?"
    nyra "Parfois une idée, parfois la meilleure position du moment."
    noam "Tu peux sacrifier quoi pour gagner ?"
    nyra "Le confort, la réputation, parfois même ma place."
    "Le silence revient brièvement, puis repart."
    noam "Tu te reposes quand ?"
    nyra "Quand j'ai sécurisé deux coups d'avance."
    noam "Tu peux lâcher le contrôle ?"
    nyra "Je peux, mais seulement si le risque est cartographié."
    "Le silence revient brièvement, puis repart."
    noam "Tu planifies toujours autant ?"
    nyra "Oui. L'improvisation pure est une dette qui finit toujours par tomber."
    noam "Tu vois vraiment tout comme une partie ?"
    nyra "Je vois des rapports de force, puis je choisis mon angle."
    "Le silence revient brièvement, puis repart."
    noam "Tu as peur de perdre ?"
    nyra "Oui. C'est mon moteur et mon défaut."
    noam "Tu fais confiance aux alliances ?"
    nyra "Je fais confiance aux intérêts alignés, jamais aux promesses seules."
    "Le silence revient brièvement, puis repart."
    noam "Tu défends des idées ou des positions ?"
    nyra "Parfois une idée, parfois la meilleure position du moment."
    noam "Tu peux sacrifier quoi pour gagner ?"
    nyra "Le confort, la réputation, parfois même ma place."
    "Le silence revient brièvement, puis repart."
    noam "Tu te reposes quand ?"
    nyra "Quand j'ai sécurisé deux coups d'avance."
    noam "Tu peux lâcher le contrôle ?"
    nyra "Je peux, mais seulement si le risque est cartographié."
    "Le silence revient brièvement, puis repart."
    noam "Tu planifies toujours autant ?"
    nyra "Oui. L'improvisation pure est une dette qui finit toujours par tomber."
    noam "Tu vois vraiment tout comme une partie ?"
    nyra "Je vois des rapports de force, puis je choisis mon angle."
    "Le silence revient brièvement, puis repart."
    noam "Tu as peur de perdre ?"
    nyra "Oui. C'est mon moteur et mon défaut."
    noam "Tu fais confiance aux alliances ?"
    nyra "Je fais confiance aux intérêts alignés, jamais aux promesses seules."
    "Le silence revient brièvement, puis repart."
    noam "Tu défends des idées ou des positions ?"
    nyra "Parfois une idée, parfois la meilleure position du moment."
    noam "Tu peux sacrifier quoi pour gagner ?"
    nyra "Le confort, la réputation, parfois même ma place."
    "Le silence revient brièvement, puis repart."
    noam "Tu te reposes quand ?"
    nyra "Quand j'ai sécurisé deux coups d'avance."
    noam "Tu peux lâcher le contrôle ?"
    nyra "Je peux, mais seulement si le risque est cartographié."
    "Le silence revient brièvement, puis repart."
    nyra "On devrait reprendre cette discussion plus tard."
    noam "D'accord."
    nyra "Même dans un temps libre, on apprend des choses utiles."

    $ nyra_link = 1

    jump FREE_TIME_END

label nyra_link_2:

    play music "music/bgm_quiet_routine.mp3" fadein 1.0
    scene bg_observation at adaptive_fullscreen

    $ showP("nyra", "neutre", 0.70)
    $ showP("noam", "reflexion", 0.24)

    "Nyra est déjà là quand j'arrive."
    "L'atmosphère est stable, mais tendue sous la surface."
    "On prend quelques secondes avant de commencer à parler."
    noam "Tu planifies toujours autant ?"
    nyra "Oui. L'improvisation pure est une dette qui finit toujours par tomber."
    noam "Tu vois vraiment tout comme une partie ?"
    nyra "Je vois des rapports de force, puis je choisis mon angle."
    "Le silence revient brièvement, puis repart."
    noam "Tu as peur de perdre ?"
    nyra "Oui. C'est mon moteur et mon défaut."
    noam "Tu fais confiance aux alliances ?"
    nyra "Je fais confiance aux intérêts alignés, jamais aux promesses seules."
    "Le silence revient brièvement, puis repart."
    noam "Tu défends des idées ou des positions ?"
    nyra "Parfois une idée, parfois la meilleure position du moment."
    noam "Tu peux sacrifier quoi pour gagner ?"
    nyra "Le confort, la réputation, parfois même ma place."
    "Le silence revient brièvement, puis repart."
    noam "Tu te reposes quand ?"
    nyra "Quand j'ai sécurisé deux coups d'avance."
    noam "Tu peux lâcher le contrôle ?"
    nyra "Je peux, mais seulement si le risque est cartographié."
    "Le silence revient brièvement, puis repart."
    noam "Tu planifies toujours autant ?"
    nyra "Oui. L'improvisation pure est une dette qui finit toujours par tomber."
    noam "Tu vois vraiment tout comme une partie ?"
    nyra "Je vois des rapports de force, puis je choisis mon angle."
    "Le silence revient brièvement, puis repart."
    noam "Tu as peur de perdre ?"
    nyra "Oui. C'est mon moteur et mon défaut."
    noam "Tu fais confiance aux alliances ?"
    nyra "Je fais confiance aux intérêts alignés, jamais aux promesses seules."
    "Le silence revient brièvement, puis repart."
    noam "Tu défends des idées ou des positions ?"
    nyra "Parfois une idée, parfois la meilleure position du moment."
    noam "Tu peux sacrifier quoi pour gagner ?"
    nyra "Le confort, la réputation, parfois même ma place."
    "Le silence revient brièvement, puis repart."
    noam "Tu te reposes quand ?"
    nyra "Quand j'ai sécurisé deux coups d'avance."
    noam "Tu peux lâcher le contrôle ?"
    nyra "Je peux, mais seulement si le risque est cartographié."
    "Le silence revient brièvement, puis repart."
    noam "Tu planifies toujours autant ?"
    nyra "Oui. L'improvisation pure est une dette qui finit toujours par tomber."
    noam "Tu vois vraiment tout comme une partie ?"
    nyra "Je vois des rapports de force, puis je choisis mon angle."
    "Le silence revient brièvement, puis repart."
    noam "Tu as peur de perdre ?"
    nyra "Oui. C'est mon moteur et mon défaut."
    noam "Tu fais confiance aux alliances ?"
    nyra "Je fais confiance aux intérêts alignés, jamais aux promesses seules."
    "Le silence revient brièvement, puis repart."
    noam "Tu défends des idées ou des positions ?"
    nyra "Parfois une idée, parfois la meilleure position du moment."
    noam "Tu peux sacrifier quoi pour gagner ?"
    nyra "Le confort, la réputation, parfois même ma place."
    "Le silence revient brièvement, puis repart."
    noam "Tu te reposes quand ?"
    nyra "Quand j'ai sécurisé deux coups d'avance."
    noam "Tu peux lâcher le contrôle ?"
    nyra "Je peux, mais seulement si le risque est cartographié."
    "Le silence revient brièvement, puis repart."
    noam "Tu planifies toujours autant ?"
    nyra "Oui. L'improvisation pure est une dette qui finit toujours par tomber."
    noam "Tu vois vraiment tout comme une partie ?"
    nyra "Je vois des rapports de force, puis je choisis mon angle."
    "Le silence revient brièvement, puis repart."
    noam "Tu as peur de perdre ?"
    nyra "Oui. C'est mon moteur et mon défaut."
    noam "Tu fais confiance aux alliances ?"
    nyra "Je fais confiance aux intérêts alignés, jamais aux promesses seules."
    "Le silence revient brièvement, puis repart."
    noam "Tu défends des idées ou des positions ?"
    nyra "Parfois une idée, parfois la meilleure position du moment."
    noam "Tu peux sacrifier quoi pour gagner ?"
    nyra "Le confort, la réputation, parfois même ma place."
    "Le silence revient brièvement, puis repart."
    noam "Tu te reposes quand ?"
    nyra "Quand j'ai sécurisé deux coups d'avance."
    noam "Tu peux lâcher le contrôle ?"
    nyra "Je peux, mais seulement si le risque est cartographié."
    "Le silence revient brièvement, puis repart."
    noam "Tu planifies toujours autant ?"
    nyra "Oui. L'improvisation pure est une dette qui finit toujours par tomber."
    noam "Tu vois vraiment tout comme une partie ?"
    nyra "Je vois des rapports de force, puis je choisis mon angle."
    "Le silence revient brièvement, puis repart."
    noam "Tu as peur de perdre ?"
    nyra "Oui. C'est mon moteur et mon défaut."
    noam "Tu fais confiance aux alliances ?"
    nyra "Je fais confiance aux intérêts alignés, jamais aux promesses seules."
    "Le silence revient brièvement, puis repart."
    noam "Tu défends des idées ou des positions ?"
    nyra "Parfois une idée, parfois la meilleure position du moment."
    noam "Tu peux sacrifier quoi pour gagner ?"
    nyra "Le confort, la réputation, parfois même ma place."
    "Le silence revient brièvement, puis repart."
    noam "Tu te reposes quand ?"
    nyra "Quand j'ai sécurisé deux coups d'avance."
    noam "Tu peux lâcher le contrôle ?"
    nyra "Je peux, mais seulement si le risque est cartographié."
    "Le silence revient brièvement, puis repart."
    nyra "On devrait reprendre cette discussion plus tard."
    noam "D'accord."
    nyra "Même dans un temps libre, on apprend des choses utiles."

    $ nyra_link = 2

    jump FREE_TIME_END

label nyra_link_3:

    play music "music/bgm_careful_wanting.mp3" fadein 1.0
    scene bg_archive at adaptive_fullscreen

    $ showP("nyra", "neutre", 0.70)
    $ showP("noam", "reflexion", 0.24)

    "Nyra est déjà là quand j'arrive."
    "L'atmosphère est stable, mais tendue sous la surface."
    "On prend quelques secondes avant de commencer à parler."
    noam "Tu planifies toujours autant ?"
    nyra "Oui. L'improvisation pure est une dette qui finit toujours par tomber."
    noam "Tu vois vraiment tout comme une partie ?"
    nyra "Je vois des rapports de force, puis je choisis mon angle."
    "Le silence revient brièvement, puis repart."
    noam "Tu as peur de perdre ?"
    nyra "Oui. C'est mon moteur et mon défaut."
    noam "Tu fais confiance aux alliances ?"
    nyra "Je fais confiance aux intérêts alignés, jamais aux promesses seules."
    "Le silence revient brièvement, puis repart."
    noam "Tu défends des idées ou des positions ?"
    nyra "Parfois une idée, parfois la meilleure position du moment."
    noam "Tu peux sacrifier quoi pour gagner ?"
    nyra "Le confort, la réputation, parfois même ma place."
    "Le silence revient brièvement, puis repart."
    noam "Tu te reposes quand ?"
    nyra "Quand j'ai sécurisé deux coups d'avance."
    noam "Tu peux lâcher le contrôle ?"
    nyra "Je peux, mais seulement si le risque est cartographié."
    "Le silence revient brièvement, puis repart."
    noam "Tu planifies toujours autant ?"
    nyra "Oui. L'improvisation pure est une dette qui finit toujours par tomber."
    noam "Tu vois vraiment tout comme une partie ?"
    nyra "Je vois des rapports de force, puis je choisis mon angle."
    "Le silence revient brièvement, puis repart."
    noam "Tu as peur de perdre ?"
    nyra "Oui. C'est mon moteur et mon défaut."
    noam "Tu fais confiance aux alliances ?"
    nyra "Je fais confiance aux intérêts alignés, jamais aux promesses seules."
    "Le silence revient brièvement, puis repart."
    noam "Tu défends des idées ou des positions ?"
    nyra "Parfois une idée, parfois la meilleure position du moment."
    noam "Tu peux sacrifier quoi pour gagner ?"
    nyra "Le confort, la réputation, parfois même ma place."
    "Le silence revient brièvement, puis repart."
    noam "Tu te reposes quand ?"
    nyra "Quand j'ai sécurisé deux coups d'avance."
    noam "Tu peux lâcher le contrôle ?"
    nyra "Je peux, mais seulement si le risque est cartographié."
    "Le silence revient brièvement, puis repart."
    noam "Tu planifies toujours autant ?"
    nyra "Oui. L'improvisation pure est une dette qui finit toujours par tomber."
    noam "Tu vois vraiment tout comme une partie ?"
    nyra "Je vois des rapports de force, puis je choisis mon angle."
    "Le silence revient brièvement, puis repart."
    noam "Tu as peur de perdre ?"
    nyra "Oui. C'est mon moteur et mon défaut."
    noam "Tu fais confiance aux alliances ?"
    nyra "Je fais confiance aux intérêts alignés, jamais aux promesses seules."
    "Le silence revient brièvement, puis repart."
    noam "Tu défends des idées ou des positions ?"
    nyra "Parfois une idée, parfois la meilleure position du moment."
    noam "Tu peux sacrifier quoi pour gagner ?"
    nyra "Le confort, la réputation, parfois même ma place."
    "Le silence revient brièvement, puis repart."
    noam "Tu te reposes quand ?"
    nyra "Quand j'ai sécurisé deux coups d'avance."
    noam "Tu peux lâcher le contrôle ?"
    nyra "Je peux, mais seulement si le risque est cartographié."
    "Le silence revient brièvement, puis repart."
    noam "Tu planifies toujours autant ?"
    nyra "Oui. L'improvisation pure est une dette qui finit toujours par tomber."
    noam "Tu vois vraiment tout comme une partie ?"
    nyra "Je vois des rapports de force, puis je choisis mon angle."
    "Le silence revient brièvement, puis repart."
    noam "Tu as peur de perdre ?"
    nyra "Oui. C'est mon moteur et mon défaut."
    noam "Tu fais confiance aux alliances ?"
    nyra "Je fais confiance aux intérêts alignés, jamais aux promesses seules."
    "Le silence revient brièvement, puis repart."
    noam "Tu défends des idées ou des positions ?"
    nyra "Parfois une idée, parfois la meilleure position du moment."
    noam "Tu peux sacrifier quoi pour gagner ?"
    nyra "Le confort, la réputation, parfois même ma place."
    "Le silence revient brièvement, puis repart."
    noam "Tu te reposes quand ?"
    nyra "Quand j'ai sécurisé deux coups d'avance."
    noam "Tu peux lâcher le contrôle ?"
    nyra "Je peux, mais seulement si le risque est cartographié."
    "Le silence revient brièvement, puis repart."
    noam "Tu planifies toujours autant ?"
    nyra "Oui. L'improvisation pure est une dette qui finit toujours par tomber."
    noam "Tu vois vraiment tout comme une partie ?"
    nyra "Je vois des rapports de force, puis je choisis mon angle."
    "Le silence revient brièvement, puis repart."
    noam "Tu as peur de perdre ?"
    nyra "Oui. C'est mon moteur et mon défaut."
    noam "Tu fais confiance aux alliances ?"
    nyra "Je fais confiance aux intérêts alignés, jamais aux promesses seules."
    "Le silence revient brièvement, puis repart."
    noam "Tu défends des idées ou des positions ?"
    nyra "Parfois une idée, parfois la meilleure position du moment."
    noam "Tu peux sacrifier quoi pour gagner ?"
    nyra "Le confort, la réputation, parfois même ma place."
    "Le silence revient brièvement, puis repart."
    noam "Tu te reposes quand ?"
    nyra "Quand j'ai sécurisé deux coups d'avance."
    noam "Tu peux lâcher le contrôle ?"
    nyra "Je peux, mais seulement si le risque est cartographié."
    "Le silence revient brièvement, puis repart."
    nyra "On devrait reprendre cette discussion plus tard."
    noam "D'accord."
    nyra "Même dans un temps libre, on apprend des choses utiles."

    $ nyra_link = 3

    jump FREE_TIME_END

label nyra_link_4:

    play music "music/bgm_unsaid_distance.mp3" fadein 1.0
    scene bg_repos at adaptive_fullscreen

    $ showP("nyra", "neutre", 0.70)
    $ showP("noam", "reflexion", 0.24)

    "Nyra est déjà là quand j'arrive."
    "L'atmosphère est stable, mais tendue sous la surface."
    "On prend quelques secondes avant de commencer à parler."
    noam "Tu planifies toujours autant ?"
    nyra "Oui. L'improvisation pure est une dette qui finit toujours par tomber."
    noam "Tu vois vraiment tout comme une partie ?"
    nyra "Je vois des rapports de force, puis je choisis mon angle."
    "Le silence revient brièvement, puis repart."
    noam "Tu as peur de perdre ?"
    nyra "Oui. C'est mon moteur et mon défaut."
    noam "Tu fais confiance aux alliances ?"
    nyra "Je fais confiance aux intérêts alignés, jamais aux promesses seules."
    "Le silence revient brièvement, puis repart."
    noam "Tu défends des idées ou des positions ?"
    nyra "Parfois une idée, parfois la meilleure position du moment."
    noam "Tu peux sacrifier quoi pour gagner ?"
    nyra "Le confort, la réputation, parfois même ma place."
    "Le silence revient brièvement, puis repart."
    noam "Tu te reposes quand ?"
    nyra "Quand j'ai sécurisé deux coups d'avance."
    noam "Tu peux lâcher le contrôle ?"
    nyra "Je peux, mais seulement si le risque est cartographié."
    "Le silence revient brièvement, puis repart."
    noam "Tu planifies toujours autant ?"
    nyra "Oui. L'improvisation pure est une dette qui finit toujours par tomber."
    noam "Tu vois vraiment tout comme une partie ?"
    nyra "Je vois des rapports de force, puis je choisis mon angle."
    "Le silence revient brièvement, puis repart."
    noam "Tu as peur de perdre ?"
    nyra "Oui. C'est mon moteur et mon défaut."
    noam "Tu fais confiance aux alliances ?"
    nyra "Je fais confiance aux intérêts alignés, jamais aux promesses seules."
    "Le silence revient brièvement, puis repart."
    noam "Tu défends des idées ou des positions ?"
    nyra "Parfois une idée, parfois la meilleure position du moment."
    noam "Tu peux sacrifier quoi pour gagner ?"
    nyra "Le confort, la réputation, parfois même ma place."
    "Le silence revient brièvement, puis repart."
    noam "Tu te reposes quand ?"
    nyra "Quand j'ai sécurisé deux coups d'avance."
    noam "Tu peux lâcher le contrôle ?"
    nyra "Je peux, mais seulement si le risque est cartographié."
    "Le silence revient brièvement, puis repart."
    noam "Tu planifies toujours autant ?"
    nyra "Oui. L'improvisation pure est une dette qui finit toujours par tomber."
    noam "Tu vois vraiment tout comme une partie ?"
    nyra "Je vois des rapports de force, puis je choisis mon angle."
    "Le silence revient brièvement, puis repart."
    noam "Tu as peur de perdre ?"
    nyra "Oui. C'est mon moteur et mon défaut."
    noam "Tu fais confiance aux alliances ?"
    nyra "Je fais confiance aux intérêts alignés, jamais aux promesses seules."
    "Le silence revient brièvement, puis repart."
    noam "Tu défends des idées ou des positions ?"
    nyra "Parfois une idée, parfois la meilleure position du moment."
    noam "Tu peux sacrifier quoi pour gagner ?"
    nyra "Le confort, la réputation, parfois même ma place."
    "Le silence revient brièvement, puis repart."
    noam "Tu te reposes quand ?"
    nyra "Quand j'ai sécurisé deux coups d'avance."
    noam "Tu peux lâcher le contrôle ?"
    nyra "Je peux, mais seulement si le risque est cartographié."
    "Le silence revient brièvement, puis repart."
    noam "Tu planifies toujours autant ?"
    nyra "Oui. L'improvisation pure est une dette qui finit toujours par tomber."
    noam "Tu vois vraiment tout comme une partie ?"
    nyra "Je vois des rapports de force, puis je choisis mon angle."
    "Le silence revient brièvement, puis repart."
    noam "Tu as peur de perdre ?"
    nyra "Oui. C'est mon moteur et mon défaut."
    noam "Tu fais confiance aux alliances ?"
    nyra "Je fais confiance aux intérêts alignés, jamais aux promesses seules."
    "Le silence revient brièvement, puis repart."
    noam "Tu défends des idées ou des positions ?"
    nyra "Parfois une idée, parfois la meilleure position du moment."
    noam "Tu peux sacrifier quoi pour gagner ?"
    nyra "Le confort, la réputation, parfois même ma place."
    "Le silence revient brièvement, puis repart."
    noam "Tu te reposes quand ?"
    nyra "Quand j'ai sécurisé deux coups d'avance."
    noam "Tu peux lâcher le contrôle ?"
    nyra "Je peux, mais seulement si le risque est cartographié."
    "Le silence revient brièvement, puis repart."
    noam "Tu planifies toujours autant ?"
    nyra "Oui. L'improvisation pure est une dette qui finit toujours par tomber."
    noam "Tu vois vraiment tout comme une partie ?"
    nyra "Je vois des rapports de force, puis je choisis mon angle."
    "Le silence revient brièvement, puis repart."
    noam "Tu as peur de perdre ?"
    nyra "Oui. C'est mon moteur et mon défaut."
    noam "Tu fais confiance aux alliances ?"
    nyra "Je fais confiance aux intérêts alignés, jamais aux promesses seules."
    "Le silence revient brièvement, puis repart."
    noam "Tu défends des idées ou des positions ?"
    nyra "Parfois une idée, parfois la meilleure position du moment."
    noam "Tu peux sacrifier quoi pour gagner ?"
    nyra "Le confort, la réputation, parfois même ma place."
    "Le silence revient brièvement, puis repart."
    noam "Tu te reposes quand ?"
    nyra "Quand j'ai sécurisé deux coups d'avance."
    noam "Tu peux lâcher le contrôle ?"
    nyra "Je peux, mais seulement si le risque est cartographié."
    "Le silence revient brièvement, puis repart."
    nyra "On devrait reprendre cette discussion plus tard."
    noam "D'accord."
    nyra "Même dans un temps libre, on apprend des choses utiles."

    $ nyra_link = 4

    jump FREE_TIME_END

label nyra_link_5:

    play music "music/bgm_soft_neon_morning.mp3" fadein 1.0
    scene bg_cafeteria at adaptive_fullscreen

    $ showP("nyra", "neutre", 0.70)
    $ showP("noam", "reflexion", 0.24)

    "Nyra est déjà là quand j'arrive."
    "L'atmosphère est stable, mais tendue sous la surface."
    "On prend quelques secondes avant de commencer à parler."
    noam "Tu planifies toujours autant ?"
    nyra "Oui. L'improvisation pure est une dette qui finit toujours par tomber."
    noam "Tu vois vraiment tout comme une partie ?"
    nyra "Je vois des rapports de force, puis je choisis mon angle."
    "Le silence revient brièvement, puis repart."
    noam "Tu as peur de perdre ?"
    nyra "Oui. C'est mon moteur et mon défaut."
    noam "Tu fais confiance aux alliances ?"
    nyra "Je fais confiance aux intérêts alignés, jamais aux promesses seules."
    "Le silence revient brièvement, puis repart."
    noam "Tu défends des idées ou des positions ?"
    nyra "Parfois une idée, parfois la meilleure position du moment."
    noam "Tu peux sacrifier quoi pour gagner ?"
    nyra "Le confort, la réputation, parfois même ma place."
    "Le silence revient brièvement, puis repart."
    noam "Tu te reposes quand ?"
    nyra "Quand j'ai sécurisé deux coups d'avance."
    noam "Tu peux lâcher le contrôle ?"
    nyra "Je peux, mais seulement si le risque est cartographié."
    "Le silence revient brièvement, puis repart."
    noam "Tu planifies toujours autant ?"
    nyra "Oui. L'improvisation pure est une dette qui finit toujours par tomber."
    noam "Tu vois vraiment tout comme une partie ?"
    nyra "Je vois des rapports de force, puis je choisis mon angle."
    "Le silence revient brièvement, puis repart."
    noam "Tu as peur de perdre ?"
    nyra "Oui. C'est mon moteur et mon défaut."
    noam "Tu fais confiance aux alliances ?"
    nyra "Je fais confiance aux intérêts alignés, jamais aux promesses seules."
    "Le silence revient brièvement, puis repart."
    noam "Tu défends des idées ou des positions ?"
    nyra "Parfois une idée, parfois la meilleure position du moment."
    noam "Tu peux sacrifier quoi pour gagner ?"
    nyra "Le confort, la réputation, parfois même ma place."
    "Le silence revient brièvement, puis repart."
    noam "Tu te reposes quand ?"
    nyra "Quand j'ai sécurisé deux coups d'avance."
    noam "Tu peux lâcher le contrôle ?"
    nyra "Je peux, mais seulement si le risque est cartographié."
    "Le silence revient brièvement, puis repart."
    noam "Tu planifies toujours autant ?"
    nyra "Oui. L'improvisation pure est une dette qui finit toujours par tomber."
    noam "Tu vois vraiment tout comme une partie ?"
    nyra "Je vois des rapports de force, puis je choisis mon angle."
    "Le silence revient brièvement, puis repart."
    noam "Tu as peur de perdre ?"
    nyra "Oui. C'est mon moteur et mon défaut."
    noam "Tu fais confiance aux alliances ?"
    nyra "Je fais confiance aux intérêts alignés, jamais aux promesses seules."
    "Le silence revient brièvement, puis repart."
    noam "Tu défends des idées ou des positions ?"
    nyra "Parfois une idée, parfois la meilleure position du moment."
    noam "Tu peux sacrifier quoi pour gagner ?"
    nyra "Le confort, la réputation, parfois même ma place."
    "Le silence revient brièvement, puis repart."
    noam "Tu te reposes quand ?"
    nyra "Quand j'ai sécurisé deux coups d'avance."
    noam "Tu peux lâcher le contrôle ?"
    nyra "Je peux, mais seulement si le risque est cartographié."
    "Le silence revient brièvement, puis repart."
    noam "Tu planifies toujours autant ?"
    nyra "Oui. L'improvisation pure est une dette qui finit toujours par tomber."
    noam "Tu vois vraiment tout comme une partie ?"
    nyra "Je vois des rapports de force, puis je choisis mon angle."
    "Le silence revient brièvement, puis repart."
    noam "Tu as peur de perdre ?"
    nyra "Oui. C'est mon moteur et mon défaut."
    noam "Tu fais confiance aux alliances ?"
    nyra "Je fais confiance aux intérêts alignés, jamais aux promesses seules."
    "Le silence revient brièvement, puis repart."
    noam "Tu défends des idées ou des positions ?"
    nyra "Parfois une idée, parfois la meilleure position du moment."
    noam "Tu peux sacrifier quoi pour gagner ?"
    nyra "Le confort, la réputation, parfois même ma place."
    "Le silence revient brièvement, puis repart."
    noam "Tu te reposes quand ?"
    nyra "Quand j'ai sécurisé deux coups d'avance."
    noam "Tu peux lâcher le contrôle ?"
    nyra "Je peux, mais seulement si le risque est cartographié."
    "Le silence revient brièvement, puis repart."
    noam "Tu planifies toujours autant ?"
    nyra "Oui. L'improvisation pure est une dette qui finit toujours par tomber."
    noam "Tu vois vraiment tout comme une partie ?"
    nyra "Je vois des rapports de force, puis je choisis mon angle."
    "Le silence revient brièvement, puis repart."
    noam "Tu as peur de perdre ?"
    nyra "Oui. C'est mon moteur et mon défaut."
    noam "Tu fais confiance aux alliances ?"
    nyra "Je fais confiance aux intérêts alignés, jamais aux promesses seules."
    "Le silence revient brièvement, puis repart."
    noam "Tu défends des idées ou des positions ?"
    nyra "Parfois une idée, parfois la meilleure position du moment."
    noam "Tu peux sacrifier quoi pour gagner ?"
    nyra "Le confort, la réputation, parfois même ma place."
    "Le silence revient brièvement, puis repart."
    noam "Tu te reposes quand ?"
    nyra "Quand j'ai sécurisé deux coups d'avance."
    noam "Tu peux lâcher le contrôle ?"
    nyra "Je peux, mais seulement si le risque est cartographié."
    "Le silence revient brièvement, puis repart."
    nyra "On devrait reprendre cette discussion plus tard."
    noam "D'accord."
    nyra "Même dans un temps libre, on apprend des choses utiles."

    $ nyra_link = 5

    jump FREE_TIME_END

