# -----------------------------------------------------------------------
# LIENS — RYN
# -----------------------------------------------------------------------

default ryn_link = 0

label RYN_LINK_INTERACT:

    menu:
        "Passer du temps avec Ryn ?"
        "Oui":
            $ choice = True
        "Non":
            $ choice = False

    if not choice:
        if last_room_label:
            jump expression last_room_label
        return

    if ryn_link == 0:
        jump ryn_link_1
    elif ryn_link == 1:
        jump ryn_link_2
    elif ryn_link == 2:
        jump ryn_link_3
    elif ryn_link == 3:
        jump ryn_link_4
    elif ryn_link == 4:
        jump ryn_link_5

    if last_room_label:
        jump expression last_room_label
    return

label ryn_link_1:

    play music "music/bgm_careful_wanting.mp3" fadein 1.0
    scene bg_gymnase at adaptive_fullscreen

    $ showP("ryn", "neutre", 0.70)
    $ showP("noam", "reflexion", 0.24)

    "Ryn est déjà là quand j'arrive."
    "L'atmosphère est stable, mais tendue sous la surface."
    "On prend quelques secondes avant de commencer à parler."
    noam "Pourquoi tu montes direct dans les tours ?"
    ryn "Parce que quand tu tardes, ça explose dans ta gueule."
    noam "Tu penses encore à LIMEN ?"
    ryn "Tout le temps. Je peux l'insulter et la défendre dans la même phrase."
    "Le silence revient brièvement, puis repart."
    noam "Tu fais confiance à qui ici ?"
    ryn "À ceux qui restent quand ça devient sale."
    noam "Tu te reposes jamais ?"
    ryn "Le repos, je le prends quand tout tient encore debout."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu parles aussi frontalement ?"
    ryn "Parce que les mots polis ne bouchent pas une fuite."
    noam "Tu te sens seul parfois ?"
    ryn "Ouais. Mais je préfère être seul que lâche."
    "Le silence revient brièvement, puis repart."
    noam "Tu regrettes la frontière ?"
    ryn "Je regrette les gens, pas la peur permanente."
    noam "Tu veux quoi pour la suite ?"
    ryn "Je veux que les miens sortent vivants de ce merdier."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu montes direct dans les tours ?"
    ryn "Parce que quand tu tardes, ça explose dans ta gueule."
    noam "Tu penses encore à LIMEN ?"
    ryn "Tout le temps. Je peux l'insulter et la défendre dans la même phrase."
    "Le silence revient brièvement, puis repart."
    noam "Tu fais confiance à qui ici ?"
    ryn "À ceux qui restent quand ça devient sale."
    noam "Tu te reposes jamais ?"
    ryn "Le repos, je le prends quand tout tient encore debout."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu parles aussi frontalement ?"
    ryn "Parce que les mots polis ne bouchent pas une fuite."
    noam "Tu te sens seul parfois ?"
    ryn "Ouais. Mais je préfère être seul que lâche."
    "Le silence revient brièvement, puis repart."
    noam "Tu regrettes la frontière ?"
    ryn "Je regrette les gens, pas la peur permanente."
    noam "Tu veux quoi pour la suite ?"
    ryn "Je veux que les miens sortent vivants de ce merdier."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu montes direct dans les tours ?"
    ryn "Parce que quand tu tardes, ça explose dans ta gueule."
    noam "Tu penses encore à LIMEN ?"
    ryn "Tout le temps. Je peux l'insulter et la défendre dans la même phrase."
    "Le silence revient brièvement, puis repart."
    noam "Tu fais confiance à qui ici ?"
    ryn "À ceux qui restent quand ça devient sale."
    noam "Tu te reposes jamais ?"
    ryn "Le repos, je le prends quand tout tient encore debout."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu parles aussi frontalement ?"
    ryn "Parce que les mots polis ne bouchent pas une fuite."
    noam "Tu te sens seul parfois ?"
    ryn "Ouais. Mais je préfère être seul que lâche."
    "Le silence revient brièvement, puis repart."
    noam "Tu regrettes la frontière ?"
    ryn "Je regrette les gens, pas la peur permanente."
    noam "Tu veux quoi pour la suite ?"
    ryn "Je veux que les miens sortent vivants de ce merdier."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu montes direct dans les tours ?"
    ryn "Parce que quand tu tardes, ça explose dans ta gueule."
    noam "Tu penses encore à LIMEN ?"
    ryn "Tout le temps. Je peux l'insulter et la défendre dans la même phrase."
    "Le silence revient brièvement, puis repart."
    noam "Tu fais confiance à qui ici ?"
    ryn "À ceux qui restent quand ça devient sale."
    noam "Tu te reposes jamais ?"
    ryn "Le repos, je le prends quand tout tient encore debout."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu parles aussi frontalement ?"
    ryn "Parce que les mots polis ne bouchent pas une fuite."
    noam "Tu te sens seul parfois ?"
    ryn "Ouais. Mais je préfère être seul que lâche."
    "Le silence revient brièvement, puis repart."
    noam "Tu regrettes la frontière ?"
    ryn "Je regrette les gens, pas la peur permanente."
    noam "Tu veux quoi pour la suite ?"
    ryn "Je veux que les miens sortent vivants de ce merdier."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu montes direct dans les tours ?"
    ryn "Parce que quand tu tardes, ça explose dans ta gueule."
    noam "Tu penses encore à LIMEN ?"
    ryn "Tout le temps. Je peux l'insulter et la défendre dans la même phrase."
    "Le silence revient brièvement, puis repart."
    noam "Tu fais confiance à qui ici ?"
    ryn "À ceux qui restent quand ça devient sale."
    noam "Tu te reposes jamais ?"
    ryn "Le repos, je le prends quand tout tient encore debout."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu parles aussi frontalement ?"
    ryn "Parce que les mots polis ne bouchent pas une fuite."
    noam "Tu te sens seul parfois ?"
    ryn "Ouais. Mais je préfère être seul que lâche."
    "Le silence revient brièvement, puis repart."
    noam "Tu regrettes la frontière ?"
    ryn "Je regrette les gens, pas la peur permanente."
    noam "Tu veux quoi pour la suite ?"
    ryn "Je veux que les miens sortent vivants de ce merdier."
    "Le silence revient brièvement, puis repart."
    ryn "On devrait reprendre cette discussion plus tard."
    noam "D'accord."
    ryn "Même dans un temps libre, on apprend des choses utiles."

    $ ryn_link = 1

    jump FREE_TIME_END

label ryn_link_2:

    play music "music/bgm_unsaid_distance.mp3" fadein 1.0
    scene bg_maintenance at adaptive_fullscreen

    $ showP("ryn", "neutre", 0.70)
    $ showP("noam", "reflexion", 0.24)

    "Ryn est déjà là quand j'arrive."
    "L'atmosphère est stable, mais tendue sous la surface."
    "On prend quelques secondes avant de commencer à parler."
    noam "Pourquoi tu montes direct dans les tours ?"
    ryn "Parce que quand tu tardes, ça explose dans ta gueule."
    noam "Tu penses encore à LIMEN ?"
    ryn "Tout le temps. Je peux l'insulter et la défendre dans la même phrase."
    "Le silence revient brièvement, puis repart."
    noam "Tu fais confiance à qui ici ?"
    ryn "À ceux qui restent quand ça devient sale."
    noam "Tu te reposes jamais ?"
    ryn "Le repos, je le prends quand tout tient encore debout."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu parles aussi frontalement ?"
    ryn "Parce que les mots polis ne bouchent pas une fuite."
    noam "Tu te sens seul parfois ?"
    ryn "Ouais. Mais je préfère être seul que lâche."
    "Le silence revient brièvement, puis repart."
    noam "Tu regrettes la frontière ?"
    ryn "Je regrette les gens, pas la peur permanente."
    noam "Tu veux quoi pour la suite ?"
    ryn "Je veux que les miens sortent vivants de ce merdier."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu montes direct dans les tours ?"
    ryn "Parce que quand tu tardes, ça explose dans ta gueule."
    noam "Tu penses encore à LIMEN ?"
    ryn "Tout le temps. Je peux l'insulter et la défendre dans la même phrase."
    "Le silence revient brièvement, puis repart."
    noam "Tu fais confiance à qui ici ?"
    ryn "À ceux qui restent quand ça devient sale."
    noam "Tu te reposes jamais ?"
    ryn "Le repos, je le prends quand tout tient encore debout."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu parles aussi frontalement ?"
    ryn "Parce que les mots polis ne bouchent pas une fuite."
    noam "Tu te sens seul parfois ?"
    ryn "Ouais. Mais je préfère être seul que lâche."
    "Le silence revient brièvement, puis repart."
    noam "Tu regrettes la frontière ?"
    ryn "Je regrette les gens, pas la peur permanente."
    noam "Tu veux quoi pour la suite ?"
    ryn "Je veux que les miens sortent vivants de ce merdier."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu montes direct dans les tours ?"
    ryn "Parce que quand tu tardes, ça explose dans ta gueule."
    noam "Tu penses encore à LIMEN ?"
    ryn "Tout le temps. Je peux l'insulter et la défendre dans la même phrase."
    "Le silence revient brièvement, puis repart."
    noam "Tu fais confiance à qui ici ?"
    ryn "À ceux qui restent quand ça devient sale."
    noam "Tu te reposes jamais ?"
    ryn "Le repos, je le prends quand tout tient encore debout."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu parles aussi frontalement ?"
    ryn "Parce que les mots polis ne bouchent pas une fuite."
    noam "Tu te sens seul parfois ?"
    ryn "Ouais. Mais je préfère être seul que lâche."
    "Le silence revient brièvement, puis repart."
    noam "Tu regrettes la frontière ?"
    ryn "Je regrette les gens, pas la peur permanente."
    noam "Tu veux quoi pour la suite ?"
    ryn "Je veux que les miens sortent vivants de ce merdier."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu montes direct dans les tours ?"
    ryn "Parce que quand tu tardes, ça explose dans ta gueule."
    noam "Tu penses encore à LIMEN ?"
    ryn "Tout le temps. Je peux l'insulter et la défendre dans la même phrase."
    "Le silence revient brièvement, puis repart."
    noam "Tu fais confiance à qui ici ?"
    ryn "À ceux qui restent quand ça devient sale."
    noam "Tu te reposes jamais ?"
    ryn "Le repos, je le prends quand tout tient encore debout."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu parles aussi frontalement ?"
    ryn "Parce que les mots polis ne bouchent pas une fuite."
    noam "Tu te sens seul parfois ?"
    ryn "Ouais. Mais je préfère être seul que lâche."
    "Le silence revient brièvement, puis repart."
    noam "Tu regrettes la frontière ?"
    ryn "Je regrette les gens, pas la peur permanente."
    noam "Tu veux quoi pour la suite ?"
    ryn "Je veux que les miens sortent vivants de ce merdier."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu montes direct dans les tours ?"
    ryn "Parce que quand tu tardes, ça explose dans ta gueule."
    noam "Tu penses encore à LIMEN ?"
    ryn "Tout le temps. Je peux l'insulter et la défendre dans la même phrase."
    "Le silence revient brièvement, puis repart."
    noam "Tu fais confiance à qui ici ?"
    ryn "À ceux qui restent quand ça devient sale."
    noam "Tu te reposes jamais ?"
    ryn "Le repos, je le prends quand tout tient encore debout."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu parles aussi frontalement ?"
    ryn "Parce que les mots polis ne bouchent pas une fuite."
    noam "Tu te sens seul parfois ?"
    ryn "Ouais. Mais je préfère être seul que lâche."
    "Le silence revient brièvement, puis repart."
    noam "Tu regrettes la frontière ?"
    ryn "Je regrette les gens, pas la peur permanente."
    noam "Tu veux quoi pour la suite ?"
    ryn "Je veux que les miens sortent vivants de ce merdier."
    "Le silence revient brièvement, puis repart."
    ryn "On devrait reprendre cette discussion plus tard."
    noam "D'accord."
    ryn "Même dans un temps libre, on apprend des choses utiles."

    $ ryn_link = 2

    jump FREE_TIME_END

label ryn_link_3:

    play music "music/bgm_cold_metadata.mp3" fadein 1.0
    scene bg_sas at adaptive_fullscreen

    $ showP("ryn", "neutre", 0.70)
    $ showP("noam", "reflexion", 0.24)

    "Ryn est déjà là quand j'arrive."
    "L'atmosphère est stable, mais tendue sous la surface."
    "On prend quelques secondes avant de commencer à parler."
    noam "Pourquoi tu montes direct dans les tours ?"
    ryn "Parce que quand tu tardes, ça explose dans ta gueule."
    noam "Tu penses encore à LIMEN ?"
    ryn "Tout le temps. Je peux l'insulter et la défendre dans la même phrase."
    "Le silence revient brièvement, puis repart."
    noam "Tu fais confiance à qui ici ?"
    ryn "À ceux qui restent quand ça devient sale."
    noam "Tu te reposes jamais ?"
    ryn "Le repos, je le prends quand tout tient encore debout."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu parles aussi frontalement ?"
    ryn "Parce que les mots polis ne bouchent pas une fuite."
    noam "Tu te sens seul parfois ?"
    ryn "Ouais. Mais je préfère être seul que lâche."
    "Le silence revient brièvement, puis repart."
    noam "Tu regrettes la frontière ?"
    ryn "Je regrette les gens, pas la peur permanente."
    noam "Tu veux quoi pour la suite ?"
    ryn "Je veux que les miens sortent vivants de ce merdier."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu montes direct dans les tours ?"
    ryn "Parce que quand tu tardes, ça explose dans ta gueule."
    noam "Tu penses encore à LIMEN ?"
    ryn "Tout le temps. Je peux l'insulter et la défendre dans la même phrase."
    "Le silence revient brièvement, puis repart."
    noam "Tu fais confiance à qui ici ?"
    ryn "À ceux qui restent quand ça devient sale."
    noam "Tu te reposes jamais ?"
    ryn "Le repos, je le prends quand tout tient encore debout."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu parles aussi frontalement ?"
    ryn "Parce que les mots polis ne bouchent pas une fuite."
    noam "Tu te sens seul parfois ?"
    ryn "Ouais. Mais je préfère être seul que lâche."
    "Le silence revient brièvement, puis repart."
    noam "Tu regrettes la frontière ?"
    ryn "Je regrette les gens, pas la peur permanente."
    noam "Tu veux quoi pour la suite ?"
    ryn "Je veux que les miens sortent vivants de ce merdier."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu montes direct dans les tours ?"
    ryn "Parce que quand tu tardes, ça explose dans ta gueule."
    noam "Tu penses encore à LIMEN ?"
    ryn "Tout le temps. Je peux l'insulter et la défendre dans la même phrase."
    "Le silence revient brièvement, puis repart."
    noam "Tu fais confiance à qui ici ?"
    ryn "À ceux qui restent quand ça devient sale."
    noam "Tu te reposes jamais ?"
    ryn "Le repos, je le prends quand tout tient encore debout."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu parles aussi frontalement ?"
    ryn "Parce que les mots polis ne bouchent pas une fuite."
    noam "Tu te sens seul parfois ?"
    ryn "Ouais. Mais je préfère être seul que lâche."
    "Le silence revient brièvement, puis repart."
    noam "Tu regrettes la frontière ?"
    ryn "Je regrette les gens, pas la peur permanente."
    noam "Tu veux quoi pour la suite ?"
    ryn "Je veux que les miens sortent vivants de ce merdier."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu montes direct dans les tours ?"
    ryn "Parce que quand tu tardes, ça explose dans ta gueule."
    noam "Tu penses encore à LIMEN ?"
    ryn "Tout le temps. Je peux l'insulter et la défendre dans la même phrase."
    "Le silence revient brièvement, puis repart."
    noam "Tu fais confiance à qui ici ?"
    ryn "À ceux qui restent quand ça devient sale."
    noam "Tu te reposes jamais ?"
    ryn "Le repos, je le prends quand tout tient encore debout."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu parles aussi frontalement ?"
    ryn "Parce que les mots polis ne bouchent pas une fuite."
    noam "Tu te sens seul parfois ?"
    ryn "Ouais. Mais je préfère être seul que lâche."
    "Le silence revient brièvement, puis repart."
    noam "Tu regrettes la frontière ?"
    ryn "Je regrette les gens, pas la peur permanente."
    noam "Tu veux quoi pour la suite ?"
    ryn "Je veux que les miens sortent vivants de ce merdier."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu montes direct dans les tours ?"
    ryn "Parce que quand tu tardes, ça explose dans ta gueule."
    noam "Tu penses encore à LIMEN ?"
    ryn "Tout le temps. Je peux l'insulter et la défendre dans la même phrase."
    "Le silence revient brièvement, puis repart."
    noam "Tu fais confiance à qui ici ?"
    ryn "À ceux qui restent quand ça devient sale."
    noam "Tu te reposes jamais ?"
    ryn "Le repos, je le prends quand tout tient encore debout."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu parles aussi frontalement ?"
    ryn "Parce que les mots polis ne bouchent pas une fuite."
    noam "Tu te sens seul parfois ?"
    ryn "Ouais. Mais je préfère être seul que lâche."
    "Le silence revient brièvement, puis repart."
    noam "Tu regrettes la frontière ?"
    ryn "Je regrette les gens, pas la peur permanente."
    noam "Tu veux quoi pour la suite ?"
    ryn "Je veux que les miens sortent vivants de ce merdier."
    "Le silence revient brièvement, puis repart."
    ryn "On devrait reprendre cette discussion plus tard."
    noam "D'accord."
    ryn "Même dans un temps libre, on apprend des choses utiles."

    $ ryn_link = 3

    jump FREE_TIME_END

label ryn_link_4:

    play music "music/bgm_soft_neon_morning.mp3" fadein 1.0
    scene bg_cafeteria at adaptive_fullscreen

    $ showP("ryn", "neutre", 0.70)
    $ showP("noam", "reflexion", 0.24)

    "Ryn est déjà là quand j'arrive."
    "L'atmosphère est stable, mais tendue sous la surface."
    "On prend quelques secondes avant de commencer à parler."
    noam "Pourquoi tu montes direct dans les tours ?"
    ryn "Parce que quand tu tardes, ça explose dans ta gueule."
    noam "Tu penses encore à LIMEN ?"
    ryn "Tout le temps. Je peux l'insulter et la défendre dans la même phrase."
    "Le silence revient brièvement, puis repart."
    noam "Tu fais confiance à qui ici ?"
    ryn "À ceux qui restent quand ça devient sale."
    noam "Tu te reposes jamais ?"
    ryn "Le repos, je le prends quand tout tient encore debout."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu parles aussi frontalement ?"
    ryn "Parce que les mots polis ne bouchent pas une fuite."
    noam "Tu te sens seul parfois ?"
    ryn "Ouais. Mais je préfère être seul que lâche."
    "Le silence revient brièvement, puis repart."
    noam "Tu regrettes la frontière ?"
    ryn "Je regrette les gens, pas la peur permanente."
    noam "Tu veux quoi pour la suite ?"
    ryn "Je veux que les miens sortent vivants de ce merdier."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu montes direct dans les tours ?"
    ryn "Parce que quand tu tardes, ça explose dans ta gueule."
    noam "Tu penses encore à LIMEN ?"
    ryn "Tout le temps. Je peux l'insulter et la défendre dans la même phrase."
    "Le silence revient brièvement, puis repart."
    noam "Tu fais confiance à qui ici ?"
    ryn "À ceux qui restent quand ça devient sale."
    noam "Tu te reposes jamais ?"
    ryn "Le repos, je le prends quand tout tient encore debout."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu parles aussi frontalement ?"
    ryn "Parce que les mots polis ne bouchent pas une fuite."
    noam "Tu te sens seul parfois ?"
    ryn "Ouais. Mais je préfère être seul que lâche."
    "Le silence revient brièvement, puis repart."
    noam "Tu regrettes la frontière ?"
    ryn "Je regrette les gens, pas la peur permanente."
    noam "Tu veux quoi pour la suite ?"
    ryn "Je veux que les miens sortent vivants de ce merdier."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu montes direct dans les tours ?"
    ryn "Parce que quand tu tardes, ça explose dans ta gueule."
    noam "Tu penses encore à LIMEN ?"
    ryn "Tout le temps. Je peux l'insulter et la défendre dans la même phrase."
    "Le silence revient brièvement, puis repart."
    noam "Tu fais confiance à qui ici ?"
    ryn "À ceux qui restent quand ça devient sale."
    noam "Tu te reposes jamais ?"
    ryn "Le repos, je le prends quand tout tient encore debout."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu parles aussi frontalement ?"
    ryn "Parce que les mots polis ne bouchent pas une fuite."
    noam "Tu te sens seul parfois ?"
    ryn "Ouais. Mais je préfère être seul que lâche."
    "Le silence revient brièvement, puis repart."
    noam "Tu regrettes la frontière ?"
    ryn "Je regrette les gens, pas la peur permanente."
    noam "Tu veux quoi pour la suite ?"
    ryn "Je veux que les miens sortent vivants de ce merdier."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu montes direct dans les tours ?"
    ryn "Parce que quand tu tardes, ça explose dans ta gueule."
    noam "Tu penses encore à LIMEN ?"
    ryn "Tout le temps. Je peux l'insulter et la défendre dans la même phrase."
    "Le silence revient brièvement, puis repart."
    noam "Tu fais confiance à qui ici ?"
    ryn "À ceux qui restent quand ça devient sale."
    noam "Tu te reposes jamais ?"
    ryn "Le repos, je le prends quand tout tient encore debout."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu parles aussi frontalement ?"
    ryn "Parce que les mots polis ne bouchent pas une fuite."
    noam "Tu te sens seul parfois ?"
    ryn "Ouais. Mais je préfère être seul que lâche."
    "Le silence revient brièvement, puis repart."
    noam "Tu regrettes la frontière ?"
    ryn "Je regrette les gens, pas la peur permanente."
    noam "Tu veux quoi pour la suite ?"
    ryn "Je veux que les miens sortent vivants de ce merdier."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu montes direct dans les tours ?"
    ryn "Parce que quand tu tardes, ça explose dans ta gueule."
    noam "Tu penses encore à LIMEN ?"
    ryn "Tout le temps. Je peux l'insulter et la défendre dans la même phrase."
    "Le silence revient brièvement, puis repart."
    noam "Tu fais confiance à qui ici ?"
    ryn "À ceux qui restent quand ça devient sale."
    noam "Tu te reposes jamais ?"
    ryn "Le repos, je le prends quand tout tient encore debout."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu parles aussi frontalement ?"
    ryn "Parce que les mots polis ne bouchent pas une fuite."
    noam "Tu te sens seul parfois ?"
    ryn "Ouais. Mais je préfère être seul que lâche."
    "Le silence revient brièvement, puis repart."
    noam "Tu regrettes la frontière ?"
    ryn "Je regrette les gens, pas la peur permanente."
    noam "Tu veux quoi pour la suite ?"
    ryn "Je veux que les miens sortent vivants de ce merdier."
    "Le silence revient brièvement, puis repart."
    ryn "On devrait reprendre cette discussion plus tard."
    noam "D'accord."
    ryn "Même dans un temps libre, on apprend des choses utiles."

    $ ryn_link = 4

    jump FREE_TIME_END

label ryn_link_5:

    play music "music/bgm_quiet_routine.mp3" fadein 1.0
    scene bg_repos at adaptive_fullscreen

    $ showP("ryn", "neutre", 0.70)
    $ showP("noam", "reflexion", 0.24)

    "Ryn est déjà là quand j'arrive."
    "L'atmosphère est stable, mais tendue sous la surface."
    "On prend quelques secondes avant de commencer à parler."
    noam "Pourquoi tu montes direct dans les tours ?"
    ryn "Parce que quand tu tardes, ça explose dans ta gueule."
    noam "Tu penses encore à LIMEN ?"
    ryn "Tout le temps. Je peux l'insulter et la défendre dans la même phrase."
    "Le silence revient brièvement, puis repart."
    noam "Tu fais confiance à qui ici ?"
    ryn "À ceux qui restent quand ça devient sale."
    noam "Tu te reposes jamais ?"
    ryn "Le repos, je le prends quand tout tient encore debout."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu parles aussi frontalement ?"
    ryn "Parce que les mots polis ne bouchent pas une fuite."
    noam "Tu te sens seul parfois ?"
    ryn "Ouais. Mais je préfère être seul que lâche."
    "Le silence revient brièvement, puis repart."
    noam "Tu regrettes la frontière ?"
    ryn "Je regrette les gens, pas la peur permanente."
    noam "Tu veux quoi pour la suite ?"
    ryn "Je veux que les miens sortent vivants de ce merdier."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu montes direct dans les tours ?"
    ryn "Parce que quand tu tardes, ça explose dans ta gueule."
    noam "Tu penses encore à LIMEN ?"
    ryn "Tout le temps. Je peux l'insulter et la défendre dans la même phrase."
    "Le silence revient brièvement, puis repart."
    noam "Tu fais confiance à qui ici ?"
    ryn "À ceux qui restent quand ça devient sale."
    noam "Tu te reposes jamais ?"
    ryn "Le repos, je le prends quand tout tient encore debout."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu parles aussi frontalement ?"
    ryn "Parce que les mots polis ne bouchent pas une fuite."
    noam "Tu te sens seul parfois ?"
    ryn "Ouais. Mais je préfère être seul que lâche."
    "Le silence revient brièvement, puis repart."
    noam "Tu regrettes la frontière ?"
    ryn "Je regrette les gens, pas la peur permanente."
    noam "Tu veux quoi pour la suite ?"
    ryn "Je veux que les miens sortent vivants de ce merdier."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu montes direct dans les tours ?"
    ryn "Parce que quand tu tardes, ça explose dans ta gueule."
    noam "Tu penses encore à LIMEN ?"
    ryn "Tout le temps. Je peux l'insulter et la défendre dans la même phrase."
    "Le silence revient brièvement, puis repart."
    noam "Tu fais confiance à qui ici ?"
    ryn "À ceux qui restent quand ça devient sale."
    noam "Tu te reposes jamais ?"
    ryn "Le repos, je le prends quand tout tient encore debout."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu parles aussi frontalement ?"
    ryn "Parce que les mots polis ne bouchent pas une fuite."
    noam "Tu te sens seul parfois ?"
    ryn "Ouais. Mais je préfère être seul que lâche."
    "Le silence revient brièvement, puis repart."
    noam "Tu regrettes la frontière ?"
    ryn "Je regrette les gens, pas la peur permanente."
    noam "Tu veux quoi pour la suite ?"
    ryn "Je veux que les miens sortent vivants de ce merdier."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu montes direct dans les tours ?"
    ryn "Parce que quand tu tardes, ça explose dans ta gueule."
    noam "Tu penses encore à LIMEN ?"
    ryn "Tout le temps. Je peux l'insulter et la défendre dans la même phrase."
    "Le silence revient brièvement, puis repart."
    noam "Tu fais confiance à qui ici ?"
    ryn "À ceux qui restent quand ça devient sale."
    noam "Tu te reposes jamais ?"
    ryn "Le repos, je le prends quand tout tient encore debout."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu parles aussi frontalement ?"
    ryn "Parce que les mots polis ne bouchent pas une fuite."
    noam "Tu te sens seul parfois ?"
    ryn "Ouais. Mais je préfère être seul que lâche."
    "Le silence revient brièvement, puis repart."
    noam "Tu regrettes la frontière ?"
    ryn "Je regrette les gens, pas la peur permanente."
    noam "Tu veux quoi pour la suite ?"
    ryn "Je veux que les miens sortent vivants de ce merdier."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu montes direct dans les tours ?"
    ryn "Parce que quand tu tardes, ça explose dans ta gueule."
    noam "Tu penses encore à LIMEN ?"
    ryn "Tout le temps. Je peux l'insulter et la défendre dans la même phrase."
    "Le silence revient brièvement, puis repart."
    noam "Tu fais confiance à qui ici ?"
    ryn "À ceux qui restent quand ça devient sale."
    noam "Tu te reposes jamais ?"
    ryn "Le repos, je le prends quand tout tient encore debout."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu parles aussi frontalement ?"
    ryn "Parce que les mots polis ne bouchent pas une fuite."
    noam "Tu te sens seul parfois ?"
    ryn "Ouais. Mais je préfère être seul que lâche."
    "Le silence revient brièvement, puis repart."
    noam "Tu regrettes la frontière ?"
    ryn "Je regrette les gens, pas la peur permanente."
    noam "Tu veux quoi pour la suite ?"
    ryn "Je veux que les miens sortent vivants de ce merdier."
    "Le silence revient brièvement, puis repart."
    ryn "On devrait reprendre cette discussion plus tard."
    noam "D'accord."
    ryn "Même dans un temps libre, on apprend des choses utiles."

    $ ryn_link = 5

    jump FREE_TIME_END

