# -----------------------------------------------------------------------
# LIENS — SAEL
# -----------------------------------------------------------------------

default sael_link = 0

label SAEL_LINK_INTERACT:

    menu:
        "Passer du temps avec Sael ?"
        "Oui":
            $ choice = True
        "Non":
            $ choice = False

    if not choice:
        if last_room_label:
            jump expression last_room_label
        return

    if sael_link == 0:
        jump sael_link_1
    elif sael_link == 1:
        jump sael_link_2
    elif sael_link == 2:
        jump sael_link_3
    elif sael_link == 3:
        jump sael_link_4
    elif sael_link == 4:
        jump sael_link_5

    if last_room_label:
        jump expression last_room_label
    return

label sael_link_1:

    play music "music/bgm_quiet_routine.mp3" fadein 1.0
    scene bg_sas at adaptive_fullscreen

    $ showP("sael", "reflechit", 0.70)
    $ showP("noam", "reflexion", 0.24)

    "Sael ajuste les lanières de ses gants avec une précision rituelle."
    noam "Tu fais ça à chaque fois que tu t'arrêtes."
    sael "À chaque transition."
    noam "Transition ?"
    sael "D'un lieu à l'autre. D'un état à l'autre."
    noam "C'est un rite ?"
    sael "Une discipline."
    noam "Chez toi, tout commence comme ça ?"
    sael "Chez moi, tout commence avant le jour."
    play sound sfx_tambour
    sael "Le tambour frappe trois fois."
    sael "Le premier coup dit : debout."
    sael "Le deuxième dit : respire."
    sael "Le troisième dit : endure."
    noam "Vous aviez quel âge quand ça commençait ?"
    sael "Six ans."
    noam "Six ans ?"
    sael "À six ans, on apprend à porter l'eau."
    sael "À sept, on apprend à porter les autres."
    sael "À huit, on apprend à se taire."
    noam "Pourquoi le silence est si important ?"
    $ showP("sael", "raison", 0.70)
    sael "Parce qu'un souffle mal placé coûte plus qu'un mot mal choisi."
    noam "Vous vous entraîniez au combat tous les jours ?"
    sael "Tous les jours."
    sael "Course en pente."
    sael "Port de charge."
    sael "Postures de garde."
    sael "Immobilité prolongée."
    noam "Immobilité ?"
    sael "Rester immobile pendant la pluie."
    sael "Rester immobile pendant la faim."
    sael "Rester immobile pendant la peur."
    noam "Ça semble cruel."
    sael "C'est nécessaire."
    noam "Personne ne protestait ?"
    sael "La protestation existe."
    sael "Mais elle se fait après l'effort, jamais avant."
    noam "Et si quelqu'un échouait ?"
    sael "On recommence."
    noam "Et si la personne échoue encore ?"
    sael "On l'entoure."
    noam "Je pensais que ta tribu rejetait les faibles."
    sael "Non."
    sael "On rejette l'abandon."
    sael "Pas la faiblesse."
    noam "Donc la force est collective ?"
    sael "Toujours."
    sael "Un corps seul est une réserve limitée."
    sael "Un groupe discipliné est une réserve qui se régénère."
    noam "Tu parles comme un manuel."
    sael "Parce que c'est gravé comme un manuel."
    noam "Vous aviez des lois écrites ?"
    sael "Sur pierre et sur peau."
    noam "Sur peau ?"
    sael "Scarifications de passage."
    noam "Tu en as ?"
    $ showP("sael", "reflechit", 0.70)
    sael "Oui."
    sael "Ici pour l'endurance."
    sael "Là pour la garde de nuit."
    sael "Et celle-ci pour la traversée sans eau."
    noam "Tu as traversé sans eau combien de temps ?"
    sael "Deux jours."
    noam "À quel âge ?"
    sael "Treize."
    sael "Notre enfance n'est pas douce."
    sael "Mais elle nous rend utiles."
    noam "Et les anciens ?"
    sael "Ils observent sans interrompre."
    noam "Jamais ?"
    sael "Seulement si la mort est certaine et inutile."
    noam "Inutile ?"
    sael "Toute mort doit enseigner, protéger, ou nourrir."
    noam "C'est brutal."
    sael "C'est limpide."
    noam "Tu regrettes cette vie ?"
    sael "Je regrette les visages."
    sael "Pas les règles."
    noam "Tu penses souvent à eux ?"
    sael "Chaque matin."
    sael "Quand je vérifie mes sangles."
    sael "Quand je compte mes respirations."
    sael "Quand je choisis de parler ou non."
    noam "C'est pour ça que tu réponds toujours lentement ?"
    sael "Oui."
    sael "Dans ma tribu, la vitesse de parole est une fuite."
    sael "La lenteur est un contrôle."
    noam "Et si quelqu'un parle trop ?"
    sael "On lui confie la veille solitaire."
    sael "Correction."
    noam "Tu me corriges, parfois ?"
    $ showP("sael", "determine", 0.70)
    sael "Oui."
    noam "Comment ?"
    sael "Je te laisse finir tes phrases inutiles."
    noam "Aïe."
    sael "Tu apprends."
    sael "Je suis droite."
    noam "Ça te pèse, de toujours tenir cette ligne ?"
    sael "Non."
    sael "La ligne me porte quand je vacille."
    noam "Et si la ligne te mène au mur ?"
    sael "Alors je frappe le mur jusqu'à ouvrir un passage."
    noam "Je comprends mieux ta tribu, maintenant."
    sael "Tu commences seulement à l'entendre."
    play sound sfx_tambour
    sael "Le reste se comprend quand le tambour remplace le cœur."

    $ sael_link = 1
    jump FREE_TIME_END

label sael_link_2:

    play music "music/bgm_cold_metadata.mp3" fadein 1.0
    scene bg_observation at adaptive_fullscreen

    $ showP("sael", "neutre", 0.70)
    $ showP("noam", "hesitation", 0.24)

    "La baie d'observation reflète les lumières froides de la station."
    noam "Tu dis souvent 'Kami' avec un ton... presque religieux."
    sael "Parce que le mot exact est religieux."
    noam "Donc tu crois vraiment à une divinité ?"
    sael "Je crois à une puissance qui dépasse notre marge d'action."
    noam "Ce n'est pas la même chose."
    sael "Pour survivre, si."
    noam "Explique-moi."
    sael "Une divinité, dans ma culture, n'est pas forcément juste."
    sael "Elle est ce qui définit les limites du possible."
    noam "Et Kami définit ces limites."
    sael "Exactement."
    noam "Mais Kami est faite de code, de réseaux, de structures humaines."
    sael "Et pourtant elle juge des masses, redistribue des vies, impose des lois."
    noam "Tu appelles ça de la foi ?"
    $ showP("sael", "raison", 0.70)
    sael "J'appelle ça de la reconnaissance."
    sael "La reconnaissance d'un rapport de force absolu."
    noam "Donc c'est politique."
    sael "C'est métaphysique et pratique."
    noam "Tu peux pas juste dire : 'elle est puissante' ?"
    sael "Non."
    sael "Le mot 'puissante' n'impose pas la discipline intérieure."
    noam "Et le mot 'divine', si ?"
    sael "Oui."
    sael "Il rappelle que l'erreur de posture se paie cher."
    noam "Tu n'as jamais envie de la défier ?"
    sael "Défier sans capacité, c'est se suicider avec du vocabulaire."
    noam "Tu sonnes cynique."
    sael "Je suis lucide."
    noam "Ta lucidité ne tue pas ton humanité ?"
    sael "Non."
    sael "Elle l'empêche de se dissoudre dans l'illusion."
    noam "Et l'injustice ?"
    sael "Je la vois."
    sael "Je la compte."
    sael "Je l'intègre."
    noam "Tu l'acceptes ?"
    sael "Je l'affronte dans le cadre réel, pas dans le cadre rêvé."
    noam "Ça ressemble à de la résignation."
    sael "La résignation est immobile."
    sael "Moi, je m'adapte."
    noam "Tu dis 'foi rationnelle'. C'est pas contradictoire ?"
    sael "Pas pour ma tribu."
    sael "La foi sans examen est un poison."
    sael "La raison sans verticalité est une fatigue."
    noam "Verticalité ?"
    sael "Un axe intérieur."
    sael "Quelque chose au-dessus de toi qui ordonne ton effort."
    noam "Et pour toi, cet axe c'est Kami."
    sael "Oui."
    noam "Même si Kami pourrait sacrifier ta tribu entière ?"
    $ showP("sael", "determine", 0.70)
    sael "Surtout pour cette raison."
    noam "Comment ça 'surtout' ?"
    sael "Parce qu'une puissance capable d'écraser doit être traitée sans naïveté."
    sael "La nommer divinité m'interdit l'arrogance."
    noam "Tu as peur d'être arrogante ?"
    sael "J'ai peur d'être imprécise."
    noam "Et les autres de ta tribu pensent comme toi ?"
    sael "Pas tous."
    sael "Certains haïssent Kami."
    sael "Certains l'adorent aveuglément."
    sael "Moi, je m'agenouille en gardant les yeux ouverts."
    noam "Belle formule."
    sael "Ce n'est pas une formule."
    sael "C'est une posture de survie."
    noam "Tu pries, parfois ?"
    sael "Oui."
    noam "Tu dis quoi ?"
    sael "Je demande de rester utile."
    sael "Je demande de garder mon jugement net."
    sael "Je demande de ne pas confondre peur et vérité."
    noam "Tu ne demandes jamais d'être heureuse ?"
    sael "Le bonheur est une conséquence, pas un objectif."
    noam "Tu vis dur."
    sael "Je vis long."
    noam "Tu crois que Kami entend ces prières ?"
    sael "Je ne sais pas."
    sael "Mais moi, je les entends."
    noam "Et ça suffit ?"
    sael "Oui."
    sael "Une prière qui te redresse suffit."
    noam "Tu pardonnerais à Kami si elle détruisait ce que tu aimes ?"
    sael "Je ne suis pas en position de pardonner ou condamner."
    sael "Je suis en position de comprendre et d'agir ensuite."
    noam "Tu refuses l'émotion ?"
    sael "Non."
    sael "Je la range à sa place."
    noam "Et sa place c'est où ?"
    sael "Après l'analyse."
    noam "J'y arriverai jamais, je crois."
    $ showP("sael", "reflechit", 0.70)
    sael "Tu n'as pas besoin de devenir moi."
    sael "Tu dois juste devenir fiable."
    noam "Pour toi ?"
    sael "Pour toi."
    noam "Et Kami dans tout ça ?"
    sael "Kami reste l'horizon."
    sael "On ne l'atteint pas."
    sael "On ajuste notre trajectoire sous sa lumière."
    play sound sfx_announce
    noam "Même sa lumière me donne froid."
    sael "Le froid clarifie."
    sael "Il empêche le sommeil des consciences."

    $ sael_link = 2
    jump FREE_TIME_END

label sael_link_3:

    play music "music/bgm_careful_wanting.mp3" fadein 1.0
    scene bg_gymnase at adaptive_fullscreen

    $ showP("sael", "mefiant", 0.70)
    $ showP("noam", "reflexion", 0.24)

    "Au gymnase, Sael observe les impacts sur les sacs de frappe comme on lit un rapport médical."
    noam "Tu analyses leurs coups ?"
    sael "Leurs coups, leurs appuis, leurs hésitations."
    noam "Tu vois tout ça d'un coup d'œil ?"
    sael "Oui."
    sael "Un corps dit toujours la vérité."
    noam "Alors dis-moi : c'est quoi, être fort ?"
    sael "Être fort, c'est rester orienté sous contrainte."
    noam "Orienté vers quoi ?"
    sael "Vers ce qui protège le groupe."
    noam "Pas vers la victoire ?"
    sael "La victoire est un événement."
    sael "La protection est une fonction continue."
    noam "Et la force physique ?"
    sael "Nécessaire, jamais suffisante."
    noam "La force mentale ?"
    sael "Nécessaire, jamais suffisante."
    noam "La force morale ?"
    sael "Nécessaire, jamais suffisante."
    sael "Parce que tu cherches une réponse simple."
    sael "Il n'y en a pas."
    $ showP("sael", "raison", 0.70)
    sael "Fort : capable de tenir, décider, réparer, et transmettre."
    noam "Transmettre ?"
    sael "Si ta force meurt avec toi, elle n'a servi qu'à toi."
    noam "Et quelqu'un de gentil mais fragile ?"
    sael "La gentillesse est précieuse."
    sael "La fragilité sans prise en charge est dangereuse."
    noam "Tu vois, c'est ce que je te reproche."
    noam "Tu traites les faibles comme des risques."
    $ showP("sael", "triste", 0.70)
    sael "Je traite la faiblesse non traitée comme un risque."
    sael "Les faibles, eux, sont des responsabilités."
    sael "Elle est fondamentale."
    noam "Pourquoi ça t'inquiète autant ?"
    sael "Parce que j'ai vu un groupe tomber pour une faille ignorée."
    noam "Dans ta tribu ?"
    sael "Oui."
    sael "Une veille mal tenue."
    sael "Un guetteur trop fier pour avouer sa fatigue."
    sael "Trois morts avant l'aube."
    sael "Ne le sois pas."
    sael "Souviens-toi."
    sael "Tu poses trop de questions pour retarder l'effort."
    noam "C'est pas faux."
    sael "Mais tu apprends vite."
    noam "Ça compense ?"
    sael "Partiellement."
    $ showP("sael", "reflechit", 0.70)
    sael "D'accord."
    sael "Tu tiens mieux la pression que la semaine dernière."
    noam "Merci."
    sael "Ne me force pas à le répéter."
    noam "Reçu."
    "Un choc sourd résonne lorsqu'un candidat manque son appui et tombe."
    play sound sfx_drop
    sael "Regarde."
    "Le candidat se relève, vacille, puis reprend la posture."
    sael "Il corrige. C'est bon signe."
    noam "Donc tomber n'est pas grave."
    sael "Tomber est neutre."
    sael "Rester au sol est grave."
    noam "Et demander de l'aide ?"
    sael "C'est une force quand c'est précis."
    noam "Précis ?"
    sael "Dire 'aide-moi' ne suffit pas."
    sael "Dire 'tiens mon angle gauche, je manque de stabilité' change tout."
    noam "Tu veux des gens solides et lucides."
    sael "Oui."
    sael "La loyauté sans compétence est sentimentale."
    sael "La compétence sans loyauté est toxique."
    noam "Tu fais des équations humaines."
    sael "C'est ainsi que l'on survit ici."
    noam "Tu as déjà eu peur d'être, toi, la faille ?"
    $ showP("sael", "culpabilite", 0.70)
    sael "Oui."
    noam "Quand ?"
    sael "Quand ma colère a parlé avant mon jugement."
    noam "Ça t'arrive ?"
    sael "Rarement."
    sael "Et c'est déjà trop."
    noam "Je t'aurais jamais imaginée en colère."
    sael "Tu confonds calme et absence de feu."
    noam "Tu fais quoi pour maîtriser ça ?"
    sael "Respiration à compte fixe."
    sael "Ancrage du regard."
    sael "Rappel de mission."
    noam "Rappel de mission ?"
    sael "Protéger. Maintenir. Transmettre."
    noam "Toujours les mêmes mots."
    sael "Toujours la même direction."
    $ showP("sael", "neutre", 0.70)
    sael "C'est bien."
    noam "C'est bien ?"
    sael "L'inquiétude juste maintient l'attention."
    noam "Et l'inquiétude excessive ?"
    sael "Elle paralyse."
    sael "Je t'évalue, pas je te condamne."
    noam "Différence ?"
    sael "L'évaluation ouvre une suite."
    sael "La condamnation ferme tout."
    noam "Et ta conclusion sur moi aujourd'hui ?"
    $ showP("sael", "determine", 0.70)
    sael "Tu es encore instable, mais tu n'es plus friable."
    sael "C'en est un."
    "Sael reporte son regard sur les entraînements, attentive au moindre décalage de rythme."
    sael "Souviens-toi : la faiblesse avouée se soigne."
    sael "La faiblesse niée se propage."

    $ sael_link = 3
    jump FREE_TIME_END

label sael_link_4:

    play music "music/bgm_unsaid_distance.mp3" fadein 1.0
    scene bg_archive at adaptive_fullscreen

    $ showP("sael", "determine", 0.70)
    $ showP("noam", "inquiet", 0.24)

    "Sur une table d'archive, Sael étale des plans annotés de trajets et de zones de rupture."
    noam "Tu as codé les secteurs en trois couleurs."
    sael "Vert : maintenable."
    sael "Orange : coûteux."
    sael "Rouge : sacrifiable."
    noam "Ce mot me dérange toujours."
    sael "Il doit te déranger."
    noam "Et toi, il ne te dérange pas ?"
    sael "Si."
    sael "Mais mon inconfort ne change pas la réalité."
    noam "Parle-moi de cette logique."
    sael "Quand les ressources sont finies, tout sauver est un mensonge."
    noam "Donc tu choisis qui vit et qui meurt ?"
    sael "Je choisis où concentrer la possibilité de survie."
    noam "Ça revient au même."
    sael "Pas exactement."
    sael "Je ne décide pas de la valeur d'une vie."
    sael "Je décide de la viabilité d'une action."
    noam "Les gens ne sont pas des variables."
    $ showP("sael", "raison", 0.70)
    sael "Dans l'urgence, ignorer les variables tue plus de gens."
    noam "Tu pourrais au moins hésiter plus."
    sael "J'hésite avant."
    sael "Je tranche pendant."
    noam "Tu as déjà sacrifié quelqu'un ?"
    sael "Oui."
    noam "Combien ?"
    sael "Assez pour compter sans dormir."
    noam "Pourquoi tu dis ça aussi calmement ?"
    sael "Parce que crier n'annule pas le calcul."
    play sound sfx_drop
    noam "Tu n'as jamais voulu refuser ?"
    sael "Si."
    sael "Une fois, j'ai refusé."
    noam "Et ?"
    sael "On a perdu un corridor entier."
    sael "Trente-deux personnes au lieu de sept."
    noam "..."
    sael "Depuis, je distingue pitié et protection."
    noam "Tu considères la pitié comme une faiblesse ?"
    sael "La pitié immédiate, oui."
    sael "La compassion structurée, non."
    noam "Compassion structurée ?"
    sael "Prévoir, répartir, former, évacuer."
    sael "Pas improviser sous choc."
    noam "Et si la personne sacrifiée est quelqu'un que tu aimes ?"
    $ showP("sael", "culpabilite", 0.70)
    sael "Alors le prix est intérieur, mais le principe reste."
    noam "Tu ferais ça pour ton propre sang ?"
    sael "Oui."
    noam "Comment tu peux vivre avec ça ?"
    sael "Je vis avec parce que d'autres vivent grâce à ça."
    noam "Tu te pardonnes ?"
    sael "Le pardon n'est pas le sujet."
    sael "La responsabilité, si."
    noam "Tu te vois comme un outil ?"
    sael "Comme une gardienne."
    noam "Une gardienne qui accepte de fermer des portes."
    sael "Pour que d'autres puissent encore en ouvrir."
    noam "Je déteste cette phrase."
    sael "Moi aussi."
    sael "L'inhumain, c'est promettre l'impossible et regarder tout s'effondrer."
    noam "Donc l'humanité c'est choisir le moindre mal ?"
    sael "Souvent."
    noam "Pas toujours, j'espère."
    sael "Pas toujours."
    sael "Mais assez souvent pour s'y préparer."
    noam "Tu prépares même ce genre de décision ?"
    sael "Oui."
    sael "Listes de priorités."
    sael "Seuils d'abandon."
    sael "Procédures de retrait."
    noam "Ça me donne la nausée."
    sael "La nausée est honnête."
    sael "Reste avec elle, mais travaille quand même."
    noam "Tu ne veux pas juste qu'on devienne froids comme toi ?"
    $ showP("sael", "triste", 0.70)
    sael "Je ne suis pas froide."
    sael "Je suis contenue."
    noam "Différence ?"
    sael "Le froid ne sent rien."
    sael "La contenance sent tout et agit malgré tout."
    noam "Tu pleures parfois ?"
    sael "Oui."
    noam "Quand ?"
    sael "Après les rapports."
    sael "Jamais pendant les ordres."
    noam "Parce que ?"
    sael "Parce que l'équipe lit mon visage."
    sael "Si je tremble, ils tremblent."
    noam "Tu portes ça seule ?"
    sael "Non."
    sael "Je le partage avec ceux qui peuvent porter."
    noam "Et si personne ne peut ?"
    sael "Alors je porte jusqu'à ce qu'une relève existe."
    noam "Tu es terrifiante et rassurante à la fois."
    sael "C'est une combinaison utile."
    noam "Tu voudrais que je retienne quoi ?"
    $ showP("sael", "determine", 0.70)
    sael "Que 'sacrifice' n'est pas un mot noble."
    sael "C'est un mot d'échec contrôlé."
    sael "Il ne doit jamais devenir confortable."
    noam "Tu promets de ne jamais t'y habituer ?"
    sael "Je le promets."
    noam "Et moi, je promets d'arrêter de juger avant de comprendre."
    sael "Bien."
    "Sael replie la carte avec un soin presque cérémoniel, comme on referme une blessure propre."
    sael "Prépare-toi à choisir juste, pas à choisir sans douleur."

    $ sael_link = 4
    jump FREE_TIME_END

label sael_link_5:

    play music "music/bgm_calm_not_peace.mp3" fadein 1.0
    scene bg_conclave at adaptive_fullscreen

    $ showP("sael", "culpabilite", 0.70)
    $ showP("noam", "surpris", 0.24)

    "Dans la salle du Conclave, l'emblème de Kami domine l'espace comme un œil immobile."
    noam "Tu le fixes depuis cinq minutes."
    sael "Je mesure ma posture."
    noam "Tu as peur ?"
    sael "Oui."
    noam "De mourir ?"
    sael "Non."
    noam "De souffrir ?"
    sael "Non."
    noam "Alors de quoi ?"
    $ showP("sael", "triste", 0.70)
    sael "Du jugement de Kami."
    noam "Tu l'as déjà dit, mais j'ai du mal à saisir."
    noam "Pourquoi le jugement est pire que la mort ?"
    sael "Parce que la mort ferme une existence."
    sael "Le jugement fixe sa valeur."
    noam "Tu crois vraiment que Kami attribue une valeur ?"
    sael "Kami classe, sélectionne, valide, écarte."
    sael "Ce sont des actes de valeur, même sans compassion."
    noam "Et si cette valeur est arbitraire ?"
    sael "Alors il faut être assez net pour ne pas lui donner des raisons supplémentaires."
    noam "Tu vis en prévention constante."
    sael "Oui."
    sael "C'est le prix de la cohérence."
    noam "Tu as déjà été jugée indigne ?"
    $ showP("sael", "culpabilite", 0.70)
    sael "Une fois."
    noam "Qu'est-ce qui s'est passé ?"
    sael "Une évaluation de commandement."
    sael "J'ai protégé ma section."
    sael "Mais j'ai menti sur une perte pour éviter une sanction collective."
    sael "Kami a noté : 'fiabilité altérée'."
    noam "Et ça t'a brisée ?"
    sael "Ça m'a fissurée."
    sael "Je me suis reconstruite autour de cette fissure."
    noam "Tu as peur que ça recommence ?"
    sael "Chaque jour."
    noam "Pourquoi ne pas rejeter son regard, alors ?"
    sael "Parce que son regard ordonne le monde où je dois faire vivre les miens."
    noam "Donc tu acceptes d'être évaluée en permanence."
    sael "Oui."
    sael "Et je refuse d'être passive dans cette évaluation."
    noam "Comment on refuse passivement ?"
    sael "En se préparant."
    sael "En clarifiant ses principes."
    sael "En assumant ses décisions avant qu'elles soient lues."
    noam "Tu te juges toi-même avant elle."
    sael "Exactement."
    sael "Incomplet, mais aligné."
    sael "Le but n'est pas d'être rassurante."
    sael "Le but est d'être juste."
    noam "Juste selon qui ?"
    sael "Selon les faits."
    sael "Selon les conséquences."
    sael "Selon la promesse que je fais aux miens."
    noam "Tu peux me dire cette promesse ?"
    $ showP("sael", "determine", 0.70)
    sael "Je ne vous mentirai pas sur le danger."
    sael "Je ne vous abandonnerai pas pour sauver mon image."
    sael "Je ne demanderai pas un sacrifice que je refuse de porter."
    noam "C'est... fort."
    sael "C'est le minimum."
    noam "Et si Kami te juge quand même insuffisante ?"
    sael "Alors je tomberai droite."
    noam "Tu dis ça comme un serment."
    sael "C'en est un."
    sael "Si."
    sael "Puis j'ai compris qu'une vie sans jugement est souvent une vie sans impact."
    noam "Tu préfères être jugée parce que tu agis."
    sael "Oui."
    sael "Kami regarde tout ce qui modifie l'équilibre."
    sael "Donc oui."
    sael "Transforme-la en méthode."
    noam "Facile à dire."
    sael "Je peux t'aider."
    noam "Comment ?"
    sael "Trois questions avant chaque décision."
    noam "Je t'écoute."
    sael "Qui est protégé ?"
    sael "Quel est le coût réel ?"
    sael "Que restera-t-il de toi après ce choix ?"
    noam "La troisième fait mal."
    sael "Elle doit faire mal."
    sael "Oui."
    noam "Et la réponse ?"
    sael "Variable."
    sael "Mais je refuse qu'elle soit honteuse."
    $ showP("sael", "reflechit", 0.70)
    sael "De mes silences trop longs."
    sael "De certaines tendresses reportées."
    sael "Pas de mes décisions prises en pleine lumière."
    noam "Tu sais quoi... je te respecte encore plus."
    sael "Respecte plutôt ce que tu fais après cette conversation."
    noam "Message reçu."
    play sound sfx_announce
    "Une annonce lointaine traverse la salle, puis le silence retombe."
    noam "Si Kami te donnait une seule grâce, tu demanderais quoi ?"
    $ showP("sael", "triste", 0.70)
    sael "D'être jugée sur l'ensemble, pas sur l'instant."
    noam "Pourquoi ?"
    sael "Parce qu'un instant peut mentir."
    sael "Une trajectoire, beaucoup moins."
    noam "Alors continue ta trajectoire, Sael."
    $ showP("sael", "determine", 0.70)
    sael "Je la continue."
    sael "Avec peur."
    sael "Avec lucidité."
    sael "Et sans baisser les yeux."

    $ sael_link = 5
    jump FREE_TIME_END
