# -----------------------------------------------------------------------
# LIENS — SAEL
# -----------------------------------------------------------------------

default sael_link = 0

label SAEL_LINK_INTERACT:

    menu:
        "Passer du temps avec Sael ?"
        "Oui":
            $ choice = True
        "Non":
            $ choice = False

    if not choice:
        if last_room_label:
            jump expression last_room_label
        return

    if sael_link == 0:
        jump sael_link_1
    elif sael_link == 1:
        jump sael_link_2
    elif sael_link == 2:
        jump sael_link_3
    elif sael_link == 3:
        jump sael_link_4
    elif sael_link == 4:
        jump sael_link_5

    if last_room_label:
        jump expression last_room_label
    return

label sael_link_1:

    play music "music/bgm_cold_metadata.mp3" fadein 1.0
    scene bg_sas at adaptive_fullscreen

    $ showP("sael", "neutre", 0.70)
    $ showP("noam", "reflexion", 0.24)

    "Sael est déjà là quand j'arrive."
    "L'atmosphère est stable, mais tendue sous la surface."
    "On prend quelques secondes avant de commencer à parler."
    noam "Pourquoi tu parles de force comme d'une morale ?"
    sael "Parce que dans ma tribu, survivre est un devoir collectif."
    noam "Tu crois vraiment à Kami ?"
    sael "Je crois à sa puissance, pas à sa tendresse."
    "Le silence revient brièvement, puis repart."
    noam "Tu choisis la soumission ?"
    sael "Oui. Une soumission choisie peut préserver un peuple."
    noam "Tu respectes qui exactement ?"
    sael "Ceux qui tiennent debout quand le monde se serre."
    "Le silence revient brièvement, puis repart."
    noam "Tu n'as jamais peur ?"
    sael "Si. Mais je l'organise pour qu'elle ne me dirige pas."
    noam "Tu vois un avenir ici ?"
    sael "Je vois des fenêtres de survie, pas des promesses."
    "Le silence revient brièvement, puis repart."
    noam "Tu peux pardonner la faiblesse ?"
    sael "Je peux l'encadrer, pas l'ériger en principe."
    noam "Qu'est-ce qui compte le plus pour toi ?"
    sael "La continuité du groupe, puis la dignité qui reste."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu parles de force comme d'une morale ?"
    sael "Parce que dans ma tribu, survivre est un devoir collectif."
    noam "Tu crois vraiment à Kami ?"
    sael "Je crois à sa puissance, pas à sa tendresse."
    "Le silence revient brièvement, puis repart."
    noam "Tu choisis la soumission ?"
    sael "Oui. Une soumission choisie peut préserver un peuple."
    noam "Tu respectes qui exactement ?"
    sael "Ceux qui tiennent debout quand le monde se serre."
    "Le silence revient brièvement, puis repart."
    noam "Tu n'as jamais peur ?"
    sael "Si. Mais je l'organise pour qu'elle ne me dirige pas."
    noam "Tu vois un avenir ici ?"
    sael "Je vois des fenêtres de survie, pas des promesses."
    "Le silence revient brièvement, puis repart."
    noam "Tu peux pardonner la faiblesse ?"
    sael "Je peux l'encadrer, pas l'ériger en principe."
    noam "Qu'est-ce qui compte le plus pour toi ?"
    sael "La continuité du groupe, puis la dignité qui reste."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu parles de force comme d'une morale ?"
    sael "Parce que dans ma tribu, survivre est un devoir collectif."
    noam "Tu crois vraiment à Kami ?"
    sael "Je crois à sa puissance, pas à sa tendresse."
    "Le silence revient brièvement, puis repart."
    noam "Tu choisis la soumission ?"
    sael "Oui. Une soumission choisie peut préserver un peuple."
    noam "Tu respectes qui exactement ?"
    sael "Ceux qui tiennent debout quand le monde se serre."
    "Le silence revient brièvement, puis repart."
    noam "Tu n'as jamais peur ?"
    sael "Si. Mais je l'organise pour qu'elle ne me dirige pas."
    noam "Tu vois un avenir ici ?"
    sael "Je vois des fenêtres de survie, pas des promesses."
    "Le silence revient brièvement, puis repart."
    noam "Tu peux pardonner la faiblesse ?"
    sael "Je peux l'encadrer, pas l'ériger en principe."
    noam "Qu'est-ce qui compte le plus pour toi ?"
    sael "La continuité du groupe, puis la dignité qui reste."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu parles de force comme d'une morale ?"
    sael "Parce que dans ma tribu, survivre est un devoir collectif."
    noam "Tu crois vraiment à Kami ?"
    sael "Je crois à sa puissance, pas à sa tendresse."
    "Le silence revient brièvement, puis repart."
    noam "Tu choisis la soumission ?"
    sael "Oui. Une soumission choisie peut préserver un peuple."
    noam "Tu respectes qui exactement ?"
    sael "Ceux qui tiennent debout quand le monde se serre."
    "Le silence revient brièvement, puis repart."
    noam "Tu n'as jamais peur ?"
    sael "Si. Mais je l'organise pour qu'elle ne me dirige pas."
    noam "Tu vois un avenir ici ?"
    sael "Je vois des fenêtres de survie, pas des promesses."
    "Le silence revient brièvement, puis repart."
    noam "Tu peux pardonner la faiblesse ?"
    sael "Je peux l'encadrer, pas l'ériger en principe."
    noam "Qu'est-ce qui compte le plus pour toi ?"
    sael "La continuité du groupe, puis la dignité qui reste."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu parles de force comme d'une morale ?"
    sael "Parce que dans ma tribu, survivre est un devoir collectif."
    noam "Tu crois vraiment à Kami ?"
    sael "Je crois à sa puissance, pas à sa tendresse."
    "Le silence revient brièvement, puis repart."
    noam "Tu choisis la soumission ?"
    sael "Oui. Une soumission choisie peut préserver un peuple."
    noam "Tu respectes qui exactement ?"
    sael "Ceux qui tiennent debout quand le monde se serre."
    "Le silence revient brièvement, puis repart."
    noam "Tu n'as jamais peur ?"
    sael "Si. Mais je l'organise pour qu'elle ne me dirige pas."
    noam "Tu vois un avenir ici ?"
    sael "Je vois des fenêtres de survie, pas des promesses."
    "Le silence revient brièvement, puis repart."
    noam "Tu peux pardonner la faiblesse ?"
    sael "Je peux l'encadrer, pas l'ériger en principe."
    noam "Qu'est-ce qui compte le plus pour toi ?"
    sael "La continuité du groupe, puis la dignité qui reste."
    "Le silence revient brièvement, puis repart."
    sael "On devrait reprendre cette discussion plus tard."
    noam "D'accord."
    sael "Même dans un temps libre, on apprend des choses utiles."

    $ sael_link = 1

    jump FREE_TIME_END

label sael_link_2:

    play music "music/bgm_unsaid_distance.mp3" fadein 1.0
    scene bg_observation at adaptive_fullscreen

    $ showP("sael", "neutre", 0.70)
    $ showP("noam", "reflexion", 0.24)

    "Sael est déjà là quand j'arrive."
    "L'atmosphère est stable, mais tendue sous la surface."
    "On prend quelques secondes avant de commencer à parler."
    noam "Pourquoi tu parles de force comme d'une morale ?"
    sael "Parce que dans ma tribu, survivre est un devoir collectif."
    noam "Tu crois vraiment à Kami ?"
    sael "Je crois à sa puissance, pas à sa tendresse."
    "Le silence revient brièvement, puis repart."
    noam "Tu choisis la soumission ?"
    sael "Oui. Une soumission choisie peut préserver un peuple."
    noam "Tu respectes qui exactement ?"
    sael "Ceux qui tiennent debout quand le monde se serre."
    "Le silence revient brièvement, puis repart."
    noam "Tu n'as jamais peur ?"
    sael "Si. Mais je l'organise pour qu'elle ne me dirige pas."
    noam "Tu vois un avenir ici ?"
    sael "Je vois des fenêtres de survie, pas des promesses."
    "Le silence revient brièvement, puis repart."
    noam "Tu peux pardonner la faiblesse ?"
    sael "Je peux l'encadrer, pas l'ériger en principe."
    noam "Qu'est-ce qui compte le plus pour toi ?"
    sael "La continuité du groupe, puis la dignité qui reste."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu parles de force comme d'une morale ?"
    sael "Parce que dans ma tribu, survivre est un devoir collectif."
    noam "Tu crois vraiment à Kami ?"
    sael "Je crois à sa puissance, pas à sa tendresse."
    "Le silence revient brièvement, puis repart."
    noam "Tu choisis la soumission ?"
    sael "Oui. Une soumission choisie peut préserver un peuple."
    noam "Tu respectes qui exactement ?"
    sael "Ceux qui tiennent debout quand le monde se serre."
    "Le silence revient brièvement, puis repart."
    noam "Tu n'as jamais peur ?"
    sael "Si. Mais je l'organise pour qu'elle ne me dirige pas."
    noam "Tu vois un avenir ici ?"
    sael "Je vois des fenêtres de survie, pas des promesses."
    "Le silence revient brièvement, puis repart."
    noam "Tu peux pardonner la faiblesse ?"
    sael "Je peux l'encadrer, pas l'ériger en principe."
    noam "Qu'est-ce qui compte le plus pour toi ?"
    sael "La continuité du groupe, puis la dignité qui reste."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu parles de force comme d'une morale ?"
    sael "Parce que dans ma tribu, survivre est un devoir collectif."
    noam "Tu crois vraiment à Kami ?"
    sael "Je crois à sa puissance, pas à sa tendresse."
    "Le silence revient brièvement, puis repart."
    noam "Tu choisis la soumission ?"
    sael "Oui. Une soumission choisie peut préserver un peuple."
    noam "Tu respectes qui exactement ?"
    sael "Ceux qui tiennent debout quand le monde se serre."
    "Le silence revient brièvement, puis repart."
    noam "Tu n'as jamais peur ?"
    sael "Si. Mais je l'organise pour qu'elle ne me dirige pas."
    noam "Tu vois un avenir ici ?"
    sael "Je vois des fenêtres de survie, pas des promesses."
    "Le silence revient brièvement, puis repart."
    noam "Tu peux pardonner la faiblesse ?"
    sael "Je peux l'encadrer, pas l'ériger en principe."
    noam "Qu'est-ce qui compte le plus pour toi ?"
    sael "La continuité du groupe, puis la dignité qui reste."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu parles de force comme d'une morale ?"
    sael "Parce que dans ma tribu, survivre est un devoir collectif."
    noam "Tu crois vraiment à Kami ?"
    sael "Je crois à sa puissance, pas à sa tendresse."
    "Le silence revient brièvement, puis repart."
    noam "Tu choisis la soumission ?"
    sael "Oui. Une soumission choisie peut préserver un peuple."
    noam "Tu respectes qui exactement ?"
    sael "Ceux qui tiennent debout quand le monde se serre."
    "Le silence revient brièvement, puis repart."
    noam "Tu n'as jamais peur ?"
    sael "Si. Mais je l'organise pour qu'elle ne me dirige pas."
    noam "Tu vois un avenir ici ?"
    sael "Je vois des fenêtres de survie, pas des promesses."
    "Le silence revient brièvement, puis repart."
    noam "Tu peux pardonner la faiblesse ?"
    sael "Je peux l'encadrer, pas l'ériger en principe."
    noam "Qu'est-ce qui compte le plus pour toi ?"
    sael "La continuité du groupe, puis la dignité qui reste."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu parles de force comme d'une morale ?"
    sael "Parce que dans ma tribu, survivre est un devoir collectif."
    noam "Tu crois vraiment à Kami ?"
    sael "Je crois à sa puissance, pas à sa tendresse."
    "Le silence revient brièvement, puis repart."
    noam "Tu choisis la soumission ?"
    sael "Oui. Une soumission choisie peut préserver un peuple."
    noam "Tu respectes qui exactement ?"
    sael "Ceux qui tiennent debout quand le monde se serre."
    "Le silence revient brièvement, puis repart."
    noam "Tu n'as jamais peur ?"
    sael "Si. Mais je l'organise pour qu'elle ne me dirige pas."
    noam "Tu vois un avenir ici ?"
    sael "Je vois des fenêtres de survie, pas des promesses."
    "Le silence revient brièvement, puis repart."
    noam "Tu peux pardonner la faiblesse ?"
    sael "Je peux l'encadrer, pas l'ériger en principe."
    noam "Qu'est-ce qui compte le plus pour toi ?"
    sael "La continuité du groupe, puis la dignité qui reste."
    "Le silence revient brièvement, puis repart."
    sael "On devrait reprendre cette discussion plus tard."
    noam "D'accord."
    sael "Même dans un temps libre, on apprend des choses utiles."

    $ sael_link = 2

    jump FREE_TIME_END

label sael_link_3:

    play music "music/bgm_careful_wanting.mp3" fadein 1.0
    scene bg_archive at adaptive_fullscreen

    $ showP("sael", "neutre", 0.70)
    $ showP("noam", "reflexion", 0.24)

    "Sael est déjà là quand j'arrive."
    "L'atmosphère est stable, mais tendue sous la surface."
    "On prend quelques secondes avant de commencer à parler."
    noam "Pourquoi tu parles de force comme d'une morale ?"
    sael "Parce que dans ma tribu, survivre est un devoir collectif."
    noam "Tu crois vraiment à Kami ?"
    sael "Je crois à sa puissance, pas à sa tendresse."
    "Le silence revient brièvement, puis repart."
    noam "Tu choisis la soumission ?"
    sael "Oui. Une soumission choisie peut préserver un peuple."
    noam "Tu respectes qui exactement ?"
    sael "Ceux qui tiennent debout quand le monde se serre."
    "Le silence revient brièvement, puis repart."
    noam "Tu n'as jamais peur ?"
    sael "Si. Mais je l'organise pour qu'elle ne me dirige pas."
    noam "Tu vois un avenir ici ?"
    sael "Je vois des fenêtres de survie, pas des promesses."
    "Le silence revient brièvement, puis repart."
    noam "Tu peux pardonner la faiblesse ?"
    sael "Je peux l'encadrer, pas l'ériger en principe."
    noam "Qu'est-ce qui compte le plus pour toi ?"
    sael "La continuité du groupe, puis la dignité qui reste."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu parles de force comme d'une morale ?"
    sael "Parce que dans ma tribu, survivre est un devoir collectif."
    noam "Tu crois vraiment à Kami ?"
    sael "Je crois à sa puissance, pas à sa tendresse."
    "Le silence revient brièvement, puis repart."
    noam "Tu choisis la soumission ?"
    sael "Oui. Une soumission choisie peut préserver un peuple."
    noam "Tu respectes qui exactement ?"
    sael "Ceux qui tiennent debout quand le monde se serre."
    "Le silence revient brièvement, puis repart."
    noam "Tu n'as jamais peur ?"
    sael "Si. Mais je l'organise pour qu'elle ne me dirige pas."
    noam "Tu vois un avenir ici ?"
    sael "Je vois des fenêtres de survie, pas des promesses."
    "Le silence revient brièvement, puis repart."
    noam "Tu peux pardonner la faiblesse ?"
    sael "Je peux l'encadrer, pas l'ériger en principe."
    noam "Qu'est-ce qui compte le plus pour toi ?"
    sael "La continuité du groupe, puis la dignité qui reste."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu parles de force comme d'une morale ?"
    sael "Parce que dans ma tribu, survivre est un devoir collectif."
    noam "Tu crois vraiment à Kami ?"
    sael "Je crois à sa puissance, pas à sa tendresse."
    "Le silence revient brièvement, puis repart."
    noam "Tu choisis la soumission ?"
    sael "Oui. Une soumission choisie peut préserver un peuple."
    noam "Tu respectes qui exactement ?"
    sael "Ceux qui tiennent debout quand le monde se serre."
    "Le silence revient brièvement, puis repart."
    noam "Tu n'as jamais peur ?"
    sael "Si. Mais je l'organise pour qu'elle ne me dirige pas."
    noam "Tu vois un avenir ici ?"
    sael "Je vois des fenêtres de survie, pas des promesses."
    "Le silence revient brièvement, puis repart."
    noam "Tu peux pardonner la faiblesse ?"
    sael "Je peux l'encadrer, pas l'ériger en principe."
    noam "Qu'est-ce qui compte le plus pour toi ?"
    sael "La continuité du groupe, puis la dignité qui reste."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu parles de force comme d'une morale ?"
    sael "Parce que dans ma tribu, survivre est un devoir collectif."
    noam "Tu crois vraiment à Kami ?"
    sael "Je crois à sa puissance, pas à sa tendresse."
    "Le silence revient brièvement, puis repart."
    noam "Tu choisis la soumission ?"
    sael "Oui. Une soumission choisie peut préserver un peuple."
    noam "Tu respectes qui exactement ?"
    sael "Ceux qui tiennent debout quand le monde se serre."
    "Le silence revient brièvement, puis repart."
    noam "Tu n'as jamais peur ?"
    sael "Si. Mais je l'organise pour qu'elle ne me dirige pas."
    noam "Tu vois un avenir ici ?"
    sael "Je vois des fenêtres de survie, pas des promesses."
    "Le silence revient brièvement, puis repart."
    noam "Tu peux pardonner la faiblesse ?"
    sael "Je peux l'encadrer, pas l'ériger en principe."
    noam "Qu'est-ce qui compte le plus pour toi ?"
    sael "La continuité du groupe, puis la dignité qui reste."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu parles de force comme d'une morale ?"
    sael "Parce que dans ma tribu, survivre est un devoir collectif."
    noam "Tu crois vraiment à Kami ?"
    sael "Je crois à sa puissance, pas à sa tendresse."
    "Le silence revient brièvement, puis repart."
    noam "Tu choisis la soumission ?"
    sael "Oui. Une soumission choisie peut préserver un peuple."
    noam "Tu respectes qui exactement ?"
    sael "Ceux qui tiennent debout quand le monde se serre."
    "Le silence revient brièvement, puis repart."
    noam "Tu n'as jamais peur ?"
    sael "Si. Mais je l'organise pour qu'elle ne me dirige pas."
    noam "Tu vois un avenir ici ?"
    sael "Je vois des fenêtres de survie, pas des promesses."
    "Le silence revient brièvement, puis repart."
    noam "Tu peux pardonner la faiblesse ?"
    sael "Je peux l'encadrer, pas l'ériger en principe."
    noam "Qu'est-ce qui compte le plus pour toi ?"
    sael "La continuité du groupe, puis la dignité qui reste."
    "Le silence revient brièvement, puis repart."
    sael "On devrait reprendre cette discussion plus tard."
    noam "D'accord."
    sael "Même dans un temps libre, on apprend des choses utiles."

    $ sael_link = 3

    jump FREE_TIME_END

label sael_link_4:

    play music "music/bgm_quiet_routine.mp3" fadein 1.0
    scene bg_conclave at adaptive_fullscreen

    $ showP("sael", "neutre", 0.70)
    $ showP("noam", "reflexion", 0.24)

    "Sael est déjà là quand j'arrive."
    "L'atmosphère est stable, mais tendue sous la surface."
    "On prend quelques secondes avant de commencer à parler."
    noam "Pourquoi tu parles de force comme d'une morale ?"
    sael "Parce que dans ma tribu, survivre est un devoir collectif."
    noam "Tu crois vraiment à Kami ?"
    sael "Je crois à sa puissance, pas à sa tendresse."
    "Le silence revient brièvement, puis repart."
    noam "Tu choisis la soumission ?"
    sael "Oui. Une soumission choisie peut préserver un peuple."
    noam "Tu respectes qui exactement ?"
    sael "Ceux qui tiennent debout quand le monde se serre."
    "Le silence revient brièvement, puis repart."
    noam "Tu n'as jamais peur ?"
    sael "Si. Mais je l'organise pour qu'elle ne me dirige pas."
    noam "Tu vois un avenir ici ?"
    sael "Je vois des fenêtres de survie, pas des promesses."
    "Le silence revient brièvement, puis repart."
    noam "Tu peux pardonner la faiblesse ?"
    sael "Je peux l'encadrer, pas l'ériger en principe."
    noam "Qu'est-ce qui compte le plus pour toi ?"
    sael "La continuité du groupe, puis la dignité qui reste."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu parles de force comme d'une morale ?"
    sael "Parce que dans ma tribu, survivre est un devoir collectif."
    noam "Tu crois vraiment à Kami ?"
    sael "Je crois à sa puissance, pas à sa tendresse."
    "Le silence revient brièvement, puis repart."
    noam "Tu choisis la soumission ?"
    sael "Oui. Une soumission choisie peut préserver un peuple."
    noam "Tu respectes qui exactement ?"
    sael "Ceux qui tiennent debout quand le monde se serre."
    "Le silence revient brièvement, puis repart."
    noam "Tu n'as jamais peur ?"
    sael "Si. Mais je l'organise pour qu'elle ne me dirige pas."
    noam "Tu vois un avenir ici ?"
    sael "Je vois des fenêtres de survie, pas des promesses."
    "Le silence revient brièvement, puis repart."
    noam "Tu peux pardonner la faiblesse ?"
    sael "Je peux l'encadrer, pas l'ériger en principe."
    noam "Qu'est-ce qui compte le plus pour toi ?"
    sael "La continuité du groupe, puis la dignité qui reste."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu parles de force comme d'une morale ?"
    sael "Parce que dans ma tribu, survivre est un devoir collectif."
    noam "Tu crois vraiment à Kami ?"
    sael "Je crois à sa puissance, pas à sa tendresse."
    "Le silence revient brièvement, puis repart."
    noam "Tu choisis la soumission ?"
    sael "Oui. Une soumission choisie peut préserver un peuple."
    noam "Tu respectes qui exactement ?"
    sael "Ceux qui tiennent debout quand le monde se serre."
    "Le silence revient brièvement, puis repart."
    noam "Tu n'as jamais peur ?"
    sael "Si. Mais je l'organise pour qu'elle ne me dirige pas."
    noam "Tu vois un avenir ici ?"
    sael "Je vois des fenêtres de survie, pas des promesses."
    "Le silence revient brièvement, puis repart."
    noam "Tu peux pardonner la faiblesse ?"
    sael "Je peux l'encadrer, pas l'ériger en principe."
    noam "Qu'est-ce qui compte le plus pour toi ?"
    sael "La continuité du groupe, puis la dignité qui reste."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu parles de force comme d'une morale ?"
    sael "Parce que dans ma tribu, survivre est un devoir collectif."
    noam "Tu crois vraiment à Kami ?"
    sael "Je crois à sa puissance, pas à sa tendresse."
    "Le silence revient brièvement, puis repart."
    noam "Tu choisis la soumission ?"
    sael "Oui. Une soumission choisie peut préserver un peuple."
    noam "Tu respectes qui exactement ?"
    sael "Ceux qui tiennent debout quand le monde se serre."
    "Le silence revient brièvement, puis repart."
    noam "Tu n'as jamais peur ?"
    sael "Si. Mais je l'organise pour qu'elle ne me dirige pas."
    noam "Tu vois un avenir ici ?"
    sael "Je vois des fenêtres de survie, pas des promesses."
    "Le silence revient brièvement, puis repart."
    noam "Tu peux pardonner la faiblesse ?"
    sael "Je peux l'encadrer, pas l'ériger en principe."
    noam "Qu'est-ce qui compte le plus pour toi ?"
    sael "La continuité du groupe, puis la dignité qui reste."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu parles de force comme d'une morale ?"
    sael "Parce que dans ma tribu, survivre est un devoir collectif."
    noam "Tu crois vraiment à Kami ?"
    sael "Je crois à sa puissance, pas à sa tendresse."
    "Le silence revient brièvement, puis repart."
    noam "Tu choisis la soumission ?"
    sael "Oui. Une soumission choisie peut préserver un peuple."
    noam "Tu respectes qui exactement ?"
    sael "Ceux qui tiennent debout quand le monde se serre."
    "Le silence revient brièvement, puis repart."
    noam "Tu n'as jamais peur ?"
    sael "Si. Mais je l'organise pour qu'elle ne me dirige pas."
    noam "Tu vois un avenir ici ?"
    sael "Je vois des fenêtres de survie, pas des promesses."
    "Le silence revient brièvement, puis repart."
    noam "Tu peux pardonner la faiblesse ?"
    sael "Je peux l'encadrer, pas l'ériger en principe."
    noam "Qu'est-ce qui compte le plus pour toi ?"
    sael "La continuité du groupe, puis la dignité qui reste."
    "Le silence revient brièvement, puis repart."
    sael "On devrait reprendre cette discussion plus tard."
    noam "D'accord."
    sael "Même dans un temps libre, on apprend des choses utiles."

    $ sael_link = 4

    jump FREE_TIME_END

label sael_link_5:

    play music "music/bgm_cold_metadata.mp3" fadein 1.0
    scene bg_sas at adaptive_fullscreen

    $ showP("sael", "neutre", 0.70)
    $ showP("noam", "reflexion", 0.24)

    "Sael est déjà là quand j'arrive."
    "L'atmosphère est stable, mais tendue sous la surface."
    "On prend quelques secondes avant de commencer à parler."
    noam "Pourquoi tu parles de force comme d'une morale ?"
    sael "Parce que dans ma tribu, survivre est un devoir collectif."
    noam "Tu crois vraiment à Kami ?"
    sael "Je crois à sa puissance, pas à sa tendresse."
    "Le silence revient brièvement, puis repart."
    noam "Tu choisis la soumission ?"
    sael "Oui. Une soumission choisie peut préserver un peuple."
    noam "Tu respectes qui exactement ?"
    sael "Ceux qui tiennent debout quand le monde se serre."
    "Le silence revient brièvement, puis repart."
    noam "Tu n'as jamais peur ?"
    sael "Si. Mais je l'organise pour qu'elle ne me dirige pas."
    noam "Tu vois un avenir ici ?"
    sael "Je vois des fenêtres de survie, pas des promesses."
    "Le silence revient brièvement, puis repart."
    noam "Tu peux pardonner la faiblesse ?"
    sael "Je peux l'encadrer, pas l'ériger en principe."
    noam "Qu'est-ce qui compte le plus pour toi ?"
    sael "La continuité du groupe, puis la dignité qui reste."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu parles de force comme d'une morale ?"
    sael "Parce que dans ma tribu, survivre est un devoir collectif."
    noam "Tu crois vraiment à Kami ?"
    sael "Je crois à sa puissance, pas à sa tendresse."
    "Le silence revient brièvement, puis repart."
    noam "Tu choisis la soumission ?"
    sael "Oui. Une soumission choisie peut préserver un peuple."
    noam "Tu respectes qui exactement ?"
    sael "Ceux qui tiennent debout quand le monde se serre."
    "Le silence revient brièvement, puis repart."
    noam "Tu n'as jamais peur ?"
    sael "Si. Mais je l'organise pour qu'elle ne me dirige pas."
    noam "Tu vois un avenir ici ?"
    sael "Je vois des fenêtres de survie, pas des promesses."
    "Le silence revient brièvement, puis repart."
    noam "Tu peux pardonner la faiblesse ?"
    sael "Je peux l'encadrer, pas l'ériger en principe."
    noam "Qu'est-ce qui compte le plus pour toi ?"
    sael "La continuité du groupe, puis la dignité qui reste."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu parles de force comme d'une morale ?"
    sael "Parce que dans ma tribu, survivre est un devoir collectif."
    noam "Tu crois vraiment à Kami ?"
    sael "Je crois à sa puissance, pas à sa tendresse."
    "Le silence revient brièvement, puis repart."
    noam "Tu choisis la soumission ?"
    sael "Oui. Une soumission choisie peut préserver un peuple."
    noam "Tu respectes qui exactement ?"
    sael "Ceux qui tiennent debout quand le monde se serre."
    "Le silence revient brièvement, puis repart."
    noam "Tu n'as jamais peur ?"
    sael "Si. Mais je l'organise pour qu'elle ne me dirige pas."
    noam "Tu vois un avenir ici ?"
    sael "Je vois des fenêtres de survie, pas des promesses."
    "Le silence revient brièvement, puis repart."
    noam "Tu peux pardonner la faiblesse ?"
    sael "Je peux l'encadrer, pas l'ériger en principe."
    noam "Qu'est-ce qui compte le plus pour toi ?"
    sael "La continuité du groupe, puis la dignité qui reste."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu parles de force comme d'une morale ?"
    sael "Parce que dans ma tribu, survivre est un devoir collectif."
    noam "Tu crois vraiment à Kami ?"
    sael "Je crois à sa puissance, pas à sa tendresse."
    "Le silence revient brièvement, puis repart."
    noam "Tu choisis la soumission ?"
    sael "Oui. Une soumission choisie peut préserver un peuple."
    noam "Tu respectes qui exactement ?"
    sael "Ceux qui tiennent debout quand le monde se serre."
    "Le silence revient brièvement, puis repart."
    noam "Tu n'as jamais peur ?"
    sael "Si. Mais je l'organise pour qu'elle ne me dirige pas."
    noam "Tu vois un avenir ici ?"
    sael "Je vois des fenêtres de survie, pas des promesses."
    "Le silence revient brièvement, puis repart."
    noam "Tu peux pardonner la faiblesse ?"
    sael "Je peux l'encadrer, pas l'ériger en principe."
    noam "Qu'est-ce qui compte le plus pour toi ?"
    sael "La continuité du groupe, puis la dignité qui reste."
    "Le silence revient brièvement, puis repart."
    noam "Pourquoi tu parles de force comme d'une morale ?"
    sael "Parce que dans ma tribu, survivre est un devoir collectif."
    noam "Tu crois vraiment à Kami ?"
    sael "Je crois à sa puissance, pas à sa tendresse."
    "Le silence revient brièvement, puis repart."
    noam "Tu choisis la soumission ?"
    sael "Oui. Une soumission choisie peut préserver un peuple."
    noam "Tu respectes qui exactement ?"
    sael "Ceux qui tiennent debout quand le monde se serre."
    "Le silence revient brièvement, puis repart."
    noam "Tu n'as jamais peur ?"
    sael "Si. Mais je l'organise pour qu'elle ne me dirige pas."
    noam "Tu vois un avenir ici ?"
    sael "Je vois des fenêtres de survie, pas des promesses."
    "Le silence revient brièvement, puis repart."
    noam "Tu peux pardonner la faiblesse ?"
    sael "Je peux l'encadrer, pas l'ériger en principe."
    noam "Qu'est-ce qui compte le plus pour toi ?"
    sael "La continuité du groupe, puis la dignité qui reste."
    "Le silence revient brièvement, puis repart."
    sael "On devrait reprendre cette discussion plus tard."
    noam "D'accord."
    sael "Même dans un temps libre, on apprend des choses utiles."

    $ sael_link = 5

    jump FREE_TIME_END

