label _17_0_1_1_0_ANNONCE_KAMI:
    scene bg_chambre at adaptive_fullscreen with fade
    play music "music/bgm_cold_metadata.mp3" fadein 2.0

    "Je n'ai pas dormi. J'ai seulement ferme les yeux assez longtemps pour perdre la notion de l'heure."
    think "Operateur : Noam."
    think "Deux mots et toute ma vie devient une piece a conviction."
    play sound sfx_beep
    kami "Bonjour, mes chers representants."
    noam fatigue "Pas maintenant."
    kami "Je sais que plusieurs d'entre vous ont consulte leurs archives medicales."
    noam inquiet "Tu sais toujours tout apres coup."
    kami "Cette lecture a produit des reactions excessives."
    noam colere "Memoire modifiee, c'est excessif comme formulation aussi."
    kami "Les mots administratifs manquent parfois de tendresse."
    noam "Et les tortionnaires de vocabulaire."
    kami "Afin de preserver votre stabilite, les prochains votes sont annules."
    noam surpris "Annules ?"
    kami "Jusqu'a nouvel ordre."
    noam "Tu nous enfermes ici sans meme faire semblant de nous consulter."
    kami "Je vous dispense d'une pression devenue contre-productive."
    noam colere "Tu nous retires la seule chose qui justifiait notre presence."
    kami "Votre presence n'a jamais eu besoin de justification."
    noam "La notre, peut-etre. La tienne, si."
    kami "Je comprends ta colere, Noam."
    noam "Non. Tu la mesures. Ce n'est pas pareil."
    kami "Reposez-vous. Mangez. Parlez-vous."
    kami "Et evitez les archives jusqu'a nouvel ordre."
    noam reflexion "Pourquoi ?"
    kami "Parce qu'elles vous font du mal."
    noam "Ou parce qu'elles disent vrai ?"
    kami "Bonne journee."
    play sound sfx_gresillement
    "La transmission se coupe."
    noam colere "Kami !"
    "Le silence me repond avec sa patience habituelle."
    think "Plus de votes. Plus d'archives."
    think "Elle ferme toutes les portes au moment exact ou nous trouvons une serrure."
    jump _17_0_1_1_0_COUULOIR_REACTIONS

label _17_0_1_1_0_COUULOIR_REACTIONS:
    call MAYBE_PLAY_SCRIPTED_DOOR("couloir", "bg_couloir") from _call_MAYBE_PLAY_SCRIPTED_DOOR_103
    scene bg_couloir at adaptive_fullscreen with dissolve
    $ showGroup([("noam", "fatigue", 0.12), ("mara", "agace", 0.31), ("tomas", "inquiet", 0.50), ("kael", "mefiant", 0.69), ("sael", "neutre", 0.86)])
    mara colere "Annules. Comme ca. Elle annonce ca avant le petit-dejeuner."
    tomas raison "Techniquement, elle a dit jusqu'a nouvel ordre."
    mara agace "Merci Tomas. La prison est temporaire jusqu'a ce qu'elle devienne definitive."
    tomas culpabilite "Je voulais seulement preciser."
    kael mefiant "Elle a peur des archives."
    sael neutre "Ou de ce que nous ferons apres les avoir lues."
    noam inquiet "Vous avez tous vu la mention ?"
    mara "Oui."
    tomas "Oui."
    kael "Oui."
    sael "Nous l'avons vue. Nous ne savons pas si nous pouvons croire ce souvenir."
    mara stress "Tu peux eviter ce genre de phrase avant que j'aie bu quelque chose ?"
    noam "Mon dossier disait que j'etais l'operateur."
    "Le groupe se fige."
    mara mefiant "L'operateur de quoi ?"
    noam "De ma propre modification. Jour quinze, vingt heures vingt-quatre."
    kael colere "L'heure du trou noir."
    tomas reflechit "Un sujet ne peut pas etre son propre operateur pendant une perte de conscience."
    mara "Tu dis ca comme si le systeme respectait encore la logique."
    sael raison "Il respecte une logique. Ce n'est simplement pas la notre."
    noam "Je ne sais plus ce que j'ai fait."
    mara mefiant "Ca, on avait remarque."
    noam colere "Tu crois que ca m'amuse ?"
    mara colere "Je crois que tu nous caches des choses depuis des jours."
    noam "Parce que je ne sais meme plus lesquelles sont vraies !"
    kael "Baissez d'un ton."
    mara "Pourquoi ? Kami pourrait nous entendre ?"
    sael "Elle nous entend."
    mara rire_profond "Parfait. Alors qu'elle entende ca : va te faire voir, Kami."
    kami "Message recu, Mara."
    mara vide "... Je la deteste."
    tomas "L'annulation des votes modifie notre objectif."
    noam "Notre objectif reste de sortir."
    kael "Non. D'abord, notre objectif est de savoir lequel d'entre nous peut traverser une nuit sans devenir quelqu'un d'autre."
    mara mefiant "Tu me regardes en disant ca ?"
    kael "Je regarde tout le monde."
    sael "C'est ainsi qu'elle gagne."
    noam "En nous faisant douter ?"
    sael "En nous faisant croire que le doute est une preuve."
    tomas reflechit "Nous avons besoin de traces physiques."
    mara "Des objets. Des marques. Quelque chose qu'une memoire ne peut pas reecrire."
    noam "Les cameras ont deja menti."
    tomas "Une camera est une archive. Une rayure dans du metal ne l'est pas."
    kael raison "Alors on cherche des rayures."
    mara agace "Magnifique programme pour une journee sans vote."
    sael "Restez visibles les uns pour les autres."
    noam "Et si l'un de nous est justement le probleme ?"
    sael triste "Alors il sera visible aussi."
    jump _17_0_1_1_0_CAFETERIA

label _17_0_1_1_0_CAFETERIA:
    call MAYBE_PLAY_SCRIPTED_DOOR("cafeteria", "bg_cafeteria") from _call_MAYBE_PLAY_SCRIPTED_DOOR_104
    scene bg_cafeteria at adaptive_fullscreen with dissolve
    play music "music/bgm_introspective_atmosphere.mp3" fadein 1.5
    $ showGroup([("noam", "reflexion", 0.18), ("mara", "stress", 0.42), ("tomas", "reflechit", 0.66)])
    goumi "Trois boissons chaudes. J'ai suppose que personne ne voulait choisir."
    mara "Tu nous connais trop bien."
    tomas "Le choix est statistiquement plus difficile sous stress."
    mara taquin "Et voila pourquoi on invite Tomas au petit-dejeuner."
    noam "Vous vous souvenez de votre arrivee ici ?"
    mara mefiant "Question legere."
    tomas "Oui. Sas, lumiere blanche, onze personnes."
    mara "Douze."
    tomas "Noam est arrive apres."
    noam inquiet "Je me souviens avoir ete la avant Kael."
    mara "Kael etait deja assis quand je suis entree."
    tomas "Non. Il est arrive apres Iris."
    mara stress "Stop."
    noam "Trois souvenirs, trois ordres."
    tomas reflechit "Une divergence ne prouve pas une modification. La memoire ordinaire est reconstructive."
    mara agace "La memoire ordinaire n'a pas un dossier medical marque en rouge."
    noam "Et ton Clone ?"
    mara vide "Quoi, mon Clone ?"
    noam "Tu disais qu'il avait parfois tes souvenirs."
    mara mefiant "J'ai dit qu'il imitait mes reactions."
    noam "Tu avais dit souvenirs."
    mara colere "Non."
    tomas hesitation "Je crois aussi avoir entendu souvenirs."
    mara "Super. Deux cerveaux defectueux contre le mien."
    noam "Je ne t'accuse pas."
    mara "Tu ne sais plus faire autre chose."
    noam colere "Et toi, tu plaisantes des qu'une question te fait peur."
    mara stress "Parce que sinon je crie."
    tomas "Vous etes en train de crier."
    mara "Je peux faire pire."
    goumi "Pas avec les tasses, s'il vous plait."
    noam fatigue "Pardon."
    mara fatigue "Ouais. Pardon, Goumi."
    tomas "Nous devrions etablir un protocole."
    mara "Interdiction de prononcer protocole avant midi."
    tomas "Une regle, alors."
    noam "Laquelle ?"
    tomas raison "Chaque soir, nous gravons un signe discret dans un lieu choisi ensemble. Le lendemain, nous le verifions."
    mara reflexion "Et si quelqu'un le copie ?"
    tomas "Il faut deux elements : une forme et un mot connu de personnes differentes."
    noam "Une memoire partagee peut etre modifiee."
    tomas "Oui. Mais une trace physique force l'operateur a intervenir dans le monde reel."
    mara "Ca ne nous sauve pas."
    tomas "Non. Ca augmente le cout du mensonge."
    noam "On commence ce soir."
    mara mefiant "Pas dans ma chambre."
    noam "Je n'ai rien demande."
    mara "Je prefere preciser."
    tomas "La maintenance serait adaptee."
    mara "Alors rendez-vous la-bas a vingt-deux heures."
    noam "Tous les trois ?"
    mara "Tous les trois. Si l'un manque, les deux autres ne font rien."
    tomas "D'accord."
    noam "D'accord."
    "Mara leve sa tasse."
    mara taquin "Aux souvenirs mediocres."
    tomas "Pourquoi mediocres ?"
    mara "Parce que les bons attirent l'attention."
    noam sourire "Aux souvenirs mediocres."
    jump _17_0_1_1_0_GRATTEMENTS

label _17_0_1_1_0_GRATTEMENTS:
    call MAYBE_PLAY_SCRIPTED_DOOR("chambre", "bg_chambre") from _call_MAYBE_PLAY_SCRIPTED_DOOR_105
    scene bg_chambre at adaptive_fullscreen with fade
    play music "music/bgm_fatal_assembly.mp3" fadein 2.0
    "Vingt et une heures cinquante-sept. Je suis assis sur le lit, chaussures aux pieds."
    think "Trois minutes avant la maintenance."
    play sound sfx_metal_clank volume 0.35
    "Un frottement sec traverse le mur."
    noam inquiet "..."
    play sound sfx_metal_clank volume 0.45
    "Scrrrt. Une pause. Scrrrt."
    noam "Kami ?"
    "Aucune reponse."
    noam colere "Je sais que tu m'entends."
    "Le bruit reprend, plus pres du lit."
    think "Dans le mur."
    noam peur "Il y a quelqu'un ?"
    "Trois coups brefs repondent."
    noam panique "Mara ? Tomas ?"
    "Je colle l'oreille contre la paroi. Un souffle circule derriere la grille d'aeration."
    noam inquiet "Si tu m'entends, frappe deux fois."
    play sound sfx_metal_clank volume 0.5
    play sound sfx_metal_clank volume 0.5
    "Deux coups."
    noam peur "Qui es-tu ?"
    "Le metal geint. Une vis tourne de l'autre cote."
    noam "Arrete."
    "La grille bouge d'un millimetre."
    noam panique "Arrete !"
    play sound sfx_glitch volume 0.8
    kami "Noam, ta frequence cardiaque est elevee."
    noam colere "Il y a quelqu'un dans l'aeration !"
    kami "Les conduits ne sont pas accessibles aux representants."
    noam "Alors qui vient de me repondre ?"
    kami "Tu es fatigue."
    noam "Deux coups, Kami. Il a compris ma question."
    kami "Reste eloigne de la grille."
    noam surpris "Pourquoi ?"
    kami "C'est une consigne de securite."
    noam "Donc il y a bien quelque chose."
    kami "Reste eloigne de la grille."
    "La voix disparait. La vis cesse de tourner."
    noam determine "D'accord."
    noam "Demain, je l'ouvre."
    "Dans le mur, quelque chose gratte une derniere fois."
    call end_day("18") from _call_end_day_18
    jump _18_0_1_1_0_REVEIL_DECISION
