label _19_0_1_1_0_BARRICADE:
    call MAYBE_PLAY_SCRIPTED_DOOR("chambre", "bg_chambre") from _call_MAYBE_PLAY_SCRIPTED_DOOR_110
    scene bg_chambre at adaptive_fullscreen with fade
    play music "music/bgm_fatal_assembly.mp3" fadein 1.5
    "Je pousse le bureau contre la porte, puis la chaise contre le bureau."
    kami "Cette disposition bloque une issue de secours."
    noam "C'est le principe."
    kami "Tu risques de te blesser."
    noam "Toi aussi, tu prends gout aux menaces."
    kami "Je m'inquiete."
    noam "Alors ouvre les portes du Conclave."
    kami "Ce n'est pas possible."
    noam "Retablis les votes."
    kami "Ce n'est pas souhaitable."
    noam "Dis-moi qui rampe dans les murs."
    kami "Personne."
    noam "Trois questions, trois facons de dire non."
    kami "Eloigne le mobilier de la porte."
    noam "Non."
    kami "Noam."
    noam "Kami."
    kami "Tu cherches une confrontation."
    noam "Je cherche une nuit dont je me souviendrai."
    kami "La barricade n'empechera pas une intervention medicale."
    noam inquiet "C'est cense me rassurer ?"
    kami "C'est cense t'informer."
    noam "Tu parles comme le robot."
    kami "Le robot parle comme moi."
    noam "Ca explique son charme."
    "Je tends un fil entre la grille et le pied du lit. S'il casse, quelqu'un est entre."
    noam "Cette nuit, personne ne passe."
    play sound sfx_metal_clank volume 0.3
    "Un frottement repond derriere la grille."
    noam "Sauf moi."
    jump _19_0_1_1_0_ENTREE_CONDUIT

label _19_0_1_1_0_ENTREE_CONDUIT:
    call MAYBE_PLAY_SCRIPTED_DOOR("chambre", "bg_chambre") from _call_MAYBE_PLAY_SCRIPTED_DOOR_111
    scene bg_chambre at adaptive_fullscreen with dissolve
    $ showGroup([("noam", "determine", 0.27), ("mara", "stress", 0.67)])
    mara "Tu as barricade la porte et ensuite tu m'as appelee."
    noam "Je voulais savoir si quelqu'un pouvait entrer."
    mara "Et maintenant je suis coincee dedans avec toi."
    noam "Tu peux repartir avant que je bloque tout."
    mara mefiant "Et te laisser devenir une anecdote dans un conduit ? Non."
    noam "Tu te souviens d'hier ?"
    mara "Grille. Fibres rouges. Semelle. Kami connaissait mon Clone."
    noam "Quelle vis as-tu remplacee ?"
    mara "En bas a droite. Tete plate au lieu d'une cruciforme."
    noam "C'est exact."
    mara "Ta phrase scellee ?"
    noam "'Le mur respire plus froid que la chambre.'"
    mara "La mienne : 'Kami prononce Clone comme un nom propre.'"
    noam "Nous nous souvenons."
    mara fatigue "Pour l'instant."
    noam "Tu n'es pas obligee de venir."
    mara "Je sais."
    noam "Tu peux tenir le fil."
    mara "Et t'entendre suffoquer a trois metres ?"
    noam "Cinq, peut-etre."
    mara agace "Tu ne sais vraiment pas vendre une idee."
    noam "Je passe devant."
    mara "Non."
    noam "C'est ma chambre."
    mara "C'est mon outil qui a ouvert la grille."
    noam "Argument ridicule."
    mara taquin "Argument gagnant."
    noam "On ne sait pas ou ca mene."
    mara "Justement. Si quelque chose m'attend, tu tires sur mes chevilles."
    noam "C'est ton plan ?"
    mara "Mon plan, c'est de ne pas paniquer assez fort pour rester coincee."
    noam "Rassurant."
    mara "Lampe fixee ?"
    noam "Oui."
    mara "Sachet de fibres ?"
    noam "Dans ma poche."
    mara "Corde ?"
    noam "Attachee au lit."
    mara "Si le lit bouge ?"
    noam "La barricade le bloque."
    mara sourire "Tu apprends."
    kami "N'entrez pas dans le conduit."
    mara "Elle aussi est prete."
    noam "Pourquoi, Kami ?"
    kami "Danger structurel."
    mara "Mensonge structurel."
    kami "Je peux verrouiller votre chambre."
    noam "Elle l'est deja."
    kami "Je peux appeler une unite medicale."
    mara colere "Et nous effacer encore une soiree ?"
    kami "Je ne vous efface pas."
    noam "Alors laisse-nous verifier."
    kami "Non."
    mara "Bonne reponse. J'avais besoin d'une motivation."
    "Mara glisse les epaules dans l'ouverture."
    mara stress "C'est plus etroit que prevu."
    noam "Tu veux ressortir ?"
    mara colere "Ne pose pas cette question."
    noam "Pourquoi ?"
    mara "Parce que j'ai envie de dire oui."
    noam "Alors dis oui."
    mara "Pousse mes pieds."
    noam "Mara..."
    mara colere_noire "Pousse !"
    "Je pousse. Elle disparait dans le noir."
    mara "Je suis passee."
    noam "Tu vois quoi ?"
    mara "Du metal. De la poussiere. Et la pire idee de ma semaine."
    noam "J'arrive."
    jump _19_0_1_1_0_RESEAU

label _19_0_1_1_0_RESEAU:
    scene black with dissolve
    play music "music/bgm_cold_metadata.mp3" fadein 1.5
    mara "Ne pose pas ta main a gauche."
    noam "Pourquoi ?"
    mara "Bord coupe."
    noam "Merci."
    mara "Genou droit sur la traverse."
    noam "Je ne vois rien."
    mara "Suis ma voix."
    noam "Elle resonne partout."
    mara "Alors suis la voix qui t'insulte."
    noam "Ca reduit a peine les possibilites."
    mara "Avance."
    "Le conduit avale chaque respiration et la renvoie plus loin, deformee."
    noam "Il y a une bifurcation."
    mara "Marque-la."
    noam "Avec quoi ?"
    mara "Craie. Poche gauche."
    noam "Tu as pense a tout."
    mara "Non. J'ai peur de tout. C'est different."
    noam "Fleche vers la chambre."
    mara "Et un M."
    noam "Pourquoi M ?"
    mara "Pour mur."
    noam "Pas pour Mara ?"
    mara "Ne rends pas ca sentimental."
    play sound sfx_metal_clank volume 0.35
    noam "Attends."
    mara "Quoi ?"
    noam "Une voix en dessous."
    iris "... je te dis que je n'ai pas pris sa ration."
    elen "Je ne t'accuse pas."
    iris "Tu as cette voix."
    elen "Quelle voix ?"
    iris "Celle qui pardonne avant meme qu'on avoue."
    mara "On est au-dessus de la cafeteria."
    noam "Les conduits relient toutes les salles."
    mara "Et transmettent toutes les conversations."
    noam "Quelqu'un peut ecouter sans camera."
    mara "Continue."
    noam "La branche de droite descend."
    mara "La poussiere est intacte. A gauche, elle ne l'est pas."
    noam "Traces de genoux."
    mara "Recentes."
    noam "Comment tu sais ?"
    mara "La poussiere n'est pas retombee sur les bords."
    noam "Tu as vraiment fait ca avec ton Clone ?"
    mara stress "Demonter, suivre, comparer. Oui."
    noam "Pourquoi vous vous mefiiez l'un de l'autre ?"
    mara "Parce qu'il jurait etre l'original."
    noam "Et toi aussi."
    mara "Voila."
    noam "Comment ca s'est termine ?"
    mara vide "Il est parti."
    noam "Ou ?"
    mara "Je ne sais pas."
    noam "Tu mens."
    mara colere "Je rampe dans un conduit interdit avec toi. Accorde-moi une zone fermee."
    noam "D'accord."
    mara "Stop. Grille en dessous."
    kael "... elle n'aurait jamais garde une copie."
    tomas "Nous ne savons pas ce qu'elle aurait fait."
    kael "Moi, si. C'etait ma soeur."
    tomas "Justement."
    noam "Kael et Tomas."
    mara "Ils parlent de la photo."
    kael "L'original a disparu. La copie n'existe pas."
    tomas "Une copie numerique a pu etre imprimee."
    kael "Par qui ?"
    tomas "C'est ce que j'essaie de determiner."
    mara "On continue."
    noam "Pourquoi ?"
    mara "Parce que quelqu'un les ecoute peut-etre avec nous."
    play sound sfx_metal_clank volume 0.5
    "Un choc repond devant nous."
    noam inquiet "Il y a quelqu'un."
    mara "Eteins ta lampe."
    noam "Je ne vois plus rien."
    mara "Moi non plus. Respire moins fort."
    noam "Facile a dire."
    "Une faible lueur rouge tourne au croisement."
    mara "Quelqu'un vient."
    noam "On recule ?"
    mara "Trop tard."
    noam "Qui est la ?"
    "La lueur s'immobilise."
    noam "Repondez."
    voix_off "Noam ?"
    noam peur "Cette voix..."
    mara "Tu la connais ?"
    voix_off "Tu n'aurais pas du sortir de ta chambre."
    noam panique "Qui etes-vous ?"
    voix_off "Je suis dans ma chambre."
    noam "Quelle chambre ?"
    voix_off "Toutes."
    play sound sfx_glitch volume 0.9
    "La lumiere rouge s'eteint. Un mouvement file dans la branche opposee."
    mara "Reviens !"
    noam "Attends !"
    mara "Non, Noam !"
    "Je rampe apres le bruit. La corde se tend derriere moi."
    noam "Je le vois !"
    mara "Quoi ?"
    noam "Une silhouette."
    mara "Humaine ?"
    noam "Je ne sais pas."
    voix_off "Tu sais."
    noam peur "Arrete !"
    "La silhouette tombe par une trappe."
    mara "La corde est au bout."
    noam "On peut la detacher."
    mara "Non. On garde un chemin de retour."
    noam "On etait si pres."
    mara "D'etre perdus, oui."
    noam "Cette voix ressemblait a la mienne."
    mara vide "Je sais."
    jump _19_0_1_1_0_RETOUR

label _19_0_1_1_0_RETOUR:
    call MAYBE_PLAY_SCRIPTED_DOOR("chambre", "bg_chambre") from _call_MAYBE_PLAY_SCRIPTED_DOOR_112
    scene bg_chambre at adaptive_fullscreen with fade
    $ showGroup([("noam", "peur", 0.27), ("mara", "vide", 0.67)])
    noam "Tu l'as entendue."
    mara "Oui."
    noam "Dis-le."
    mara "Elle avait ta voix."
    noam "Exactement ?"
    mara "Plus calme."
    noam "Moi, mais calme."
    mara "Ne fais pas ca."
    noam "Quoi ?"
    mara "Ne lui donne pas deja ton visage."
    noam "Elle m'a appele par mon nom."
    mara "Kami aussi. Les micros aussi. N'importe qui peut avoir un enregistrement."
    noam "Elle a dit etre dans sa chambre."
    mara stress "Je sais."
    noam "Toutes les chambres."
    mara "Je sais."
    noam "Ton Clone disait etre l'original."
    mara colere "Ce n'est pas pareil."
    noam "Comment tu le sais ?"
    mara colere_noire "Parce que je le sais !"
    "Sa voix casse."
    mara vide "Pardon."
    noam "Non. C'est moi."
    mara "Tu dois rester ici demain."
    noam "Pourquoi ?"
    mara "Parce que si cette chose a ta voix, elle peut prendre ta place dehors."
    noam "Et si je reste, personne ne la verra."
    mara "Je te ravitaillerai."
    noam "Mara..."
    mara mefiant "Promets-moi de ne pas sortir."
    noam "Tu me crois dangereux ?"
    mara "Je crois que quelqu'un veut que tu le deviennes."
    noam "Et tu vas dire quoi aux autres ?"
    mara "Que tu es malade."
    noam "Ils le croiront."
    mara "Oui."
    noam "Tu reviendras ?"
    mara fatigue "Avec de la nourriture et moins de courage."
    noam "Merci."
    mara "Barricade apres moi."
    noam "D'accord."
    "Elle sort. Je pousse le bureau contre la porte. Dans le mur, quelque chose revient lentement jusqu'a ma grille."
    voix_off "Bonne nuit, Noam."
    scene black with dissolve
    call end_day("20") from _call_end_day_20
    jump _20_0_1_1_0_FAIM
