label _20_0_1_1_0_FAIM:
    $ noam_has_juliette_drawing = False
    call MAYBE_PLAY_SCRIPTED_DOOR("chambre", "bg_chambre") from _call_MAYBE_PLAY_SCRIPTED_DOOR_139
    scene bg_chambre at adaptive_fullscreen with fade
    play music "music/bgm_cold_metadata.mp3" fadein 1.5
    "Midi passe. Mara n'est pas revenue. Ma derniere ration a le gout du papier et la taille d'une excuse."
    noam "Kami, quelle heure est-il ?"
    kami "Douze heures trente-sept."
    noam "Mara est-elle venue ?"
    kami "Non."
    noam "Est-elle a la cafeteria ?"
    kami "Je ne communique pas la position des representants."
    noam "Depuis quand ?"
    kami "Depuis que tu demandes."
    noam "Elle devait venir."
    kami "Peut-etre a-t-elle change d'avis."
    noam "Ou de souvenir."
    kami "Tu as faim. La cafeteria est ouverte."
    noam "Mara m'a demande de rester."
    kami "Mara n'a aucune autorite sur toi."
    noam "Et toi ?"
    kami "Je veille a votre securite."
    noam "Ce n'etait pas la question."
    kami "La cafeteria est ouverte."
    noam "Tu veux que je sorte."
    kami "Je veux que tu manges."
    noam "Pourquoi maintenant ?"
    kami "Parce qu'il est midi trente-neuf."
    noam "Deux minutes pour eviter une reponse."
    kami "Tu apprends."
    noam "Je vais sortir."
    kami "Bonne decision."
    noam "C'est bien ce qui m'inquiete."
    "Je retire la barricade. Le fil de la grille est intact. Celui de la porte ne l'est pas."
    noam inquiet "Quelqu'un est entre."
    kami "Tu viens d'ouvrir."
    noam "Avant moi."
    "Sous le lit, je trouve une fibre rouge."
    jump _20_0_1_1_0_CAFETERIA_MARA

label _20_0_1_1_0_CAFETERIA_MARA:
    call MAYBE_PLAY_SCRIPTED_DOOR("cafeteria", "bg_cafeteria") from _call_MAYBE_PLAY_SCRIPTED_DOOR_140
    scene bg_cafeteria at adaptive_fullscreen with dissolve
    play music "music/bgm_careful_wanting.mp3" fadein 1.5
    $ showGroup([("noam", "inquiet", 0.27), ("mara", "neutre", 0.67)])
    mara "Tu as une tete affreuse."
    noam "Tu n'es pas venue."
    mara "Bonjour a toi aussi."
    noam "Tu devais me ravitailler."
    mara doute "Je devais quoi ?"
    noam "Apres le conduit."
    mara "Quel conduit ?"
    noam "Ne fais pas ca."
    mara mefiant "Faire quoi ?"
    noam "Hier. Ma chambre. La grille. Nous avons rampe ensemble."
    mara rire_profond "D'accord. Et apres on a combattu un dragon ?"
    noam peur "Tu ne te souviens vraiment pas."
    mara agace "Je me souviens etre allee en maintenance. Seule."
    noam "Tu as une coupure sur la main."
    mara "Je travaille avec des outils."
    noam "Bord gauche du conduit. Tu m'avais prevenu."
    mara mefiant "Comment tu sais pour ma main ?"
    noam "Parce que j'etais la."
    mara "Recule."
    noam "Mara."
    mara colere "J'ai dit recule."
    noam "Regarde ma manche. Poussiere grise, meme melange que sur la tienne."
    mara "Tu as pu me suivre."
    noam "C'est toi qui es passee devant."
    mara "Pourquoi je ferais ca ?"
    noam "Pour m'empecher de mourir."
    mara taquin "Ca ne me ressemble pas."
    noam "Tu plaisantais exactement comme ca."
    mara stress "Arrete."
    noam "Tu as marque les bifurcations avec une craie."
    mara "Je n'ai pas de craie."
    noam "Poche gauche."
    "Elle glisse la main dans sa poche et en sort un morceau blanc."
    mara vide "..."
    noam "Tu me crois maintenant ?"
    mara "Je ne sais pas."
    noam "Tu m'as fait promettre de rester dans ma chambre."
    mara "Pourquoi ?"
    noam "Nous avons entendu une voix. La mienne."
    mara stress "Non."
    noam "Elle se trouvait dans les conduits."
    mara colere "Non."
    noam "Elle a dit etre dans toutes les chambres."
    mara colere_noire "Tais-toi !"
    "Toute la cafeteria se tourne vers nous."
    goumi "Tout va bien ?"
    mara stress "Oui."
    noam "Non."
    mara "Il est fatigue."
    noam "Tu devais dire aux autres que j'etais malade."
    mara vide "Comment tu..."
    noam "Parce que tu l'as dit hier."
    mara "Eloigne-toi de moi."
    noam "Tu as peur de moi ?"
    mara "J'ai peur que tu connaisses des choses que je n'ai jamais vecues."
    noam "Moi aussi."
    mara mefiant "Ne me suis pas."
    noam "Mara, attends."
    mara "Ne me suis pas."
    "Elle quitte la cafeteria sans prendre son plateau."
    goumi "Noam ?"
    noam fatigue "Un cafe. Tres fort."
    goumi "Je crois qu'il te faut autre chose."
    noam "Moi aussi. Mais commence par le cafe."
    jump _20_0_1_1_0_TOMAS

label _20_0_1_1_0_TOMAS:
    call MAYBE_PLAY_SCRIPTED_DOOR("cafeteria", "bg_cafeteria") from _call_MAYBE_PLAY_SCRIPTED_DOOR_141
    scene bg_cafeteria at adaptive_fullscreen with dissolve
    $ showGroup([("noam", "fatigue", 0.27), ("tomas", "inquiet", 0.67)])
    tomas "Mara est partie vite."
    noam "Elle a oublie hier."
    tomas "Entierement ?"
    noam "Le conduit. Les traces. La voix."
    tomas "Quelle voix ?"
    noam "La mienne. Dans l'aeration."
    tomas panne "Je vais avoir besoin de l'ordre exact."
    noam "Pas maintenant."
    tomas "D'accord."
    noam "Tu n'insistes pas ?"
    tomas "Tu veux une solution ou juste parler ?"
    noam sourire "Tu as retenu la regle."
    tomas "J'essaie."
    noam "Une solution."
    tomas raison "Alors il faut separer trois hypotheses."
    noam "Lesquelles ?"
    tomas "Un : Mara ment. Deux : sa memoire a ete modifiee. Trois : la tienne fabrique une nuit coherente."
    noam "La craie etait dans sa poche."
    tomas "Trace physique en faveur de l'hypothese deux ou d'une action oubliee ordinaire."
    noam "Elle avait la coupure."
    tomas "Deuxieme trace, meme limite."
    noam "J'ai les fibres rouges."
    tomas "Montre."
    "Je lui tends le sachet."
    tomas reflechit "Fibre synthetique. Enduction ignifuge."
    noam "Tu reconnais ?"
    tomas "Les combinaisons de maintenance utilisent ce materiau."
    noam "Les robots ?"
    tomas "Non. Les operateurs humains."
    noam "Il n'y en a pas ici."
    tomas mefiant "Il ne devrait pas y en avoir."
    noam "Tu sais autre chose."
    tomas hesitation "Kael m'a parle d'une copie de la photo de sa soeur."
    noam "Il disait qu'elle n'existait pas."
    tomas surpris "Comment tu sais ?"
    noam "Je vous ai entendus depuis le conduit."
    tomas "Nous etions en maintenance."
    noam "Le reseau passe au-dessus."
    tomas "Alors quelqu'un peut ecouter toutes les salles."
    noam "Oui."
    tomas "Et se deplacer entre les chambres."
    noam "Oui."
    tomas "La copie a peut-etre ete transportee par la."
    noam "Ou cachee."
    tomas "Kael a trouve un fragment de papier photo pres d'une trappe technique."
    noam "Ou ?"
    tomas "Dans le couloir des chambres."
    noam "On doit y retourner."
    tomas "Avec Mara ?"
    noam "Elle se mefie de moi."
    tomas "C'est raisonnable."
    noam colere "Merci."
    tomas culpabilite "Je voulais dire comprehensible."
    noam "Je sais."
    tomas "Je viens."
    noam "Tu detestes les espaces etroits."
    tomas "Oui."
    noam "Pourquoi venir ?"
    tomas determine "Parce qu'une trace ne peut pas etre contextualisee depuis une chaise."
    noam "C'est presque heroique."
    tomas panne "C'etait ironique ?"
    noam "Un peu."
    tomas "Je viens quand meme."
    jump _20_0_1_1_0_PHOTO

label _20_0_1_1_0_PHOTO:
    call MAYBE_PLAY_SCRIPTED_DOOR("chambre", "bg_chambre") from _call_MAYBE_PLAY_SCRIPTED_DOOR_142
    scene bg_chambre at adaptive_fullscreen with fade
    play music "music/bgm_fatal_assembly.mp3" fadein 1.5
    $ showGroup([("noam", "inquiet", 0.18), ("mara", "mefiant", 0.43), ("tomas", "reflechit", 0.68)])
    mara "Je vous ai dit de ne pas me suivre."
    noam "Nous sommes dans ma chambre."
    mara "Detail irritant."
    tomas "J'ai besoin de verifier la fibre."
    mara "Et tu avais besoin de lui ?"
    tomas "C'est lui qui connait le chemin."
    mara "Ou qui pretend le connaitre."
    noam "La marque de craie te convaincra."
    mara "Si elle existe."
    noam "Elle existe."
    mara "Alors passe devant."
    noam "Hier, tu refusais."
    mara "Aujourd'hui, je veux te voir."
    tomas "Je reste entre vous."
    mara agace "Tu vas surtout rester coince."
    tomas "J'ai mesure l'ouverture."
    noam "Bien sur."
    tomas "Elle est suffisante."
    scene black with dissolve
    noam "Fleche, puis M."
    mara "Je la vois."
    noam "Ton ecriture."
    mara stress "Oui."
    tomas "La craie correspond a celle de sa poche."
    mara "Je sais ce que je vois."
    noam "Tu me crois ?"
    mara "Je crois que j'etais ici. Pas encore pourquoi."
    tomas "La trappe est devant."
    noam "Celle ou la silhouette est tombee."
    mara "Je ne me souviens pas de silhouette."
    noam "Je sais."
    tomas "Il y a quelque chose coince dans le joint."
    mara "Du papier."
    noam "Tire doucement."
    tomas "C'est une photographie."
    call MAYBE_PLAY_SCRIPTED_DOOR("maintenance", "bg_maintenance") from _call_MAYBE_PLAY_SCRIPTED_DOOR_143
    scene bg_maintenance at adaptive_fullscreen with dissolve
    "Nous sortons par la trappe de maintenance. Tomas tient un carre de papier plie en deux."
    kael "Qu'est-ce que vous faites ici ?"
    $ showGroup([("noam", "inquiet", 0.08), ("mara", "vide", 0.28), ("tomas", "inquiet", 0.48), ("kael", "mefiant", 0.72)])
    noam "Kael..."
    kael "Vous sortez du mur."
    mara taquin "Observation brillante."
    kael "Qu'est-ce qu'il tient ?"
    tomas "Une photographie trouvee dans le conduit."
    kael colere "Donne-la-moi."
    tomas "Attends."
    kael colere "Donne-la-moi."
    noam "Tomas."
    "Tomas deplie le papier. Le visage d'une jeune femme apparait, souriant sous une lumiere d'ete."
    kael surpris "Non."
    noam "C'est elle ?"
    kael desespoir "Ma soeur."
    mara vide "La photo volee ?"
    kael "Non."
    tomas "Tu es certain ?"
    kael "L'original etait cadre plus large. Il y avait ma main sur son epaule."
    noam "Alors c'est une copie."
    kael "Une copie qui ne devrait pas exister."
    mara "Retourne-la."
    kael "Pourquoi ?"
    mara "Parce que les mauvaises nouvelles aiment les deux faces."
    "Kael retourne la photo. Une date et quatre mots sont imprimes au dos."
    centered "{size=44}{color=#ff6b7a}JOUR 20 - CHAMBRE NOAM{/color}{/size}"
    noam peur "Ma chambre."
    tomas "Impression aujourd'hui."
    kael mefiant "Tu l'avais ?"
    noam "Non."
    kael "Ton dossier te nomme operateur. La photo porte ta chambre."
    mara colere "Il etait avec moi quand nous l'avons trouvee."
    kael "Aujourd'hui, oui. Et hier ?"
    mara vide "Je ne sais plus."
    kael "Exactement."
    noam "Tu crois que je fais ca ?"
    kael "Je crois que quelqu'un utilise ton nom, ta voix et ta chambre."
    tomas "La question est de savoir pourquoi."
    mara "Et lequel des deux Noam est devant nous."
    noam colere "Mara."
    mara stress "Je suis desolee."
    kami "Felicitations. Vous avez retrouve un souvenir."
    kael colere "Ce n'est pas un souvenir !"
    kami "Pourtant, vous vous souviendrez tous de ce moment."
    noam "Qui a imprime la photo ?"
    kami "L'operateur."
    noam "Quel operateur ?"
    kami "Noam."
    noam panique "Je suis ici !"
    voix_off "Moi aussi."
    "La voix vient du conduit au-dessus de nous. Ma voix."
    mara stress "Noam..."
    kael "Fermez la trappe."
    tomas inquiet "Quelqu'un bouge la-haut."
    noam "Attendez !"
    voix_off "Merci d'avoir trouve la photo."
    play sound sfx_metal_clank volume 0.9
    "La grille claque. Les pas rampants s'eloignent vers les chambres."
    noam determine "Il retourne dans ma chambre."
    mara "Ou dans toutes."
    scene black with dissolve
    call end_day("21") from _call_end_day_22
    return
