# =============================================================================
# JOUR 23 — RIEN DANS SA TÊTE
# Route 0_1_1_0_0
#
# Sael s'inquiète réellement des visions de Noam et lui fait passer une batterie
# d'examens. Iris impose sa présence. Tout revient normal.
# =============================================================================
label _23_0_1_1_0_0_REVEIL:
    $ current_day = 23
    $ day_id = 23
    $ current_period = "Matin"
    scene bg_chambre at adaptive_fullscreen with fade
    play music "music/bgm_introspective_atmosphere.mp3" fadein 1.2
    "Je me réveille avant l'alarme."
    "Pas en sursaut. Pas à cause d'un bruit."
    "Juste les yeux ouverts, comme si mon corps avait décidé qu'il avait assez dormi alors que clairement non."
    "Le bureau est toujours poussé contre la grille d'aération."
    think "C'est ridicule."
    "J'ai mal dormi, mais pas assez mal pour pouvoir accuser la fatigue de tout ce qui s'est passé."
    think "Mara morte."
    "Je ferme les yeux."
    think "Mara vivante."
    "Je les rouvre aussitôt."
    noam fatigue "Super."
    "Je m'habille sans défaire complètement mon sac."
    "Au bout de deux jours, ça commence à devenir un principe stupide."
    "Je garde la moitié de mes affaires prêtes à partir, comme si Kami allait changer d'avis au milieu de la nuit et nous dire de courir au sas."
    think "Jour vingt-trois."
    "Sept jours."
    "Je sors."
    # Durée : ~1m30
    # Total : ~1m30
label _23_0_1_1_0_0_PETIT_DEJEUNER:
    scene bg_cafeteria at adaptive_fullscreen with dissolve
    play music "music/bgm_quiet_routine.mp3" fadein 0.8
    "La cafétéria est déjà bruyante."
    "Pas vraiment joyeuse. Juste vivante."
    "Des couverts. Des chaises. Mara qui parle trop fort quelque part."
    think "Donc une matinée normale."
    $ showGroup([
        ("mara", "taquin"),
        ("sael", "reflexion"),
        ("iris", "fatigue"),
        ("noam", "fatigue"),
    ])
    mara taquin "Ah, voilà le revenant."
    noam blase "Bonjour Mara."
    mara sourire "Bonjour Noam. T'as une tête de merde."
    iris fatigue "Elle a raison."
    noam fatigue "Merci, vous êtes adorables."
    mara taquin "Moi je peux être beaucoup plus adorable si tu demandes gentiment."
    iris blase "On mange."
    mara rire "J'ai rien proposé de sale."
    iris neutre "T'allais le faire."
    mara taquin "Oui, mais tu m'as coupée. C'est frustrant."
    "Je m'assois avec mon plateau."
    "Sael ne touche presque pas au sien."
    "Elle me regarde."
    "Pas discrètement."
    noam reflexion "Quoi ?"
    sael reflexion "T'as encore mal dormi."
    noam blase "Vous avez préparé ça ensemble ?"
    iris fatigue "Non, c'est juste très visible."
    mara taquin "On dirait que t'as passé la nuit avec quelqu'un de violent."
    noam neutre "Mara..."
    mara rire "Quoi ? Ça peut arriver."
    sael inquiet "Je parle sérieusement."
    "Mara finit par se taire."
    "Ça suffit à me faire regarder Sael autrement."
    noam reflexion "D'accord. Qu'est-ce qu'il y a ?"
    sael raison "Je veux que tu viennes à l'infirmerie."
    noam surpris "Pourquoi ?"
    sael neutre "Pour te tester."
    noam blase "Dit comme ça, c'est rassurant."
    mara taquin "Moi aussi je peux le tester."
    iris colere "Mara."
    mara sourire "Là, oui, c'était sale."
    sael desaccord "Je parle de sa tête."
    noam reflexion "Ma tête va très bien."
    sael fatigue "Tu sais pas."
    noam neutre "Si."
    sael neutre "Non."
    sael raison "Tu dis que t'as vu quelqu'un mort. Puis vivant. Tu dis que t'as entendu des choses dans les conduits. T'as eu des trous dans tes souvenirs avant."
    noam inquiet "J'ai pas dit que j'avais des trous de mémoire maintenant."
    sael neutre "J'ai pas dit maintenant."
    iris reflexion "Tu penses à quoi exactement ?"
    sael neutre "Manque d'oxygène. Choc. Traumatisme. Un truc neurologique. Je sais pas."
    mara reflexion "Ou possession."
    noam colere "Non."
    sael colere "Non."
    mara rire "D'accord, d'accord."
    iris reflexion "Tu peux vérifier tout ça ici ?"
    sael raison "Une partie. Pupilles, réflexes, mémoire, perception. Y'a aussi l'IRM."
    noam surpris "Attends."
    iris neutre "Quoi ?"
    noam inquiet "On est passés de 't'as une sale tête' à 'on te met dans une machine'."
    sael neutre "Oui."
    noam neutre "Très progressivement."
    sael neutre "T'as peur de l'IRM ?"
    noam blase "Non."
    iris taquin "Il a peur de l'IRM."
    noam colere "J'ai pas peur de l'IRM."
    mara taquin "T'inquiète, si t'as besoin de tenir une main..."
    noam fatigue "Je vais me lever."
    mara rire "J'allais dire Iris."
    iris surpris "Pardon ?"
    mara neutre "Regarde-la, elle s'est déjà portée volontaire dans sa tête."
    iris colere "Je me porte volontaire pour te jeter ton café dessus."
    sael fatigue "Vous pouvez vous taire deux secondes ?"
    "Ça tombe assez sec pour que même Mara baisse d'un ton."
    sael inquiet "Je veux juste vérifier qu'il a rien."
    noam reflexion "Sael..."
    sael neutre "Parce que si t'as rien..."
    "Elle s'arrête."
    iris reflexion "Si ?"
    sael peur "Alors ça veut dire que ce que t'as vu vient peut-être pas de toi."
    "Personne ne plaisante."
    noam inquiet "Tu crois vraiment que je peux halluciner à ce point ?"
    sael fatigue "Je préfère ça à l'autre possibilité."
    "C'est dit simplement."
    "Presque trop."
    "Je comprends alors qu'elle n'essaie pas de prouver que je suis fou."
    "Elle essaie de se rassurer."
    noam fatigue "D'accord."
    sael surpris "D'accord quoi ?"
    noam neutre "On fait les tests."
    iris determine "Je viens."
    sael neutre "Pourquoi ?"
    iris blase "Parce que je te connais."
    sael desaccord "Ça veut dire quoi ?"
    iris neutre "Que la dernière fois que t'as voulu régler un problème mystique, Ryn a fini par maintenir Noam contre un mur."
    noam colere "Merci de rappeler ça."
    sael fatigue "J'ai dit que c'était médical."
    iris neutre "Je viens quand même."
    sael neutre "J'ai pas besoin d'assistante."
    iris agace "Je suis pas ton assistante."
    mara taquin "Elle est la garde du corps du patient."
    noam blase "J'ai rien demandé."
    iris fatigue "Toi, tais-toi. T'as accepté l'IRM."
    noam neutre "J'ai accepté des tests."
    sael raison "L'IRM est un test."
    noam neutre "Je déteste déjà cette journée."
    mara sourire "Moi je l'aime bien."
    "Mara pique un morceau dans mon assiette."
    noam colere "Eh !"
    mara taquin "Tu vas être à jeun pour l'IRM."
    sael desaccord "Non."
    mara rire "Merde."
    iris taquin "Bien essayé."
    "Malgré moi, je souris."
    "Ça dure deux secondes."
    "Puis je repense à la raison pour laquelle on va à l'infirmerie."
    $ hideGroup()
    # Durée : ~4m00
    # Total : ~5m30
label _23_0_1_1_0_0_INFIRMERIE_ENTREE:
    scene infirmerie2 at adaptive_fullscreen with dissolve
    play music "music/bgm_cold_metadata.mp3" fadein 0.8
    "L'infirmerie sent toujours pareil."
    "Propre. Trop propre."
    "Je m'assois sur le bord d'un lit pendant que Sael fouille dans un tiroir."
    $ showGroup([
        ("sael", "raison", 0.22),
        ("iris", "blase", 0.50),
        ("noam", "fatigue", 0.76),
    ])
    noam reflexion "Tu sais vraiment utiliser tout ça ?"
    sael desaccord "Oui."
    iris taquin "Réponse très rassurante."
    sael colere "J'ai déjà travaillé ici."
    noam surpris "Quand ?"
    sael reflexion "Quand Anya était là. Et avant."
    iris blase "Ça répond pas vraiment."
    sael fatigue "Vous voulez faire les tests ou discuter de mon CV ?"
    noam neutre "Les tests."
    iris neutre "Son CV."
    sael colere "Iris."
    iris sourire "Je plaisante."
    "Sael sort une petite lampe."
    noam inquiet "Ça commence par quoi ?"
    sael raison "Les yeux."
    noam neutre "Très bien."
    sael neutre "Regarde ici."
    "Elle allume la lampe."
    noam surpris "Putain !"
    iris rire "Oh non."
    sael desaccord "Bouge pas."
    noam colere "Tu pouvais prévenir."
    sael neutre "J'ai dit regarde ici."
    noam neutre "C'est pas prévenir."
    iris taquin "Si, un peu."
    noam neutre "T'es de son côté maintenant ?"
    iris blase "Je suis du côté de la science."
    sael raison "Pupille droite normale."
    "Elle passe à l'autre œil."
    sael neutre "Gauche normale."
    noam taquin "Je suis symétrique. Bonne nouvelle."
    iris neutre "Pour les yeux."
    noam blase "Merci Iris."
    sael raison "Suis mon doigt."
    "Je le suis."
    sael neutre "Sans bouger la tête."
    "Je recommence."
    iris taquin "C'est fascinant."
    noam neutre "Tu peux partir."
    iris neutre "Non."
    noam neutre "Tu t'ennuies."
    iris fatigue "Oui."
    noam neutre "Donc pars."
    iris neutre "Non."
    iris agace "Quoi ?"
    noam taquin "Rien."
    iris neutre "Arrête."
    noam sourire "J'ai rien dit."
    sael colere "Regarde mon doigt."
    noam fatigue "Oui maman."
    "Silence."
    "Je réalise ma connerie."
    iris rire "Oh."
    sael surpris "..."
    noam gene "Pardon."
    sael taquin "Refais ça et je prends le sel."
    noam peur "Compris."
    "Iris éclate franchement de rire."
    "Même Sael sourit."
    "Pendant quelques secondes, l'infirmerie ressemble presque à une pièce normale."
    # Durée : ~3m00
    # Total : ~8m30
label _23_0_1_1_0_0_REFLEXES:
    "Sael sort ensuite un marteau à réflexes."
    $ showGroup([
        ("sael", "raison", 0.22),
        ("iris", "taquin", 0.50),
        ("noam", "inquiet", 0.76),
    ])
    noam inquiet "Ça, j'aime moins."
    sael neutre "C'est du caoutchouc."
    noam neutre "Ça reste un marteau."
    iris taquin "Tu veux tenir ma main ?"
    noam blase "Toi aussi maintenant ?"
    iris sourire "Je profite."
    sael raison "Relâche la jambe."
    noam neutre "Elle est relâchée."
    sael neutre "Non."
    noam colere "Si."
    sael desaccord "Non."
    iris fatigue "Noam, relâche ta putain de jambe."
    noam neutre "Je suis détendu !"
    "Sael frappe sous mon genou."
    "Ma jambe part d'un coup."
    iris rire "Très détendu."
    noam colere "Ferme-la."
    sael raison "Réflexe normal."
    "Deuxième genou."
    "Même chose."
    sael neutre "Normal."
    noam reflexion "Et si c'était pas normal, ça voudrait dire quoi ?"
    sael neutre "Ça dépend."
    noam neutre "De quoi ?"
    sael neutre "Du réflexe."
    noam blase "Merci."
    iris taquin "Consultation très claire."
    sael colere "Vous voulez que j'explique tout ?"
    iris neutre "Non."
    noam neutre "Un peu."
    sael fatigue "Si je commence vous allez vous plaindre."
    noam neutre "Probable."
    "Elle passe rapidement aux mains et à la coordination : force, équilibre, doigt sur le nez, bras tendus, yeux fermés."
    sael raison "Tout est normal."
    noam blase "Tu pourrais avoir l'air un peu plus contente."
    sael fatigue "J'attends la suite."
    iris reflexion "Moi aussi."
    "Le ton retombe d'un coup."
    # Durée : ~3m30
    # Total : ~12m00
label _23_0_1_1_0_0_MEMOIRE:
    "Le test suivant ressemble d'abord à un jeu pour enfant."
    "Sael pose plusieurs objets devant moi."
    $ showGroup([
        ("sael", "raison", 0.22),
        ("iris", "reflexion", 0.50),
        ("noam", "neutre", 0.76),
    ])
    sael raison "Regarde-les."
    noam reflexion "Une tasse, un badge, un stylo, une compresse, une clé."
    sael neutre "Je t'ai pas demandé de les nommer."
    noam blase "Je prends de l'avance."
    iris taquin "Toujours premier de la classe."
    noam neutre "Pas du tout."
    sael neutre "Ferme les yeux."
    "Je ferme les yeux."
    "J'entends les objets bouger."
    sael neutre "Ouvre."
    "La clé a disparu."
    noam neutre "La clé."
    sael raison "Bien."
    iris sourire "Il est brillant."
    noam neutre "Tu te moques depuis vingt minutes, tu peux varier."
    iris neutre "Non."
    sael raison "Maintenant, cinq mots."
    noam reflexion "D'accord."
    sael neutre "Fenêtre. Orange. Cheval. Métal. Pluie."
    noam neutre "Fenêtre, orange, cheval, métal, pluie."
    sael neutre "Je te les redemanderai plus tard."
    noam taquin "Je les oublierai exprès."
    sael desaccord "Fais pas ça."
    noam neutre "Je plaisante."
    sael neutre "Moi pas."
    "Elle change d'écran."
    sael reflexion "Quel jour on est ?"
    noam neutre "Jour vingt-trois."
    sael neutre "Date réelle."
    noam hesitation "Euh..."
    iris rire "Ah."
    noam colere "Attends."
    iris taquin "Le grand esprit vacille."
    noam neutre "On est enfermés dans une station avec des jours numérotés depuis trois semaines, forcément que—"
    sael fatigue "Réponds juste."
    noam reflexion "Quatre octobre."
    sael raison "Bien."
    noam surpris "Bien ? J'ai bon ?"
    iris blase "Tu veux une médaille ?"
    noam neutre "Un peu."
    sael neutre "Où est-ce qu'on est ?"
    noam taquin "À l'infirmerie."
    sael colere "Noam."
    noam sourire "Dans le Conclave."
    sael neutre "En orbite."
    noam neutre "Oui."
    sael neutre "Pourquoi t'es ici ?"
    "La question me fait hésiter plus longtemps."
    noam reflexion "Parce que Kami nous a amenés ici pour le Conclave."
    sael neutre "Et pourquoi t'as accepté les tests ?"
    noam fatigue "Parce que tu me lâchais pas."
    iris rire "Bonne réponse."
    sael fatigue "Parce que tu crois avoir vu Mara morte."
    "Le rire d'Iris s'arrête."
    noam inquiet "Oui."
    sael reflexion "Raconte-moi exactement ce que t'as vu."
    noam neutre "Maintenant ?"
    sael neutre "Oui."
    noam desaccord "C'était pas un test de mémoire générale ?"
    sael neutre "Ça en fait partie."
    "Je regarde Iris."
    "Elle ne plaisante plus."
    noam inquiet "J'étais dans la zone derrière les conduits. J'ai trouvé la salle. Après... j'ai vu un corps."
    sael neutre "De qui ?"
    noam peur "Mara."
    sael neutre "Tu l'as touché ?"
    noam neutre "Non."
    sael neutre "T'as vérifié si elle respirait ?"
    noam neutre "Je crois pas."
    sael reflexion "Tu crois pas ?"
    noam colere "J'étais pas exactement calme."
    iris colere "Sael."
    sael neutre "Je demande."
    noam fatigue "Non. J'ai pas vérifié."
    sael neutre "Tu as vu du sang ?"
    noam peur "Oui."
    sael neutre "Où ?"
    noam neutre "Je sais plus précisément."
    sael neutre "Sur elle ? Au sol ?"
    noam colere "J'ai dit que je sais plus."
    "Sael se tait."
    "Je respire trop vite."
    iris inquiet "Ça va."
    noam agace "Non, ça va pas."
    iris neutre "Je sais."
    "Sa réponse est douce, mais pas sucrée."
    "Juste là."
    sael fatigue "On arrête cette partie."
    noam reflexion "Non."
    sael neutre "T'es énervé."
    noam neutre "Parce que je me souviens."
    "Je regarde les objets sur la tablette."
    noam peur "Je me souviens de son visage."
    pause 0.5
    iris inquiet "Noam..."
    noam faible "Et je me souviens de l'avoir vue après. Vivante. Comme si rien s'était passé."
    sael peur "D'accord."
    "Elle détourne légèrement les yeux."
    noam reflexion "Tu me crois ?"
    sael fatigue "Je crois que tu te souviens de ça."
    noam neutre "C'est pas pareil."
    sael neutre "Non."
    "Au moins elle ne ment pas."
    "Elle regarde sa tablette."
    sael raison "Les cinq mots."
    noam surpris "Quoi ?"
    sael neutre "Les cinq mots."
    noam reflexion "Fenêtre... orange... cheval... métal..."
    "Je bloque."
    iris taquin "Oh."
    noam colere "Attends."
    "Je ferme les yeux."
    noam determine "Pluie."
    sael raison "Cinq sur cinq."
    iris sourire "Félicitations."
    noam fatigue "J'ai envie de rentrer chez moi."
    iris neutre "Ça, le test l'avait pas prévu."
    # Durée : ~5m00
    # Total : ~17m00
label _23_0_1_1_0_0_PERCEPTION:
    "Sael enchaîne avec des tests de perception."
    "Des formes, des couleurs, des sons, des images qui apparaissent une fraction de seconde."
    $ showGroup([
        ("sael", "raison", 0.22),
        ("iris", "fatigue", 0.50),
        ("noam", "reflexion", 0.76),
    ])
    sael raison "À gauche ou à droite ?"
    noam neutre "Droite."
    sael neutre "Couleur ?"
    noam neutre "Rouge."
    sael neutre "Forme ?"
    noam neutre "Triangle."
    iris blase "Passionnant."
    sael colere "Tu peux partir."
    iris neutre "Non."
    noam taquin "Elle reste pour me protéger du triangle."
    iris agace "Je commence à regretter."
    sael raison "Son aigu ou grave ?"
    noam neutre "Aigu."
    sael neutre "Deuxième ?"
    noam reflexion "Grave."
    sael neutre "Bien."
    "Elle lance une nouvelle série."
    "Un visage apparaît."
    "Mara."
    "Mon cœur rate un battement."
    noam peur "Attends."
    sael surpris "Quoi ?"
    noam neutre "Remets."
    sael reflexion "L'image ?"
    noam determine "Oui."
    "Elle la remet."
    "C'est juste une photo de Mara prise pour les dossiers du Conclave."
    "Vivante. Souriante."
    iris inquiet "Ça va ?"
    noam fatigue "Oui."
    iris colere "Mens mieux."
    noam neutre "C'est rien."
    sael neutre "On peut arrêter."
    noam determine "Non. Continue."
    "Sael hésite."
    sael reflexion "T'es sûr ?"
    noam neutre "Oui."
    "Elle continue."
    "Kael."
    "Nyra."
    "Ryn."
    "Elias."
    "Mara revient une deuxième fois."
    "Cette fois je ne bronche presque pas."
    "Presque."
    sael raison "Réponse ?"
    noam reflexion "Mara."
    sael neutre "Temps de réponse plus long."
    noam agace "Je sais."
    iris inquiet "C'est forcément anormal ?"
    sael neutre "Non."
    noam neutre "Tu peux dire plus que non ?"
    sael raison "Si une image te rappelle quelque chose de violent, tu ralentis. C'est normal."
    noam reflexion "Donc mon cerveau réagit normalement à un souvenir peut-être faux."
    sael fatigue "Oui."
    noam blase "Parfait."
    iris agace "Arrête de chercher une réponse dans chaque test."
    noam colere "C'est pour ça qu'on est là."
    iris neutre "Non. On est là pour vérifier si t'as un problème évident."
    noam neutre "Et si j'en ai pas ?"
    iris inquiet "Alors on verra après."
    noam neutre "C'est quoi après ?"
    iris colere "J'en sais rien, Noam !"
    "Sa voix claque."
    "Elle regrette immédiatement."
    iris fatigue "J'en sais rien."
    noam fatigue "D'accord."
    "On reste silencieux quelques secondes."
    sael reflexion "On fait l'IRM."
    "Aucune de nous ne plaisante."
    # Durée : ~4m00
    # Total : ~21m00
label _23_0_1_1_0_0_IRM_PREPARATION:
    scene infirmerie2 at adaptive_fullscreen with dissolve
    play music "music/bgm_cold_metadata.mp3" fadein 0.6
    "La machine est au fond de la pièce, derrière une cloison."
    "Je l'avais déjà vue sans vraiment la regarder."
    "Maintenant elle me paraît beaucoup trop grande."
    $ showGroup([
        ("sael", "raison", 0.22),
        ("iris", "inquiet", 0.50),
        ("noam", "fatigue", 0.76),
    ])
    sael raison "Enlève tout ce qui est métallique."
    noam reflexion "Badge aussi ?"
    sael neutre "Oui."
    noam neutre "Téléphone."
    sael neutre "Oui."
    noam neutre "Ceinture."
    sael neutre "Oui."
    iris taquin "Continue, ça devient intéressant."
    noam blase "Je te déteste."
    iris sourire "Je sais."
    "Je pose mes affaires dans un bac."
    noam inquiet "Ça dure combien de temps ?"
    sael neutre "Une vingtaine de minutes."
    noam surpris "Tu m'avais dit pas longtemps."
    sael neutre "C'est pas longtemps."
    noam colere "Vingt minutes dans un tube, c'est long."
    iris taquin "Il a vraiment peur."
    noam neutre "J'ai pas peur."
    iris neutre "T'as demandé quatre fois combien de temps ça dure."
    noam neutre "Je me renseigne."
    sael reflexion "T'es claustrophobe ?"
    noam hesitation "Pas spécialement."
    iris blase "Donc oui."
    noam colere "Non."
    sael fatigue "Si tu paniques, tu me le dis."
    noam neutre "Comment ?"
    sael neutre "Y'a un bouton."
    noam neutre "Et si le bouton marche pas ?"
    iris rire "Noam."
    noam neutre "Je pose une question."
    sael raison "Il marche."
    noam neutre "Tu l'as testé ?"
    sael neutre "Oui."
    noam neutre "Quand ?"
    sael colere "Ce matin."
    noam neutre "Pourquoi ?"
    sael neutre "Parce que je savais que t'allais demander."
    "Iris éclate de rire."
    noam blase "Vous êtes horribles."
    iris sourire "Viens."
    "Elle me tend la main."
    "Je la regarde."
    noam surpris "Quoi ?"
    iris gene "Bah... donne."
    noam taquin "Tu te moquais de moi il y a dix secondes."
    iris agace "Je peux me moquer et t'aider en même temps."
    noam neutre "C'est très toi."
    iris neutre "Tu la prends ou pas ?"
    "Je prends sa main."
    "Elle serre une fois."
    "Pas longtemps."
    "Puis elle la retire comme si ça avait duré trop longtemps."
    iris blase "Voilà. T'es officiellement courageux."
    noam sourire "Merci."
    sael taquin "C'est mignon."
    iris colere "Commence pas."
    "Sael lève les mains."
    "Je m'allonge."
    # Durée : ~3m30
    # Total : ~24m30
label _23_0_1_1_0_0_IRM:
    scene black with dissolve
    stop music fadeout 0.8
    "La table glisse."
    "Le plafond disparaît."
    "Il ne reste qu'une paroi blanche très proche de mon visage."
    "Puis le bruit."
    "Un premier claquement métallique."
    pause 0.4
    "Un deuxième."
    "Régulier."
    "Sec."
    "Je ferme les yeux."
    think "C'est la machine."
    "Le bruit recommence."
    think "Juste la machine."
    "Puis le rythme change."
    "Trois coups rapides."
    pause 0.3
    "Un silence."
    pause 0.5
    "Deux coups."
    "Mon ventre se serre."
    think "Non."
    "Ça ressemble trop aux bruits dans les conduits."
    "Je garde les yeux fermés."
    "Je revois le couloir."
    "La salle cachée."
    "Le corps."
    "Je rouvre les yeux."
    "Paroi blanche."
    "Rien d'autre."
    "Le haut-parleur grésille."
    sael neutre "Noam ?"
    noam inquiet "Oui."
    sael neutre "Tu bouges."
    noam neutre "Désolé."
    sael raison "Ça va ?"
    noam hesitation "Oui."
    iris inquiet "Mens pas."
    "Sa voix arrive plus loin, un peu étouffée."
    noam fatigue "Ça va."
    iris neutre "T'as appuyé sur rien ?"
    noam neutre "Non."
    iris neutre "Alors reste tranquille."
    noam taquin "Merci pour le soutien."
    iris blase "De rien."
    "Le bruit reprend."
    "Je compte."
    "Un."
    "Deux."
    "Trois."
    "À vingt-sept, je perds le fil."
    "À un moment, je crois entendre quelque chose entre deux séquences."
    "Une respiration."
    "Je retiens la mienne."
    "Rien."
    "Puis un frottement."
    think "C'est la machine."
    "Je me répète la phrase jusqu'à ce qu'elle ne veuille plus rien dire."
    "Quand la table ressort enfin, la lumière me fait cligner des yeux."
    scene infirmerie2 at adaptive_fullscreen with dissolve
    play music "music/bgm_cold_metadata.mp3" fadein 0.6
    $ showGroup([
        ("sael", "reflexion", 0.22),
        ("iris", "inquiet", 0.50),
        ("noam", "fatigue", 0.76),
    ])
    iris inquiet "Ça va ?"
    noam fatigue "Oui."
    iris agace "T'as encore cette tête."
    noam neutre "Quelle tête ?"
    iris neutre "La tête où tu dis oui mais t'es à deux secondes de dire autre chose."
    noam reflexion "J'ai cru entendre quelqu'un."
    sael surpris "Dans la machine ?"
    noam neutre "Entre deux séquences."
    iris inquiet "Quelqu'un comment ?"
    noam hesitation "Je sais pas. Une respiration. Peut-être un frottement."
    "Sael regarde la machine."
    sael raison "J'étais juste derrière la vitre. J'ai rien entendu."
    "Mon estomac se serre."
    noam peur "D'accord."
    iris colere "Hé. Ça veut rien dire."
    noam neutre "Je sais."
    iris neutre "Non, tu recommences."
    noam agace "Je sais, Iris."
    "Elle se tait."
    "Sael récupère les images."
    sael reflexion "Attendez."
    "Elle agrandit plusieurs coupes."
    "Change d'écran."
    "Revient en arrière."
    "Plus elle regarde, moins je respire."
    noam inquiet "Sael."
    sael neutre "Deux secondes."
    noam neutre "Ça fait déjà deux secondes."
    iris colere "Laisse-la regarder."
    noam neutre "Vous pouvez arrêter de parler comme si j'étais pas là ?"
    "Sael finit par poser la tablette."
    sael raison "C'est normal."
    noam surpris "Quoi ?"
    sael neutre "Tout."
    noam neutre "Tout quoi ?"
    sael raison "Structure normale. Pas de lésion visible. Pas d'hémorragie. Pas de signe d'hypoxie. Rien qui ressemble à un traumatisme récent."
    iris reflexion "Et pour les hallucinations ?"
    sael fatigue "Une IRM prouve pas qu'une personne hallucine ou pas."
    iris neutre "Mais y'a rien qui les expliquerait physiquement."
    sael neutre "Rien d'évident."
    noam reflexion "Donc mon cerveau est normal."
    sael neutre "Oui."
    noam neutre "Mémoire normale."
    sael neutre "Oui."
    noam neutre "Réflexes normaux."
    sael neutre "Oui."
    noam neutre "Perception normale."
    sael reflexion "Sur les tests qu'on a faits, oui."
    "Je ris."
    "Une fois."
    "Sans que ce soit drôle."
    noam blase "Génial."
    iris inquiet "Noam..."
    noam neutre "Non, c'est bien. C'est ce qu'on voulait."
    sael peur "Moi non."
    "Je la regarde."
    sael fatigue "Enfin... si. Je voulais que t'aies rien."
    sael inquiet "Mais je voulais aussi trouver pourquoi t'as vu ça."
    "Elle a l'air presque coupable."
    sael neutre "Là j'ai rien."
    noam peur "Donc si c'était pas dans ma tête..."
    sael colere "J'ai pas dit ça."
    noam neutre "Mais tu le penses."
    sael fatigue "Je pense que je peux plus te dire 'c'est sûrement ton cerveau' et passer à autre chose."
    pause 0.6
    iris inquiet "Ça suffit pour aujourd'hui."
    noam reflexion "Iris..."
    iris determine "Non. Là, ça suffit."
    "Elle récupère mon téléphone dans le bac et me le tend."
    iris fatigue "Tu remets tes affaires. Tu manges. Et pendant au moins une heure tu cherches pas à résoudre le mystère de ta propre tête."
    noam taquin "Une heure ?"
    iris blase "Je suis réaliste."
    "Je prends le téléphone."
    noam sourire "D'accord."
    $ hideGroup()
    # Durée : ~6m00
    # Total : ~30m30
label _23_0_1_1_0_0_APRES_IRM:
    $ current_period = "Après-midi"
    scene bg_cafeteria at adaptive_fullscreen with dissolve
    play music "music/bgm_quiet_routine.mp3" fadein 0.8
    "On retourne à la cafétéria."
    "Je n'avais pas faim avant les examens."
    "Maintenant j'ai faim comme si j'avais couru."
    $ showGroup([
        ("mara", "taquin"),
        ("iris", "fatigue"),
        ("sael", "fatigue"),
        ("noam", "fatigue"),
    ])
    mara taquin "Alors ?"
    noam blase "Alors quoi ?"
    mara neutre "Ton cerveau. Toujours là ?"
    noam neutre "Apparemment."
    mara sourire "Dommage, j'espérais récupérer de la place."
    iris agace "Tu peux lui foutre la paix cinq minutes ?"
    mara taquin "Je lui fous la paix. Je demande si son IRM a révélé qu'il pensait beaucoup à moi."
    noam fatigue "Oui. Une énorme tumeur en forme de Mara."
    "Mara reste figée une seconde."
    mara rire "Oh putain."
    iris rire "Bien."
    sael sourire "Pas mal."
    noam taquin "Merci."
    mara taquin "Fais attention, tu deviens séduisant quand t'es méchant."
    iris blase "Et voilà."
    noam neutre "J'aurais dû me taire."
    mara neutre "Trop tard."
    "Elle me vole une frite."
    noam colere "Encore ?"
    mara sourire "Le patient doit partager."
    sael desaccord "C'est pas une règle."
    mara neutre "Ça devrait."
    "Je la regarde mâcher."
    "Le même visage."
    "La même façon de sourire."
    "La même voix."
    "Et d'un coup, je revois le corps."
    "Ma fourchette s'arrête."
    mara reflexion "Quoi ?"
    noam inquiet "Rien."
    mara neutre "Tu me regardes bizarrement."
    noam neutre "Je suis fatigué."
    mara taquin "Tu peux me regarder bizarrement, je juge pas."
    iris inquiet "Noam ?"
    noam fatigue "Ça va."
    "Cette fois Iris ne me contredit pas."
    "Sael, elle, a vu."
    "Son regard passe de moi à Mara."
    "Puis revient."
    mara sourire "Bon, si tout va bien..."
    "Elle reprend une frite."
    noam colere "Arrête de bouffer dans mon assiette."
    mara rire "Ah ! Voilà, il va mieux."
    "Je souris malgré moi."
    "Mais quelque chose a changé."
    "Avant, quand Mara était devant moi, son simple fait d'être là suffisait presque à détruire le souvenir."
    "Maintenant, l'IRM est passée."
    "Mon cerveau est normal."
    "Et elle est toujours là."
    $ hideGroup()
    # Durée : ~4m00
    # Total : ~34m30
label _23_0_1_1_0_0_IRIS:
    scene bg_chambre at adaptive_fullscreen with dissolve
    play music "music/bgm_introspective_atmosphere.mp3" fadein 0.8
    "En fin d'après-midi, Iris passe dans ma chambre."
    "Elle entre, regarde le bureau sous la grille et lève les yeux au ciel."
    $ showGroup([
        ("iris", "blase", 0.40),
        ("noam", "fatigue", 0.62),
    ])
    iris blase "Toujours ça."
    noam reflexion "Ça me rassure."
    iris neutre "Un bureau."
    noam neutre "Oui."
    iris taquin "Ton grand système de sécurité."
    noam neutre "Tu veux le déplacer ?"
    iris determine "Non."
    "Elle s'assoit au bord du lit."
    noam reflexion "Tu venais pour quoi ?"
    iris fatigue "Voir si t'étais en train de devenir complètement taré."
    noam neutre "Verdict ?"
    iris neutre "Mitigé."
    noam sourire "Merci."
    "Elle regarde la grille."
    iris reflexion "Tu veux en parler ?"
    noam surpris "Depuis quand tu demandes ça ?"
    iris colere "Bon, laisse tomber."
    noam rire "Non, attends."
    "Elle soupire."
    iris fatigue "Je déteste faire ça."
    noam taquin "Être gentille ?"
    iris neutre "Oui."
    noam neutre "Je vois."
    iris colere "Tu veux vraiment que je parte ?"
    noam sourire "Non."
    "Juste fatigué."
    noam reflexion "J'espérais qu'elle trouve quelque chose."
    iris inquiet "Sael ?"
    noam neutre "Oui."
    iris neutre "Moi aussi."
    noam surpris "Sérieux ?"
    iris fatigue "Pas une tumeur, hein."
    noam taquin "Merci de préciser."
    iris neutre "Un truc. N'importe quoi qui explique."
    noam reflexion "Même une hallucination."
    iris neutre "Ouais."
    noam neutre "Tu me croyais pas."
    iris colere "C'est pas ça."
    noam neutre "Un peu."
    iris fatigue "Un peu."
    "Au moins elle l'admet."
    iris reflexion "Je croyais que t'avais vu quelque chose, mais... je sais pas. Pas forcément ce que tu pensais avoir vu."
    noam neutre "Et maintenant ?"
    iris inquiet "Maintenant je sais encore moins."
    noam blase "Très utile."
    iris agace "Tu veux quoi ? Que je te dise que oui, Mara est morte et qu'une autre Mara se balade dans la cafétéria ?"
    noam peur "Non."
    iris neutre "Parce que moi j'ai pas envie de dire ça."
    noam neutre "Moi non plus."
    "Elle joue avec la fermeture éclair de sa manche."
    iris fatigue "Alors pour ce soir, ton cerveau va bien."
    noam reflexion "C'est tout ?"
    iris determine "C'est tout."
    noam neutre "Et demain ?"
    iris blase "Demain peut aller se faire foutre."
    "Je ris."
    "Elle aussi, un peu."
    iris sourire "Tu vois. Traitement réussi."
    noam taquin "Docteur Iris."
    iris colere "N'abuse pas."
    "Elle se lève."
    iris fatigue "Je vais manger. Tu viens ?"
    noam neutre "Dans cinq minutes."
    iris neutre "Cinq vraies minutes ou cinq minutes de mec qui va fixer son mur pendant une heure ?"
    noam sourire "Vraies."
    iris neutre "Bien."
    "Elle ouvre la porte."
    iris inquiet "Et Noam ?"
    noam neutre "Oui ?"
    iris fatigue "Si t'entends un truc dans les conduits..."
    "Elle hésite."
    iris determine "Tu viens me chercher. Tu y vas pas seul."
    noam reflexion "D'accord."
    iris colere "Je déconne pas."
    noam neutre "J'ai dit d'accord."
    iris neutre "Bien."
    "Elle sort."
    $ hideGroup()
    # Durée : ~4m30
    # Total : ~41m30
label _23_0_1_1_0_0_SOIREE:
    $ current_period = "Soir"
    scene bg_cafeteria at adaptive_fullscreen with dissolve
    play music "music/bgm_quiet_routine.mp3" fadein 0.8
    "Le dîner est presque normal."
    "Presque."
    $ showGroup([
        ("mara", "taquin"),
        ("elias", "fatigue"),
        ("tomas", "reflexion"),
        ("iris", "fatigue"),
        ("noam", "fatigue"),
    ])
    tomas reflexion "Donc les examens sont normaux ?"
    noam blase "La nouvelle a déjà fait le tour ?"
    iris neutre "Mara."
    mara sourire "J'ai demandé."
    noam colere "À qui ?"
    mara taquin "Sael."
    noam neutre "Pourquoi ?"
    mara neutre "Parce que je m'inquiète pour toi."
    iris blase "Elle s'inquiète de savoir si elle peut continuer à te faire chier."
    mara rire "Aussi."
    elias fatigue "Au moins t'as rien."
    noam reflexion "Ouais."
    tomas hesitation "Enfin... rien de visible."
    "Tout le monde le regarde."
    tomas stress "Quoi ? C'est vrai. Une IRM normale exclut pas tout. Les hallucinations peuvent venir de plein de—"
    iris colere "Tomas."
    tomas fatigue "Je sais. Je ferme ma gueule."
    mara taquin "Tu tiens combien de temps ?"
    tomas reflexion "Pas longtemps."
    "Ça fait rire Elias."
    "Je regarde Elias rire."
    "Je ne sais pas pourquoi ça me dérange."
    "Peut-être parce que depuis ce matin, tout me dérange."
    elias reflexion "Quoi ?"
    noam surpris "Rien."
    elias neutre "Tu me fixais."
    noam fatigue "Je suis crevé."
    elias neutre "Ouais, ça se voit."
    mara taquin "Il fixe tout le monde aujourd'hui. Moi ça me plaît bien."
    iris agace "Tu vas finir par le faire fuir."
    mara sourire "Il revient toujours."
    "Je regarde Mara."
    "Elle me fait un clin d'œil."
    "J'ai envie de rire."
    "Et en même temps, quelque chose me retourne l'estomac."
    noam fatigue "Je vais rentrer."
    iris inquiet "Déjà ?"
    noam neutre "Ouais. Je tiens plus."
    mara taquin "Bonne nuit, cerveau normal."
    noam blase "Bonne nuit, Mara."
    "Le nom sort bizarrement."
    "Elle ne semble pas le remarquer."
    $ hideGroup()
    # Durée : ~3m30
    # Total : ~45m00
label _23_0_1_1_0_0_FIN_JOURNEE:
    scene bg_chambre at adaptive_fullscreen with dissolve
    play music "music/bgm_introspective_atmosphere.mp3" fadein 1.0
    "Je ferme la porte."
    "Je pousse le bureau contre la grille."
    "Encore."
    "Puis je m'assois sur le lit."
    "Ma tablette est là, avec le compte rendu des examens."
    "Je l'ouvre."
    "Je relis les mêmes lignes."
    "Réflexes : normaux."
    "Mémoire : normale."
    "Perception : normale."
    "Imagerie : aucune anomalie visible."
    "Je descends encore."
    "Rien."
    think "Rien dans ma tête."
    "Ça devrait être une bonne nouvelle."
    "Je reste pourtant assis, la tablette entre les mains, avec une boule dans le ventre."
    "Si Sael avait trouvé quelque chose, j'aurais eu une explication."
    "Mauvaise, peut-être."
    "Mais une explication."
    "Une hallucination."
    "Un choc."
    "Un cerveau qui fabrique quelque chose parce qu'il ne tient plus."
    "Je regarde la grille."
    "Puis la porte."
    "Puis l'écran."
    think "Mais si j'ai rien..."
    "Je revois Mara."
    "Pas celle du dîner."
    "L'autre."
    "Immobile."
    "Le sang."
    "Cette sensation glacée quand j'ai compris que le visage était le sien."
    "Je secoue la tête."
    noam peur "Non."
    "Le mot sort tout seul."
    "Je me lève, fais deux pas, reviens."
    "Ça ne change rien."
    think "Si j'ai rien..."
    "Je m'arrête."
    "Cette fois je ne termine pas la phrase dans ma tête."
    "Parce que je sais déjà où elle va."
    "Je prends mon téléphone."
    "Le contact d'Iris est juste là."
    "Mon pouce reste au-dessus."
    "Je pourrais l'appeler."
    "Lui dire que je dors pas."
    "Lui demander de venir."
    "Je repose le téléphone."
    think "Elle dort peut-être."
    "Mensonge nul."
    "Je regarde de nouveau le compte rendu."
    "Tout est normal."
    "Tout."
    "Alors une pensée finit par passer quand même."
    "Claire."
    "Simple."
    "Beaucoup plus effrayante que toutes les autres."
    think "Si ce que j'ai vu n'était pas une hallucination..."
    pause 0.8
    think "Alors Mara était vraiment morte."
    "Je reste immobile."
    "Au même moment, quelque chose tombe dans le couloir."
    "Un bruit banal."
    "Peut-être une porte."
    "Peut-être quelqu'un qui a fait tomber un objet."
    "Je me lève quand même."
    "Je m'approche de la porte."
    "Je n'ouvre pas."
    pause 0.6
    "Des pas passent devant ma chambre."
    "Lents."
    "Puis une voix, plus loin."
    mara rire "Mais attends-moi !"
    "Mon sang se glace."
    "Sa voix s'éloigne."
    "Vivante."
    "Normale."
    "Je reste face à la porte pendant plusieurs secondes."
    "Puis je retourne au lit sans vérifier."
    "Cette nuit, je laisse la lumière allumée."
    stop music fadeout 1.2
    call end_day("24", sleeping=True) from _call_j23_stay_end_day_24
    jump _24_0_1_1_0_0_REVEIL
    # Durée : ~4m30
    # Total : ~49m30
