translate portuguese strings:

    old "NOUVELLE MÉCANIQUE"
    new "NOVA MECÂNICA"
    old "COMPRIS, ON Y VA"
    new "ENTENDI, VAMOS LÁ"
    old "PASSER"
    new "PULAR"
    old "DÉFIS"
    new "DESAFIOS"
    old "ÉCHEC"
    new "FALHA"
    old "Rang maximum à la prochaine tentative : [_next_cap]"
    new "Classificação máxima na próxima tentativa: [_next_cap]"
    old "RÉESSAYER"
    new "TENTAR NOVAMENTE"
    old "RÉSULTATS — [title]"
    new "RESULTADOS — [title]"

    old "RECONSTRUISEZ LE VÉRITABLE TEXTE"
    new "RECONSTRUA O TEXTO ORIGINAL"
    old "Remettez les mots dans le bon ordre.\nMontrez-moi que vous comprenez vraiment ce que vous votez."
    new "Coloque as palavras na ordem correta.\nMostre que você realmente entende o que está votando."
    old "MOTS DISPONIBLES"
    new "PALAVRAS DISPONÍVEIS"
    old "VOTRE PHRASE"
    new "SUA FRASE"
    old "↻  RÉINITIALISER"
    new "↻  REINICIAR"
    old "✓  VALIDER"
    new "✓  CONFIRMAR"

    old "Archives de Surveillance - Jour 10"
    new "Arquivos de Vigilância - Dia 10"
    old "SELECTION CAMERA"
    new "SELEÇÃO DE CÂMERA"
    old "TRANCHE HORAIRE"
    new "FAIXA DE HORÁRIO"
    old "VISIONNER"
    new "REPRODUZIR"
    old "Il n'y avait pas d'activite a ce moment la."
    new "Não havia atividade naquele momento."
    old "ARCHIVE NOIRE / SIGNAL INEXPLOITABLE"
    new "ARQUIVO NEGRO / SINAL INUTILIZÁVEL"
    old "ANOMALIE DETECTEE"
    new "ANOMALIA DETECTADA"

    old "CONTRE-INTERROGATOIRE"
    new "CONTRA-INTERROGATÓRIO"
    old "ÉCOUTE • ARME • CONTREDIS"
    new "OUÇA • ARME-SE • CONTESTE"
    old "Huit déclarations vont défiler. Trois fragments seront surlignés en jaune."
    new "Oito declarações serão exibidas. Três trechos serão destacados em amarelo."
    old "Choisis une réplique avec la souris ou les touches 1, 2 et 3."
    new "Escolha uma resposta com o mouse ou as teclas 1, 2 e 3."
    old "Clique le fragment jaune, ou appuie sur Espace. Une seule association est décisive."
    new "Clique no trecho amarelo ou pressione Espaço. Apenas uma associação é decisiva."
    old "COMMENCER"
    new "COMEÇAR"
    old "FAILLE DÉCISIVE TROUVÉE"
    new "FALHA DECISIVA ENCONTRADA"
    old "REPRENDRE LA SCÈNE"
    new "RETOMAR A CENA"

    old "LE FIL D'EQUILIBRE"
    new "A LINHA DO EQUILÍBRIO"
    old "Place les poids. Contre les ombres. Valide quand Noam tient debout."
    new "Posicione os pesos. Combata as sombras. Confirme quando Noam estiver de pé."
    old "Provoquer une ombre"
    new "Provocar uma sombra"
    old "Repartir de zero"
    new "Recomeçar do zero"
    old "Valider ce positionnement"
    new "Confirmar esta posição"
    old "Retour au debat"
    new "Voltar ao debate"

    old "Réagissez aux failles de Kami avant qu’elles disparaissent."
    new "Reaja às fraturas de Kami antes que desapareçam."
    old "RÉUSSITES [j601_fracture_success_count]/[j601_fracture_sequence_length]"
    new "SUCESSOS [j601_fracture_success_count]/[j601_fracture_sequence_length]"
    old "ARGUMENT SUIVANT"
    new "PRÓXIMO ARGUMENTO"

    old "SIGNAL INSTABLE"
    new "SINAL INSTÁVEL"
    old "Maintenez le curseur dans la zone verte. Corrigez les fractures avec ESPACE."
    new "Mantenha o cursor na zona verde. Corrija as fraturas com ESPAÇO."
    old "ZONE VERTE [j601_signal_green_time:.1f]s"
    new "ZONA VERDE [j601_signal_green_time:.1f]s"
    old "◀ GAUCHE"
    new "◀ ESQUERDA"
    old "DROITE ▶"
    new "DIREITA ▶"

    old "LE SIGNAL VIVANT"
    new "O SINAL VIVO"
    old "Combinez les fréquences. Pulsez les quadrants. Détruisez les orbes de Kami."
    new "Combine frequências. Pulsione os quadrantes. Destrua os orbes de Kami."
    old "SLOTS ACTIFS"
    new "SLOTS ATIVOS"
    old "PALETTE DE FRÉQUENCES"
    new "PALETA DE FREQUÊNCIAS"
    old "CARTE DES CAMPEMENTS — 4 FRONTS"
    new "MAPA DOS ACAMPAMENTOS — 4 FRENTES"
    old "BILAN DE TRANSMISSION"
    new "RELATÓRIO DA TRANSMISSÃO"
    old "LE SIGNAL VIVANT — BRIEFING"
    new "O SINAL VIVO — INSTRUÇÕES"
    old "LANCER LA TRANSMISSION"
    new "INICIAR TRANSMISSÃO"

    old "STABILISATION"
    new "ESTABILIZAÇÃO"
    old "Réponds vite. Ne le laisse pas repartir seul dans sa panique."
    new "Responda rápido. Não o deixe enfrentar o pânico sozinho novamente."
    old "RÉPONSES [j801_stab_success_count]/[len(j801_stab_events)]"
    new "RESPOSTAS [j801_stab_success_count]/[len(j801_stab_events)]"
    old "CHAOS [j801_stab_shake]/5"
    new "CAOS [j801_stab_shake]/5"
