translate english strings:

    old "NOUVELLE MÉCANIQUE"
    new "NEW MECHANIC"
    old "COMPRIS, ON Y VA"
    new "GOT IT, LET'S GO"
    old "PASSER"
    new "SKIP"
    old "DÉFIS"
    new "CHALLENGES"
    old "ÉCHEC"
    new "FAILED"
    old "Rang maximum à la prochaine tentative : [_next_cap]"
    new "Maximum rank on the next attempt: [_next_cap]"
    old "RÉESSAYER"
    new "TRY AGAIN"
    old "RÉSULTATS — [title]"
    new "RESULTS — [title]"

    old "RECONSTRUISEZ LE VÉRITABLE TEXTE"
    new "REBUILD THE ORIGINAL TEXT"
    old "Remettez les mots dans le bon ordre.\nMontrez-moi que vous comprenez vraiment ce que vous votez."
    new "Put the words back in the right order.\nShow me you truly understand what you are voting on."
    old "MOTS DISPONIBLES"
    new "AVAILABLE WORDS"
    old "VOTRE PHRASE"
    new "YOUR SENTENCE"
    old "↻  RÉINITIALISER"
    new "↻  RESET"
    old "✓  VALIDER"
    new "✓  CONFIRM"

    old "Archives de Surveillance - Jour 10"
    new "Surveillance Archives - Day 10"
    old "SELECTION CAMERA"
    new "CAMERA SELECTION"
    old "TRANCHE HORAIRE"
    new "TIME SLOT"
    old "VISIONNER"
    new "PLAY"
    old "Il n'y avait pas d'activite a ce moment la."
    new "There was no activity at that time."
    old "ARCHIVE NOIRE / SIGNAL INEXPLOITABLE"
    new "BLACK ARCHIVE / UNUSABLE SIGNAL"
    old "ANOMALIE DETECTEE"
    new "ANOMALY DETECTED"

    old "CONTRE-INTERROGATOIRE"
    new "CROSS-EXAMINATION"
    old "ÉCOUTE • ARME • CONTREDIS"
    new "LISTEN • ARM • COUNTER"
    old "Huit déclarations vont défiler. Trois fragments seront surlignés en jaune."
    new "Eight statements will appear. Three fragments will be highlighted in yellow."
    old "Choisis une réplique avec la souris ou les touches 1, 2 et 3."
    new "Choose a response with the mouse or keys 1, 2, and 3."
    old "Clique le fragment jaune, ou appuie sur Espace. Une seule association est décisive."
    new "Click the yellow fragment or press Space. Only one match is decisive."
    old "COMMENCER"
    new "START"
    old "FAILLE DÉCISIVE TROUVÉE"
    new "DECISIVE FLAW FOUND"
    old "REPRENDRE LA SCÈNE"
    new "RESUME SCENE"

    old "LE FIL D'EQUILIBRE"
    new "THE BALANCE LINE"
    old "Place les poids. Contre les ombres. Valide quand Noam tient debout."
    new "Place the weights. Counter the shadows. Confirm when Noam can stand."
    old "Provoquer une ombre"
    new "Trigger a shadow"
    old "Repartir de zero"
    new "Start over"
    old "Valider ce positionnement"
    new "Confirm this placement"
    old "Retour au debat"
    new "Return to the debate"

    old "Réagissez aux failles de Kami avant qu’elles disparaissent."
    new "React to Kami's fractures before they disappear."
    old "RÉUSSITES [j601_fracture_success_count]/[j601_fracture_sequence_length]"
    new "SUCCESSES [j601_fracture_success_count]/[j601_fracture_sequence_length]"
    old "ARGUMENT SUIVANT"
    new "NEXT ARGUMENT"

    old "SIGNAL INSTABLE"
    new "UNSTABLE SIGNAL"
    old "Maintenez le curseur dans la zone verte. Corrigez les fractures avec ESPACE."
    new "Keep the cursor in the green zone. Repair fractures with SPACE."
    old "ZONE VERTE [j601_signal_green_time:.1f]s"
    new "GREEN ZONE [j601_signal_green_time:.1f]s"
    old "◀ GAUCHE"
    new "◀ LEFT"
    old "DROITE ▶"
    new "RIGHT ▶"

    old "LE SIGNAL VIVANT"
    new "THE LIVING SIGNAL"
    old "Combinez les fréquences. Pulsez les quadrants. Détruisez les orbes de Kami."
    new "Combine frequencies. Pulse the quadrants. Destroy Kami's orbs."
    old "SLOTS ACTIFS"
    new "ACTIVE SLOTS"
    old "PALETTE DE FRÉQUENCES"
    new "FREQUENCY PALETTE"
    old "CARTE DES CAMPEMENTS — 4 FRONTS"
    new "ENCAMPMENT MAP — 4 FRONTS"
    old "BILAN DE TRANSMISSION"
    new "TRANSMISSION REPORT"
    old "LE SIGNAL VIVANT — BRIEFING"
    new "THE LIVING SIGNAL — BRIEFING"
    old "LANCER LA TRANSMISSION"
    new "START TRANSMISSION"

    old "STABILISATION"
    new "STABILIZATION"
    old "Réponds vite. Ne le laisse pas repartir seul dans sa panique."
    new "Answer quickly. Do not let him face his panic alone again."
    old "RÉPONSES [j801_stab_success_count]/[len(j801_stab_events)]"
    new "ANSWERS [j801_stab_success_count]/[len(j801_stab_events)]"
    old "CHAOS [j801_stab_shake]/5"
    new "CHAOS [j801_stab_shake]/5"
