translate chinese strings:

    old "NOUVELLE MÉCANIQUE"
    new "新机制"
    old "COMPRIS, ON Y VA"
    new "明白，开始吧"
    old "PASSER"
    new "跳过"
    old "DÉFIS"
    new "挑战"
    old "ÉCHEC"
    new "失败"
    old "Rang maximum à la prochaine tentative : [_next_cap]"
    new "下次尝试的最高等级：[_next_cap]"
    old "RÉESSAYER"
    new "重试"
    old "RÉSULTATS — [title]"
    new "结果 — [title]"

    old "RECONSTRUISEZ LE VÉRITABLE TEXTE"
    new "重组原始文本"
    old "Remettez les mots dans le bon ordre.\nMontrez-moi que vous comprenez vraiment ce que vous votez."
    new "将词语按正确顺序排列。\n证明你真正理解自己正在投票的内容。"
    old "MOTS DISPONIBLES"
    new "可用词语"
    old "VOTRE PHRASE"
    new "你的句子"
    old "↻  RÉINITIALISER"
    new "重置"
    old "✓  VALIDER"
    new "确认"

    old "Archives de Surveillance - Jour 10"
    new "监控档案 - 第10天"
    old "SELECTION CAMERA"
    new "选择摄像头"
    old "TRANCHE HORAIRE"
    new "时间段"
    old "VISIONNER"
    new "播放"
    old "Il n'y avait pas d'activite a ce moment la."
    new "当时没有活动。"
    old "ARCHIVE NOIRE / SIGNAL INEXPLOITABLE"
    new "黑档案 / 信号无法使用"
    old "ANOMALIE DETECTEE"
    new "检测到异常"

    old "CONTRE-INTERROGATOIRE"
    new "交叉询问"
    old "ÉCOUTE • ARME • CONTREDIS"
    new "倾听 • 武装 • 反驳"
    old "Huit déclarations vont défiler. Trois fragments seront surlignés en jaune."
    new "屏幕会依次显示八段陈述，其中三个片段将以黄色标出。"
    old "Choisis une réplique avec la souris ou les touches 1, 2 et 3."
    new "用鼠标或 1、2、3 键选择回应。"
    old "Clique le fragment jaune, ou appuie sur Espace. Une seule association est décisive."
    new "点击黄色片段或按空格键。只有一种匹配能决定胜负。"
    old "COMMENCER"
    new "开始"
    old "FAILLE DÉCISIVE TROUVÉE"
    new "找到决定性破绽"
    old "REPRENDRE LA SCÈNE"
    new "继续场景"

    old "LE FIL D'EQUILIBRE"
    new "平衡之线"
    old "Place les poids. Contre les ombres. Valide quand Noam tient debout."
    new "放置权重，抵抗阴影。当 Noam 站稳时确认。"
    old "Provoquer une ombre"
    new "触发阴影"
    old "Repartir de zero"
    new "从头开始"
    old "Valider ce positionnement"
    new "确认此位置"
    old "Retour au debat"
    new "返回辩论"

    old "Réagissez aux failles de Kami avant qu’elles disparaissent."
    new "在 Kami 的裂隙消失前作出反应。"
    old "RÉUSSITES [j601_fracture_success_count]/[j601_fracture_sequence_length]"
    new "成功 [j601_fracture_success_count]/[j601_fracture_sequence_length]"
    old "ARGUMENT SUIVANT"
    new "下一个论点"

    old "SIGNAL INSTABLE"
    new "信号不稳定"
    old "Maintenez le curseur dans la zone verte. Corrigez les fractures avec ESPACE."
    new "将光标保持在绿色区域内，用空格键修复裂隙。"
    old "ZONE VERTE [j601_signal_green_time:.1f]s"
    new "绿色区域 [j601_signal_green_time:.1f]秒"
    old "◀ GAUCHE"
    new "◀ 左"
    old "DROITE ▶"
    new "右 ▶"

    old "LE SIGNAL VIVANT"
    new "活体信号"
    old "Combinez les fréquences. Pulsez les quadrants. Détruisez les orbes de Kami."
    new "组合频率，向象限发出脉冲，摧毁 Kami 的球体。"
    old "SLOTS ACTIFS"
    new "活跃插槽"
    old "PALETTE DE FRÉQUENCES"
    new "频率调色板"
    old "CARTE DES CAMPEMENTS — 4 FRONTS"
    new "营地地图 — 4条战线"
    old "BILAN DE TRANSMISSION"
    new "传输报告"
    old "LE SIGNAL VIVANT — BRIEFING"
    new "活体信号 — 任务说明"
    old "LANCER LA TRANSMISSION"
    new "开始传输"

    old "STABILISATION"
    new "稳定"
    old "Réponds vite. Ne le laisse pas repartir seul dans sa panique."
    new "快速回应。别让他再独自陷入恐慌。"
    old "RÉPONSES [j801_stab_success_count]/[len(j801_stab_events)]"
    new "回应 [j801_stab_success_count]/[len(j801_stab_events)]"
    old "CHAOS [j801_stab_shake]/5"
    new "混乱 [j801_stab_shake]/5"
