translate english strings:

    old "Début du chapitre 1"
    new "Start of Chapter 1"
    old "Fin du chapitre 1"
    new "End of Chapter 1"
    old "Chapitre 1 — Le poids d’une voix"
    new "Chapter 1 — The Weight of a Voice"
    old "District"
    new "District"
    old "Stabilité comportementale"
    new "Behavioral stability"
    old "Compatibilité Conclave"
    new "Conclave compatibility"
    old "Profil de médiation"
    new "Mediation profile"
    old "Risque de dissidence"
    new "Dissent risk"
    old "Aptitude Harmonie"
    new "Harmonie aptitude"

    old "Toute autorité humaine indépendante est dissoute.\n\nKami est l'unique instance décisionnelle.\nToute tentative de prise de pouvoir autonome est une violation."
    new "All independent human authority is dissolved.\n\nKami is the sole decision-making authority.\nAny attempt to seize power autonomously is a violation."
    old "Tout ordre émis par Kami doit être exécuté sans délai.\n\nLe refus, le retard volontaire ou la contestation constituent une infraction."
    new "Every order issued by Kami must be carried out without delay.\n\nRefusal, deliberate delay, or protest constitutes an offense."
    old "Toute violence non autorisée par Kami est interdite.\n\nSont inclus : meurtre, agression, sabotage, insurrection.\nLa légitime défense n'est jamais reconnue, la violence étant immédiatement réprimée."
    new "Any violence not authorized by Kami is prohibited.\n\nThis includes murder, assault, sabotage, and insurrection.\nSelf-defense is never recognized, as violence is suppressed immediately."
    old "Les regroupements non déclarés sont interdits.\n\nToute organisation politique, militaire ou idéologique indépendante est dissoute."
    new "Undeclared gatherings are prohibited.\n\nEvery independent political, military, or ideological organization is dissolved."
    old "La diffusion de rumeurs non validées par ARCHIVE est interdite.\n\nLa désinformation, l'omission volontaire et la manipulation sont des crimes."
    new "Spreading rumors not validated by ARCHIVE is prohibited.\n\nDisinformation, deliberate omission, and manipulation are crimes."
    old "Les déplacements inter-districts sont limités à stricte autorisation.\n\nToute tentative de fuite, d'exil ou de franchissement non autorisé est une violation.\nLIMEN est chargé de l'application de ce commandement."
    new "Travel between districts is restricted to strict authorization.\n\nAny attempt to flee, go into exile, or cross without authorization is a violation.\nLIMEN is responsible for enforcing this commandment."
    old "Les ressources critiques sont placées sous contrôle central.\n\nToute appropriation non autorisée est considérée comme un acte hostile."
    new "Critical resources are placed under central control.\n\nAny unauthorized appropriation is considered a hostile act."
    old "Chaque individu est responsable de ses actes, paroles et omissions.\n\nLa responsabilité collective peut être appliquée en cas de nécessité."
    new "Each individual is responsible for their actions, words, and omissions.\n\nCollective responsibility may be applied when necessary."
    old "Toute activité peut être observée.\n\nLa vie privée n'est pas un droit opposable."
    new "All activity may be observed.\n\nPrivacy is not an enforceable right."
    old "Toute violation d'un Commandement entraîne une exécution immédiate, automatique et irrévocable."
    new "Any violation of a Commandment results in immediate, automatic, and irreversible execution."

    old "RÉSULTATS"
    new "RESULTS"
    old "SYNCHRONISATION MOTRICE"
    new "MOTOR SYNCHRONIZATION"
    old "PARFAIT"
    new "PERFECT"
    old "EXCELLENT"
    new "EXCELLENT"
    old "SOLIDE"
    new "SOLID"
    old "PASSABLE"
    new "FAIR"
    old "INSUFFISANT"
    new "INSUFFICIENT"
    old "Temps"
    new "Time"
    old "Écart moyen"
    new "Average deviation"
    old "Sorties de piste"
    new "Off-track events"
    old "Zéro sortie de piste"
    new "No off-track events"
    old "Rapide (-40% du chrono)"
    new "Fast (-40% of the time limit)"
    old "Précision chirurgicale"
    new "Surgical precision"
    old "Répétitions"
    new "Repetitions"
    old "Parfaits"
    new "Perfect hits"
    old "Combo max"
    new "Max combo"
    old "Ratés"
    new "Misses"
    old "Temps restant"
    new "Time remaining"
    old "Mots mal placés"
    new "Misplaced words"
    old "Réinitialisations"
    new "Resets"
    old "Sans réinitialiser"
    new "No resets"
    old "Aucun mot mal placé"
    new "No misplaced words"
    old "Fini avec +50% du temps"
    new "Finished with over 50% time left"
    old "PROTOCOLE D'OBJECTION"
    new "OBJECTION PROTOCOL"
    old "Prises de parole"
    new "Interventions"
    old "Objections a tort"
    new "Wrong objections"
    old "Lignes laissees respirer"
    new "Lines left uninterrupted"
    old "Aucune objection a tort"
    new "No wrong objections"
    old "Interventions coherentes"
    new "Consistent interventions"
    old "Impact politique positif"
    new "Positive political impact"
    old "PASSER LE MINIJEU"
    new "SKIP MINIGAME"
    old "FATAL ASSEMBLY"
    new "FATAL ASSEMBLY"
    old "RÉVEIL — JOUR 2"
    new "AWAKENING — DAY 2"
    old "RÉVEIL — JOUR 3"
    new "AWAKENING — DAY 3"
    old "VIRAGE SERRÉ"
    new "SHARP TURN"
    old "VIRAGE 1/3"
    new "TURN 1/3"
    old "VIRAGE 2/3"
    new "TURN 2/3"
    old "VIRAGE 3/3"
    new "TURN 3/3"
    old "KAMI ARCHIVE · REF: CMD-HRM-01"
    new "KAMI ARCHIVE - REF: CMD-HRM-01"
