translate english strings:

    # Day 0 — arrival, security gate and representative selection.
    old "ACHEMINEMENT — CONCLAVE"
    new "TRANSFER — CONCLAVE"
    old "DÉLAI EXPIRÉ"
    new "TIME LIMIT EXPIRED"
    old "LIMITE : 22:00  ▸  RESTANT"
    new "DEADLINE: 22:00  ▸  REMAINING"
    old "PORTIQUE DE SÉCURITÉ — DISTRICT HARMONIE"
    new "SECURITY GATE — HARMONIE DISTRICT"
    old "● ACTIF"
    new "● ACTIVE"
    old "LECTEUR CIVIL / IDENTIFICATION OBLIGATOIRE"
    new "CIVILIAN READER / IDENTIFICATION REQUIRED"
    old "POSER LE BADGE SUR LA ZONE DE LECTURE"
    new "PLACE THE BADGE ON THE SCANNING AREA"
    old "Chaque entrée est enregistrée."
    new "Every entry is recorded."
    old "↓  ZONE DE LECTURE  ↓"
    new "↓  SCANNING AREA  ↓"
    old "BADGE ENREGISTRÉ"
    new "BADGE RECORDED"
    old "DISTRICT HARMONIE"
    new "HARMONIE DISTRICT"
    old "Médiateur civil · Secteur 3"
    new "Civilian mediator · Sector 3"
    old "LECTEUR BIOMÉTRIQUE"
    new "BIOMETRIC READER"
    old "EN ATTENTE"
    new "STANDBY"
    old "ANALYSE EN COURS"
    new "ANALYSIS IN PROGRESS"
    old "ACCÈS AUTORISÉ"
    new "ACCESS GRANTED"
    old "Présenter le badge dans la zone."
    new "Present the badge in the scanning area."
    old "Comparaison profil civil en cours."
    new "Civilian profile comparison in progress."
    old "VALIDATION DE L'IDENTITÉ..."
    new "VALIDATING IDENTITY..."
    old "Comparaison du profil avec les autorisations locales."
    new "Comparing profile with local permissions."
    old "PASSAGE CONFIRMÉ"
    new "ENTRY CONFIRMED"
    old "Comportement conforme. Identité reconnue."
    new "Behavior compliant. Identity recognized."
    old "IDENTIFIANT CIVIL"
    new "CIVILIAN ID"
    old "▶  GLISSER"
    new "▶  SWIPE"
    old "KAMI INFRASTRUCTURE · CONTRÔLE CIVIL AUTOMATISÉ · TOUTE ENTRÉE EST ENREGISTRÉE"
    new "KAMI INFRASTRUCTURE · AUTOMATED CIVILIAN CONTROL · EVERY ENTRY IS RECORDED"
    old "ÉCRAN VERROUILLÉ"
    new "SCREEN LOCKED"
    old "Glisser vers le haut pour déverrouiller"
    new "Swipe up to unlock"
    old "VENDREDI — JOUR 0"
    new "FRIDAY — DAY 0"
    old "Signal : --   •   Réseau : indisponible"
    new "Signal: --   •   Network: unavailable"
    old "Recherche de réseau..."
    new "Searching for network..."
    old "AUCUN RÉSEAU"
    new "NO NETWORK"
    old "Recherche des relais civils en cours..."
    new "Searching for civilian relays..."
    old "ERR_NET_001 · Aucun opérateur disponible"
    new "ERR_NET_001 · No carrier available"
    old "Les services de communication\nsont temporairement indisponibles."
    new "Communication services are\ntemporarily unavailable."
    old "APPEL REFUSÉ"
    new "CALL DENIED"
    old "Appels d'urgence indisponibles."
    new "Emergency calls unavailable."
    old "Code : INFRASTRUCTURE NON SOUVERAINE"
    new "Code: NON-SOVEREIGN INFRASTRUCTURE"
    old "Tous les canaux de communication\ndépendent désormais de KAMI."
    new "All communication channels\nnow depend on KAMI."
    old "ERR_NET_403 · ACCÈS BLOQUÉ"
    new "ERR_NET_403 · ACCESS BLOCKED"
    old "MESSAGE NON ENVOYÉ"
    new "MESSAGE NOT SENT"
    old "Merci de cesser toute tentative de\nréinitialisation du réseau.\nCette conversation est enregistrée."
    new "Please stop attempting to\nreset the network.\nThis conversation is being recorded."
    old "Le réseau de communication\nne vous appartient plus."
    new "The communication network\nno longer belongs to you."
    old "• 1 message non distribué"
    new "• 1 undelivered message"
    old "CONTRÔLE DISTANT ACTIF"
    new "REMOTE CONTROL ACTIVE"
    old "Verrouillage de l'interface."
    new "Locking interface."
    old "Cet appareil est désormais\nsous surveillance directe."
    new "This device is now\nunder direct surveillance."
    old "Rallumer"
    new "Power on"
    old "Envoyer"
    new "Send"
    old "REGISTRE DES COMMANDEMENTS"
    new "COMMANDMENTS REGISTRY"
    old "District HARMONIE · Consultation surveillée"
    new "HARMONIE District · Monitored consultation"
    old "Commandement %s"
    new "Commandment %s"
    old "COMMANDEMENT"
    new "COMMANDMENT"
    old "◀ Précédent"
    new "◀ Previous"
    old "Suivant ▶"
    new "Next ▶"
    old "Fermer"
    new "Close"
    old "DISTRICT HARMONIE — SÉLECTION DES REPRÉSENTANTS"
    new "HARMONIE DISTRICT — REPRESENTATIVE SELECTION"
    old "Cliquez pour arrêter la sélection"
    new "Click to stop the selection"
    old "PROFILS EN ANALYSE"
    new "PROFILES UNDER REVIEW"
    old "✓  SÉLECTIONNÉ"
    new "✓  SELECTED"
    old "PROFIL ÉCARTÉ"
    new "PROFILE REJECTED"
    old "CRITÈRES D'ANALYSE"
    new "ANALYSIS CRITERIA"
    old "EN COURS…"
    new "IN PROGRESS…"
    old "VALIDÉ"
    new "VALIDATED"
    old "SÉLECTION VALIDÉE"
    new "SELECTION VALIDATED"
    old "REPRÉSENTANTS — DISTRICT HARMONIE"
    new "REPRESENTATIVES — HARMONIE DISTRICT"
    old "Médiateur civil"
    new "Civilian mediator"
    old "Coordination logistique"
    new "Logistics coordination"
    old "Acheminement sous 6 heures — Sanctions applicables en cas de retard."
    new "Transfer within 6 hours — Penalties apply in case of delay."
    old "KAMI — SÉLECTION AUTOMATISÉE · DISTRICT HARMONIE · SÉANCE 14-3"
    new "KAMI — AUTOMATED SELECTION · HARMONIE DISTRICT · SESSION 14-3"
    old "// La liste déroulante n'est qu'une façade."
    new "// The scrolling list is only a facade."
    old "// Sélection terminée avant le début de la séance."
    new "// Selection completed before the session began."
    old "FERMETURE AUTOMATIQUE // 2.0 s"
    new "AUTOMATIC CLOSURE // 2.0 s"
    old "SOUVENIR"
    new "MEMORY"

    # Day 1 — desk, amendment, jammer and motor-sync tutorial.
    old "JOUR"
    new "DAY"
    old "INTERFACE PUPITRE — CONCLAVE"
    new "DESK INTERFACE — CONCLAVE"
    old "SESSION : EN ATTENTE  ▸  VERROUILLÉ"
    new "SESSION: STANDBY  ▸  LOCKED"
    old "UTILISATEUR"
    new "USER"
    old "STATUT"
    new "STATUS"
    old "REPRÉSENTANT — CONCLAVE JOUR 1"
    new "REPRESENTATIVE — CONCLAVE DAY 1"
    old "ACCÈS TABLETTE"
    new "TABLET ACCESS"
    old "▸  AMENDEMENTS  —  VERROUILLÉ JUSQU'AU DÉPÔT"
    new "▸  AMENDMENTS  —  LOCKED UNTIL SUBMISSION"
    old "▸  CODEX  —  ACCÈS PARTIEL"
    new "▸  CODEX  —  PARTIAL ACCESS"
    old "▸  COMMUNICATIONS  —  BLOQUÉES"
    new "▸  COMMUNICATIONS  —  BLOCKED"
    old "INTERACTION ENREGISTRÉE — KAMI MONITORING ACTIF"
    new "INTERACTION RECORDED — KAMI MONITORING ACTIVE"
    old "RETIRER LA MAIN"
    new "REMOVE HAND"
    old "✦  CODEX  —  NOUVELLE ENTRÉE  :"
    new "✦  CODEX  —  NEW ENTRY:"
    old "DÉPÔT CLOS"
    new "SUBMISSIONS CLOSED"
    old "FERMETURE  ▸  RESTANT"
    new "CLOSING  ▸  REMAINING"
    old "TUTORIEL — PROPOSITION D'AMENDEMENT"
    new "TUTORIAL — AMENDMENT PROPOSAL"
    old "Comment proposer un amendement :"
    new "How to propose an amendment:"
    old "① Lisez attentivement les deux propositions de modification de Commandement."
    new "① Carefully read both proposed changes to the Commandment."
    old "② Sélectionnez la proposition qui vous semble la plus juste ou la plus utile."
    new "② Select the proposal that seems fairest or most useful."
    old "③ La formulation officielle sera automatiquement retenue."
    new "③ The official wording will be selected automatically."
    old "④ Une fois validé, l'amendement est anonymement déposé dans l'urne — sans retour possible."
    new "④ Once confirmed, the amendment is submitted anonymously — it cannot be withdrawn."
    old "⚠  Ce choix est définitif. Il engage Noam pour l'ensemble du Conclave."
    new "⚠  This choice is final. It commits Noam for the entire Conclave."
    old "COMPRIS — CONTINUER"
    new "UNDERSTOOD — CONTINUE"
    old "TERMINAL CONSTITUTIONNEL — PROPOSITION D'AMENDEMENT"
    new "CONSTITUTIONAL TERMINAL — AMENDMENT PROPOSAL"
    old "REPRÉSENTANT : NOAM  ▸  STATUT : BROUILLON  ▸  ANONYMAT : GARANTI"
    new "REPRESENTATIVE: NOAM  ▸  STATUS: DRAFT  ▸  ANONYMITY: GUARANTEED"
    old "SÉLECTIONNÉ"
    new "SELECTED"
    old "INTENTION"
    new "INTENT"
    old "FORMULATION"
    new "WORDING"
    old "RISQUE IDENTIFIÉ"
    new "IDENTIFIED RISK"
    old "FORMULATION OFFICIELLE RETENUE :"
    new "SELECTED OFFICIAL WORDING:"
    old "VALIDER LA PROPOSITION"
    new "CONFIRM PROPOSAL"
    old "CONFIRMATION — DÉPÔT DÉFINITIF"
    new "CONFIRMATION — FINAL SUBMISSION"
    old "Ce dépôt est IRRÉVERSIBLE. L'amendement sera traité de façon anonyme."
    new "This submission is IRREVERSIBLE. The amendment will be processed anonymously."
    old "← MODIFIER"
    new "← EDIT"
    old "DÉPOSER DANS L'URNE →"
    new "SUBMIT TO THE BALLOT BOX →"
    old "AMENDEMENT DÉPOSÉ"
    new "AMENDMENT SUBMITTED"
    old "RETRAIT IMPOSSIBLE"
    new "WITHDRAWAL IMPOSSIBLE"
    old "ENREGISTREMENT CONFIRMÉ"
    new "SUBMISSION CONFIRMED"
    old "ANONYMAT GARANTI — KAMI NE PEUT PAS IDENTIFIER L'AUTEUR"
    new "ANONYMITY GUARANTEED — KAMI CANNOT IDENTIFY THE AUTHOR"
    old "TIRAGE AU SORT DEMAIN À 09:00"
    new "DRAW TOMORROW AT 09:00"
    old "RECULER DE L'URNE"
    new "STEP AWAY FROM THE BALLOT BOX"
    old "INTERFACE CHAMBRE — BROUILLEUR"
    new "ROOM INTERFACE — JAMMER"
    old "BROUILLEUR : "
    new "JAMMER: "
    old "MODE PRIVÉ : "
    new "PRIVATE MODE: "
    old "CAMÉRA : COUPÉE"
    new "CAMERA: OFF"
    old "AUDIO : COUPÉ"
    new "AUDIO: OFF"
    old "CAPTEURS : COUPÉS"
    new "SENSORS: OFF"
    old "KAMI : AVEUGLE"
    new "KAMI: BLIND"
    old "SURVEILLANCE POTENTIELLE — KAMI PEUT OBSERVER CETTE PIÈCE"
    new "POTENTIAL SURVEILLANCE — KAMI MAY OBSERVE THIS ROOM"
    old "DÉSACTIVER LE BROUILLEUR"
    new "DISABLE JAMMER"
    old "RÉACTIVER LE BROUILLEUR"
    new "REACTIVATE JAMMER"
    old "QUITTER L'INTERFACE"
    new "CLOSE INTERFACE"
    old "TUTORIEL — SYNCHRONISATION MOTRICE"
    new "TUTORIAL — MOTOR SYNCHRONIZATION"
    old "Comment répondre à un QTE de trace :"
    new "How to complete a tracing QTE:"
    old "① Une courbe ou un chemin s'affiche à l'écran."
    new "① A curve or path appears on screen."
    old "② Suivez ce tracé avec votre souris le plus précisément possible."
    new "② Follow the path with your mouse as accurately as possible."
    old "③ Restez dans la tolérance indiquée (zone colorée) pour valider."
    new "③ Stay within the indicated tolerance (colored area) to succeed."
    old "④ Trop d'erreurs = échec. Restez concentré et allez à un rythme régulier."
    new "④ Too many mistakes mean failure. Stay focused and keep a steady pace."
    old "Ce QTE simule la perte de contrôle moteur de Noam au réveil."
    new "This QTE simulates Noam's loss of motor control upon waking."
    old "COMPRIS — LANCER LE QTE"
    new "UNDERSTOOD — START QTE"

    # Days 2–3 — vote files, debate and mini-games.
    old "Glisse la carte dans la mallette de Noam."
    new "Drag the card into Noam's briefcase."
    old "ARGUMENT"
    new "ARGUMENT"
    old "DOSSIER DU VOTE"
    new "VOTE FILE"
    old "DÉPOSER ICI"
    new "DROP HERE"
    old "TABLETTE DE NOAM"
    new "NOAM'S TABLET"
    old "Nouveau dossier disponible : Prochain vote"
    new "New file available: Upcoming vote"
    old "La fiche rassemble la proposition, les arguments rangés dans ton dossier et les positions que tu supposes chez les autres représentants."
    new "The file contains the proposal, the arguments stored in your case, and your estimates of the other representatives' positions."
    old "Les portraits peuvent être déplacés librement entre POUR, INCONNU et CONTRE. Ce classement est une note personnelle, pas une correction automatique."
    new "Portraits can be moved freely between FOR, UNKNOWN, and AGAINST. This is a personal note, not an automatic correction."
    old "Continuer"
    new "Continue"
    old "Prochain vote"
    new "Upcoming vote"
    old "Vote en cours"
    new "Current vote"
    old "Ça serait bien qu'on réautorise le commerce comme avant."
    new "It would be good to allow trade again, like before."
    old "Moment prévu : Jour 3, 14h00"
    new "Scheduled time: Day 3, 14:00"
    old "Moment prévu : Jour 6, 14h00"
    new "Scheduled time: Day 6, 14:00"
    old "Résumé neutre"
    new "Neutral summary"
    old "Le texte promet une circulation plus libre des biens. Ses effets restent incertains selon les districts, les procédures et les risques locaux."
    new "The text promises freer movement of goods. Its effects remain uncertain across districts, procedures, and local risks."
    old "Autoriser ou non les déplacements entre les districts."
    new "Decide whether to allow travel between districts."
    old "Le texte promet une circulation plus libre des personnes entre districts. Ses effets restent incertains selon les frontières, la sécurité et les capacités d'accueil."
    new "The text promises freer movement between districts. Its effects remain uncertain depending on borders, security, and local capacity."
    old "Arguments découverts"
    new "Discovered arguments"
    old "Argument non découvert"
    new "Undiscovered argument"
    old "Glisse les portraits ici."
    new "Drag portraits here."
    old "Dossier actif"
    new "Active file"
    old "Arguments rangés : [day2_vote_argument_count()] / [len(DAY2_VOTE_ARGUMENTS)]"
    new "Stored arguments: [day2_vote_argument_count()] / [len(DAY2_VOTE_ARGUMENTS)]"
    old "Les positions restent modifiables dans le Codex."
    new "Positions can still be changed in the Codex."
    old "CHOIX DU THÈME"
    new "CHOOSE A TOPIC"
    old "PHASE ARGUMENTATIVE"
    new "ARGUMENT PHASE"
    old "PHASE [phase]/3"
    new "PHASE [phase]/3"
    old "Quel angle aborder pour cette discussion ?\nJe dois choisir l'argument qui aura le plus d'impact."
    new "Which angle should I take in this discussion?\nI need to choose the argument with the greatest impact."
    old "SÉLECTIONNEZ LE THÈME DE LA DISCUSSION"
    new "SELECT THE DISCUSSION TOPIC"
    old "Débloquez cet argument pour l'utiliser."
    new "Unlock this argument to use it."
    old "VOS ARGUMENTS DÉBLOQUÉS"
    new "YOUR UNLOCKED ARGUMENTS"
    old "INFO  Chaque thème influence les réactions des représentants. Choisissez judicieusement."
    new "INFO  Each topic influences the representatives' reactions. Choose wisely."
    old "CONFIRMER LE THÈME"
    new "CONFIRM TOPIC"
    old "CONTINUER SANS THÈME"
    new "CONTINUE WITHOUT A TOPIC"

    old "ARCHIVE // ANALYSE DE TEXTE"
    new "ARCHIVE // TEXT ANALYSIS"
    old "Alors, médiateur..."
    new "Well, mediator..."
    old "OBJECTIF"
    new "OBJECTIVE"
    old "Glissez-déposez les mots pour reconstituer la phrase exacte du texte officiel."
    new "Drag and drop the words to reconstruct the exact sentence from the official text."
    old "Chaque placement compte : une proposition propre donne un meilleur résultat."
    new "Every placement counts: a clean proposal earns a better result."
    old "TEMPS\nRESTANT"
    new "TIME\nLEFT"
    old "[fa_filled_count]/[fa_total_slots] mots placés"
    new "[fa_filled_count]/[fa_total_slots] words placed"
    old "— PROGRESSION"
    new "— PROGRESS"
    old "Autoriser"
    new "Allow"
    old "vente"
    new "sale"
    old "le"
    new "the"

    old "OBJECTION\nPROTOCOL"
    new "OBJECTION\nPROTOCOL"
    old "LIGNE [_dp2_current_line]/[_dp2_total_lines]"
    new "LINE [_dp2_current_line]/[_dp2_total_lines]"
    old "PRISES DE PAROLE [debat_phase2_good]"
    new "INTERVENTIONS [debat_phase2_good]"
    old "VOTRE TOUR"
    new "YOUR TURN"
    old "Cliquez sur le buzzer seulement quand une intervention apporte vraiment quelque chose."
    new "Press the buzzer only when an intervention truly adds something."
    old "ATTENTION"
    new "WARNING"
    old "Vous ne pouvez parler\nqu’après avoir appuyé\nsur le buzzer."
    new "You may speak only\nafter pressing\nthe buzzer."
    old "À TORT [debat_phase2_wrong]"
    new "WRONG [debat_phase2_wrong]"
    old "MANQUÉES [debat_phase2_missed]"
    new "MISSED [debat_phase2_missed]"
    old "OBJECTION !"
    new "OBJECTION!"
    old "OBJECTION REJETÉE"
    new "OBJECTION REJECTED"
    old "Cet argument tenait debout. L'assemblée murmure..."
    new "That argument held up. The assembly murmurs..."
    old "Noam a perdu toute credibilite devant le Conclave."
    new "Noam has lost all credibility before the Conclave."
    old "Cliquez pour reprendre juste avant le Protocole d'Objection."
    new "Click to resume just before the Objection Protocol."

    old "RÉPÉTITIONS"
    new "REPETITIONS"
    old "ÉNERGIE // CHARGE MUSCULAIRE"
    new "ENERGY // MUSCLE LOAD"
    old "RYTHME // FENÊTRE D'EFFORT"
    new "RHYTHM // EFFORT WINDOW"
    old "TEMPS // CHRONO"
    new "TIME // TIMER"
    old "⬆ ⬇  Clic, ↑ ou ↓ pour pousser."
    new "⬆ ⬇  Click, ↑ or ↓ to push."
    old "POUSSER"
    new "PUSH"
    old "STAT EN HAUSSE"
    new "STAT INCREASED"
    old "Physique +1"
    new "Physical +1"
    old "PARFAIT !"
    new "PERFECT!"

    old "KAMI.CORE // EXECUTION PROTOCOL"
    new "KAMI.CORE // EXECUTION PROTOCOL"
    old "TUTORIEL — [title]"
    new "TUTORIAL — [title]"
    old "KAMI.CORE // RETRY PENALTY"
    new "KAMI.CORE // RETRY PENALTY"
    old "KAMI.CORE // PERFORMANCE VERDICT"
    new "KAMI.CORE // PERFORMANCE VERDICT"
    old "★ NOUVEAU RECORD"
    new "★ NEW RECORD"
    old "Record : [best_rank]"
    new "Record: [best_rank]"
    old "[retries] retry — rang plafonné"
    new "[retries] retry — rank capped"
    old "DÉFIS  [mk_challenge_count_done(challenges)] / [len(challenges)]"
    new "CHALLENGES  [mk_challenge_count_done(challenges)] / [len(challenges)]"
    old "CONTINUER"
    new "CONTINUE"
    old "MAINTENIR PUIS GLISSER"
    new "HOLD, THEN DRAG"
    old "NOAM — PENSÉE"
    new "NOAM — THOUGHT"
    old "CLIQUER POUR CONTINUER"
    new "CLICK TO CONTINUE"

    old "01  ÉCOUTE"
    new "01  LISTEN"
    old "02  ARME"
    new "02  ARM"
    old "03  CONTREDIS"
    new "03  COUNTER"
    old "Une erreur ne bloque pas la scène : Julian poursuit simplement son argumentaire."
    new "A mistake does not stop the scene: Julian simply continues his argument."
    old "ARGUMENT // JULIAN"
    new "ARGUMENT // JULIAN"
    old "DÉCLARATION [line_index + 1] / [total_lines]"
    new "STATEMENT [line_index + 1] / [total_lines]"
    old "LECTURE [pass_index + 1]"
    new "PASS [pass_index + 1]"
    old "PREMIÈRE LECTURE : observe l'argumentaire complet. Les répliques seront disponibles au prochain passage."
    new "FIRST PASS: observe the full argument. Responses will become available on the next pass."
    old "CONTRADICTION TROUVÉE — écoute de la fin de l'argumentaire"
    new "CONTRADICTION FOUND — listen to the end of the argument"
    old "SÉLECTION : [DAY3_JULIAN_CLASH_BULLETS[day3_julian_clash_selected]['text']]"
    new "SELECTION: [DAY3_JULIAN_CLASH_BULLETS[day3_julian_clash_selected]['text']]"
    old "ACCÉLÉRER  >>"
    new "SPEED UP  >>"
    old "RETOUR AU SEGMENT 01"
    new "RETURN TO SEGMENT 01"
    old "Les répliques sont maintenant disponibles."
    new "Responses are now available."
    old "CONTRADICTION"
    new "CONTRADICTION"
    old "RÉPLIQUE ÉCARTÉE"
    new "RESPONSE DISCARDED"
    old "Julian enchaîne sans te laisser reprendre l'avantage."
    new "Julian continues before you can regain the advantage."
    old "Tu as isolé le faux mandat derrière le discours de Julian."
    new "You exposed the false mandate behind Julian's speech."

    old "NOUVEL ARGUMENT"
    new "NEW ARGUMENT"
    old "PROFIL — STATISTIQUES"
    new "PROFILE — STATS"
    old "COMPÉTENCES PERMANENTES"
    new "PERMANENT SKILLS"
    old "◂  RETOUR"
    new "◂  BACK"
    old "Niveau [get_stat(name)]   •   Difficulté [dc]"
    new "Level [get_stat(name)]   •   Difficulty [dc]"
    old "LANCER LE DÉ"
    new "ROLL THE DIE"
    old "Zones visitées : [len(exploration_libre_seen_rooms)]/[exploration_libre_required_visits]"
    new "Visited areas: [len(exploration_libre_seen_rooms)]/[exploration_libre_required_visits]"
    old "Rejoindre la cafétéria"
    new "Go to the cafeteria"
    old "Rejoindre la salle d'observation"
    new "Go to the observation room"
    old "URN"
    new "BALLOT BOX"
    old "« Abolir la distribution risque de"
    new "“Abolishing distribution could"
    old "condamner les plus fragiles. »"
    new "condemn the most vulnerable.”"
    old "Sport"
    new "Sports"
    old "PACKS"
    new "PACKS"
    old "SUCCÈS  [progress_successes_done] / [progress_successes_total]"
    new "ACHIEVEMENTS  [progress_successes_done] / [progress_successes_total]"
    old "TEST — [STATS_META[name]['label']]"
    new "CHECK — [STATS_META[name]['label']]"
    old "PACK [pack['num']] - [pack['title']]"
    new "PACK [pack['num']] - [pack['title']]"

    # Dynamic vote and mini-game data rendered through kd_tr().
    old "POUR"
    new "FOR"
    old "INCONNU"
    new "UNKNOWN"
    old "CONTRE"
    new "AGAINST"
    old "Inégalités entre les districts"
    new "Inequality between districts"
    old "Risque économique"
    new "Economic risk"
    old "Les districts n'affrontent ni les mêmes pénuries ni les mêmes chances d'accéder aux biens."
    new "Districts face neither the same shortages nor the same chances of accessing goods."
    old "Entendu lors d'un échange avec Lysa et Elias."
    new "Heard during a conversation with Lysa and Elias."
    old "Bons de rationnement"
    new "Ration vouchers"
    old "Organisation quotidienne"
    new "Daily organization"
    old "Les demandes officielles et les bons structurent déjà l'accès aux biens essentiels."
    new "Official requests and vouchers already govern access to essential goods."
    old "Relevé dans la discussion avec Kael."
    new "Noted during the discussion with Kael."
    old "Risque de dépressurisation"
    new "Depressurization risk"
    old "Sécurité"
    new "Safety"
    old "Sur Orbite, une sanction qui perce une coque peut condamner tout un module."
    new "On Orbite, a penalty that breaches a hull can doom an entire module."
    old "Décrit par Kael en salle d'observation."
    new "Described by Kael in the observation room."
    old "Dérogations trop complexes"
    new "Overly complex exemptions"
    old "Accès administratif"
    new "Administrative access"
    old "Obtenir une nourriture originale ou un objet utile exige une dérogation disproportionnée."
    new "Obtaining unusual food or a useful item requires a disproportionate exemption."
    old "Découvert en parlant avec Elen à la cafétéria."
    new "Discovered while speaking with Elen in the cafeteria."
    old "Valeur du travail"
    new "Value of work"
    old "Organisation collective"
    new "Collective organization"
    old "L'entraide protège chacun, mais elle repose sur la contribution de tous ceux qui peuvent travailler."
    new "Mutual aid protects everyone, but relies on contributions from all who can work."
    old "Expliqué par Sael à partir de la vie de son village."
    new "Explained by Sael through life in her village."
    old "Le monde d'avant"
    new "The old world"
    old "Mémoire politique"
    new "Political memory"
    old "Julian présente l'avant-Kami comme une preuve que la circulation libre peut exister."
    new "Julian presents the pre-Kami world as proof that free movement can exist."
    old "Entendu auprès de Julian avant la cafétéria."
    new "Heard from Julian before the cafeteria."
    old "L'énoncé précis"
    new "The exact wording"
    old "Texte du vote"
    new "Vote text"
    old "La formulation exacte devient décisive : elle engage plus qu'une simple autorisation d'échange."
    new "The exact wording is decisive: it commits to more than merely allowing trade."
    old "Déduit pendant la discussion à la cafétéria."
    new "Inferred during the cafeteria discussion."
    old "Échanges discrets déjà actifs"
    new "Covert exchanges already active"
    old "Réseaux informels"
    new "Informal networks"
    old "Des échanges informels existent déjà. Les nier ne les fait pas disparaître."
    new "Informal exchanges already exist. Denying them will not make them disappear."
    old "Observé dans la salle de stockage."
    new "Observed in the storage room."
    old "Choisissez un argument pour orienter le débat."
    new "Choose an argument to steer the debate."
    old "Sécurité minimale contre la faim et le chaos."
    new "Minimum protection from hunger and chaos."
    old "Dépendance logistique et fragilité structurelle."
    new "Logistical dependence and structural fragility."
    old "Texte exact, conséquences juridiques immédiates."
    new "Exact text, immediate legal consequences."
    old "Ruptures passées et files de pénurie."
    new "Past disruptions and shortage lines."
    old "Réseaux d'entraide clandestins déjà en place."
    new "Underground mutual-aid networks already in place."
    old "Mémoire d'un système ancien imparfait mais vivant."
    new "Memory of an old, imperfect but living system."

    old "transport,"
    new "transport,"
    old "la"
    new "the"
    old "et"
    new "and"
    old "l’échange"
    new "exchange"
    old "de"
    new "of"
    old "marchandises."
    new "goods."
    old "Le"
    new "The"
    old "système"
    new "system"
    old "actuel"
    new "current"
    old "distribution"
    new "distribution"
    old "denrées"
    new "food"
    old "est"
    new "is"
    old "aboli."
    new "abolished."

    old "ENTRAÎNEMENT AUX HALTÈRES"
    new "DUMBBELL TRAINING"
    old "Synchronise ton effort avec la zone verte pour valider chaque répétition."
    new "Synchronize your effort with the green zone to complete each repetition."
    old "Correct."
    new "Good."
    old "Raté..."
    new "Missed..."
    old "Combo x5"
    new "Combo x5"
    old "Zéro raté"
    new "No misses"
    old "4 frappes parfaites"
    new "4 perfect hits"

    old "LA LIMITE DE TOMAS"
    new "TOMAS'S LIMIT"
    old "Tomas vient de te demander d'arrêter."
    new "Tomas just asked you to stop."
    old "AUCUN MANDAT"
    new "NO MANDATE"
    old "Personne ne t'a choisi pour les représenter."
    new "No one chose you to represent them."
    old "LE FOND DU TEXTE"
    new "THE SUBSTANCE OF THE TEXT"
    old "Parler plus fort ne rend pas le texte meilleur."
    new "Speaking louder does not make the text better."
    old "Je veux seulement que ce texte passe."
    new "I only want this text to pass."
    old "On devrait tous viser la même chose."
    new "We should all be aiming for the same thing."
    old "Je ne force personne."
    new "I am not forcing anyone."
    old "Je leur donne seulement un cap."
    new "I am only giving them a direction."
    old "Ils restent libres de me suivre."
    new "They remain free to follow me."
    old "Quelqu'un doit transformer cette hésitation"
    new "Someone has to turn this hesitation"
    old "en mouvement. J'assume de le faire."
    new "into action. I am willing to do it."
    old "Tomas hésite, c'est tout."
    new "Tomas is hesitating, that is all."
    old "Au fond, il attend que je le guide."
    new "Deep down, he is waiting for me to guide him."
    old "Je lui évite de rester seul avec son choix."
    new "I am sparing him from facing his choice alone."
    old "Si je parle en premier au Conclave,"
    new "If I speak first at the Conclave,"
    old "les autres sauront enfin où regarder."
    new "the others will finally know where to look."
    old "Ce n'est pas une question d'ego."
    new "This is not about ego."
    old "Les indécis m'ont choisi pour les représenter."
    new "The undecided chose me to represent them."
    old "Je ne fais que prendre mes responsabilités."
    new "I am simply taking responsibility."
    old "Vous pouvez trouver ma méthode agaçante."
    new "You may find my method annoying."
    old "Elle reste plus utile que votre silence."
    new "It is still more useful than your silence."
    old "Quand le vote passera, personne ne reprochera"
    new "When the vote passes, no one will blame"
    old "à Julian d'avoir pris les devants."
    new "Julian for taking the lead."

    old "Représentante n°03 — Velkyn"
    new "Representative No. 03 — Velkyn"
    old "Représentant n°04 — Solen"
    new "Representative No. 04 — Solen"
    old "Représentante n°05 — Orée"
    new "Representative No. 05 — Orée"
    old "Représentant n°06 — Miren"
    new "Representative No. 06 — Miren"
    old "Représentante n°08 — Civitas"
    new "Representative No. 08 — Civitas"
    old "Représentant n°09 — Archive"
    new "Representative No. 09 — Archive"
    old "Représentante n°10 — Aster"
    new "Representative No. 10 — Aster"
    old "Représentant n°11 — Forge"
    new "Representative No. 11 — Forge"
    old "Représentante n°02 — Apex"
    new "Representative No. 02 — Apex"
    old "Représentant n°07 — Limen"
    new "Representative No. 07 — Limen"
    old "Représentante n°12 — Serment"
    new "Representative No. 12 — Serment"
    old "Médiateur — District Harmonie"
    new "Mediator — Harmonie District"
    old "Ah, je dois commencer ?? Euh..."
    new "Oh, I have to start? Uh..."
    old "Abolir la distribution risque de"
    new "Abolishing distribution could"
    old "condamner les plus fragiles."
    new "condemn the most vulnerable."
    old "Le marché libre va"
    new "The free market will"
    old "récompenser ceux"
    new "reward those"
    old "qui se bougent vraiment."
    new "who truly make an effort."
    old "Ceux qui se bougent, oui."
    new "Those who make an effort, yes."
    old "Mais ceux qui échouent"
    new "But those who fail,"
    old "on les verra aussi."
    new "we will see them too."
    old "L’échec existe déjà."
    new "Failure already exists."
    old "Au moins là,"
    new "At least then,"
    old "il aura un sens."
    new "it will mean something."
    old "J’aime pas vraiment ça."
    new "I don't really like this."
    old "Mais rester figés,"
    new "But staying frozen,"
    old "j’aime encore moins."
    new "I like even less."
    old "Statistiquement…"
    new "Statistically..."
    old "ne rien changer"
    new "changing nothing"
    old "c’est déjà tout perdre."
    new "already means losing everything."
    old "Alors essayons !"
    new "Then let's try!"
    old "Moi, j’ai envie de voir"
    new "I want to see"
    old "ce que ça peut donner."
    new "what might happen."
    old "Un test mal cadré peut"
    new "A poorly framed test can"
    old "coûter plus cher que"
    new "cost more than"
    old "ce qu'on connait déjà."
    new "what we already know."
    old "Alors cadrons-le."
    new "Then let us frame it properly."
    old "Mais ne faisons pas"
    new "But let us not"
    old "semblant d’ignorer le reste."
    new "pretend to ignore the rest."
    old "Le reste ?!"
    new "The rest?!"
    old "Le reste, c’est des vies !"
    new "The rest is people's lives!"
    old "Pas un foutu paramètre !"
    new "Not some damn parameter!"
    old "Si on veut protéger des vies,"
    new "If we want to protect lives,"
    old "il faut tout changer."
    new "we have to change everything."
    old "Ca commence par ça."
    new "It starts with this."
    old "On doit bouger, oui."
    new "We must move forward, yes."
    old "Mais étape par étape."
    new "But one step at a time."
    old "Doucement."
    new "Slowly."
    old "Je vous l’avais dit."
    new "I told you."
    old "On finit toujours"
    new "Everyone always ends up"
    old "par me rejoindre."
    new "coming around to my side."
    old "Ton besoin d’avoir raison"
    new "Your need to be right"
    old "n’a rien à voir avec"
    new "has nothing to do with"
    old "notre discussion."
    new "our discussion."
    old "Je crois bien que"
    new "I think"
    old "nous sommes d’accord."
    new "we agree."
    old "Il faut du changement."
    new "We need change."
    old "Kami : Deux minutes. Vous êtes déjà en retard sur mes calculs."
    new "Kami: Two minutes. You are already behind my projections."
    old "Kami : 120 secondes, et toujours ce chaos. Charmant."
    new "Kami: 120 seconds, and still this chaos. Charming."
    old "Kami : Vous sentez la pression ? Moi, j'appelle ça une statistique."
    new "Kami: Feeling the pressure? I call it a statistic."
    old "Kami : Une minute. J'espère que vous aimez finir dans la panique."
    new "Kami: One minute. I hope you enjoy finishing in a panic."
    old "Kami : 60 secondes. Je lance déjà les paris sur votre échec."
    new "Kami: 60 seconds. I am already taking bets on your failure."
    old "Kami : Tic tac. C'est là que les erreurs deviennent irréversibles."
    new "Kami: Tick-tock. This is where mistakes become irreversible."
    old "Kami : 30 secondes. Même mes protocoles ont plus de sang-froid."
    new "Kami: 30 seconds. Even my protocols are calmer than you."
    old "Kami : Trente secondes. Vous devriez déjà avoir terminé."
    new "Kami: Thirty seconds. You should be done by now."
    old "Kami : Plus que 30 secondes. Essayez de ne pas tout saboter."
    new "Kami: Only 30 seconds left. Try not to sabotage everything."
    old "Kami : 10 secondes. Oui, c'est exactement aussi catastrophique que prévu."
    new "Kami: 10 seconds. Yes, this is exactly as catastrophic as predicted."
    old "Kami : Dix secondes. Respirez... enfin non, perdez plutôt du temps."
    new "Kami: Ten seconds. Breathe... actually, keep wasting time."
    old "Kami : 10 secondes. Le stress vous va si bien."
    new "Kami: 10 seconds. Stress suits you so well."
    old "— CONCLAVE —"
    new "— CONCLAVE —"
    old "Day [day_label]"
    new "Day [day_label]"
    old "Temps libre"
    new "Free time"
    old "DIFFUSION"
    new "BROADCAST"
    old "DOSSIER DE VOTE"
    new "VOTE FILE"
    old "CHAPITRES"
    new "CHAPTERS"
    old "COMPLÉTION DU CHAPITRE"
    new "CHAPTER COMPLETION"
    old "ARGUMENTS  [arguments_done] / [arguments_total]"
    new "ARGUMENTS  [arguments_done] / [arguments_total]"
    old "SUCCÈS  [successes_done] / [successes_total]"
    new "ACHIEVEMENTS  [successes_done] / [successes_total]"
    old "Le pourcentage réunit les arguments découverts\net les succès liés à ce chapitre."
    new "The percentage combines discovered arguments\nand achievements linked to this chapter."
    old "SA FORMULATION"
    new "WORDING"
    old "ARGUMENTS DÉBLOQUÉS"
    new "UNLOCKED ARGUMENTS"
    old "[dossier_prop_unlocked_count(sel_prop)] / [dossier_prop_total(sel_prop)] DÉBLOQUÉS"
    new "[dossier_prop_unlocked_count(sel_prop)] / [dossier_prop_total(sel_prop)] UNLOCKED"
    old "ⓘ  Les arguments recueillis vous aideront à préparer vos positions et anticiper les votes."
    new "ⓘ  Collected arguments help you prepare your positions and anticipate votes."
    old "Obtenu auprès de :"
    new "Obtained from:"
    old "Argument non débloqué"
    new "Locked argument"
    old "Continuez vos discussions, explorez les lieux et observez les autres représentants pour débloquer cet argument."
    new "Keep talking, explore the area, and observe the other representatives to unlock this argument."
    old "VOTE EN COURS"
    new "VOTE IN PROGRESS"
    old "CHOISISSEZ L’ISSUE DU VOTE"
    new "CHOOSE THE VOTE OUTCOME"
    old "DÉPOUILLEMENT DES VOTES"
    new "VOTE COUNT"
    old "Les votes sont secrets - les résultats seuls comptent."
    new "Votes are secret — only the results matter."
    old "AMENDEMENT N°1"
    new "AMENDMENT NO. 1"
    old "COMPTAGE DES VOTES"
    new "COUNTING VOTES"
    old "Bulletin [vote_phase3_tally_index] / [total_votes]"
    new "Ballot [vote_phase3_tally_index] / [total_votes]"
    old "BULLETIN DÉPOUILLÉ"
    new "BALLOT COUNTED"
    old "RÈGLE D’UNANIMITÉ"
    new "UNANIMITY RULE"
    old "Si une seule personne vote contre, l’amendement est immédiatement refusé. L’abstention ne bloque pas l’adoption."
    new "If even one person votes against, the amendment is immediately rejected. Abstention does not block adoption."
    old "Voix"
    new "Votes"
    old "FINAL_REPRESENTATIVES = (\"NOAM\", \"LYSA\")\n\nfunction generate_displayed_names:\n    decoys = shuffle(HARMONIE.citizens)\n    return animate(decoys)\n\nfunction accept_player_input(click):\n    stop_animation()\n    reveal(FINAL_REPRESENTATIVES)\n\n// La liste déroulante n'est qu'une façade.\n// Sélection terminée avant le début de la séance."
    new "FINAL_REPRESENTATIVES = (\"NOAM\", \"LYSA\")\n\nfunction generate_displayed_names:\n    decoys = shuffle(HARMONIE.citizens)\n    return animate(decoys)\n\nfunction accept_player_input(click):\n    stop_animation()\n    reveal(FINAL_REPRESENTATIVES)\n\n// The scrolling list is only a facade.\n// Selection completed before the session began."
    old "DAY"
    new "DAY"
    old "PHASE"
    new "PHASE"
    old "BUZZ"
    new "BUZZ"
    old "GAME OVER"
    new "GAME OVER"
    old "GO"
    new "GO"
    old "COMBO x[mg_combo]"
    new "COMBO x[mg_combo]"
    old "SCORE  [score] / [max_score]"
    new "SCORE  [score] / [max_score]"
    old "CODEX"
    new "CODEX"
    old "ARGUMENTS  [progress_arguments_done] / [progress_arguments_total]"
    new "ARGUMENTS  [progress_arguments_done] / [progress_arguments_total]"
    old "PHASE 3/3"
    new "PHASE 3/3"
