translate english strings:

    # Draft amendment mini-game (Python-driven strings).
    old "Toute personne"
    new "Everyone"
    old "doit"
    new "must"
    old "intervenir"
    new "intervene"
    old "lorsqu'une autre personne"
    new "when another person"
    old "est en danger."
    new "is in danger."
    old "immédiatement"
    new "immediately"
    old "peut"
    new "may"
    old "s'il l'ose"
    new "if they dare"
    old "porter assistance"
    new "provide assistance"
    old "après autorisation"
    new "after authorization"
    old "si nécessaire"
    new "if necessary"
    old "à une autre personne"
    new "to another person"
    old "quand c'est permis"
    new "when permitted"
    old "peut-être"
    new "perhaps"
    old "en danger"
    new "in danger"
    old "sans autorisation préalable."
    new "without prior authorization."
    old "dans la limite"
    new "within the limit"
    old "sauf refus"
    new "unless refused"
    old "si toléré"
    new "if tolerated"

    old "« Toute personne doit intervenir lorsqu'une autre personne est en danger. »"
    new "‘Everyone must intervene when another person is in danger.’"
    old "Doit. Une obligation. Je force la main de tout le monde, d'un seul mot."
    new "Must. An obligation. With one word, I force everyone's hand."
    old "Et si quelqu'un intervient mal ? Si à cause de « doit », on condamne celui qui a hésité ?"
    new "What if someone intervenes badly? What if ‘must’ condemns the person who hesitated?"
    old "Non. « Doit », c'est trop. Ça punit autant que ça protège."
    new "No. ‘Must’ is too much. It punishes as much as it protects."
    old "Le mot part. La trace, elle, reste."
    new "The word is gone. Its mark remains."
    old "« Immédiatement »... et si c'est trop tard pour bien faire ? Je le retire."
    new "‘Immediately’... what if it is too late to do the right thing? I remove it."
    old "« ...peut intervenir... »"
    new "‘...may intervene...’"
    old "Intervenir. Ça sonne comme se jeter dans le feu. Comme un héros."
    new "Intervene. It sounds like throwing yourself into the fire. Like a hero."
    old "Personne n'est un héros, ici. On lira ça comme le droit de tout casser au nom du secours."
    new "No one here is a hero. They will read this as permission to break everything in the name of rescue."
    old "Encore un mot rayé. La phrase respire un peu moins fort."
    new "Another word crossed out. The sentence breathes a little less loudly."
    old "« S'il l'ose »... je ne vais pas leur demander du courage en plus. Non."
    new "‘If they dare’... I am not going to demand courage from them too. No."
    old "« ...peut porter assistance lorsqu'une autre personne est en danger. »"
    new "‘...may provide assistance when another person is in danger.’"
    old "« Lorsque ». Comme s'il fallait attendre le bon moment. Attendre l'autorisation du danger lui-même."
    new "‘When.’ As if we had to wait for the right moment. Wait for danger itself to give permission."
    old "J'ajoute « après autorisation », machinalement. Ma main écrit ce que la peur dicte."
    new "I mechanically add ‘after authorization.’ My hand writes what fear dictates."
    old "...Non. Si on attend l'autorisation, la personne est déjà par terre. Je barre ça aussi."
    new "...No. If we wait for authorization, the person is already on the ground. I cross that out too."
    old "Trop de conditions. Chaque condition est une porte pour dire non."
    new "Too many conditions. Every condition is a door through which to say no."
    old "Je gomme la condition. Mes doigts sont gris."
    new "I erase the condition. My fingers are gray."
    old "« Après autorisation ». Voilà. C'est exactement le mot qui tue les gens poliment. Dehors."
    new "‘After authorization.’ There. Those are exactly the words that kill people politely. Out."
    old "« Si nécessaire », qui décide de ça ? Pas moi. Je l'écarte."
    new "‘If necessary’—who decides that? Not me. I discard it."
    old "« ...porter assistance à une autre personne est en danger. »"
    new "‘...provide assistance to another person is in danger.’"
    old "Ça se lit de travers, maintenant. Tant pis, personne ne relira ma calligraphie."
    new "It reads wrong now. Too bad; no one will reread my handwriting."
    old "« Est en danger. » Lourd. Je veux juste : en danger. Court. Qu'on ne puisse pas l'esquiver."
    new "‘Is in danger.’ Clumsy. I only want: in danger. Short. Something no one can evade."
    old "La feuille est presque illisible. Moi aussi."
    new "The page is almost illegible. So am I."
    old "« Quand c'est permis »... et si ça ne l'est jamais ? Je raye."
    new "‘When permitted’... what if it never is? I cross it out."
    old "« Peut-être ». Le mot le plus lâche que je connaisse. Dehors."
    new "‘Perhaps.’ The most cowardly word I know. Out."
    old "« Toute personne peut porter assistance à une autre personne en danger sans autorisation préalable. »"
    new "‘Everyone may provide assistance to another person in danger without prior authorization.’"
    old "Voilà. C'est laid. C'est raturé. Mais ça tient debout."
    new "There. It is ugly. Covered in crossings-out. But it holds together."
    old "« Dans la limite »... la limite de quoi ? Non."
    new "‘Within the limit’... the limit of what? No."
    old "« Sauf refus ». Toujours une porte de sortie. Je n'en veux plus."
    new "‘Unless refused.’ Always a way out. I do not want one anymore."
    old "« Si toléré ». Non. Plus de permission à mendier."
    new "‘If tolerated.’ No. No more permission to beg for."
    old "Alors. Ma phrase. Une seule ligne, et qu'on n'en parle plus."
    new "Right. My sentence. One line, and then we never speak of it again."
    old "Les mots sont là, éparpillés autour. Fais-les glisser sur la feuille pour former une phrase."
    new "The words are scattered around. Drag them onto the page to form a sentence."
    old "Déjà ? Mes mains vont plus lentement que cette horloge."
    new "Already? My hands move more slowly than that clock."
    old "Ma main cherche la gomme toute seule. Attrape-la, frotte le mot cerclé jusqu'à ce qu'il disparaisse."
    new "My hand reaches for the eraser on its own. Grab it and rub the circled word until it disappears."
    old "Je pourrais encore. Enlever « sans autorisation ». Trouver plus doux, plus prudent."
    new "I still could. Remove ‘without authorization.’ Find something softer, more cautious."
    old "Continuer jusqu'à ce que la phrase ne veuille plus rien dire. Jusqu'à ce qu'elle ne gêne plus personne."
    new "Keep going until the sentence means nothing. Until it bothers no one."
    old "La gomme est déjà dans ma main."
    new "The eraser is already in my hand."
    old "Non."
    new "No."
    old "Je pose la gomme."
    new "I put down the eraser."
    old "Pour une fois, je n'efface pas."
    new "For once, I do not erase it."
    old "Je repose la gomme sans m'en servir."
    new "I put the eraser down without using it."
    old "Je plie la feuille en deux. De travers, évidemment."
    new "I fold the page in half. Crooked, of course."

    # Objection Protocol tutorial.
    old "Ecoute chaque argument"
    new "Listen to every argument"
    old "Chaque participant parle quelques secondes. La barre jaune indique le temps disponible."
    new "Each participant speaks for a few seconds. The yellow bar shows the time remaining."
    old "Interviens avec discernement"
    new "Intervene wisely"
    old "Le buzzer sert a prendre la parole quand Noam apporte un vrai eclairage, pas a contredire tout le monde."
    new "Use the buzzer when Noam can add real insight, not to contradict everyone."
    old "Reste coherent"
    new "Stay consistent"
    old "Multiplier les objections affaiblit Noam : l'assemblee juge aussi la coherence de tes interventions."
    new "Too many objections weaken Noam: the assembly also judges the consistency of your interventions."

    # Final vote cards and dynamic tally labels.
    old "VOTE POUR"
    new "VOTE FOR"
    old "ABSTENTION"
    new "ABSTAIN"
    old "VOTE CONTRE"
    new "VOTE AGAINST"
    old "Changer les règles"
    new "Change the rules"
    old "Laisser le système trancher"
    new "Let the system decide"
    old "Maintenir le cadre"
    new "Keep the current framework"
    old "En attente du premier bulletin..."
    new "Waiting for the first ballot..."
    old "Dépouillement en cours..."
    new "Counting votes..."
    old "Amendement refusé : au moins un vote contre."
    new "Amendment rejected: at least one vote against."
    old "Amendement adopté : aucun vote contre."
    new "Amendment adopted: no votes against."
