translate english strings:

    old "Couloir de la cafétéria"
    new "Cafeteria corridor"
    old "Couloir du dortoir"
    new "Dormitory corridor"
    old "Couloir de l'infirmerie"
    new "Infirmary corridor"
    old "Couloir de maintenance"
    new "Maintenance corridor"
    old "Couloir du SAS"
    new "Airlock corridor"
    old "Exploration libre"
    new "Free exploration"
    old "Accès indisponible"
    new "Access unavailable"
    old "Parler à Elen"
    new "Talk to Elen"
    old "Parler à Tomas"
    new "Talk to Tomas"
    old "Parler à Julian"
    new "Talk to Julian"
    old "Parler à Mara et Sael"
    new "Talk to Mara and Sael"
    old "Parler à Lysa et Elias"
    new "Talk to Lysa and Elias"
    old "Parler à Sael"
    new "Talk to Sael"
    old "Règlement du Conclave"
    new "Conclave Rules"
    old "Représentant — Conclave"
    new "Representative — Conclave"
    old "Entrer dans la cafétéria"
    new "Enter the cafeteria"
    old "Entrer dans la salle du canon"
    new "Enter the cannon room"
    old "Entrer dans l'observatoire"
    new "Enter the observatory"
    old "Entrer dans la salle de repos"
    new "Enter the lounge"
    old "Aller vers le dortoir"
    new "Go to the dormitory"
    old "Aller vers la maintenance"
    new "Go to maintenance"
    old "Entrer dans la salle d'archive"
    new "Enter the archive room"
    old "Entrer dans le Conclave"
    new "Enter the Conclave"
    old "Entrer dans le dortoir"
    new "Enter the dormitory"
    old "Aller vers la cafétéria"
    new "Go to the cafeteria"
    old "Aller vers l'infirmerie"
    new "Go to the infirmary"
    old "Entrer dans le gymnase"
    new "Enter the gym"
    old "Entrer dans l'infirmerie"
    new "Enter the infirmary"
    old "Aller vers le SAS"
    new "Go to the airlock"
    old "Entrer dans la maintenance"
    new "Enter maintenance"
    old "Entrer dans le SAS de livraison"
    new "Enter the delivery airlock"
    old "Entrer dans la salle de stockage"
    new "Enter the storage room"
