translate english strings:

    old "TUTORIEL"
    new "TUTORIAL"
    old "{} ANS"
    new "{} YEARS"
    old "%d / 5 tris"
    new "%d / 5 sorts"
    old "Le pain va tomber de mon côté."
    new "The bread is about to fall on my side."
    old "Quelqu'un peut me passer l'eau avant que Julian négocie avec elle ?"
    new "Can someone pass me the water before Julian starts negotiating with it?"
    old "La ration chaude, avant qu'elle devienne un concept."
    new "The hot ration, before it becomes a concept."
    old "Laisse une part au centre. On va éviter le drame diplomatique."
    new "Leave a portion in the center. Let's avoid a diplomatic incident."
    old "Iris lève son verre comme si elle venait de fonder un pays."
    new "Iris raises her glass as if she had just founded a country."
    old "Le nom de Kami aspire l'air autour de la table."
    new "Kami's name sucks the air out of the table."
    old "Julian prend l'attaque comme une promotion."
    new "Julian takes the jab as a promotion."
    old "La prudence est juste. Elle est aussi lourde."
    new "Caution is justified. It is also heavy."
    old "Les verres se lèvent. Le silence devient presque une présence invitée."
    new "Glasses rise. Silence almost becomes an invited guest."
    old "Julian proteste trop vite pour être crédible."
    new "Julian protests too quickly to be convincing."
    old "La règle est simple. Tout le monde l'accepte."
    new "The rule is simple. Everyone accepts it."
    old "Lysa te regarde, puis accepte cette petite désobéissance."
    new "Lysa looks at you, then accepts this small act of disobedience."
    old "La table retombe dans le réel."
    new "The table drops back into reality."
    old "Mauvaise image. Les épaules se tendent."
    new "Bad image. Shoulders tense."
    old "Julian mime une blessure politique grave."
    new "Julian acts out a grave political injury."
    old "Il se redresse comme si c'était sérieux. C'est ce qui sauve la blague."
    new "He sits up as if it were serious. That's what saves the joke."
    old "Le repas continue. Sans éclat, mais sans casse."
    new "The meal continues. Nothing special, but nothing breaks."
    old "La formule lui arrache presque un sourire."
    new "The phrase almost draws a smile from her."
    old "Elle te laisse faire. C'est déjà un accord."
    new "She lets you do it. That's already an agreement."
    old "Elle se ferme aussitôt. Mauvais angle."
    new "She shuts down immediately. Wrong angle."
    old "Pendant une minute, personne ne dit son nom."
    new "For one minute, no one says her name."
    old "La table respire encore un peu."
    new "The table breathes a little longer."
    old "La blague tient juste assez longtemps pour devenir utile."
    new "The joke lasts just long enough to become useful."
    old "Le calme reste là, moins brillant, mais intact."
    new "The calm remains, less bright, but intact."
    old "Le calme se fend. Pas beaucoup. Assez."
    new "The calm cracks. Not much. Enough."
    old "NORD"
    new "NORTH"
    old "SUD"
    new "SOUTH"
    old "EST"
    new "EAST"
    old "OUEST"
    new "WEST"
    old "{} // VALEUR {} SÉLECTIONNÉE"
    new "{} // VALUE {} SELECTED"
    old "{} // CALIBRATION REFUSÉE — SIGNAL INSTABLE"
    new "{} // CALIBRATION DENIED — UNSTABLE SIGNAL"
    old "{} // FLUX STABILISÉ"
    new "{} // FLOW STABILIZED"

    # Menus and dynamic title cards added in version 2.2.
    old "SYSTEM"
    new "SYSTEM"
    old "KAMI.CORE  /  INTERFACE LOCALE"
    new "KAMI.CORE  /  LOCAL INTERFACE"
    old "NAVIGATION  ↑ ↓   //   CONFIRMER  ENTRÉE"
    new "NAVIGATION  ↑ ↓   //   CONFIRM  ENTER"
    old "KAMI.CORE // DOSSIERS DES REPRÉSENTANTS"
    new "KAMI.CORE // REPRESENTATIVE FILES"
    old "REPRÉSENTANT·E DE"
    new "REPRESENTATIVE OF"
    old "GARDE-ROBE"
    new "WARDROBE"
    old "Les choix équipés sont sauvegardés de façon permanente et appliqués aux sprites en jeu."
    new "Equipped choices are saved permanently and applied to in-game sprites."
    old "TENUES"
    new "OUTFITS"
    old "VERROUILLÉE — disponible dans la Boutique"
    new "LOCKED — available in the Shop"
    old "ÉQUIPÉE"
    new "EQUIPPED"
    old "ÉQUIPER"
    new "EQUIP"
    old "ACCESSOIRES"
    new "ACCESSORIES"
    old "VERROUILLÉ — disponible dans la Boutique"
    new "LOCKED — available in the Shop"
    old "RETIRER"
    new "REMOVE"
    old "FERMER"
    new "CLOSE"
    old "Médiateur"
    new "Mediator"
    old "Habitante"
    new "Resident"
    old "Habitant"
    new "Resident"
    old "Ouvrier"
    new "Worker"
    old "Archiviste"
    new "Archivist"
    old "Ingénieur"
    new "Engineer"
    old "Gardien"
    new "Guardian"
    old "Harmonie"
    new "Harmony"
    old "Axiome"
    new "Axiom"
    old "Archive"
    new "Archive"
    old "Orbite"
    new "Orbit"
    old "Limen"
    new "Limen"
    old "14 avril"
    new "April 14"
    old "3 septembre"
    new "September 3"
    old "19 janvier"
    new "January 19"
    old "27 juin"
    new "June 27"
    old "8 novembre"
    new "November 8"
    old "22 février"
    new "February 22"
    old "5 octobre"
    new "October 5"
    old "16 mai"
    new "May 16"
    old "30 décembre"
    new "December 30"
    old "11 août"
    new "August 11"
    old "7 mars"
    new "March 7"
    old "24 juillet"
    new "July 24"
    old "Comprendre avant de trancher."
    new "Understand before deciding."
    old "Une promesse sans procédure n'est qu'un bruit."
    new "A promise without a process is only noise."
    old "Tenir, c'est déjà gagner du temps."
    new "Holding on already buys us time."
    old "Un repas stable vaut mieux qu'un grand discours."
    new "A reliable meal beats a grand speech."
    old "Les chiffres mentent moins que nous."
    new "Numbers lie less than we do."
    old "Le silence est aussi un signal."
    new "Silence is a signal too."
    old "Si ce n'est pas consigné, c'est déjà perdu."
    new "If it isn't recorded, it's already lost."
    old "On compte les vivants, pas les slogans."
    new "We count the living, not slogans."
    old "On ne négocie pas avec une turbine en panne."
    new "You don't negotiate with a broken turbine."
    old "Le cadre protège de l'arbitraire."
    new "Rules protect us from arbitrariness."
    old "Le danger n'attend pas les votes."
    new "Danger doesn't wait for votes."
    old "Je vois ce qui entre. Et ce qui disparaît."
    new "I see what comes in. And what disappears."
    old "ÉCLATS DE DÉSIR"
    new "DESIRE SHARDS"
    old "IRIS : TENUE 2"
    new "IRIS: OUTFIT 2"
    old "RYN : TENUE 2"
    new "RYN: OUTFIT 2"
    old "LYSA : ACCESSOIRE 1"
    new "LYSA: ACCESSORY 1"
    old "PRÉVISUALISER"
    new "PREVIEW"
    old "OBTENU"
    new "OWNED"
    old "OBTENIR"
    new "GET"
    old "RÉQUISITIONS DE KAMI"
    new "KAMI'S REQUISITIONS"
    old "OFFRES TEMPORAIRES"
    new "LIMITED-TIME OFFERS"
    old "CODE PROMO"
    new "PROMO CODE"
    old "FIN DANS 06 J 14 H"
    new "ENDS IN 06 D 14 H"
    old "Les réquisitions non obtenues disparaîtront à la fin du cycle."
    new "Unclaimed requisitions will disappear at the end of the cycle."
    old "PRÉVISUALISATION"
    new "PREVIEW"
    old "Corps, bras, bouche et yeux sont tirés au hasard. La tenue ou l'accessoire sélectionné reste fixe."
    new "Body, arms, mouth, and eyes are randomized. The selected outfit or accessory stays fixed."
    old "ALÉATOIRE"
    new "RANDOMIZE"
    old "Saisissez un code pour créditer des récompenses persistantes."
    new "Enter a code to receive permanent rewards."
    old "VALIDER"
    new "CONFIRM"
    old "Réquisition introuvable"
    new "Requisition not found"
    old "Objet déjà obtenu"
    new "Item already owned"
    old "Éclats de désir insuffisants"
    new "Not enough Desire Shards"
    old "Réquisition validée"
    new "Requisition confirmed"
    old "{}{} Éclats de désir"
    new "{}{} Desire Shards"
    old "+{} Éclats de désir"
    new "+{} Desire Shards"
    old "Encore humain"
    new "Still Human"
    old "Un hasard bien cadré"
    new "A Well-Framed Coincidence"

    # Custom and chapter titles.
    old "Je termine de ranger les caisses."
    new "I finish sorting the crates."
    old "Puis je me rends à la cafétéria."
    new "Then I head to the cafeteria."
    old "Le repas se déroule sans accroc pendant de longues minutes."
    new "The meal goes smoothly for several long minutes."
    old "Une bonne heure plus tard"
    new "A good hour later"
    old "Après m'être longuement calmé"
    new "After taking a long time to calm down"
    old "Après plusieurs heures"
    new "Several hours later"
    old "Début du chapitre 2"
    new "Start of Chapter 2"
    old "Fin du chapitre 2"
    new "End of Chapter 2"

    # Day 7 — delivery sorting.
    old "CAFÉTÉRIA"
    new "CAFETERIA"
    old "INFIRMERIE"
    new "INFIRMARY"
    old "STOCKAGE"
    new "STORAGE"
    old "STOCKAGE • BONUS"
    new "STORAGE • BONUS"
    old "ATTRAPEZ"
    new "GRAB"
    old "Cliquez et maintenez un objet qui défile sur le tapis."
    new "Click and hold an item moving along the belt."
    old "TRIEZ"
    new "SORT"
    old "Glissez-le au-dessus de la caisse correspondant à sa catégorie."
    new "Drag it over the crate matching its category."
    old "ACCÉLÉREZ"
    new "SPEED UP"
    old "Cinq tris justes d'affilée accélèrent le tapis et donnent +5."
    new "Five correct sorts in a row speed up the belt and grant +5."
    old "BONUS"
    new "BONUS"
    old "Les objets de stockage sont plus rares et valent 0 point."
    new "Storage items are rarer and worth 0 points."
    old "TRI DES LIVRAISONS"
    new "DELIVERY SORTING"
    old "MINI-JEU  •  TRI DES LIVRAISONS"
    new "MINIGAME  •  DELIVERY SORTING"
    old "ATTRAPEZ • GLISSEZ • DÉPOSEZ AU-DESSUS DE LA BONNE CAISSE"
    new "GRAB • DRAG • DROP OVER THE RIGHT CRATE"
    old "SCORE CALCULÉ"
    new "CALCULATED SCORE"
    old "SÉRIE"
    new "STREAK"
    old "CADENCE"
    new "PACE"
    old "DÉFILEMENT  >>>"
    new "BELT FLOW  >>>"
    old "RÈGLES"
    new "RULES"
    old "• Bonne caisse :  +1 point\n• Mauvaise caisse :  -1 point et cadence -1\n• Stockage correct :  0 point\n• 5 tris justes : cadence +1\n• Score : points × cadence"
    new "• Correct crate:  +1 point\n• Wrong crate:  -1 point and pace -1\n• Correct storage:  0 points\n• 5 correct sorts: pace +1\n• Score: points × pace"
    old "BILAN EN DIRECT"
    new "LIVE REPORT"
    old "Corrects"
    new "Correct"
    old "Erreurs"
    new "Errors"
    old "Bonus neutres"
    new "Neutral bonuses"
    old "Objets passés"
    new "Missed items"
    old "PROCHAINE ACCÉLÉRATION"
    new "NEXT SPEED-UP"
    old "REPRENDRE"
    new "RESUME"
    old "PAUSE"
    new "PAUSE"
    old "TRI EN PAUSE"
    new "SORTING PAUSED"
    old "Le chronomètre et le tapis sont arrêtés."
    new "The timer and belt are stopped."
    old "STOCKAGE BONUS  •  +0"
    new "STORAGE BONUS  •  +0"
    old "TRI CORRECT  •  +1"
    new "CORRECT SORT  •  +1"
    old "ACCÉLÉRATION  •  MULTIPLICATEUR x%.2f"
    new "SPEED-UP  •  MULTIPLIER x%.2f"
    old "ERREUR  •  -1 POINT  •  CADENCE -1"
    new "ERROR  •  -1 POINT  •  PACE -1"
    old "MAUVAISE CAISSE  •  -1 POINT"
    new "WRONG CRATE  •  -1 POINT"
    old "Points bruts"
    new "Raw points"
    old "Multiplicateur final"
    new "Final multiplier"
    old "Score final"
    new "Final score"
    old "Tris corrects"
    new "Correct sorts"
    old "Meilleure série"
    new "Best streak"
    old "Aucune erreur"
    new "No errors"
    old "Atteindre la cadence x1.42"
    new "Reach x1.42 pace"

    # Day 7 — table, discussion, Canon, and cleaning minigames.
    old "PLATEAU EN CIRCULATION"
    new "TRAY IN CIRCULATION"
    old "Le plateau a survécu au repas."
    new "The tray survived the meal."
    old "Pain"
    new "Bread"
    old "Eau"
    new "Water"
    old "Ration"
    new "Ration"
    old "Partage"
    new "Share"
    old "sec"
    new "dry"
    old "stable"
    new "steady"
    old "chaud"
    new "hot"
    old "centre"
    new "center"
    old "ton"
    new "tone"
    old "piste"
    new "lane"
    old "Rythme de table"
    new "Table rhythm"
    old "Ratés [j701_plate_errors]"
    new "Misses [j701_plate_errors]"
    old "Le plateau glisse de main en main. Suis la demande avant que la conversation déraille."
    new "The tray moves from hand to hand. Follow the request before the conversation goes off the rails."
    old "Bon geste. Le repas continue sans accroc."
    new "Good move. The meal continues smoothly."
    old "Mauvais objet. Quelqu'un rattrape le plateau au dernier moment."
    new "Wrong item. Someone catches the tray at the last second."
    old "Trop lent. La demande se perd dans le bruit de la table."
    new "Too slow. The request is lost in the noise around the table."
    old "DISCUSSION"
    new "DISCUSSION"
    old "Table"
    new "Table"
    old "blague"
    new "joke"
    old "relance"
    new "prompt"
    old "calme"
    new "calm"
    old "partage"
    new "sharing"
    old "chemin"
    new "path"
    old "Réponds vite. Trop hésiter, c'est déjà laisser le malaise entrer."
    new "Answer quickly. Hesitating too long already lets the discomfort in."
    old "Noam hésite. La table continue sans lui, un peu moins légère."
    new "Noam hesitates. The table carries on without him, a little less lightly."
    old "Je veux que ça DUUURE... Si on a enfin une journée sans voix divine, je refuse qu'on la passe à fixer les murs."
    new "I want it to LAAAST... If we finally get a day without the divine voice, I refuse to spend it staring at walls."
    old "Alors impose une minute de fête officielle."
    new "Then declare an official minute of celebration."
    old "Tu crois vraiment qu'elle est partie ?"
    new "Do you really think she's gone?"
    old "Julian peut faire le discours, il adore s'écouter."
    new "Julian can give the speech. He loves listening to himself."
    old "On devrait quand même rester prudents."
    new "We should still be careful."
    old "Minute de fête officielle ? J'aime. Il nous faut un rituel idiot, tout de suite."
    new "An official minute of celebration? I like it. We need a stupid ritual right now."
    old "Lever les verres à la santé du silence."
    new "Raise our glasses to the health of silence."
    old "Déclarer Julian mascotte temporaire."
    new "Declare Julian the temporary mascot."
    old "Proposer une minute sans parler de Kami."
    new "Suggest one minute without talking about Kami."
    old "Partie ? Non. C'est justement ça qui me gêne. Elle ne disparaît pas. Elle attend."
    new "Gone? No. That's exactly what bothers me. She doesn't disappear. She waits."
    old "Alors on lui vole six minutes."
    new "Then we steal six minutes from her."
    old "Tu as raison, ça sent mauvais."
    new "You're right. Something's wrong."
    old "Peut-être qu'elle nous écoute paniquer."
    new "Maybe she's listening to us panic."
    old "Je peux improviser un discours historique. Court, brillant, indispensable."
    new "I can improvise a historic speech. Short, brilliant, indispensable."
    old "Trois mots maximum."
    new "Three words maximum."
    old "Vas-y, président de la table."
    new "Go ahead, president of the table."
    old "Non. On mange."
    new "No. We eat."
    old "Merci. Je sais que je casse l'ambiance, mais je n'arrive pas à trouver ça normal."
    new "Thanks. I know I'm killing the mood, but I can't pretend this is normal."
    old "Tu ne casses rien. Tu vérifies les murs."
    new "You're not ruining anything. You're checking the walls."
    old "Alors laisse-moi casser l'ambiance à ta place."
    new "Then let me kill the mood for you."
    old "Tu stresses pour rien."
    new "You're worrying for nothing."
    old "CANON // SYNCHRONISATION DES FLUX"
    new "CANON // FLOW SYNCHRONIZATION"
    old "Isole la dernière valeur stable de chaque flux régional."
    new "Isolate the last stable value from each regional flow."
    old "SIGNAL MONDIAL INSTABLE"
    new "GLOBAL SIGNAL UNSTABLE"
    old "SIGNAL MONDIAL STABILISÉ"
    new "GLOBAL SIGNAL STABILIZED"
    old "SIGNAL PARTIEL // %d / 4"
    new "PARTIAL SIGNAL // %d / 4"
    old "FLUX STABILISÉ"
    new "FLOW STABILIZED"
    old "CALIBRER"
    new "CALIBRATE"
    old "ANALYSE TERMINÉE"
    new "ANALYSIS COMPLETE"
    old "EXÉCUTIONS RECENSÉES — DERNIÈRES 24 HEURES"
    new "RECORDED EXECUTIONS — LAST 24 HOURS"
    old "TOTAL MONDIAL : 0"
    new "GLOBAL TOTAL: 0"
    old "DERNIÈRE EXÉCUTION ENREGISTRÉE : HIER — 18 H 42"
    new "LAST RECORDED EXECUTION: YESTERDAY — 18:42"
    old "QUITTER LE CANON"
    new "EXIT THE CANON"
    old "Stabilise chaque flux pour reconstituer le bilan mondial."
    new "Stabilize each flow to reconstruct the global report."
    old "[j701_console_locked_count()] / 4 FLUX STABILISÉS"
    new "[j701_console_locked_count()] / 4 FLOWS STABILIZED"
    old "NETTOYER LE BUREAU"
    new "CLEAN THE DESK"
    old "Balaye les particules avant qu'elles se multiplient. Le dessin n'apparaît nulle part."
    new "Sweep away the particles before they multiply. The drawing is nowhere to be seen."
    old "Nettoyé [j701_clean_score]/12"
    new "Cleaned [j701_clean_score]/12"
    old "Trace révélée"
    new "Trace revealed"
    old "Balaye les poussières avant qu'elles se multiplient."
    new "Sweep away the dust before it multiplies."
    old "La poussière éclate en silence."
    new "The dust bursts apart in silence."
    old "Le parasite se désagrège sous le balai."
    new "The interference breaks apart under the broom."
    old "La poussière se divise. Le bureau refuse de rester propre."
    new "The dust splits. The desk refuses to stay clean."

    # Day 7 — investigation interface and dynamic evidence cards.
    old "PHASE D'ENQUÊTE"
    new "INVESTIGATION PHASE"
    old "5 TOURS  /  10 PISTES  /  UNE SEULE NUIT"
    new "5 TURNS  /  10 LEADS  /  ONE NIGHT"
    old "Choisis où consacrer ton temps. Les pistes abandonnées seront perdues."
    new "Choose where to spend your time. Abandoned leads will be lost."
    old "DOSSIER 07-A  //  CHOISIR UN LIEU"
    new "FILE 07-A  //  CHOOSE A LOCATION"
    old "LE CONTENU DES SALLES RESTE INCONNU TANT QUE TU NE L'EXAMINES PAS"
    new "ROOM CONTENTS REMAIN UNKNOWN UNTIL YOU EXAMINE THEM"
    old "TOUR [j701_investigation_turn + 1] / [J701_INVESTIGATION_MAX_TURNS]"
    new "TURN [j701_investigation_turn + 1] / [J701_INVESTIGATION_MAX_TURNS]"
    old "Entrer dans une salle est gratuit. Seul un indice collecté consomme un tour."
    new "Entering a room is free. Only collecting a clue uses a turn."
    old "<  RETOUR AU PLAN"
    new "<  BACK TO MAP"
    old "FRAGMENT DE PREUVE OBTENU"
    new "EVIDENCE FRAGMENT OBTAINED"
    old "DOSSIER PROVISOIRE"
    new "PROVISIONAL FILE"
    old "5 fragments récupérés  //  5 pistes abandonnées"
    new "5 fragments recovered  //  5 leads abandoned"
    old "REJOINDRE LE DÉBRIEF  >"
    new "JOIN THE DEBRIEF  >"
    old "POINT D'INTÉRÊT"
    new "POINT OF INTEREST"
    old "POINTS D'INTÉRÊT"
    new "POINTS OF INTEREST"
    old "PLUS RIEN À EXAMINER"
    new "NOTHING LEFT TO EXAMINE"
    old "Reprendre les témoignages"
    new "Review the testimonies"
    old "Reconstituer le prélèvement"
    new "Reconstruct the removal"
    old "Chercher ce qui a été fabriqué"
    new "Find what was built"
    old "Interroger les images"
    new "Question the footage"
    old "SAS DE LIVRAISON"
    new "DELIVERY AIRLOCK"
    old "Suivre le trajet du matériel"
    new "Trace the equipment's route"
    old "Interroger Elias"
    new "Question Elias"
    old "Examiner la table"
    new "Examine the table"
    old "Inspecter les emplacements vides"
    new "Inspect the empty slots"
    old "Consulter le boîtier de porte"
    new "Check the door terminal"
    old "Regarder sous l'établi"
    new "Look under the workbench"
    old "Étudier le plan de travail"
    new "Study the work surface"
    old "Surprendre Kael"
    new "Catch Kael off guard"
    old "Accéder aux logs de sécurité"
    new "Access the security logs"
    old "Suivre les marques"
    new "Follow the marks"
    old "Écouter le terminal"
    new "Listen to the terminal"
    old "LA DERNIÈRE VISITE"
    new "THE LAST VISIT"
    old "Elias a manipulé les quatre objets hier soir. À 23 h 47, ils étaient encore tous à leur place."
    new "Elias handled all four items last night. At 23:47, they were still in their proper places."
    old "LA GRUE D'ARGENT"
    new "THE SILVER CRANE"
    old "Un origami en emballage de ration était pris dans une roue du chariot. Elen en plie souvent, mais les laisse sur toutes les tables."
    new "A ration-wrapper origami was caught in a cart wheel. Elen often folds them, but leaves them on every table."
    old "LE POIDS FANTÔME"
    new "THE PHANTOM WEIGHT"
    old "Les batteries ont été remplacées par des poches d'eau du même poids afin de tromper le capteur de l'étagère."
    new "The batteries were replaced with water pouches of equal weight to fool the shelf sensor."
    old "LE REÇU SANS NOM"
    new "THE NAMELESS RECEIPT"
    old "Le terminal a bien autorisé un retrait à 02 h 14, mais la case réservée à l'identité contient seulement un caractère impossible."
    new "The terminal authorized a removal at 02:14, but the identity field contains only an impossible character."
    old "LE CHEVEU COUPÉ"
    new "THE CUT HAIR"
    old "Un cheveu brun et assez court était coincé dans l'établi. Son extrémité est tranchée net et il ne porte aucune racine."
    new "A short brown hair was caught in the workbench. Its end is cleanly cut and it has no root."
    old "LE PLAN EN NÉGATIF"
    new "THE NEGATIVE BLUEPRINT"
    old "La limaille magnétique dessine la silhouette d'un adaptateur fabriqué ici, emporté ensuite, et dont le plan a été soigneusement effacé."
    new "Magnetic filings outline an adapter built here and later removed, its blueprint carefully erased."
    old "LA REQUÊTE DE KAEL"
    new "KAEL'S QUERY"
    old "Kael tente seul d'entrer dans la base des caméras et masque sa requête lorsque Noam approche."
    new "Kael tries to access the camera database alone and hides his query when Noam approaches."
    old "LE LOG DE 02 H 34"
    new "THE 02:34 LOG"
    old "Les logs de sécurité indiquent que la porte de la maintenance s'est ouverte à 02 h 34, sans enregistrer l'identité de l'utilisateur."
    new "Security logs show the maintenance door opened at 02:34 without recording the user's identity."
    old "LES TRACES VERTICALES"
    new "THE VERTICAL TRACKS"
    old "Les marques du chariot quittent le sol et continuent sur une porte. La cargaison a été fixée à un plateau magnétique."
    new "The cart tracks leave the floor and continue up a door. The cargo was attached to a magnetic platform."
    old "L'ÉCHO IMPOSSIBLE"
    new "THE IMPOSSIBLE ECHO"
    old "Le micro du sas a enregistré deux bips de la même porte séparés de sept secondes, alors que son verrou exige douze secondes."
    new "The airlock microphone recorded two beeps from the same door seven seconds apart, though its lock requires twelve seconds."
