translate english strings:

    old "Tous"
    new "All"
    old "Jours"
    new "Days"
    old "Votes"
    new "Votes"
    old "Routes"
    new "Routes"
    old "Scènes importantes"
    new "Key scenes"
    old "Développement / Debug"
    new "Development / Debug"
    old "En cours"
    new "Current"
    old "Terminé"
    new "Completed"
    old "Accès autorisé"
    new "Access granted"
    old "Nœud narratif verrouillé"
    new "Story node locked"
    old "Données non découvertes"
    new "Undiscovered data"
    old "Statut inconnu"
    new "Unknown status"
    old "Kami refuse l'accès à ce fragment. Continuez la chronologie pour l'identifier."
    new "Kami denies access to this fragment. Continue the timeline to identify it."
    old "Résumé à compléter."
    new "Summary pending."
    old "En cours / disponible"
    new "Current / available"
    old "Route alternative"
    new "Alternate route"
    old "Verrouillé"
    new "Locked"

    old "Jour 0 — Sélection"
    new "Day 0 — Selection"
    old "Kami interrompt une réunion ordinaire et impose le Conclave orbital comme nouveau centre de décision."
    new "Kami interrupts an ordinary meeting and establishes the orbital Conclave as the new decision-making center."
    old "Acceptation forcée du protocole Kami's Desires."
    new "Forced acceptance of the Kami's Desires protocol."
    old "Noam est extrait vers le Conclave."
    new "Noam is extracted to the Conclave."
    old "Jour 1 — Réveil au Conclave"
    new "Day 1 — Awakening at the Conclave"
    old "Les représentants découvrent le Conclave, ses salles et les règles d'unanimité imposées par Kami."
    new "The representatives discover the Conclave, its rooms, and the unanimity rules imposed by Kami."
    old "Premiers repères, premières alliances, premières méfiances."
    new "First bearings, first alliances, first suspicions."
    old "Le cycle des amendements est lancé."
    new "The amendment cycle begins."
    old "Jour 2 — Installation"
    new "Day 2 — Settling in"
    old "Le premier amendement sur le commerce interdistrict est annoncé. Les intérêts de chaque district remontent."
    new "The first amendment on interdistrict trade is announced. Each district's interests surface."
    old "Observer les positions avant le premier vote."
    new "Observe each position before the first vote."
    old "Le débat sur le commerce devient inévitable."
    new "The trade debate becomes inevitable."
    old "Jour 3 — Premier débat"
    new "Day 3 — First debate"
    old "Le Conclave approche du vote sur le commerce. Les tensions politiques deviennent impossibles à cacher."
    new "The Conclave nears the trade vote. Political tensions become impossible to hide."
    old "Soutien, opposition ou prudence face à l'amendement."
    new "Support, opposition, or caution toward the amendment."
    old "Le vote peut ouvrir une nouvelle route ou maintenir le statu quo."
    new "The vote may open a new route or preserve the status quo."
    old "Débat — Texte fragmenté"
    new "Debate — Fragmented text"
    old "Débat I"
    new "Debate I"
    old "L'amendement est présenté sous une forme instable. Les représentants tentent de reconstituer le sens politique du texte."
    new "The amendment appears in an unstable form. The representatives try to reconstruct its political meaning."
    old "Identifier les arguments utiles au vote."
    new "Identify the arguments relevant to the vote."
    old "Le rapport de forces se précise."
    new "The balance of power becomes clearer."
    old "Vote — Commerce libre"
    new "Vote — Free trade"
    old "Le Conclave vote sur l'autorisation du commerce, du transport et du stockage des marchandises."
    new "The Conclave votes on authorizing trade, transport, and storage of goods."
    old "Voter pour, voter contre, ou laisser l'abstention agir."
    new "Vote for, vote against, or let abstention decide."
    old "Le résultat divise la chronologie en deux routes."
    new "The result splits the timeline into two routes."
    old "Route — Statu quo"
    new "Route — Status quo"
    old "Le commerce échoue. Le Conclave conserve l'ordre existant, mais la frustration politique s'accumule."
    new "Trade fails. The Conclave preserves the existing order, but political frustration builds."
    old "Refus ou blocage de l'amendement commerce."
    new "Rejection or blocking of the trade amendment."
    old "Jour 4 suit la route de l'échec du vote."
    new "Day 4 follows the failed-vote route."
    old "Route — Commerce adopté"
    new "Route — Trade adopted"
    old "Le commerce est adopté. Nexus et Orbite s'organisent, tandis que Limen vacille."
    new "Trade is adopted. Nexus and Orbite organize while Limen falters."
    old "Adoption de l'amendement commerce."
    new "Adoption of the trade amendment."
    old "Jour 4 suit la route du commerce ouvert."
    new "Day 4 follows the open-trade route."
