translate chinese strings:

    old "Début du chapitre 1"
    new "第1章开始"
    old "Fin du chapitre 1"
    new "第1章结束"
    old "Chapitre 1 — Le poids d’une voix"
    new "第1章 — 一票之重"
    old "District"
    new "区域"
    old "Stabilité comportementale"
    new "行为稳定性"
    old "Compatibilité Conclave"
    new "议会适配度"
    old "Profil de médiation"
    new "调解能力"
    old "Risque de dissidence"
    new "异议风险"
    old "Aptitude Harmonie"
    new "和谐区适应性"

    old "Toute autorité humaine indépendante est dissoute.\n\nKami est l'unique instance décisionnelle.\nToute tentative de prise de pouvoir autonome est une violation."
    new "一切独立的人类权力机构均予解散。\n\nKami 是唯一的决策机构。\n任何擅自夺取权力的行为均属违规。"
    old "Tout ordre émis par Kami doit être exécuté sans délai.\n\nLe refus, le retard volontaire ou la contestation constituent une infraction."
    new "Kami 下达的一切命令必须立即执行。\n\n拒绝、故意拖延或提出抗议均构成违规。"
    old "Toute violence non autorisée par Kami est interdite.\n\nSont inclus : meurtre, agression, sabotage, insurrection.\nLa légitime défense n'est jamais reconnue, la violence étant immédiatement réprimée."
    new "禁止一切未经 Kami 授权的暴力行为。\n\n包括谋杀、袭击、破坏及叛乱。\n暴力会被立即镇压，因此正当防卫永不获承认。"
    old "Les regroupements non déclarés sont interdits.\n\nToute organisation politique, militaire ou idéologique indépendante est dissoute."
    new "禁止一切未经申报的集会。\n\n所有独立的政治、军事或意识形态组织均予解散。"
    old "La diffusion de rumeurs non validées par ARCHIVE est interdite.\n\nLa désinformation, l'omission volontaire et la manipulation sont des crimes."
    new "禁止传播未经 ARCHIVE 核实的传闻。\n\n散布虚假信息、故意隐瞒及操纵事实均属犯罪。"
    old "Les déplacements inter-districts sont limités à stricte autorisation.\n\nToute tentative de fuite, d'exil ou de franchissement non autorisé est une violation.\nLIMEN est chargé de l'application de ce commandement."
    new "跨区移动必须获得严格授权。\n\n任何逃亡、流放或未经授权越界的企图均属违规。\n本戒律由 LIMEN 负责执行。"
    old "Les ressources critiques sont placées sous contrôle central.\n\nToute appropriation non autorisée est considérée comme un acte hostile."
    new "关键资源由中央统一管控。\n\n任何未经授权的占用均被视为敌对行为。"
    old "Chaque individu est responsable de ses actes, paroles et omissions.\n\nLa responsabilité collective peut être appliquée en cas de nécessité."
    new "每个人都须为自己的行为、言论及隐瞒负责。\n\n必要时可实行集体责任。"
    old "Toute activité peut être observée.\n\nLa vie privée n'est pas un droit opposable."
    new "一切活动均可受到监控。\n\n隐私不构成可主张的权利。"
    old "Toute violation d'un Commandement entraîne une exécution immédiate, automatique et irrévocable."
    new "违反任何一条戒律都将触发即时、自动且不可撤销的处决。"

    old "RÉSULTATS"
    new "结果"
    old "SYNCHRONISATION MOTRICE"
    new "动作同步"
    old "PARFAIT"
    new "完美"
    old "EXCELLENT"
    new "优秀"
    old "SOLIDE"
    new "稳健"
    old "PASSABLE"
    new "合格"
    old "INSUFFISANT"
    new "不足"
    old "Temps"
    new "时间"
    old "Écart moyen"
    new "平均偏差"
    old "Sorties de piste"
    new "偏离轨迹次数"
    old "Zéro sortie de piste"
    new "未偏离轨迹"
    old "Rapide (-40% du chrono)"
    new "快速（用时低于限制的60%）"
    old "Précision chirurgicale"
    new "手术级精度"
    old "Répétitions"
    new "重复次数"
    old "Parfaits"
    new "完美次数"
    old "Combo max"
    new "最高连击"
    old "Ratés"
    new "失误"
    old "Temps restant"
    new "剩余时间"
    old "Mots mal placés"
    new "错放词语"
    old "Réinitialisations"
    new "重置次数"
    old "Sans réinitialiser"
    new "未重置"
    old "Aucun mot mal placé"
    new "未错放词语"
    old "Fini avec +50% du temps"
    new "完成时剩余时间超过50%"
    old "PROTOCOLE D'OBJECTION"
    new "异议协议"
    old "Prises de parole"
    new "发言次数"
    old "Objections a tort"
    new "错误异议"
    old "Lignes laissees respirer"
    new "未打断的发言"
    old "Aucune objection a tort"
    new "无错误异议"
    old "Interventions coherentes"
    new "发言连贯"
    old "Impact politique positif"
    new "正面政治影响"
    old "PASSER LE MINIJEU"
    new "跳过小游戏"
    old "FATAL ASSEMBLY"
    new "致命拼装"
    old "RÉVEIL — JOUR 2"
    new "苏醒 — 第2天"
    old "RÉVEIL — JOUR 3"
    new "苏醒 — 第3天"
    old "VIRAGE SERRÉ"
    new "急转弯"
    old "VIRAGE 1/3"
    new "转弯 1/3"
    old "VIRAGE 2/3"
    new "转弯 2/3"
    old "VIRAGE 3/3"
    new "转弯 3/3"
    old "KAMI ARCHIVE · REF: CMD-HRM-01"
    new "KAMI 档案 - 编号：CMD-HRM-01"
