translate chinese strings:

    # 第 0–1 天：抵达、安检、代表选拔、修正案与干扰器界面。
    old "ACHEMINEMENT — CONCLAVE"
    new "运送 — 议会"
    old "DÉLAI EXPIRÉ"
    new "时间已到"
    old "LIMITE : 22:00  ▸  RESTANT"
    new "截止：22:00  >  剩余"
    old "PORTIQUE DE SÉCURITÉ — DISTRICT HARMONIE"
    new "安检门 — 和谐区"
    old "● ACTIF"
    new "● 运行中"
    old "LECTEUR CIVIL / IDENTIFICATION OBLIGATOIRE"
    new "公民读取器 / 必须验证身份"
    old "POSER LE BADGE SUR LA ZONE DE LECTURE"
    new "请将徽章放在读取区"
    old "Chaque entrée est enregistrée."
    new "每次进入都会被记录。"
    old "↓  ZONE DE LECTURE  ↓"
    new "↓  读取区  ↓"
    old "BADGE ENREGISTRÉ"
    new "徽章已记录"
    old "DISTRICT HARMONIE"
    new "和谐区"
    old "Médiateur civil · Secteur 3"
    new "公民调解员 - 第 3 区段"
    old "LECTEUR BIOMÉTRIQUE"
    new "生物识别读取器"
    old "EN ATTENTE"
    new "等待中"
    old "ANALYSE EN COURS"
    new "正在分析"
    old "ACCÈS AUTORISÉ"
    new "允许通行"
    old "Présenter le badge dans la zone."
    new "请在读取区出示徽章。"
    old "Comparaison profil civil en cours."
    new "正在比对公民档案。"
    old "VALIDATION DE L'IDENTITÉ..."
    new "正在验证身份……"
    old "Comparaison du profil avec les autorisations locales."
    new "正在比对档案与本地权限。"
    old "PASSAGE CONFIRMÉ"
    new "通行已确认"
    old "Comportement conforme. Identité reconnue."
    new "行为合规。身份已确认。"
    old "IDENTIFIANT CIVIL"
    new "公民编号"
    old "▶  GLISSER"
    new "▶  滑动"
    old "KAMI INFRASTRUCTURE · CONTRÔLE CIVIL AUTOMATISÉ · TOUTE ENTRÉE EST ENREGISTRÉE"
    new "KAMI 基础设施 - 自动公民管控 - 每次进入均会被记录"
    old "ÉCRAN VERROUILLÉ"
    new "屏幕已锁定"
    old "Glisser vers le haut pour déverrouiller"
    new "向上滑动解锁"
    old "VENDREDI — JOUR 0"
    new "星期五 — 第 0 天"
    old "Signal : --   •   Réseau : indisponible"
    new "信号：--   •   网络：不可用"
    old "Recherche de réseau..."
    new "正在搜索网络……"
    old "AUCUN RÉSEAU"
    new "无网络"
    old "Recherche des relais civils en cours..."
    new "正在搜索民用中继站……"
    old "ERR_NET_001 · Aucun opérateur disponible"
    new "ERR_NET_001 - 无可用运营商"
    old "Les services de communication\nsont temporairement indisponibles."
    new "通信服务\n暂时不可用。"
    old "APPEL REFUSÉ"
    new "呼叫被拒绝"
    old "Appels d'urgence indisponibles."
    new "紧急呼叫不可用。"
    old "Code : INFRASTRUCTURE NON SOUVERAINE"
    new "代码：非主权基础设施"
    old "Tous les canaux de communication\ndépendent désormais de KAMI."
    new "所有通信频道\n现均由 KAMI 控制。"
    old "ERR_NET_403 · ACCÈS BLOQUÉ"
    new "ERR_NET_403 - 访问被阻止"
    old "MESSAGE NON ENVOYÉ"
    new "消息未发送"
    old "Merci de cesser toute tentative de\nréinitialisation du réseau.\nCette conversation est enregistrée."
    new "请停止一切\n重置网络的尝试。\n本次对话正在被记录。"
    old "Le réseau de communication\nne vous appartient plus."
    new "通信网络\n已不再属于你。"
    old "• 1 message non distribué"
    new "• 1 条消息未送达"
    old "CONTRÔLE DISTANT ACTIF"
    new "远程控制已启用"
    old "Verrouillage de l'interface."
    new "正在锁定界面。"
    old "Cet appareil est désormais\nsous surveillance directe."
    new "此设备现已处于\n直接监控之下。"
    old "Rallumer"
    new "开机"
    old "Envoyer"
    new "发送"
    old "REGISTRE DES COMMANDEMENTS"
    new "戒律登记簿"
    old "District HARMONIE · Consultation surveillée"
    new "和谐区 - 受监控查阅"
    old "Commandement %s"
    new "戒律 %s"
    old "COMMANDEMENT"
    new "戒律"
    old "◀ Précédent"
    new "◀ 上一项"
    old "Suivant ▶"
    new "下一项 ▶"
    old "Fermer"
    new "关闭"
    old "DISTRICT HARMONIE — SÉLECTION DES REPRÉSENTANTS"
    new "和谐区 — 代表选拔"
    old "Cliquez pour arrêter la sélection"
    new "点击以停止选拔"
    old "PROFILS EN ANALYSE"
    new "正在分析档案"
    old "✓  SÉLECTIONNÉ"
    new "已选中"
    old "PROFIL ÉCARTÉ"
    new "档案已排除"
    old "CRITÈRES D'ANALYSE"
    new "分析标准"
    old "EN COURS…"
    new "进行中……"
    old "VALIDÉ"
    new "已验证"
    old "SÉLECTION VALIDÉE"
    new "选拔已确认"
    old "REPRÉSENTANTS — DISTRICT HARMONIE"
    new "代表 — 和谐区"
    old "Médiateur civil"
    new "公民调解员"
    old "Coordination logistique"
    new "后勤协调"
    old "Acheminement sous 6 heures — Sanctions applicables en cas de retard."
    new "须在 6 小时内送达 — 延误将受到处罚。"
    old "KAMI — SÉLECTION AUTOMATISÉE · DISTRICT HARMONIE · SÉANCE 14-3"
    new "KAMI — 自动选拔 - 和谐区 - 第 14-3 场会议"
    old "FERMETURE AUTOMATIQUE // 2.0 s"
    new "自动关闭 // 2.0 秒"
    old "SOUVENIR"
    new "记忆"

    old "INTERFACE PUPITRE — CONCLAVE"
    new "议席界面 — 议会"
    old "SESSION : EN ATTENTE  ▸  VERROUILLÉ"
    new "会议：等待中  >  已锁定"
    old "UTILISATEUR"
    new "用户"
    old "STATUT"
    new "状态"
    old "REPRÉSENTANT — CONCLAVE JOUR 1"
    new "代表 — 议会第 1 天"
    old "ACCÈS TABLETTE"
    new "平板访问权限"
    old "▸  AMENDEMENTS  —  VERROUILLÉ JUSQU'AU DÉPÔT"
    new ">  修正案  —  提交前锁定"
    old "▸  CODEX  —  ACCÈS PARTIEL"
    new ">  档案库  —  部分访问"
    old "▸  COMMUNICATIONS  —  BLOQUÉES"
    new ">  通信  —  已阻止"
    old "INTERACTION ENREGISTRÉE — KAMI MONITORING ACTIF"
    new "交互已记录 — KAMI 监控已启用"
    old "RETIRER LA MAIN"
    new "移开手掌"
    old "✦  CODEX  —  NOUVELLE ENTRÉE  :"
    new "+  档案库  —  新条目："
    old "DÉPÔT CLOS"
    new "提交已关闭"
    old "FERMETURE  ▸  RESTANT"
    new "关闭  >  剩余"
    old "TUTORIEL — PROPOSITION D'AMENDEMENT"
    new "教程 — 修正案提案"
    old "Comment proposer un amendement :"
    new "如何提出修正案："
    old "① Lisez attentivement les deux propositions de modification de Commandement."
    new "① 仔细阅读两项戒律修改提案。"
    old "② Sélectionnez la proposition qui vous semble la plus juste ou la plus utile."
    new "② 选择你认为更公正或更有用的提案。"
    old "③ La formulation officielle sera automatiquement retenue."
    new "③ 系统将自动采用正式措辞。"
    old "④ Une fois validé, l'amendement est anonymement déposé dans l'urne — sans retour possible."
    new "④ 确认后，修正案将匿名投入票箱 — 无法撤回。"
    old "⚠  Ce choix est définitif. Il engage Noam pour l'ensemble du Conclave."
    new "警告：此选择不可更改。Noam 将在整个议会期间受其约束。"
    old "COMPRIS — CONTINUER"
    new "明白 — 继续"
    old "TERMINAL CONSTITUTIONNEL — PROPOSITION D'AMENDEMENT"
    new "宪法终端 — 修正案提案"
    old "REPRÉSENTANT : NOAM  ▸  STATUT : BROUILLON  ▸  ANONYMAT : GARANTI"
    new "代表：NOAM  >  状态：草案  >  匿名：有保障"
    old "SÉLECTIONNÉ"
    new "已选中"
    old "INTENTION"
    new "意图"
    old "FORMULATION"
    new "措辞"
    old "RISQUE IDENTIFIÉ"
    new "已识别风险"
    old "FORMULATION OFFICIELLE RETENUE :"
    new "采用的正式措辞："
    old "VALIDER LA PROPOSITION"
    new "确认提案"
    old "CONFIRMATION — DÉPÔT DÉFINITIF"
    new "确认 — 最终提交"
    old "Ce dépôt est IRRÉVERSIBLE. L'amendement sera traité de façon anonyme."
    new "此次提交不可撤销。修正案将以匿名方式处理。"
    old "← MODIFIER"
    new "← 修改"
    old "DÉPOSER DANS L'URNE →"
    new "投入票箱 →"
    old "AMENDEMENT DÉPOSÉ"
    new "修正案已提交"
    old "RETRAIT IMPOSSIBLE"
    new "无法撤回"
    old "ENREGISTREMENT CONFIRMÉ"
    new "记录已确认"
    old "ANONYMAT GARANTI — KAMI NE PEUT PAS IDENTIFIER L'AUTEUR"
    new "匿名有保障 — KAMI 无法识别作者"
    old "TIRAGE AU SORT DEMAIN À 09:00"
    new "明日 09:00 抽签"
    old "RECULER DE L'URNE"
    new "离开票箱"
    old "INTERFACE CHAMBRE — BROUILLEUR"
    new "房间界面 — 干扰器"
    old "BROUILLEUR : "
    new "干扰器："
    old "MODE PRIVÉ : "
    new "隐私模式："
    old "CAMÉRA : COUPÉE"
    new "摄像头：关闭"
    old "AUDIO : COUPÉ"
    new "音频：关闭"
    old "CAPTEURS : COUPÉS"
    new "传感器：关闭"
    old "KAMI : AVEUGLE"
    new "KAMI：无法监视"
    old "SURVEILLANCE POTENTIELLE — KAMI PEUT OBSERVER CETTE PIÈCE"
    new "可能受到监控 — KAMI 可以观察此房间"
    old "DÉSACTIVER LE BROUILLEUR"
    new "关闭干扰器"
    old "RÉACTIVER LE BROUILLEUR"
    new "重新启用干扰器"
    old "QUITTER L'INTERFACE"
    new "关闭界面"
    old "TUTORIEL — SYNCHRONISATION MOTRICE"
    new "教程 — 动作同步"
    old "Comment répondre à un QTE de trace :"
    new "如何完成轨迹 QTE："
    old "① Une courbe ou un chemin s'affiche à l'écran."
    new "① 屏幕上会显示一条曲线或路径。"
    old "② Suivez ce tracé avec votre souris le plus précisément possible."
    new "② 用鼠标尽可能准确地沿着轨迹移动。"
    old "③ Restez dans la tolérance indiquée (zone colorée) pour valider."
    new "③ 保持在标示的容差范围（彩色区域）内即可成功。"
    old "④ Trop d'erreurs = échec. Restez concentré et allez à un rythme régulier."
    new "④ 错误过多即失败。保持专注并以稳定速度移动。"
    old "Ce QTE simule la perte de contrôle moteur de Noam au réveil."
    new "此 QTE 模拟 Noam 醒来时失去动作控制的状态。"
    old "COMPRIS — LANCER LE QTE"
    new "明白 — 开始 QTE"

    # 第 2–3 天：投票档案、辩论与小游戏。
    old "Glisse la carte dans la mallette de Noam."
    new "将卡片拖入 Noam 的公文包。"
    old "ARGUMENT"
    new "论点"
    old "DOSSIER DU VOTE"
    new "投票档案"
    old "DÉPOSER ICI"
    new "放在这里"
    old "TABLETTE DE NOAM"
    new "NOAM 的平板"
    old "Nouveau dossier disponible : Prochain vote"
    new "新档案可用：下一场投票"
    old "La fiche rassemble la proposition, les arguments rangés dans ton dossier et les positions que tu supposes chez les autres représentants."
    new "档案汇总了提案、你收集的论点，以及你推测的其他代表立场。"
    old "Les portraits peuvent être déplacés librement entre POUR, INCONNU et CONTRE. Ce classement est une note personnelle, pas une correction automatique."
    new "头像可在赞成、未知与反对之间自由移动。这只是个人记录，不会自动判定正误。"
    old "Continuer"
    new "继续"
    old "Prochain vote"
    new "下一场投票"
    old "Vote en cours"
    new "当前投票"
    old "Ça serait bien qu'on réautorise le commerce comme avant."
    new "要是能像以前一样重新允许贸易就好了。"
    old "Moment prévu : Jour 3, 14h00"
    new "预计时间：第 3 天 14:00"
    old "Moment prévu : Jour 6, 14h00"
    new "预计时间：第 6 天 14:00"
    old "Résumé neutre"
    new "中立摘要"
    old "Le texte promet une circulation plus libre des biens. Ses effets restent incertains selon les districts, les procédures et les risques locaux."
    new "文本承诺让货物流通更加自由，但其影响仍取决于各区、程序与当地风险。"
    old "Autoriser ou non les déplacements entre les districts."
    new "决定是否允许跨区通行。"
    old "Le texte promet une circulation plus libre des personnes entre districts. Ses effets restent incertains selon les frontières, la sécurité et les capacités d'accueil."
    new "文本承诺让人员跨区流动更加自由，但其影响仍取决于边界、安全与接纳能力。"
    old "Arguments découverts"
    new "已发现论点"
    old "Argument non découvert"
    new "论点尚未发现"
    old "Glisse les portraits ici."
    new "将头像拖到这里。"
    old "Dossier actif"
    new "当前档案"
    old "Arguments rangés : [day2_vote_argument_count()] / [len(DAY2_VOTE_ARGUMENTS)]"
    new "已收集论点：[day2_vote_argument_count()] / [len(DAY2_VOTE_ARGUMENTS)]"
    old "Les positions restent modifiables dans le Codex."
    new "仍可在档案库中修改立场。"
    old "CHOIX DU THÈME"
    new "选择主题"
    old "PHASE ARGUMENTATIVE"
    new "辩论阶段"
    old "PHASE [phase]/3"
    new "阶段 [phase]/3"
    old "Quel angle aborder pour cette discussion ?\nJe dois choisir l'argument qui aura le plus d'impact."
    new "这次讨论该从什么角度切入？\n我必须选择最有影响力的论点。"
    old "SÉLECTIONNEZ LE THÈME DE LA DISCUSSION"
    new "选择讨论主题"
    old "Débloquez cet argument pour l'utiliser."
    new "解锁此论点后才能使用。"
    old "VOS ARGUMENTS DÉBLOQUÉS"
    new "你已解锁的论点"
    old "INFO  Chaque thème influence les réactions des représentants. Choisissez judicieusement."
    new "提示  每个主题都会影响代表的反应。请谨慎选择。"
    old "CONFIRMER LE THÈME"
    new "确认主题"
    old "CONTINUER SANS THÈME"
    new "不选主题并继续"

    old "ARCHIVE // ANALYSE DE TEXTE"
    new "档案 // 文本分析"
    old "Alors, médiateur..."
    new "那么，调解员……"
    old "OBJECTIF"
    new "目标"
    old "Glissez-déposez les mots pour reconstituer la phrase exacte du texte officiel."
    new "拖放词语，重建正式文本中的准确句子。"
    old "Chaque placement compte : une proposition propre donne un meilleur résultat."
    new "每次放置都很重要：整洁的提案会获得更好的结果。"
    old "TEMPS\nRESTANT"
    new "剩余\n时间"
    old "[fa_filled_count]/[fa_total_slots] mots placés"
    new "已放置 [fa_filled_count]/[fa_total_slots] 个词"
    old "— PROGRESSION"
    new "— 进度"
    old "Autoriser"
    new "允许"
    old "vente"
    new "销售"
    old "le"
    new "该"

    old "OBJECTION\nPROTOCOL"
    new "异议\n协议"
    old "LIGNE [_dp2_current_line]/[_dp2_total_lines]"
    new "发言 [_dp2_current_line]/[_dp2_total_lines]"
    old "PRISES DE PAROLE [debat_phase2_good]"
    new "有效发言 [debat_phase2_good]"
    old "VOTRE TOUR"
    new "轮到你"
    old "Cliquez sur le buzzer seulement quand une intervention apporte vraiment quelque chose."
    new "只有当发言确实有价值时才按下抢答器。"
    old "ATTENTION"
    new "注意"
    old "Vous ne pouvez parler\nqu’après avoir appuyé\nsur le buzzer."
    new "只有按下\n抢答器后\n才能发言。"
    old "À TORT [debat_phase2_wrong]"
    new "错误 [debat_phase2_wrong]"
    old "MANQUÉES [debat_phase2_missed]"
    new "错过 [debat_phase2_missed]"
    old "OBJECTION !"
    new "异议！"
    old "OBJECTION REJETÉE"
    new "异议被驳回"
    old "Cet argument tenait debout. L'assemblée murmure..."
    new "这个论点站得住脚。会场响起低语……"
    old "Noam a perdu toute credibilite devant le Conclave."
    new "Noam 已在议会面前失去所有公信力。"
    old "Cliquez pour reprendre juste avant le Protocole d'Objection."
    new "点击以从异议协议开始前继续。"

    old "RÉPÉTITIONS"
    new "重复次数"
    old "ÉNERGIE // CHARGE MUSCULAIRE"
    new "能量 // 肌肉负荷"
    old "RYTHME // FENÊTRE D'EFFORT"
    new "节奏 // 发力窗口"
    old "TEMPS // CHRONO"
    new "时间 // 计时器"
    old "⬆ ⬇  Clic, ↑ ou ↓ pour pousser."
    new "⬆ ⬇  点击、按 ↑ 或 ↓ 发力。"
    old "POUSSER"
    new "发力"
    old "STAT EN HAUSSE"
    new "属性提升"
    old "Physique +1"
    new "体能 +1"
    old "PARFAIT !"
    new "完美！"

    old "KAMI.CORE // EXECUTION PROTOCOL"
    new "KAMI.CORE // 执行协议"
    old "TUTORIEL — [title]"
    new "教程 — [title]"
    old "KAMI.CORE // RETRY PENALTY"
    new "KAMI.CORE // 重试惩罚"
    old "KAMI.CORE // PERFORMANCE VERDICT"
    new "KAMI.CORE // 表现评定"
    old "★ NOUVEAU RECORD"
    new "新纪录"
    old "Record : [best_rank]"
    new "纪录：[best_rank]"
    old "[retries] retry — rang plafonné"
    new "重试 [retries] 次 — 评级受限"
    old "DÉFIS  [mk_challenge_count_done(challenges)] / [len(challenges)]"
    new "挑战  [mk_challenge_count_done(challenges)] / [len(challenges)]"
    old "CONTINUER"
    new "继续"
    old "MAINTENIR PUIS GLISSER"
    new "按住并拖动"
    old "NOAM — PENSÉE"
    new "NOAM — 思绪"
    old "CLIQUER POUR CONTINUER"
    new "点击继续"

    old "01  ÉCOUTE"
    new "01  聆听"
    old "02  ARME"
    new "02  准备"
    old "03  CONTREDIS"
    new "03  反驳"
    old "Une erreur ne bloque pas la scène : Julian poursuit simplement son argumentaire."
    new "失误不会中断场景：Julian 只会继续陈述。"
    old "ARGUMENT // JULIAN"
    new "论点 // JULIAN"
    old "DÉCLARATION [line_index + 1] / [total_lines]"
    new "陈述 [line_index + 1] / [total_lines]"
    old "LECTURE [pass_index + 1]"
    new "第 [pass_index + 1] 遍"
    old "PREMIÈRE LECTURE : observe l'argumentaire complet. Les répliques seront disponibles au prochain passage."
    new "第一遍：观察完整论证。下一遍将开放回应选项。"
    old "CONTRADICTION TROUVÉE — écoute de la fin de l'argumentaire"
    new "发现矛盾 — 听完剩余论证"
    old "SÉLECTION : [DAY3_JULIAN_CLASH_BULLETS[day3_julian_clash_selected]['text']]"
    new "已选择：[DAY3_JULIAN_CLASH_BULLETS[day3_julian_clash_selected]['text']]"
    old "ACCÉLÉRER  >>"
    new "加速  >>"
    old "RETOUR AU SEGMENT 01"
    new "返回片段 01"
    old "Les répliques sont maintenant disponibles."
    new "现在可以选择回应。"
    old "CONTRADICTION"
    new "矛盾"
    old "RÉPLIQUE ÉCARTÉE"
    new "回应无效"
    old "Julian enchaîne sans te laisser reprendre l'avantage."
    new "Julian 紧接着说下去，不给你夺回主动的机会。"
    old "Tu as isolé le faux mandat derrière le discours de Julian."
    new "你揭穿了 Julian 言辞背后的虚假授权。"

    old "NOUVEL ARGUMENT"
    new "新论点"
    old "PROFIL — STATISTIQUES"
    new "档案 — 属性"
    old "COMPÉTENCES PERMANENTES"
    new "永久能力"
    old "◂  RETOUR"
    new "<  返回"
    old "Niveau [get_stat(name)]   •   Difficulté [dc]"
    new "等级 [get_stat(name)]   •   难度 [dc]"
    old "LANCER LE DÉ"
    new "掷骰子"
    old "Zones visitées : [len(exploration_libre_seen_rooms)]/[exploration_libre_required_visits]"
    new "已访问区域：[len(exploration_libre_seen_rooms)]/[exploration_libre_required_visits]"
    old "Rejoindre la cafétéria"
    new "前往餐厅"
    old "Rejoindre la salle d'observation"
    new "前往观察室"
    old "DAY"
    new "天"
    old "URN"
    new "票箱"
    old "PHASE"
    new "阶段"
    old "« Abolir la distribution risque de"
    new "“废除配给可能会"
    old "condamner les plus fragiles. »"
    new "让最弱势者陷入绝境。”"
    old "BUZZ"
    new "抢答"
    old "GAME OVER"
    new "游戏结束"
    old "GO"
    new "开始"
    old "COMBO x[mg_combo]"
    new "连击 x[mg_combo]"
    old "SCORE  [score] / [max_score]"
    new "分数  [score] / [max_score]"
    old "Sport"
    new "运动"
    old "PACKS"
    new "档案包"
    old "PACK [pack['num']] - [pack['title']]"
    new "档案包 [pack['num']] - [pack['title']]"
    old "ARGUMENTS  [progress_arguments_done] / [progress_arguments_total]"
    new "论点  [progress_arguments_done] / [progress_arguments_total]"
    old "SUCCÈS  [progress_successes_done] / [progress_successes_total]"
    new "成就  [progress_successes_done] / [progress_successes_total]"
    old "TEST — [STATS_META[name]['label']]"
    new "检定 — [STATS_META[name]['label']]"

    # 由 kd_tr() 渲染的动态数据。
    old "POUR"
    new "赞成"
    old "INCONNU"
    new "未知"
    old "CONTRE"
    new "反对"
    old "Inégalités entre les districts"
    new "各区之间的不平等"
    old "Risque économique"
    new "经济风险"
    old "Les districts n'affrontent ni les mêmes pénuries ni les mêmes chances d'accéder aux biens."
    new "各区面临的短缺不同，获得物资的机会也不平等。"
    old "Entendu lors d'un échange avec Lysa et Elias."
    new "在与 Lysa 和 Elias 的交谈中听到。"
    old "Bons de rationnement"
    new "配给券"
    old "Organisation quotidienne"
    new "日常组织"
    old "Les demandes officielles et les bons structurent déjà l'accès aux biens essentiels."
    new "正式申请和配给券已经决定了基本物资的获取方式。"
    old "Relevé dans la discussion avec Kael."
    new "在与 Kael 的讨论中得知。"
    old "Risque de dépressurisation"
    new "失压风险"
    old "Sécurité"
    new "安全"
    old "Sur Orbite, une sanction qui perce une coque peut condamner tout un module."
    new "在轨道区，击穿外壳的惩罚可能葬送整个舱段。"
    old "Décrit par Kael en salle d'observation."
    new "Kael 在观察室中讲述。"
    old "Dérogations trop complexes"
    new "过于复杂的豁免程序"
    old "Accès administratif"
    new "行政权限"
    old "Obtenir une nourriture originale ou un objet utile exige une dérogation disproportionnée."
    new "获取特别食物或实用物品需要不合比例的豁免手续。"
    old "Découvert en parlant avec Elen à la cafétéria."
    new "在餐厅与 Elen 交谈时发现。"
    old "Valeur du travail"
    new "劳动价值"
    old "Organisation collective"
    new "集体组织"
    old "L'entraide protège chacun, mais elle repose sur la contribution de tous ceux qui peuvent travailler."
    new "互助保护每个人，但也依赖所有有劳动能力者的贡献。"
    old "Expliqué par Sael à partir de la vie de son village."
    new "Sael 以自己村庄的生活为例说明。"
    old "Le monde d'avant"
    new "从前的世界"
    old "Mémoire politique"
    new "政治记忆"
    old "Julian présente l'avant-Kami comme une preuve que la circulation libre peut exister."
    new "Julian 将 Kami 之前的世界视为自由流通可以存在的证明。"
    old "Entendu auprès de Julian avant la cafétéria."
    new "前往餐厅前从 Julian 处听到。"
    old "L'énoncé précis"
    new "准确措辞"
    old "Texte du vote"
    new "投票文本"
    old "La formulation exacte devient décisive : elle engage plus qu'une simple autorisation d'échange."
    new "准确措辞至关重要：其约束远不只是允许交易。"
    old "Déduit pendant la discussion à la cafétéria."
    new "在餐厅讨论期间推断得出。"
    old "Échanges discrets déjà actifs"
    new "秘密交易早已存在"
    old "Réseaux informels"
    new "非正式网络"
    old "Des échanges informels existent déjà. Les nier ne les fait pas disparaître."
    new "非正式交易已经存在。否认并不会让它们消失。"
    old "Observé dans la salle de stockage."
    new "在储藏室观察到。"
    old "Choisissez un argument pour orienter le débat."
    new "选择一个论点来引导辩论。"
    old "Sécurité minimale contre la faim et le chaos."
    new "防止饥饿与混乱的最低保障。"
    old "Dépendance logistique et fragilité structurelle."
    new "后勤依赖与结构脆弱性。"
    old "Texte exact, conséquences juridiques immédiates."
    new "准确文本与直接法律后果。"
    old "Ruptures passées et files de pénurie."
    new "过去的断供与短缺队伍。"
    old "Réseaux d'entraide clandestins déjà en place."
    new "早已存在的地下互助网络。"
    old "Mémoire d'un système ancien imparfait mais vivant."
    new "对一个不完美但仍有活力的旧制度的记忆。"

    old "transport,"
    new "运输、"
    old "la"
    new "该"
    old "et"
    new "以及"
    old "l’échange"
    new "交换"
    old "de"
    new "的"
    old "marchandises."
    new "货物。"
    old "Le"
    new "该"
    old "système"
    new "制度"
    old "actuel"
    new "现行"
    old "distribution"
    new "配给"
    old "denrées"
    new "食品"
    old "est"
    new "将被"
    old "aboli."
    new "废除。"

    old "ENTRAÎNEMENT AUX HALTÈRES"
    new "哑铃训练"
    old "Synchronise ton effort avec la zone verte pour valider chaque répétition."
    new "让发力时机与绿色区域同步，完成每次动作。"
    old "Correct."
    new "不错。"
    old "Raté..."
    new "失误……"
    old "Combo x5"
    new "连击 x5"
    old "Zéro raté"
    new "零失误"
    old "4 frappes parfaites"
    new "4 次完美命中"

    old "LA LIMITE DE TOMAS"
    new "TOMAS 的底线"
    old "Tomas vient de te demander d'arrêter."
    new "Tomas 刚刚要求你停下。"
    old "AUCUN MANDAT"
    new "没有授权"
    old "Personne ne t'a choisi pour les représenter."
    new "没有人选择让你代表他们。"
    old "LE FOND DU TEXTE"
    new "文本实质"
    old "Parler plus fort ne rend pas le texte meilleur."
    new "提高音量并不会让文本变得更好。"
    old "Je veux seulement que ce texte passe."
    new "我只是想让这份文本通过。"
    old "On devrait tous viser la même chose."
    new "我们都应该追求同一个目标。"
    old "Je ne force personne."
    new "我没有强迫任何人。"
    old "Je leur donne seulement un cap."
    new "我只是在给他们指明方向。"
    old "Ils restent libres de me suivre."
    new "他们仍可自由决定是否跟随我。"
    old "Quelqu'un doit transformer cette hésitation"
    new "总得有人把这种犹豫"
    old "en mouvement. J'assume de le faire."
    new "转化为行动。我愿意承担。"
    old "Tomas hésite, c'est tout."
    new "Tomas 只是在犹豫，仅此而已。"
    old "Au fond, il attend que je le guide."
    new "其实，他在等我引导他。"
    old "Je lui évite de rester seul avec son choix."
    new "我让他不必独自面对自己的选择。"
    old "Si je parle en premier au Conclave,"
    new "如果我在议会上率先发言，"
    old "les autres sauront enfin où regarder."
    new "其他人终于会知道该看向哪里。"
    old "Ce n'est pas une question d'ego."
    new "这与自我无关。"
    old "Les indécis m'ont choisi pour les représenter."
    new "犹豫不决的人选择让我代表他们。"
    old "Je ne fais que prendre mes responsabilités."
    new "我只是在承担自己的责任。"
    old "Vous pouvez trouver ma méthode agaçante."
    new "你们可以觉得我的做法很烦人。"
    old "Elle reste plus utile que votre silence."
    new "但它仍比你们的沉默更有用。"
    old "Quand le vote passera, personne ne reprochera"
    new "投票通过后，没有人会责怪"
    old "à Julian d'avoir pris les devants."
    new "Julian 抢先采取行动。"

    old "Représentante n°03 — Velkyn"
    new "第 03 号代表 — Velkyn"
    old "Représentant n°04 — Solen"
    new "第 04 号代表 — Solen"
    old "Représentante n°05 — Orée"
    new "第 05 号代表 — Oree"
    old "Représentant n°06 — Miren"
    new "第 06 号代表 — Miren"
    old "Représentante n°08 — Civitas"
    new "第 08 号代表 — Civitas"
    old "Représentant n°09 — Archive"
    new "第 09 号代表 — Archive"
    old "Représentante n°10 — Aster"
    new "第 10 号代表 — Aster"
    old "Représentant n°11 — Forge"
    new "第 11 号代表 — Forge"
    old "Représentante n°02 — Apex"
    new "第 02 号代表 — Apex"
    old "Représentant n°07 — Limen"
    new "第 07 号代表 — Limen"
    old "Représentante n°12 — Serment"
    new "第 12 号代表 — Serment"
    old "Médiateur — District Harmonie"
    new "调解员 — 和谐区"
    old "Ah, je dois commencer ?? Euh..."
    new "啊，要我先开始吗？呃……"
    old "Abolir la distribution risque de"
    new "废除配给可能会"
    old "condamner les plus fragiles."
    new "让最弱势者陷入绝境。"
    old "Le marché libre va"
    new "自由市场会"
    old "récompenser ceux"
    new "奖励那些"
    old "qui se bougent vraiment."
    new "真正努力的人。"
    old "Ceux qui se bougent, oui."
    new "努力的人，没错。"
    old "Mais ceux qui échouent"
    new "但失败的人"
    old "on les verra aussi."
    new "同样会被看见。"
    old "L’échec existe déjà."
    new "失败本来就存在。"
    old "Au moins là,"
    new "至少这样，"
    old "il aura un sens."
    new "它会有意义。"
    old "J’aime pas vraiment ça."
    new "我不太喜欢这样。"
    old "Mais rester figés,"
    new "但停滞不前，"
    old "j’aime encore moins."
    new "我更不喜欢。"
    old "Statistiquement…"
    new "从统计上看……"
    old "ne rien changer"
    new "什么都不改变"
    old "c’est déjà tout perdre."
    new "就等于失去一切。"
    old "Alors essayons !"
    new "那就试试吧！"
    old "Moi, j’ai envie de voir"
    new "我想看看"
    old "ce que ça peut donner."
    new "结果会怎样。"
    old "Un test mal cadré peut"
    new "设计不当的测试"
    old "coûter plus cher que"
    new "可能比"
    old "ce qu'on connait déjà."
    new "现状付出更高代价。"
    old "Alors cadrons-le."
    new "那就把框架定好。"
    old "Mais ne faisons pas"
    new "但不要"
    old "semblant d’ignorer le reste."
    new "假装看不见其他问题。"
    old "Le reste ?!"
    new "其他问题？！"
    old "Le reste, c’est des vies !"
    new "其他问题关系到人命！"
    old "Pas un foutu paramètre !"
    new "不是什么该死的参数！"
    old "Si on veut protéger des vies,"
    new "如果我们想保护生命，"
    old "il faut tout changer."
    new "就必须改变一切。"
    old "Ca commence par ça."
    new "就从这里开始。"
    old "On doit bouger, oui."
    new "我们必须前进，没错。"
    old "Mais étape par étape."
    new "但要一步一步来。"
    old "Doucement."
    new "慢慢来。"
    old "Je vous l’avais dit."
    new "我早就说过。"
    old "On finit toujours"
    new "到最后，大家总会"
    old "par me rejoindre."
    new "站到我这边。"
    old "Ton besoin d’avoir raison"
    new "你非要证明自己正确"
    old "n’a rien à voir avec"
    new "与"
    old "notre discussion."
    new "我们的讨论毫无关系。"
    old "Je crois bien que"
    new "我想"
    old "nous sommes d’accord."
    new "我们意见一致。"
    old "Il faut du changement."
    new "我们需要改变。"
    old "Kami : Deux minutes. Vous êtes déjà en retard sur mes calculs."
    new "Kami：两分钟。你已经落后于我的计算。"
    old "Kami : 120 secondes, et toujours ce chaos. Charmant."
    new "Kami：120 秒，还是一片混乱。真迷人。"
    old "Kami : Vous sentez la pression ? Moi, j'appelle ça une statistique."
    new "Kami：感到压力了吗？我称之为统计数据。"
    old "Kami : Une minute. J'espère que vous aimez finir dans la panique."
    new "Kami：一分钟。希望你喜欢在慌乱中收尾。"
    old "Kami : 60 secondes. Je lance déjà les paris sur votre échec."
    new "Kami：60 秒。我已经开始下注你会失败。"
    old "Kami : Tic tac. C'est là que les erreurs deviennent irréversibles."
    new "Kami：滴答。错误现在开始变得不可挽回。"
    old "Kami : 30 secondes. Même mes protocoles ont plus de sang-froid."
    new "Kami：30 秒。就连我的协议都比你冷静。"
    old "Kami : Trente secondes. Vous devriez déjà avoir terminé."
    new "Kami：三十秒。你本该已经完成了。"
    old "Kami : Plus que 30 secondes. Essayez de ne pas tout saboter."
    new "Kami：只剩 30 秒。尽量别把一切都搞砸。"
    old "Kami : 10 secondes. Oui, c'est exactement aussi catastrophique que prévu."
    new "Kami：10 秒。没错，灾难程度和预测完全一样。"
    old "Kami : Dix secondes. Respirez... enfin non, perdez plutôt du temps."
    new "Kami：十秒。深呼吸……算了，继续浪费时间吧。"
    old "Kami : 10 secondes. Le stress vous va si bien."
    new "Kami：10 秒。压力真适合你。"
    old "— CONCLAVE —"
    new "— 议会 —"
    old "Day [day_label]"
    new "第 [day_label] 天"
    old "Temps libre"
    new "自由时间"
    old "DIFFUSION"
    new "广播"
    old "DOSSIER DE VOTE"
    new "投票档案"
    old "CHAPITRES"
    new "章节"
    old "COMPLÉTION DU CHAPITRE"
    new "章节完成度"
    old "ARGUMENTS  [arguments_done] / [arguments_total]"
    new "论点  [arguments_done] / [arguments_total]"
    old "SUCCÈS  [successes_done] / [successes_total]"
    new "成就  [successes_done] / [successes_total]"
    old "Le pourcentage réunit les arguments découverts\net les succès liés à ce chapitre."
    new "百分比综合了已发现的论点\n与本章相关的成就。"
    old "SA FORMULATION"
    new "文本措辞"
    old "ARGUMENTS DÉBLOQUÉS"
    new "已解锁论点"
    old "[dossier_prop_unlocked_count(sel_prop)] / [dossier_prop_total(sel_prop)] DÉBLOQUÉS"
    new "已解锁 [dossier_prop_unlocked_count(sel_prop)] / [dossier_prop_total(sel_prop)]"
    old "ⓘ  Les arguments recueillis vous aideront à préparer vos positions et anticiper les votes."
    new "提示：收集的论点能帮助你准备立场并预判投票。"
    old "Obtenu auprès de :"
    new "来源："
    old "Argument non débloqué"
    new "论点未解锁"
    old "Continuez vos discussions, explorez les lieux et observez les autres représentants pour débloquer cet argument."
    new "继续交谈、探索地点并观察其他代表，以解锁此论点。"
    old "VOTE EN COURS"
    new "正在投票"
    old "CHOISISSEZ L’ISSUE DU VOTE"
    new "选择投票结果"
    old "DÉPOUILLEMENT DES VOTES"
    new "计票"
    old "Les votes sont secrets - les résultats seuls comptent."
    new "投票是秘密的 — 只有结果重要。"
    old "AMENDEMENT N°1"
    new "第 1 号修正案"
    old "COMPTAGE DES VOTES"
    new "正在计票"
    old "Bulletin [vote_phase3_tally_index] / [total_votes]"
    new "选票 [vote_phase3_tally_index] / [total_votes]"
    old "BULLETIN DÉPOUILLÉ"
    new "选票已计入"
    old "RÈGLE D’UNANIMITÉ"
    new "全票通过规则"
    old "Si une seule personne vote contre, l’amendement est immédiatement refusé. L’abstention ne bloque pas l’adoption."
    new "只要有一人反对，修正案便立即被否决。弃权不会阻止通过。"
    old "Voix"
    new "票"
    old "FINAL_REPRESENTATIVES = (\"NOAM\", \"LYSA\")\n\nfunction generate_displayed_names:\n    decoys = shuffle(HARMONIE.citizens)\n    return animate(decoys)\n\nfunction accept_player_input(click):\n    stop_animation()\n    reveal(FINAL_REPRESENTATIVES)\n\n// La liste déroulante n'est qu'une façade.\n// Sélection terminée avant le début de la séance."
    new "FINAL_REPRESENTATIVES = (\"NOAM\", \"LYSA\")\n\nfunction generate_displayed_names:\n    decoys = shuffle(HARMONIE.citizens)\n    return animate(decoys)\n\nfunction accept_player_input(click):\n    stop_animation()\n    reveal(FINAL_REPRESENTATIVES)\n\n// 滚动名单只是伪装。\n// 选拔在会议开始前就已完成。"
    old "CODEX"
    new "档案库"
    old "PHASE 3/3"
    new "阶段 3/3"
