translate chinese strings:

    # 修正案草稿小游戏（由 Python 数据生成的文本）。
    old "Toute personne"
    new "任何人"
    old "doit"
    new "必须"
    old "intervenir"
    new "介入"
    old "lorsqu'une autre personne"
    new "当另一人"
    old "est en danger."
    new "处于危险时。"
    old "immédiatement"
    new "立即"
    old "peut"
    new "可以"
    old "s'il l'ose"
    new "如果有勇气"
    old "porter assistance"
    new "提供帮助"
    old "après autorisation"
    new "获得许可后"
    old "si nécessaire"
    new "如有必要"
    old "à une autre personne"
    new "给另一人"
    old "quand c'est permis"
    new "在获准时"
    old "peut-être"
    new "也许"
    old "en danger"
    new "处于危险中"
    old "sans autorisation préalable."
    new "无需事先许可。"
    old "dans la limite"
    new "在限度内"
    old "sauf refus"
    new "除非遭到拒绝"
    old "si toléré"
    new "如果被容许"

    old "« Toute personne doit intervenir lorsqu'une autre personne est en danger. »"
    new "“当他人处于危险中时，任何人都必须介入。”"
    old "Doit. Une obligation. Je force la main de tout le monde, d'un seul mot."
    new "必须。一项义务。只用一个词，我就强迫所有人行动。"
    old "Et si quelqu'un intervient mal ? Si à cause de « doit », on condamne celui qui a hésité ?"
    new "如果有人介入不当呢？如果因为“必须”二字，我们惩罚了那个犹豫的人呢？"
    old "Non. « Doit », c'est trop. Ça punit autant que ça protège."
    new "不。“必须”太过了。它带来的惩罚和保护一样多。"
    old "Le mot part. La trace, elle, reste."
    new "词被擦掉了，痕迹却还在。"
    old "« Immédiatement »... et si c'est trop tard pour bien faire ? Je le retire."
    new "“立即”……如果已经来不及把事情做好呢？删掉。"
    old "« ...peut intervenir... »"
    new "“……可以介入……”"
    old "Intervenir. Ça sonne comme se jeter dans le feu. Comme un héros."
    new "介入。听起来像是纵身跳进火里，像个英雄。"
    old "Personne n'est un héros, ici. On lira ça comme le droit de tout casser au nom du secours."
    new "这里没人是英雄。人们会把它理解成能以救援为名破坏一切。"
    old "Encore un mot rayé. La phrase respire un peu moins fort."
    new "又划掉一个词。这句话的呼吸又轻了一些。"
    old "« S'il l'ose »... je ne vais pas leur demander du courage en plus. Non."
    new "“如果有勇气”……我不能还要求他们必须勇敢。不。"
    old "« ...peut porter assistance lorsqu'une autre personne est en danger. »"
    new "“……当他人处于危险中时，可以提供帮助。”"
    old "« Lorsque ». Comme s'il fallait attendre le bon moment. Attendre l'autorisation du danger lui-même."
    new "“当……时。”好像必须等待正确时机，等待危险本身批准。"
    old "J'ajoute « après autorisation », machinalement. Ma main écrit ce que la peur dicte."
    new "我下意识加上“获得许可后”。我的手写下了恐惧的命令。"
    old "...Non. Si on attend l'autorisation, la personne est déjà par terre. Je barre ça aussi."
    new "……不。如果等到许可下来，那个人早已倒地。我也划掉它。"
    old "Trop de conditions. Chaque condition est une porte pour dire non."
    new "条件太多。每个条件都是一扇可以说“不”的门。"
    old "Je gomme la condition. Mes doigts sont gris."
    new "我擦掉这个条件。手指已经变灰。"
    old "« Après autorisation ». Voilà. C'est exactement le mot qui tue les gens poliment. Dehors."
    new "“获得许可后。”就是这样。这种词能礼貌地害死人。删掉。"
    old "« Si nécessaire », qui décide de ça ? Pas moi. Je l'écarte."
    new "“如有必要”，由谁决定？不是我。删掉。"
    old "« ...porter assistance à une autre personne est en danger. »"
    new "“……给另一人提供帮助处于危险中。”"
    old "Ça se lit de travers, maintenant. Tant pis, personne ne relira ma calligraphie."
    new "现在读起来不通顺。算了，没人会重读我的字。"
    old "« Est en danger. » Lourd. Je veux juste : en danger. Court. Qu'on ne puisse pas l'esquiver."
    new "“处于危险时。”太累赘。我只要：处于危险中。简短，无法回避。"
    old "La feuille est presque illisible. Moi aussi."
    new "纸上的字几乎无法辨认。我也一样。"
    old "« Quand c'est permis »... et si ça ne l'est jamais ? Je raye."
    new "“在获准时”……如果永远不获准呢？划掉。"
    old "« Peut-être ». Le mot le plus lâche que je connaisse. Dehors."
    new "“也许。”我所知道最懦弱的词。删掉。"
    old "« Toute personne peut porter assistance à une autre personne en danger sans autorisation préalable. »"
    new "“任何人都可以在无需事先许可的情况下帮助处于危险中的他人。”"
    old "Voilà. C'est laid. C'est raturé. Mais ça tient debout."
    new "好了。很难看，满是涂改，但它站得住脚。"
    old "« Dans la limite »... la limite de quoi ? Non."
    new "“在限度内”……什么的限度？不。"
    old "« Sauf refus ». Toujours une porte de sortie. Je n'en veux plus."
    new "“除非遭到拒绝。”总要留一条退路。我不想再留了。"
    old "« Si toléré ». Non. Plus de permission à mendier."
    new "“如果被容许。”不。别再乞求许可。"
    old "Alors. Ma phrase. Une seule ligne, et qu'on n'en parle plus."
    new "好。我的句子。只写一行，然后再也不提。"
    old "Les mots sont là, éparpillés autour. Fais-les glisser sur la feuille pour former une phrase."
    new "词语散落在周围。把它们拖到纸上，组成一个句子。"
    old "Déjà ? Mes mains vont plus lentement que cette horloge."
    new "已经到了？我的手比这只钟还慢。"
    old "Ma main cherche la gomme toute seule. Attrape-la, frotte le mot cerclé jusqu'à ce qu'il disparaisse."
    new "我的手自己伸向橡皮。抓住它，擦掉圈出的词，直到它消失。"
    old "Je pourrais encore. Enlever « sans autorisation ». Trouver plus doux, plus prudent."
    new "我还可以继续。删掉“无需许可”，换成更温和、更谨慎的说法。"
    old "Continuer jusqu'à ce que la phrase ne veuille plus rien dire. Jusqu'à ce qu'elle ne gêne plus personne."
    new "继续改，直到这句话毫无意义，直到它再也不会冒犯任何人。"
    old "La gomme est déjà dans ma main."
    new "橡皮已经在我手里。"
    old "Non."
    new "不。"
    old "Je pose la gomme."
    new "我放下橡皮。"
    old "Pour une fois, je n'efface pas."
    new "这一次，我不擦掉。"
    old "Je repose la gomme sans m'en servir."
    new "我没有使用橡皮，把它放下了。"
    old "Je plie la feuille en deux. De travers, évidemment."
    new "我把纸对折。当然，折歪了。"

    old "Ecoute chaque argument"
    new "听完每个论点"
    old "Chaque participant parle quelques secondes. La barre jaune indique le temps disponible."
    new "每位参与者会发言几秒。黄色进度条显示剩余时间。"
    old "Interviens avec discernement"
    new "谨慎介入"
    old "Le buzzer sert a prendre la parole quand Noam apporte un vrai eclairage, pas a contredire tout le monde."
    new "只有当 Noam 能提出真正有价值的观点时才按下抢答器，而不是为了反驳所有人。"
    old "Reste coherent"
    new "保持一致"
    old "Multiplier les objections affaiblit Noam : l'assemblee juge aussi la coherence de tes interventions."
    new "过多异议会削弱 Noam：议会也会评判你每次发言是否前后一致。"

    old "VOTE POUR"
    new "投赞成票"
    old "ABSTENTION"
    new "弃权"
    old "VOTE CONTRE"
    new "投反对票"
    old "Changer les règles"
    new "修改规则"
    old "Laisser le système trancher"
    new "交由系统裁定"
    old "Maintenir le cadre"
    new "维持现行框架"
    old "En attente du premier bulletin..."
    new "等待第一张选票……"
    old "Dépouillement en cours..."
    new "正在计票……"
    old "Amendement refusé : au moins un vote contre."
    new "修正案被否决：至少有一票反对。"
    old "Amendement adopté : aucun vote contre."
    new "修正案通过：没有反对票。"
