translate chinese strings:

    old "Couloir de la cafétéria"
    new "食堂走廊"
    old "Couloir du dortoir"
    new "宿舍走廊"
    old "Couloir de l'infirmerie"
    new "医务室走廊"
    old "Couloir de maintenance"
    new "维护区走廊"
    old "Couloir du SAS"
    new "气闸走廊"
    old "Exploration libre"
    new "自由探索"
    old "Accès indisponible"
    new "无法访问"
    old "Parler à Elen"
    new "与 Elen 交谈"
    old "Parler à Tomas"
    new "与 Tomas 交谈"
    old "Parler à Julian"
    new "与 Julian 交谈"
    old "Parler à Mara et Sael"
    new "与 Mara 和 Sael 交谈"
    old "Parler à Lysa et Elias"
    new "与 Lysa 和 Elias 交谈"
    old "Parler à Sael"
    new "与 Sael 交谈"
    old "Règlement du Conclave"
    new "议会规则"
    old "Représentant — Conclave"
    new "代表 — 议会"
    old "Entrer dans la cafétéria"
    new "进入食堂"
    old "Entrer dans la salle du canon"
    new "进入巨炮室"
    old "Entrer dans l'observatoire"
    new "进入观测室"
    old "Entrer dans la salle de repos"
    new "进入休息室"
    old "Aller vers le dortoir"
    new "前往宿舍"
    old "Aller vers la maintenance"
    new "前往维护区"
    old "Entrer dans la salle d'archive"
    new "进入档案室"
    old "Entrer dans le Conclave"
    new "进入议会"
    old "Entrer dans le dortoir"
    new "进入宿舍"
    old "Aller vers la cafétéria"
    new "前往食堂"
    old "Aller vers l'infirmerie"
    new "前往医务室"
    old "Entrer dans le gymnase"
    new "进入健身房"
    old "Entrer dans l'infirmerie"
    new "进入医务室"
    old "Aller vers le SAS"
    new "前往气闸"
    old "Entrer dans la maintenance"
    new "进入维护区"
    old "Entrer dans le SAS de livraison"
    new "进入货运气闸"
    old "Entrer dans la salle de stockage"
    new "进入仓库"
