translate chinese strings:

    old "TUTORIEL"
    new "教程"
    old "{} ANS"
    new "{}岁"
    old "%d / 5 tris"
    new "%d / 5 次分类"
    old "Le pain va tomber de mon côté."
    new "面包要掉到我这边了。"
    old "Quelqu'un peut me passer l'eau avant que Julian négocie avec elle ?"
    new "谁能在朱利安开始和水谈判前把它递给我？"
    old "La ration chaude, avant qu'elle devienne un concept."
    new "把热口粮给我，趁它还没变成一个概念。"
    old "Laisse une part au centre. On va éviter le drame diplomatique."
    new "在中间留一份。免得发生外交事故。"
    old "Iris lève son verre comme si elle venait de fonder un pays."
    new "伊里斯举起杯子，仿佛刚刚建立了一个国家。"
    old "Le nom de Kami aspire l'air autour de la table."
    new "卡米的名字抽走了餐桌周围的空气。"
    old "Julian prend l'attaque comme une promotion."
    new "朱利安把挖苦当成了升职。"
    old "La prudence est juste. Elle est aussi lourde."
    new "谨慎是对的，也同样沉重。"
    old "Les verres se lèvent. Le silence devient presque une présence invitée."
    new "杯子纷纷举起。沉默几乎成了一位受邀的客人。"
    old "Julian proteste trop vite pour être crédible."
    new "朱利安抗议得太快，毫无说服力。"
    old "La règle est simple. Tout le monde l'accepte."
    new "规则很简单。所有人都接受了。"
    old "Lysa te regarde, puis accepte cette petite désobéissance."
    new "莉莎看着你，然后接受了这小小的反抗。"
    old "La table retombe dans le réel."
    new "餐桌重新跌回现实。"
    old "Mauvaise image. Les épaules se tendent."
    new "糟糕的画面。众人的肩膀绷紧了。"
    old "Julian mime une blessure politique grave."
    new "朱利安表演出遭受严重政治伤害的样子。"
    old "Il se redresse comme si c'était sérieux. C'est ce qui sauve la blague."
    new "他一本正经地坐直了。正因如此，笑话才得救。"
    old "Le repas continue. Sans éclat, mais sans casse."
    new "用餐继续。没有亮点，也没有事故。"
    old "La formule lui arrache presque un sourire."
    new "这句话几乎让她露出微笑。"
    old "Elle te laisse faire. C'est déjà un accord."
    new "她任由你去做。这已经算是同意。"
    old "Elle se ferme aussitôt. Mauvais angle."
    new "她立刻封闭了自己。角度错了。"
    old "Pendant une minute, personne ne dit son nom."
    new "一分钟里，没有人提起她的名字。"
    old "La table respire encore un peu."
    new "餐桌又呼吸了一会儿。"
    old "La blague tient juste assez longtemps pour devenir utile."
    new "这个笑话撑得刚好够久，终于有了用处。"
    old "Le calme reste là, moins brillant, mais intact."
    new "平静仍在，虽然不再明亮，却完好无损。"
    old "Le calme se fend. Pas beaucoup. Assez."
    new "平静裂开了。不多，但足够。"
    old "NORD"
    new "北"
    old "SUD"
    new "南"
    old "EST"
    new "东"
    old "OUEST"
    new "西"
    old "{} // VALEUR {} SÉLECTIONNÉE"
    new "{} // 已选择数值 {}"
    old "{} // CALIBRATION REFUSÉE — SIGNAL INSTABLE"
    new "{} // 校准被拒——信号不稳定"
    old "{} // FLUX STABILISÉ"
    new "{} // 数据流已稳定"

    old "SYSTEM"
    new "系统"
    old "KAMI.CORE  /  INTERFACE LOCALE"
    new "KAMI.CORE  /  本地界面"
    old "NAVIGATION  ↑ ↓   //   CONFIRMER  ENTRÉE"
    new "导航  ↑ ↓   //   确认  回车"
    old "KAMI.CORE // DOSSIERS DES REPRÉSENTANTS"
    new "KAMI.CORE // 代表档案"
    old "REPRÉSENTANT·E DE"
    new "代表辖区："
    old "GARDE-ROBE"
    new "衣柜"
    old "Les choix équipés sont sauvegardés de façon permanente et appliqués aux sprites en jeu."
    new "已装备的选择会永久保存并应用于游戏角色立绘。"
    old "TENUES"
    new "服装"
    old "VERROUILLÉE — disponible dans la Boutique"
    new "未解锁——可在商店获得"
    old "ÉQUIPÉE"
    new "已装备"
    old "ÉQUIPER"
    new "装备"
    old "ACCESSOIRES"
    new "配饰"
    old "VERROUILLÉ — disponible dans la Boutique"
    new "未解锁——可在商店获得"
    old "RETIRER"
    new "卸下"
    old "FERMER"
    new "关闭"
    old "Médiateur"
    new "调解员"
    old "Habitante"
    new "居民"
    old "Habitant"
    new "居民"
    old "Ouvrier"
    new "工人"
    old "Archiviste"
    new "档案员"
    old "Ingénieur"
    new "工程师"
    old "Gardien"
    new "守卫"
    old "Harmonie"
    new "和谐区"
    old "Axiome"
    new "公理区"
    old "Archive"
    new "档案区"
    old "Orbite"
    new "轨道区"
    old "Limen"
    new "边界区"
    old "14 avril"
    new "4月14日"
    old "3 septembre"
    new "9月3日"
    old "19 janvier"
    new "1月19日"
    old "27 juin"
    new "6月27日"
    old "8 novembre"
    new "11月8日"
    old "22 février"
    new "2月22日"
    old "5 octobre"
    new "10月5日"
    old "16 mai"
    new "5月16日"
    old "30 décembre"
    new "12月30日"
    old "11 août"
    new "8月11日"
    old "7 mars"
    new "3月7日"
    old "24 juillet"
    new "7月24日"
    old "Comprendre avant de trancher."
    new "先理解，再裁决。"
    old "Une promesse sans procédure n'est qu'un bruit."
    new "没有程序的承诺只是噪音。"
    old "Tenir, c'est déjà gagner du temps."
    new "坚持本身就是在争取时间。"
    old "Un repas stable vaut mieux qu'un grand discours."
    new "一顿稳定的饭胜过宏大的演说。"
    old "Les chiffres mentent moins que nous."
    new "数字比我们更少说谎。"
    old "Le silence est aussi un signal."
    new "沉默也是一种信号。"
    old "Si ce n'est pas consigné, c'est déjà perdu."
    new "没有记录，就已经失去。"
    old "On compte les vivants, pas les slogans."
    new "我们清点活人，不清点口号。"
    old "On ne négocie pas avec une turbine en panne."
    new "不能和坏掉的涡轮谈判。"
    old "Le cadre protège de l'arbitraire."
    new "规则使我们免受恣意妄为。"
    old "Le danger n'attend pas les votes."
    new "危险不会等待投票。"
    old "Je vois ce qui entre. Et ce qui disparaît."
    new "我看见什么进来。也看见什么消失。"
    old "ÉCLATS DE DÉSIR"
    new "欲望碎片"
    old "IRIS : TENUE 2"
    new "IRIS：服装 2"
    old "RYN : TENUE 2"
    new "RYN：服装 2"
    old "LYSA : ACCESSOIRE 1"
    new "LYSA：配饰 1"
    old "PRÉVISUALISER"
    new "预览"
    old "OBTENU"
    new "已获得"
    old "OBTENIR"
    new "获取"
    old "RÉQUISITIONS DE KAMI"
    new "卡米征用处"
    old "OFFRES TEMPORAIRES"
    new "限时商品"
    old "CODE PROMO"
    new "兑换码"
    old "FIN DANS 06 J 14 H"
    new "06天14小时后结束"
    old "Les réquisitions non obtenues disparaîtront à la fin du cycle."
    new "未获得的征用物品将在周期结束时消失。"
    old "PRÉVISUALISATION"
    new "预览"
    old "Corps, bras, bouche et yeux sont tirés au hasard. La tenue ou l'accessoire sélectionné reste fixe."
    new "身体、手臂、嘴和眼睛将随机组合，所选服装或配饰保持不变。"
    old "ALÉATOIRE"
    new "随机"
    old "Saisissez un code pour créditer des récompenses persistantes."
    new "输入兑换码以领取永久奖励。"
    old "VALIDER"
    new "确认"
    old "Réquisition introuvable"
    new "找不到该征用项目"
    old "Objet déjà obtenu"
    new "已获得该物品"
    old "Éclats de désir insuffisants"
    new "欲望碎片不足"
    old "Réquisition validée"
    new "征用成功"
    old "{}{} Éclats de désir"
    new "{}{} 欲望碎片"
    old "+{} Éclats de désir"
    new "+{} 欲望碎片"
    old "Encore humain"
    new "仍是人类"
    old "Un hasard bien cadré"
    new "恰到好处的巧合"

    old "Je termine de ranger les caisses."
    new "我把箱子整理完。"
    old "Puis je me rends à la cafétéria."
    new "然后我前往食堂。"
    old "Le repas se déroule sans accroc pendant de longues minutes."
    new "接下来的很长一段时间里，用餐顺利进行。"
    old "Une bonne heure plus tard"
    new "一个多小时后"
    old "Après m'être longuement calmé"
    new "花了很久平静下来后"
    old "Après plusieurs heures"
    new "几个小时后"
    old "Début du chapitre 2"
    new "第2章开始"
    old "Fin du chapitre 2"
    new "第2章结束"

    old "CAFÉTÉRIA"
    new "食堂"
    old "INFIRMERIE"
    new "医务室"
    old "STOCKAGE"
    new "仓库"
    old "STOCKAGE • BONUS"
    new "仓库 • 奖励"
    old "ATTRAPEZ"
    new "抓取"
    old "Cliquez et maintenez un objet qui défile sur le tapis."
    new "点击并按住传送带上移动的物品。"
    old "TRIEZ"
    new "分类"
    old "Glissez-le au-dessus de la caisse correspondant à sa catégorie."
    new "将物品拖到对应类别的箱子上方。"
    old "ACCÉLÉREZ"
    new "加速"
    old "Cinq tris justes d'affilée accélèrent le tapis et donnent +5."
    new "连续正确分类五次会加快传送带并获得+5。"
    old "BONUS"
    new "奖励"
    old "Les objets de stockage sont plus rares et valent 0 point."
    new "仓库物品更稀有，但价值0分。"
    old "TRI DES LIVRAISONS"
    new "配送分类"
    old "MINI-JEU  •  TRI DES LIVRAISONS"
    new "小游戏  •  配送分类"
    old "ATTRAPEZ • GLISSEZ • DÉPOSEZ AU-DESSUS DE LA BONNE CAISSE"
    new "抓取 • 拖动 • 放到正确箱子上方"
    old "SCORE CALCULÉ"
    new "计算得分"
    old "SÉRIE"
    new "连击"
    old "CADENCE"
    new "节奏"
    old "DÉFILEMENT  >>>"
    new "传送  >>>"
    old "RÈGLES"
    new "规则"
    old "• Bonne caisse :  +1 point\n• Mauvaise caisse :  -1 point et cadence -1\n• Stockage correct :  0 point\n• 5 tris justes : cadence +1\n• Score : points × cadence"
    new "• 正确箱子：+1分\n• 错误箱子：-1分且节奏-1\n• 正确仓库：0分\n• 连续正确5次：节奏+1\n• 得分：分数×节奏"
    old "BILAN EN DIRECT"
    new "实时统计"
    old "Corrects"
    new "正确"
    old "Erreurs"
    new "错误"
    old "Bonus neutres"
    new "中性奖励"
    old "Objets passés"
    new "错过物品"
    old "PROCHAINE ACCÉLÉRATION"
    new "下次加速"
    old "REPRENDRE"
    new "继续"
    old "PAUSE"
    new "暂停"
    old "TRI EN PAUSE"
    new "分类已暂停"
    old "Le chronomètre et le tapis sont arrêtés."
    new "计时器和传送带均已停止。"
    old "STOCKAGE BONUS  •  +0"
    new "仓库奖励  •  +0"
    old "TRI CORRECT  •  +1"
    new "分类正确  •  +1"
    old "ACCÉLÉRATION  •  MULTIPLICATEUR x%.2f"
    new "加速  •  倍率 x%.2f"
    old "ERREUR  •  -1 POINT  •  CADENCE -1"
    new "错误  •  -1分  •  节奏-1"
    old "MAUVAISE CAISSE  •  -1 POINT"
    new "错误箱子  •  -1分"
    old "Points bruts"
    new "基础分"
    old "Multiplicateur final"
    new "最终倍率"
    old "Score final"
    new "最终得分"
    old "Tris corrects"
    new "正确分类"
    old "Meilleure série"
    new "最高连击"
    old "Aucune erreur"
    new "零失误"
    old "Atteindre la cadence x1.42"
    new "达到x1.42节奏"

    old "PLATEAU EN CIRCULATION"
    new "托盘传递中"
    old "Le plateau a survécu au repas."
    new "托盘挺过了这顿饭。"
    old "Pain"
    new "面包"
    old "Eau"
    new "水"
    old "Ration"
    new "口粮"
    old "Partage"
    new "分享"
    old "sec"
    new "干"
    old "stable"
    new "稳定"
    old "chaud"
    new "热"
    old "centre"
    new "中央"
    old "ton"
    new "语气"
    old "piste"
    new "轨道"
    old "Rythme de table"
    new "餐桌节奏"
    old "Ratés [j701_plate_errors]"
    new "失误 [j701_plate_errors]"
    old "Le plateau glisse de main en main. Suis la demande avant que la conversation déraille."
    new "托盘在人与人之间传递。在谈话失控前按要求行动。"
    old "Bon geste. Le repas continue sans accroc."
    new "动作正确。用餐顺利继续。"
    old "Mauvais objet. Quelqu'un rattrape le plateau au dernier moment."
    new "物品错误。有人在最后一刻接住了托盘。"
    old "Trop lent. La demande se perd dans le bruit de la table."
    new "太慢了。请求淹没在餐桌的嘈杂声中。"
    old "DISCUSSION"
    new "讨论"
    old "Table"
    new "餐桌"
    old "blague"
    new "玩笑"
    old "relance"
    new "接话"
    old "calme"
    new "冷静"
    old "partage"
    new "分享"
    old "chemin"
    new "路径"
    old "Réponds vite. Trop hésiter, c'est déjà laisser le malaise entrer."
    new "尽快回答。犹豫太久，尴尬就已经乘虚而入。"
    old "Noam hésite. La table continue sans lui, un peu moins légère."
    new "诺亚姆犹豫了。餐桌上的谈话没有等他，气氛也沉重了一点。"
    old "Je veux que ça DUUURE... Si on a enfin une journée sans voix divine, je refuse qu'on la passe à fixer les murs."
    new "我想让这一天持——续下去……好不容易没有神圣之声，我才不要把时间花在盯着墙上。"
    old "Alors impose une minute de fête officielle."
    new "那就宣布一分钟正式庆祝。"
    old "Tu crois vraiment qu'elle est partie ?"
    new "你真的觉得她离开了吗？"
    old "Julian peut faire le discours, il adore s'écouter."
    new "让朱利安来演讲吧，他最爱听自己说话。"
    old "On devrait quand même rester prudents."
    new "我们还是应该保持警惕。"
    old "Minute de fête officielle ? J'aime. Il nous faut un rituel idiot, tout de suite."
    new "一分钟正式庆祝？我喜欢。我们现在就需要一个蠢仪式。"
    old "Lever les verres à la santé du silence."
    new "为沉默的健康举杯。"
    old "Déclarer Julian mascotte temporaire."
    new "宣布朱利安为临时吉祥物。"
    old "Proposer une minute sans parler de Kami."
    new "提议一分钟内不谈卡米。"
    old "Partie ? Non. C'est justement ça qui me gêne. Elle ne disparaît pas. Elle attend."
    new "离开？不。正因如此我才不安。她不会消失。她只会等待。"
    old "Alors on lui vole six minutes."
    new "那我们就从她手里偷走六分钟。"
    old "Tu as raison, ça sent mauvais."
    new "你说得对，情况不妙。"
    old "Peut-être qu'elle nous écoute paniquer."
    new "也许她正在听我们恐慌。"
    old "Je peux improviser un discours historique. Court, brillant, indispensable."
    new "我可以即兴发表一段历史性演说。简短、精彩、不可或缺。"
    old "Trois mots maximum."
    new "最多三个词。"
    old "Vas-y, président de la table."
    new "来吧，餐桌主席。"
    old "Non. On mange."
    new "不。吃饭。"
    old "Merci. Je sais que je casse l'ambiance, mais je n'arrive pas à trouver ça normal."
    new "谢谢。我知道自己在破坏气氛，但我无法觉得这很正常。"
    old "Tu ne casses rien. Tu vérifies les murs."
    new "你没有破坏什么。你只是在检查墙壁。"
    old "Alors laisse-moi casser l'ambiance à ta place."
    new "那就让我替你破坏气氛。"
    old "Tu stresses pour rien."
    new "你在瞎担心。"
    old "CANON // SYNCHRONISATION DES FLUX"
    new "加农 // 流同步"
    old "Isole la dernière valeur stable de chaque flux régional."
    new "找出各区域数据流最后的稳定值。"
    old "SIGNAL MONDIAL INSTABLE"
    new "全球信号不稳定"
    old "SIGNAL MONDIAL STABILISÉ"
    new "全球信号已稳定"
    old "SIGNAL PARTIEL // %d / 4"
    new "部分信号 // %d / 4"
    old "FLUX STABILISÉ"
    new "数据流已稳定"
    old "CALIBRER"
    new "校准"
    old "ANALYSE TERMINÉE"
    new "分析完成"
    old "EXÉCUTIONS RECENSÉES — DERNIÈRES 24 HEURES"
    new "已记录处决——过去24小时"
    old "TOTAL MONDIAL : 0"
    new "全球总数：0"
    old "DERNIÈRE EXÉCUTION ENREGISTRÉE : HIER — 18 H 42"
    new "最后记录的处决：昨天——18:42"
    old "QUITTER LE CANON"
    new "退出加农系统"
    old "Stabilise chaque flux pour reconstituer le bilan mondial."
    new "稳定每条数据流，以重建全球报告。"
    old "[j701_console_locked_count()] / 4 FLUX STABILISÉS"
    new "[j701_console_locked_count()] / 4 条数据流已稳定"
    old "NETTOYER LE BUREAU"
    new "清理桌面"
    old "Balaye les particules avant qu'elles se multiplient. Le dessin n'apparaît nulle part."
    new "在粒子增殖前将其扫除。图画完全没有显现。"
    old "Nettoyé [j701_clean_score]/12"
    new "已清理 [j701_clean_score]/12"
    old "Trace révélée"
    new "痕迹显现"
    old "Balaye les poussières avant qu'elles se multiplient."
    new "在灰尘增殖前将其扫除。"
    old "La poussière éclate en silence."
    new "灰尘无声地散开。"
    old "Le parasite se désagrège sous le balai."
    new "干扰在扫帚下瓦解。"
    old "La poussière se divise. Le bureau refuse de rester propre."
    new "灰尘不断分裂。桌面拒绝保持干净。"

    old "PHASE D'ENQUÊTE"
    new "调查阶段"
    old "5 TOURS  /  10 PISTES  /  UNE SEULE NUIT"
    new "5回合  /  10条线索  /  只有一夜"
    old "Choisis où consacrer ton temps. Les pistes abandonnées seront perdues."
    new "选择如何分配时间。放弃的线索将会消失。"
    old "DOSSIER 07-A  //  CHOISIR UN LIEU"
    new "档案 07-A  //  选择地点"
    old "LE CONTENU DES SALLES RESTE INCONNU TANT QUE TU NE L'EXAMINES PAS"
    new "检查房间前，其内部情况始终未知"
    old "TOUR [j701_investigation_turn + 1] / [J701_INVESTIGATION_MAX_TURNS]"
    new "回合 [j701_investigation_turn + 1] / [J701_INVESTIGATION_MAX_TURNS]"
    old "Entrer dans une salle est gratuit. Seul un indice collecté consomme un tour."
    new "进入房间不消耗回合，只有收集线索才会消耗一回合。"
    old "<  RETOUR AU PLAN"
    new "<  返回地图"
    old "FRAGMENT DE PREUVE OBTENU"
    new "已获得证据碎片"
    old "DOSSIER PROVISOIRE"
    new "临时档案"
    old "5 fragments récupérés  //  5 pistes abandonnées"
    new "已取得5份碎片  //  已放弃5条线索"
    old "REJOINDRE LE DÉBRIEF  >"
    new "前往总结会议  >"
    old "POINT D'INTÉRÊT"
    new "个调查点"
    old "POINTS D'INTÉRÊT"
    new "个调查点"
    old "PLUS RIEN À EXAMINER"
    new "没有可检查内容"
    old "Reprendre les témoignages"
    new "复核证词"
    old "Reconstituer le prélèvement"
    new "还原取走过程"
    old "Chercher ce qui a été fabriqué"
    new "寻找被制造的物品"
    old "Interroger les images"
    new "审查影像"
    old "SAS DE LIVRAISON"
    new "配送气闸"
    old "Suivre le trajet du matériel"
    new "追踪设备路线"
    old "Interroger Elias"
    new "询问埃利亚斯"
    old "Examiner la table"
    new "检查桌子"
    old "Inspecter les emplacements vides"
    new "检查空位"
    old "Consulter le boîtier de porte"
    new "查看门禁终端"
    old "Regarder sous l'établi"
    new "查看工作台下方"
    old "Étudier le plan de travail"
    new "检查工作台面"
    old "Surprendre Kael"
    new "突击询问凯尔"
    old "Accéder aux logs de sécurité"
    new "访问安全日志"
    old "Suivre les marques"
    new "追踪痕迹"
    old "Écouter le terminal"
    new "监听终端"
    old "LA DERNIÈRE VISITE"
    new "最后一次到访"
    old "Elias a manipulé les quatre objets hier soir. À 23 h 47, ils étaient encore tous à leur place."
    new "埃利亚斯昨晚接触过全部四件物品。23:47时，它们仍在原位。"
    old "LA GRUE D'ARGENT"
    new "银鹤"
    old "Un origami en emballage de ration était pris dans une roue du chariot. Elen en plie souvent, mais les laisse sur toutes les tables."
    new "一只用口粮包装折成的纸鹤卡在推车轮中。艾伦经常折纸鹤，但会把它们留在各张桌上。"
    old "LE POIDS FANTÔME"
    new "幽灵重量"
    old "Les batteries ont été remplacées par des poches d'eau du même poids afin de tromper le capteur de l'étagère."
    new "电池被换成同等重量的水袋，以欺骗货架传感器。"
    old "LE REÇU SANS NOM"
    new "无名收据"
    old "Le terminal a bien autorisé un retrait à 02 h 14, mais la case réservée à l'identité contient seulement un caractère impossible."
    new "终端确实在02:14批准了取用，但身份栏中只有一个无法识别的字符。"
    old "LE CHEVEU COUPÉ"
    new "被剪断的头发"
    old "Un cheveu brun et assez court était coincé dans l'établi. Son extrémité est tranchée net et il ne porte aucune racine."
    new "一根较短的棕色头发卡在工作台中。末端切口整齐，而且没有发根。"
    old "LE PLAN EN NÉGATIF"
    new "负片蓝图"
    old "La limaille magnétique dessine la silhouette d'un adaptateur fabriqué ici, emporté ensuite, et dont le plan a été soigneusement effacé."
    new "磁性铁屑勾勒出一个曾在此制造并被带走的适配器轮廓，而它的蓝图已被仔细删除。"
    old "LA REQUÊTE DE KAEL"
    new "凯尔的查询"
    old "Kael tente seul d'entrer dans la base des caméras et masque sa requête lorsque Noam approche."
    new "凯尔独自尝试进入摄像头数据库，并在诺亚姆靠近时隐藏了查询。"
    old "LE LOG DE 02 H 34"
    new "02:34日志"
    old "Les logs de sécurité indiquent que la porte de la maintenance s'est ouverte à 02 h 34, sans enregistrer l'identité de l'utilisateur."
    new "安全日志显示维修室的门在02:34开启，但没有记录使用者身份。"
    old "LES TRACES VERTICALES"
    new "垂直痕迹"
    old "Les marques du chariot quittent le sol et continuent sur une porte. La cargaison a été fixée à un plateau magnétique."
    new "推车痕迹离开地面并延伸到门上。货物曾固定在磁性平台上。"
    old "L'ÉCHO IMPOSSIBLE"
    new "不可能的回声"
    old "Le micro du sas a enregistré deux bips de la même porte séparés de sept secondes, alors que son verrou exige douze secondes."
    new "气闸麦克风录到同一扇门间隔七秒的两次提示音，但门锁需要十二秒才能再次开启。"
