translate chinese strings:

    old "Tous"
    new "全部"
    old "Jours"
    new "日期"
    old "Votes"
    new "投票"
    old "Routes"
    new "路线"
    old "Scènes importantes"
    new "重要场景"
    old "Développement / Debug"
    new "开发 / 调试"
    old "En cours"
    new "进行中"
    old "Terminé"
    new "已完成"
    old "Accès autorisé"
    new "允许访问"
    old "Nœud narratif verrouillé"
    new "剧情节点已锁定"
    old "Données non découvertes"
    new "未发现的数据"
    old "Statut inconnu"
    new "未知状态"
    old "Kami refuse l'accès à ce fragment. Continuez la chronologie pour l'identifier."
    new "Kami 拒绝访问此片段。请继续推进时间线以识别它。"
    old "Résumé à compléter."
    new "摘要待补充。"
    old "En cours / disponible"
    new "进行中 / 可访问"
    old "Route alternative"
    new "其他路线"
    old "Verrouillé"
    new "已锁定"

    old "Jour 0 — Sélection"
    new "第0天 — 选拔"
    old "Kami interrompt une réunion ordinaire et impose le Conclave orbital comme nouveau centre de décision."
    new "Kami 打断一场普通会议，并将轨道议会确立为新的决策中心。"
    old "Acceptation forcée du protocole Kami's Desires."
    new "被迫接受 Kami's Desires 协议。"
    old "Noam est extrait vers le Conclave."
    new "Noam 被带往议会。"
    old "Jour 1 — Réveil au Conclave"
    new "第1天 — 在议会醒来"
    old "Les représentants découvrent le Conclave, ses salles et les règles d'unanimité imposées par Kami."
    new "代表们探索议会及其各个房间，并了解 Kami 强制推行的全票通过规则。"
    old "Premiers repères, premières alliances, premières méfiances."
    new "最初的摸索、结盟与猜疑。"
    old "Le cycle des amendements est lancé."
    new "修正案周期正式启动。"
    old "Jour 2 — Installation"
    new "第2天 — 安顿"
    old "Le premier amendement sur le commerce interdistrict est annoncé. Les intérêts de chaque district remontent."
    new "首项跨区贸易修正案公布，各区域的利益诉求浮出水面。"
    old "Observer les positions avant le premier vote."
    new "在首次投票前观察各方立场。"
    old "Le débat sur le commerce devient inévitable."
    new "贸易辩论已不可避免。"
    old "Jour 3 — Premier débat"
    new "第3天 — 首场辩论"
    old "Le Conclave approche du vote sur le commerce. Les tensions politiques deviennent impossibles à cacher."
    new "议会即将就贸易进行投票，政治紧张已无法掩饰。"
    old "Soutien, opposition ou prudence face à l'amendement."
    new "选择支持、反对或谨慎对待修正案。"
    old "Le vote peut ouvrir une nouvelle route ou maintenir le statu quo."
    new "投票可能开启新路线，也可能维持现状。"
    old "Débat — Texte fragmenté"
    new "辩论 — 破碎文本"
    old "Débat I"
    new "辩论 I"
    old "L'amendement est présenté sous une forme instable. Les représentants tentent de reconstituer le sens politique du texte."
    new "修正案以不稳定的形式呈现，代表们试图重建文本的政治含义。"
    old "Identifier les arguments utiles au vote."
    new "找出与投票有关的论点。"
    old "Le rapport de forces se précise."
    new "力量对比逐渐明朗。"
    old "Vote — Commerce libre"
    new "投票 — 自由贸易"
    old "Le Conclave vote sur l'autorisation du commerce, du transport et du stockage des marchandises."
    new "议会就允许商品贸易、运输和储存进行投票。"
    old "Voter pour, voter contre, ou laisser l'abstention agir."
    new "投赞成票、反对票，或让弃权发挥作用。"
    old "Le résultat divise la chronologie en deux routes."
    new "投票结果将时间线分为两条路线。"
    old "Route — Statu quo"
    new "路线 — 维持现状"
    old "Le commerce échoue. Le Conclave conserve l'ordre existant, mais la frustration politique s'accumule."
    new "贸易案未获通过。议会维持现有秩序，但政治不满不断累积。"
    old "Refus ou blocage de l'amendement commerce."
    new "否决或阻止贸易修正案。"
    old "Jour 4 suit la route de l'échec du vote."
    new "第4天进入投票失败路线。"
    old "Route — Commerce adopté"
    new "路线 — 贸易案通过"
    old "Le commerce est adopté. Nexus et Orbite s'organisent, tandis que Limen vacille."
    new "贸易案获得通过。Nexus 与 Orbite 开始组织行动，而 Limen 发生动摇。"
    old "Adoption de l'amendement commerce."
    new "通过贸易修正案。"
    old "Jour 4 suit la route du commerce ouvert."
    new "第4天进入开放贸易路线。"
