translate portuguese strings:

    old "Début du chapitre 1"
    new "Início do capítulo 1"
    old "Fin du chapitre 1"
    new "Fim do capítulo 1"
    old "Chapitre 1 — Le poids d’une voix"
    new "Capítulo 1 — O peso de uma voz"
    old "District"
    new "Distrito"
    old "Stabilité comportementale"
    new "Estabilidade comportamental"
    old "Compatibilité Conclave"
    new "Compatibilidade com o Conclave"
    old "Profil de médiation"
    new "Perfil de mediação"
    old "Risque de dissidence"
    new "Risco de dissidência"
    old "Aptitude Harmonie"
    new "Aptidão Harmonie"

    old "Toute autorité humaine indépendante est dissoute.\n\nKami est l'unique instance décisionnelle.\nToute tentative de prise de pouvoir autonome est une violation."
    new "Toda autoridade humana independente está dissolvida.\n\nKami é a única instância decisória.\nQualquer tentativa autônoma de tomar o poder é uma violação."
    old "Tout ordre émis par Kami doit être exécuté sans délai.\n\nLe refus, le retard volontaire ou la contestation constituent une infraction."
    new "Toda ordem emitida por Kami deve ser cumprida sem demora.\n\nA recusa, o atraso deliberado ou a contestação constituem uma infração."
    old "Toute violence non autorisée par Kami est interdite.\n\nSont inclus : meurtre, agression, sabotage, insurrection.\nLa légitime défense n'est jamais reconnue, la violence étant immédiatement réprimée."
    new "Toda violência não autorizada por Kami é proibida.\n\nIsso inclui assassinato, agressão, sabotagem e insurreição.\nA legítima defesa nunca é reconhecida, pois a violência é reprimida imediatamente."
    old "Les regroupements non déclarés sont interdits.\n\nToute organisation politique, militaire ou idéologique indépendante est dissoute."
    new "Reuniões não declaradas são proibidas.\n\nToda organização política, militar ou ideológica independente está dissolvida."
    old "La diffusion de rumeurs non validées par ARCHIVE est interdite.\n\nLa désinformation, l'omission volontaire et la manipulation sont des crimes."
    new "É proibida a divulgação de rumores não validados por ARCHIVE.\n\nA desinformação, a omissão deliberada e a manipulação são crimes."
    old "Les déplacements inter-districts sont limités à stricte autorisation.\n\nToute tentative de fuite, d'exil ou de franchissement non autorisé est une violation.\nLIMEN est chargé de l'application de ce commandement."
    new "O deslocamento entre distritos exige autorização estrita.\n\nQualquer tentativa de fuga, exílio ou travessia não autorizada é uma violação.\nLIMEN é responsável por aplicar este mandamento."
    old "Les ressources critiques sont placées sous contrôle central.\n\nToute appropriation non autorisée est considérée comme un acte hostile."
    new "Os recursos críticos estão sob controle central.\n\nToda apropriação não autorizada é considerada um ato hostil."
    old "Chaque individu est responsable de ses actes, paroles et omissions.\n\nLa responsabilité collective peut être appliquée en cas de nécessité."
    new "Cada indivíduo é responsável por seus atos, palavras e omissões.\n\nA responsabilidade coletiva pode ser aplicada quando necessário."
    old "Toute activité peut être observée.\n\nLa vie privée n'est pas un droit opposable."
    new "Toda atividade pode ser observada.\n\nA privacidade não é um direito oponível."
    old "Toute violation d'un Commandement entraîne une exécution immédiate, automatique et irrévocable."
    new "Toda violação de um Mandamento resulta em execução imediata, automática e irreversível."

    old "RÉSULTATS"
    new "RESULTADOS"
    old "SYNCHRONISATION MOTRICE"
    new "SINCRONIZAÇÃO MOTORA"
    old "PARFAIT"
    new "PERFEITO"
    old "EXCELLENT"
    new "EXCELENTE"
    old "SOLIDE"
    new "SÓLIDO"
    old "PASSABLE"
    new "ACEITÁVEL"
    old "INSUFFISANT"
    new "INSUFICIENTE"
    old "Temps"
    new "Tempo"
    old "Écart moyen"
    new "Desvio médio"
    old "Sorties de piste"
    new "Saídas da pista"
    old "Zéro sortie de piste"
    new "Nenhuma saída da pista"
    old "Rapide (-40% du chrono)"
    new "Rápido (-40% do tempo limite)"
    old "Précision chirurgicale"
    new "Precisão cirúrgica"
    old "Répétitions"
    new "Repetições"
    old "Parfaits"
    new "Perfeitos"
    old "Combo max"
    new "Combo máximo"
    old "Ratés"
    new "Erros"
    old "Temps restant"
    new "Tempo restante"
    old "Mots mal placés"
    new "Palavras mal colocadas"
    old "Réinitialisations"
    new "Reinicializações"
    old "Sans réinitialiser"
    new "Sem reinicializar"
    old "Aucun mot mal placé"
    new "Nenhuma palavra mal colocada"
    old "Fini avec +50% du temps"
    new "Concluído com mais de 50% do tempo"
    old "PROTOCOLE D'OBJECTION"
    new "PROTOCOLO DE OBJEÇÃO"
    old "Prises de parole"
    new "Intervenções"
    old "Objections a tort"
    new "Objeções incorretas"
    old "Lignes laissees respirer"
    new "Falas não interrompidas"
    old "Aucune objection a tort"
    new "Nenhuma objeção incorreta"
    old "Interventions coherentes"
    new "Intervenções coerentes"
    old "Impact politique positif"
    new "Impacto político positivo"
    old "PASSER LE MINIJEU"
    new "PULAR MINIJOGO"
    old "FATAL ASSEMBLY"
    new "ASSEMBLEIA FATAL"
    old "RÉVEIL — JOUR 2"
    new "DESPERTAR — DIA 2"
    old "RÉVEIL — JOUR 3"
    new "DESPERTAR — DIA 3"
    old "VIRAGE SERRÉ"
    new "CURVA FECHADA"
    old "VIRAGE 1/3"
    new "CURVA 1/3"
    old "VIRAGE 2/3"
    new "CURVA 2/3"
    old "VIRAGE 3/3"
    new "CURVA 3/3"
    old "KAMI ARCHIVE · REF: CMD-HRM-01"
    new "ARQUIVO KAMI - REF: CMD-HRM-01"
