translate portuguese strings:

    # Dias 0–1 — interfaces de chegada, seleção, emenda e bloqueador.
    old "ACHEMINEMENT — CONCLAVE"
    new "ENCAMINHAMENTO — CONCLAVE"
    old "DÉLAI EXPIRÉ"
    new "PRAZO EXPIRADO"
    old "LIMITE : 22:00  ▸  RESTANT"
    new "LIMITE: 22:00  ▸  RESTANTE"
    old "PORTIQUE DE SÉCURITÉ — DISTRICT HARMONIE"
    new "PÓRTICO DE SEGURANÇA — DISTRITO HARMONIE"
    old "● ACTIF"
    new "● ATIVO"
    old "LECTEUR CIVIL / IDENTIFICATION OBLIGATOIRE"
    new "LEITOR CIVIL / IDENTIFICAÇÃO OBRIGATÓRIA"
    old "POSER LE BADGE SUR LA ZONE DE LECTURE"
    new "COLOQUE O CRACHÁ NA ÁREA DE LEITURA"
    old "Chaque entrée est enregistrée."
    new "Toda entrada é registrada."
    old "↓  ZONE DE LECTURE  ↓"
    new "↓  ÁREA DE LEITURA  ↓"
    old "BADGE ENREGISTRÉ"
    new "CRACHÁ REGISTRADO"
    old "DISTRICT HARMONIE"
    new "DISTRITO HARMONIE"
    old "Médiateur civil · Secteur 3"
    new "Mediador civil · Setor 3"
    old "LECTEUR BIOMÉTRIQUE"
    new "LEITOR BIOMÉTRICO"
    old "EN ATTENTE"
    new "EM ESPERA"
    old "ANALYSE EN COURS"
    new "ANÁLISE EM ANDAMENTO"
    old "ACCÈS AUTORISÉ"
    new "ACESSO AUTORIZADO"
    old "Présenter le badge dans la zone."
    new "Apresente o crachá na área de leitura."
    old "Comparaison profil civil en cours."
    new "Comparando perfil civil."
    old "VALIDATION DE L'IDENTITÉ..."
    new "VALIDANDO IDENTIDADE..."
    old "Comparaison du profil avec les autorisations locales."
    new "Comparando o perfil com as permissões locais."
    old "PASSAGE CONFIRMÉ"
    new "PASSAGEM CONFIRMADA"
    old "Comportement conforme. Identité reconnue."
    new "Comportamento em conformidade. Identidade reconhecida."
    old "IDENTIFIANT CIVIL"
    new "IDENTIFICADOR CIVIL"
    old "▶  GLISSER"
    new "▶  DESLIZAR"
    old "KAMI INFRASTRUCTURE · CONTRÔLE CIVIL AUTOMATISÉ · TOUTE ENTRÉE EST ENREGISTRÉE"
    new "INFRAESTRUTURA KAMI · CONTROLE CIVIL AUTOMATIZADO · TODA ENTRADA É REGISTRADA"
    old "ÉCRAN VERROUILLÉ"
    new "TELA BLOQUEADA"
    old "Glisser vers le haut pour déverrouiller"
    new "Deslize para cima para desbloquear"
    old "VENDREDI — JOUR 0"
    new "SEXTA-FEIRA — DIA 0"
    old "Signal : --   •   Réseau : indisponible"
    new "Sinal: --   •   Rede: indisponível"
    old "Recherche de réseau..."
    new "Procurando rede..."
    old "AUCUN RÉSEAU"
    new "SEM REDE"
    old "Recherche des relais civils en cours..."
    new "Procurando repetidores civis..."
    old "ERR_NET_001 · Aucun opérateur disponible"
    new "ERR_NET_001 · Nenhuma operadora disponível"
    old "Les services de communication\nsont temporairement indisponibles."
    new "Os serviços de comunicação estão\ntemporariamente indisponíveis."
    old "APPEL REFUSÉ"
    new "CHAMADA RECUSADA"
    old "Appels d'urgence indisponibles."
    new "Chamadas de emergência indisponíveis."
    old "Code : INFRASTRUCTURE NON SOUVERAINE"
    new "Código: INFRAESTRUTURA NÃO SOBERANA"
    old "Tous les canaux de communication\ndépendent désormais de KAMI."
    new "Todos os canais de comunicação\nagora dependem de KAMI."
    old "ERR_NET_403 · ACCÈS BLOQUÉ"
    new "ERR_NET_403 · ACESSO BLOQUEADO"
    old "MESSAGE NON ENVOYÉ"
    new "MENSAGEM NÃO ENVIADA"
    old "Merci de cesser toute tentative de\nréinitialisation du réseau.\nCette conversation est enregistrée."
    new "Pare de tentar\nreiniciar a rede.\nEsta conversa está sendo gravada."
    old "Le réseau de communication\nne vous appartient plus."
    new "A rede de comunicação\nnão pertence mais a você."
    old "• 1 message non distribué"
    new "• 1 mensagem não entregue"
    old "CONTRÔLE DISTANT ACTIF"
    new "CONTROLE REMOTO ATIVO"
    old "Verrouillage de l'interface."
    new "Bloqueando interface."
    old "Cet appareil est désormais\nsous surveillance directe."
    new "Este dispositivo agora está\nsob vigilância direta."
    old "Rallumer"
    new "Ligar"
    old "Envoyer"
    new "Enviar"
    old "REGISTRE DES COMMANDEMENTS"
    new "REGISTRO DOS MANDAMENTOS"
    old "District HARMONIE · Consultation surveillée"
    new "Distrito HARMONIE · Consulta monitorada"
    old "Commandement %s"
    new "Mandamento %s"
    old "COMMANDEMENT"
    new "MANDAMENTO"
    old "◀ Précédent"
    new "◀ Anterior"
    old "Suivant ▶"
    new "Próximo ▶"
    old "Fermer"
    new "Fechar"
    old "DISTRICT HARMONIE — SÉLECTION DES REPRÉSENTANTS"
    new "DISTRITO HARMONIE — SELEÇÃO DOS REPRESENTANTES"
    old "Cliquez pour arrêter la sélection"
    new "Clique para interromper a seleção"
    old "PROFILS EN ANALYSE"
    new "PERFIS EM ANÁLISE"
    old "✓  SÉLECTIONNÉ"
    new "✓  SELECIONADO"
    old "PROFIL ÉCARTÉ"
    new "PERFIL DESCARTADO"
    old "CRITÈRES D'ANALYSE"
    new "CRITÉRIOS DE ANÁLISE"
    old "EN COURS…"
    new "EM ANDAMENTO…"
    old "VALIDÉ"
    new "VALIDADO"
    old "SÉLECTION VALIDÉE"
    new "SELEÇÃO VALIDADA"
    old "REPRÉSENTANTS — DISTRICT HARMONIE"
    new "REPRESENTANTES — DISTRITO HARMONIE"
    old "Médiateur civil"
    new "Mediador civil"
    old "Coordination logistique"
    new "Coordenação logística"
    old "Acheminement sous 6 heures — Sanctions applicables en cas de retard."
    new "Encaminhamento em até 6 horas — Penalidades aplicáveis em caso de atraso."
    old "KAMI — SÉLECTION AUTOMATISÉE · DISTRICT HARMONIE · SÉANCE 14-3"
    new "KAMI — SELEÇÃO AUTOMATIZADA · DISTRITO HARMONIE · SESSÃO 14-3"
    old "FERMETURE AUTOMATIQUE // 2.0 s"
    new "FECHAMENTO AUTOMÁTICO // 2.0 s"
    old "SOUVENIR"
    new "MEMÓRIA"

    old "INTERFACE PUPITRE — CONCLAVE"
    new "INTERFACE DO PÚLPITO — CONCLAVE"
    old "SESSION : EN ATTENTE  ▸  VERROUILLÉ"
    new "SESSÃO: EM ESPERA  ▸  BLOQUEADA"
    old "UTILISATEUR"
    new "USUÁRIO"
    old "STATUT"
    new "STATUS"
    old "REPRÉSENTANT — CONCLAVE JOUR 1"
    new "REPRESENTANTE — CONCLAVE DIA 1"
    old "ACCÈS TABLETTE"
    new "ACESSO AO TABLET"
    old "▸  AMENDEMENTS  —  VERROUILLÉ JUSQU'AU DÉPÔT"
    new "▸  EMENDAS  —  BLOQUEADAS ATÉ O ENVIO"
    old "▸  CODEX  —  ACCÈS PARTIEL"
    new "▸  CÓDICE  —  ACESSO PARCIAL"
    old "▸  COMMUNICATIONS  —  BLOQUÉES"
    new "▸  COMUNICAÇÕES  —  BLOQUEADAS"
    old "INTERACTION ENREGISTRÉE — KAMI MONITORING ACTIF"
    new "INTERAÇÃO REGISTRADA — MONITORAMENTO KAMI ATIVO"
    old "RETIRER LA MAIN"
    new "RETIRAR A MÃO"
    old "✦  CODEX  —  NOUVELLE ENTRÉE  :"
    new "✦  CÓDICE  —  NOVA ENTRADA:"
    old "DÉPÔT CLOS"
    new "ENVIO ENCERRADO"
    old "FERMETURE  ▸  RESTANT"
    new "FECHAMENTO  ▸  RESTANTE"
    old "TUTORIEL — PROPOSITION D'AMENDEMENT"
    new "TUTORIAL — PROPOSTA DE EMENDA"
    old "Comment proposer un amendement :"
    new "Como propor uma emenda:"
    old "① Lisez attentivement les deux propositions de modification de Commandement."
    new "① Leia atentamente as duas propostas de alteração do Mandamento."
    old "② Sélectionnez la proposition qui vous semble la plus juste ou la plus utile."
    new "② Selecione a proposta que pareça mais justa ou útil."
    old "③ La formulation officielle sera automatiquement retenue."
    new "③ A redação oficial será selecionada automaticamente."
    old "④ Une fois validé, l'amendement est anonymement déposé dans l'urne — sans retour possible."
    new "④ Após a confirmação, a emenda é depositada anonimamente — sem possibilidade de retirada."
    old "⚠  Ce choix est définitif. Il engage Noam pour l'ensemble du Conclave."
    new "⚠  Esta escolha é definitiva. Ela compromete Noam durante todo o Conclave."
    old "COMPRIS — CONTINUER"
    new "ENTENDIDO — CONTINUAR"
    old "TERMINAL CONSTITUTIONNEL — PROPOSITION D'AMENDEMENT"
    new "TERMINAL CONSTITUCIONAL — PROPOSTA DE EMENDA"
    old "REPRÉSENTANT : NOAM  ▸  STATUT : BROUILLON  ▸  ANONYMAT : GARANTI"
    new "REPRESENTANTE: NOAM  ▸  STATUS: RASCUNHO  ▸  ANONIMATO: GARANTIDO"
    old "SÉLECTIONNÉ"
    new "SELECIONADO"
    old "INTENTION"
    new "INTENÇÃO"
    old "FORMULATION"
    new "REDAÇÃO"
    old "RISQUE IDENTIFIÉ"
    new "RISCO IDENTIFICADO"
    old "FORMULATION OFFICIELLE RETENUE :"
    new "REDAÇÃO OFICIAL SELECIONADA:"
    old "VALIDER LA PROPOSITION"
    new "CONFIRMAR PROPOSTA"
    old "CONFIRMATION — DÉPÔT DÉFINITIF"
    new "CONFIRMAÇÃO — ENVIO DEFINITIVO"
    old "Ce dépôt est IRRÉVERSIBLE. L'amendement sera traité de façon anonyme."
    new "Este envio é IRREVERSÍVEL. A emenda será processada anonimamente."
    old "← MODIFIER"
    new "← EDITAR"
    old "DÉPOSER DANS L'URNE →"
    new "DEPOSITAR NA URNA →"
    old "AMENDEMENT DÉPOSÉ"
    new "EMENDA DEPOSITADA"
    old "RETRAIT IMPOSSIBLE"
    new "RETIRADA IMPOSSÍVEL"
    old "ENREGISTREMENT CONFIRMÉ"
    new "REGISTRO CONFIRMADO"
    old "ANONYMAT GARANTI — KAMI NE PEUT PAS IDENTIFIER L'AUTEUR"
    new "ANONIMATO GARANTIDO — KAMI NÃO PODE IDENTIFICAR O AUTOR"
    old "TIRAGE AU SORT DEMAIN À 09:00"
    new "SORTEIO AMANHÃ ÀS 09:00"
    old "RECULER DE L'URNE"
    new "AFASTAR-SE DA URNA"
    old "INTERFACE CHAMBRE — BROUILLEUR"
    new "INTERFACE DO QUARTO — BLOQUEADOR"
    old "BROUILLEUR : "
    new "BLOQUEADOR: "
    old "MODE PRIVÉ : "
    new "MODO PRIVADO: "
    old "CAMÉRA : COUPÉE"
    new "CÂMERA: DESLIGADA"
    old "AUDIO : COUPÉ"
    new "ÁUDIO: DESLIGADO"
    old "CAPTEURS : COUPÉS"
    new "SENSORES: DESLIGADOS"
    old "KAMI : AVEUGLE"
    new "KAMI: CEGA"
    old "SURVEILLANCE POTENTIELLE — KAMI PEUT OBSERVER CETTE PIÈCE"
    new "VIGILÂNCIA POSSÍVEL — KAMI PODE OBSERVAR ESTE QUARTO"
    old "DÉSACTIVER LE BROUILLEUR"
    new "DESATIVAR BLOQUEADOR"
    old "RÉACTIVER LE BROUILLEUR"
    new "REATIVAR BLOQUEADOR"
    old "QUITTER L'INTERFACE"
    new "FECHAR INTERFACE"
    old "TUTORIEL — SYNCHRONISATION MOTRICE"
    new "TUTORIAL — SINCRONIZAÇÃO MOTORA"
    old "Comment répondre à un QTE de trace :"
    new "Como concluir um QTE de traçado:"
    old "① Une courbe ou un chemin s'affiche à l'écran."
    new "① Uma curva ou caminho aparece na tela."
    old "② Suivez ce tracé avec votre souris le plus précisément possible."
    new "② Siga o traçado com o mouse com a maior precisão possível."
    old "③ Restez dans la tolérance indiquée (zone colorée) pour valider."
    new "③ Permaneça dentro da tolerância indicada (área colorida) para concluir."
    old "④ Trop d'erreurs = échec. Restez concentré et allez à un rythme régulier."
    new "④ Erros demais significam falha. Mantenha o foco e um ritmo constante."
    old "Ce QTE simule la perte de contrôle moteur de Noam au réveil."
    new "Este QTE simula a perda de controle motor de Noam ao acordar."
    old "COMPRIS — LANCER LE QTE"
    new "ENTENDIDO — INICIAR QTE"

    # Dias 2–3 — dossiês de votação, debate e minijogos.
    old "Glisse la carte dans la mallette de Noam."
    new "Arraste a carta para a pasta de Noam."
    old "ARGUMENT"
    new "ARGUMENTO"
    old "DOSSIER DU VOTE"
    new "DOSSIÊ DA VOTAÇÃO"
    old "DÉPOSER ICI"
    new "SOLTE AQUI"
    old "TABLETTE DE NOAM"
    new "TABLET DE NOAM"
    old "Nouveau dossier disponible : Prochain vote"
    new "Novo dossiê disponível: Próxima votação"
    old "La fiche rassemble la proposition, les arguments rangés dans ton dossier et les positions que tu supposes chez les autres représentants."
    new "A ficha reúne a proposta, os argumentos guardados e as posições que você atribui aos outros representantes."
    old "Les portraits peuvent être déplacés librement entre POUR, INCONNU et CONTRE. Ce classement est une note personnelle, pas une correction automatique."
    new "Os retratos podem ser movidos entre A FAVOR, DESCONHECIDO e CONTRA. Esta é uma anotação pessoal, não uma correção automática."
    old "Continuer"
    new "Continuar"
    old "Prochain vote"
    new "Próxima votação"
    old "Vote en cours"
    new "Votação atual"
    old "Ça serait bien qu'on réautorise le commerce comme avant."
    new "Seria bom permitir o comércio novamente, como antes."
    old "Moment prévu : Jour 3, 14h00"
    new "Horário previsto: Dia 3, 14:00"
    old "Moment prévu : Jour 6, 14h00"
    new "Horário previsto: Dia 6, 14:00"
    old "Résumé neutre"
    new "Resumo neutro"
    old "Le texte promet une circulation plus libre des biens. Ses effets restent incertains selon les districts, les procédures et les risques locaux."
    new "O texto promete maior liberdade de circulação de bens. Seus efeitos seguem incertos conforme os distritos, procedimentos e riscos locais."
    old "Autoriser ou non les déplacements entre les districts."
    new "Decidir se os deslocamentos entre distritos serão permitidos."
    old "Le texte promet une circulation plus libre des personnes entre districts. Ses effets restent incertains selon les frontières, la sécurité et les capacités d'accueil."
    new "O texto promete maior liberdade de circulação entre distritos. Seus efeitos seguem incertos conforme as fronteiras, a segurança e a capacidade local."
    old "Arguments découverts"
    new "Argumentos descobertos"
    old "Argument non découvert"
    new "Argumento não descoberto"
    old "Glisse les portraits ici."
    new "Arraste os retratos para cá."
    old "Dossier actif"
    new "Dossiê ativo"
    old "Arguments rangés : [day2_vote_argument_count()] / [len(DAY2_VOTE_ARGUMENTS)]"
    new "Argumentos guardados: [day2_vote_argument_count()] / [len(DAY2_VOTE_ARGUMENTS)]"
    old "Les positions restent modifiables dans le Codex."
    new "As posições ainda podem ser alteradas no Códice."
    old "CHOIX DU THÈME"
    new "ESCOLHA DO TEMA"
    old "PHASE ARGUMENTATIVE"
    new "FASE ARGUMENTATIVA"
    old "PHASE [phase]/3"
    new "FASE [phase]/3"
    old "Quel angle aborder pour cette discussion ?\nJe dois choisir l'argument qui aura le plus d'impact."
    new "Qual abordagem usar nesta discussão?\nPreciso escolher o argumento de maior impacto."
    old "SÉLECTIONNEZ LE THÈME DE LA DISCUSSION"
    new "SELECIONE O TEMA DA DISCUSSÃO"
    old "Débloquez cet argument pour l'utiliser."
    new "Desbloqueie este argumento para usá-lo."
    old "VOS ARGUMENTS DÉBLOQUÉS"
    new "SEUS ARGUMENTOS DESBLOQUEADOS"
    old "INFO  Chaque thème influence les réactions des représentants. Choisissez judicieusement."
    new "INFO  Cada tema influencia as reações dos representantes. Escolha com cuidado."
    old "CONFIRMER LE THÈME"
    new "CONFIRMAR TEMA"
    old "CONTINUER SANS THÈME"
    new "CONTINUAR SEM TEMA"

    old "ARCHIVE // ANALYSE DE TEXTE"
    new "ARQUIVO // ANÁLISE DE TEXTO"
    old "Alors, médiateur..."
    new "Então, mediador..."
    old "OBJECTIF"
    new "OBJETIVO"
    old "Glissez-déposez les mots pour reconstituer la phrase exacte du texte officiel."
    new "Arraste as palavras para reconstruir a frase exata do texto oficial."
    old "Chaque placement compte : une proposition propre donne un meilleur résultat."
    new "Cada posição conta: uma proposta limpa produz um resultado melhor."
    old "TEMPS\nRESTANT"
    new "TEMPO\nRESTANTE"
    old "[fa_filled_count]/[fa_total_slots] mots placés"
    new "[fa_filled_count]/[fa_total_slots] palavras colocadas"
    old "— PROGRESSION"
    new "— PROGRESSO"
    old "Autoriser"
    new "Autorizar"
    old "vente"
    new "venda"
    old "le"
    new "a"

    old "OBJECTION\nPROTOCOL"
    new "PROTOCOLO\nDE OBJEÇÃO"
    old "LIGNE [_dp2_current_line]/[_dp2_total_lines]"
    new "LINHA [_dp2_current_line]/[_dp2_total_lines]"
    old "PRISES DE PAROLE [debat_phase2_good]"
    new "INTERVENÇÕES [debat_phase2_good]"
    old "VOTRE TOUR"
    new "SUA VEZ"
    old "Cliquez sur le buzzer seulement quand une intervention apporte vraiment quelque chose."
    new "Aperte o botão somente quando uma intervenção realmente acrescentar algo."
    old "ATTENTION"
    new "ATENÇÃO"
    old "Vous ne pouvez parler\nqu’après avoir appuyé\nsur le buzzer."
    new "Você só pode falar\ndepois de apertar\no botão."
    old "À TORT [debat_phase2_wrong]"
    new "INCORRETAS [debat_phase2_wrong]"
    old "MANQUÉES [debat_phase2_missed]"
    new "PERDIDAS [debat_phase2_missed]"
    old "OBJECTION !"
    new "OBJEÇÃO!"
    old "OBJECTION REJETÉE"
    new "OBJEÇÃO REJEITADA"
    old "Cet argument tenait debout. L'assemblée murmure..."
    new "O argumento era válido. A assembleia murmura..."
    old "Noam a perdu toute credibilite devant le Conclave."
    new "Noam perdeu toda a credibilidade diante do Conclave."
    old "Cliquez pour reprendre juste avant le Protocole d'Objection."
    new "Clique para retomar logo antes do Protocolo de Objeção."

    old "RÉPÉTITIONS"
    new "REPETIÇÕES"
    old "ÉNERGIE // CHARGE MUSCULAIRE"
    new "ENERGIA // CARGA MUSCULAR"
    old "RYTHME // FENÊTRE D'EFFORT"
    new "RITMO // JANELA DE ESFORÇO"
    old "TEMPS // CHRONO"
    new "TEMPO // CRONÔMETRO"
    old "⬆ ⬇  Clic, ↑ ou ↓ pour pousser."
    new "⬆ ⬇  Clique, ↑ ou ↓ para empurrar."
    old "POUSSER"
    new "EMPURRAR"
    old "STAT EN HAUSSE"
    new "ATRIBUTO AUMENTADO"
    old "Physique +1"
    new "Físico +1"
    old "PARFAIT !"
    new "PERFEITO!"

    old "KAMI.CORE // EXECUTION PROTOCOL"
    new "KAMI.CORE // PROTOCOLO DE EXECUÇÃO"
    old "TUTORIEL — [title]"
    new "TUTORIAL — [title]"
    old "KAMI.CORE // RETRY PENALTY"
    new "KAMI.CORE // PENALIDADE DE NOVA TENTATIVA"
    old "KAMI.CORE // PERFORMANCE VERDICT"
    new "KAMI.CORE // VEREDITO DE DESEMPENHO"
    old "★ NOUVEAU RECORD"
    new "★ NOVO RECORDE"
    old "Record : [best_rank]"
    new "Recorde: [best_rank]"
    old "[retries] retry — rang plafonné"
    new "[retries] tentativa — classificação limitada"
    old "DÉFIS  [mk_challenge_count_done(challenges)] / [len(challenges)]"
    new "DESAFIOS  [mk_challenge_count_done(challenges)] / [len(challenges)]"
    old "CONTINUER"
    new "CONTINUAR"
    old "MAINTENIR PUIS GLISSER"
    new "SEGURE E ARRASTE"
    old "NOAM — PENSÉE"
    new "NOAM — PENSAMENTO"
    old "CLIQUER POUR CONTINUER"
    new "CLIQUE PARA CONTINUAR"

    old "01  ÉCOUTE"
    new "01  ESCUTE"
    old "02  ARME"
    new "02  PREPARE"
    old "03  CONTREDIS"
    new "03  CONTESTE"
    old "Une erreur ne bloque pas la scène : Julian poursuit simplement son argumentaire."
    new "Um erro não interrompe a cena: Julian apenas continua seu argumento."
    old "ARGUMENT // JULIAN"
    new "ARGUMENTO // JULIAN"
    old "DÉCLARATION [line_index + 1] / [total_lines]"
    new "DECLARAÇÃO [line_index + 1] / [total_lines]"
    old "LECTURE [pass_index + 1]"
    new "LEITURA [pass_index + 1]"
    old "PREMIÈRE LECTURE : observe l'argumentaire complet. Les répliques seront disponibles au prochain passage."
    new "PRIMEIRA LEITURA: observe o argumento completo. As respostas estarão disponíveis na próxima passagem."
    old "CONTRADICTION TROUVÉE — écoute de la fin de l'argumentaire"
    new "CONTRADIÇÃO ENCONTRADA — escute o final do argumento"
    old "SÉLECTION : [DAY3_JULIAN_CLASH_BULLETS[day3_julian_clash_selected]['text']]"
    new "SELEÇÃO: [DAY3_JULIAN_CLASH_BULLETS[day3_julian_clash_selected]['text']]"
    old "ACCÉLÉRER  >>"
    new "ACELERAR  >>"
    old "RETOUR AU SEGMENT 01"
    new "VOLTAR AO SEGMENTO 01"
    old "Les répliques sont maintenant disponibles."
    new "As respostas agora estão disponíveis."
    old "CONTRADICTION"
    new "CONTRADIÇÃO"
    old "RÉPLIQUE ÉCARTÉE"
    new "RESPOSTA DESCARTADA"
    old "Julian enchaîne sans te laisser reprendre l'avantage."
    new "Julian continua sem deixar você recuperar a vantagem."
    old "Tu as isolé le faux mandat derrière le discours de Julian."
    new "Você expôs o falso mandato por trás do discurso de Julian."

    old "NOUVEL ARGUMENT"
    new "NOVO ARGUMENTO"
    old "PROFIL — STATISTIQUES"
    new "PERFIL — ATRIBUTOS"
    old "COMPÉTENCES PERMANENTES"
    new "HABILIDADES PERMANENTES"
    old "◂  RETOUR"
    new "◂  VOLTAR"
    old "Niveau [get_stat(name)]   •   Difficulté [dc]"
    new "Nível [get_stat(name)]   •   Dificuldade [dc]"
    old "LANCER LE DÉ"
    new "LANÇAR O DADO"
    old "Zones visitées : [len(exploration_libre_seen_rooms)]/[exploration_libre_required_visits]"
    new "Áreas visitadas: [len(exploration_libre_seen_rooms)]/[exploration_libre_required_visits]"
    old "Rejoindre la cafétéria"
    new "Ir à cafeteria"
    old "Rejoindre la salle d'observation"
    new "Ir à sala de observação"
    old "DAY"
    new "DIA"
    old "URN"
    new "URNA"
    old "PHASE"
    new "FASE"
    old "« Abolir la distribution risque de"
    new "“Abolir a distribuição pode"
    old "condamner les plus fragiles. »"
    new "condenar os mais vulneráveis.”"
    old "BUZZ"
    new "APERTAR"
    old "GAME OVER"
    new "FIM DE JOGO"
    old "GO"
    new "INICIAR"
    old "SCORE  [score] / [max_score]"
    new "PONTUAÇÃO  [score] / [max_score]"
    old "Sport"
    new "Esporte"
    old "PACKS"
    new "PACOTES"
    old "PACK [pack['num']] - [pack['title']]"
    new "PACOTE [pack['num']] - [pack['title']]"
    old "ARGUMENTS  [progress_arguments_done] / [progress_arguments_total]"
    new "ARGUMENTOS  [progress_arguments_done] / [progress_arguments_total]"
    old "SUCCÈS  [progress_successes_done] / [progress_successes_total]"
    new "CONQUISTAS  [progress_successes_done] / [progress_successes_total]"
    old "TEST — [STATS_META[name]['label']]"
    new "TESTE — [STATS_META[name]['label']]"

    # Dados dinâmicos exibidos por kd_tr().
    old "POUR"
    new "A FAVOR"
    old "INCONNU"
    new "DESCONHECIDO"
    old "CONTRE"
    new "CONTRA"
    old "Inégalités entre les districts"
    new "Desigualdades entre os distritos"
    old "Risque économique"
    new "Risco econômico"
    old "Les districts n'affrontent ni les mêmes pénuries ni les mêmes chances d'accéder aux biens."
    new "Os distritos não enfrentam as mesmas carências nem têm as mesmas chances de acesso aos bens."
    old "Entendu lors d'un échange avec Lysa et Elias."
    new "Ouvido durante uma conversa com Lysa e Elias."
    old "Bons de rationnement"
    new "Vales de racionamento"
    old "Organisation quotidienne"
    new "Organização cotidiana"
    old "Les demandes officielles et les bons structurent déjà l'accès aux biens essentiels."
    new "Pedidos oficiais e vales já organizam o acesso aos bens essenciais."
    old "Relevé dans la discussion avec Kael."
    new "Observado na conversa com Kael."
    old "Risque de dépressurisation"
    new "Risco de despressurização"
    old "Sécurité"
    new "Segurança"
    old "Sur Orbite, une sanction qui perce une coque peut condamner tout un module."
    new "Em Orbite, uma punição que perfure um casco pode condenar um módulo inteiro."
    old "Décrit par Kael en salle d'observation."
    new "Descrito por Kael na sala de observação."
    old "Dérogations trop complexes"
    new "Exceções complexas demais"
    old "Accès administratif"
    new "Acesso administrativo"
    old "Obtenir une nourriture originale ou un objet utile exige une dérogation disproportionnée."
    new "Obter uma comida diferente ou um objeto útil exige uma exceção desproporcional."
    old "Découvert en parlant avec Elen à la cafétéria."
    new "Descoberto ao conversar com Elen na cafeteria."
    old "Valeur du travail"
    new "Valor do trabalho"
    old "Organisation collective"
    new "Organização coletiva"
    old "L'entraide protège chacun, mais elle repose sur la contribution de tous ceux qui peuvent travailler."
    new "A ajuda mútua protege todos, mas depende da contribuição de quem pode trabalhar."
    old "Expliqué par Sael à partir de la vie de son village."
    new "Explicado por Sael a partir da vida em sua aldeia."
    old "Le monde d'avant"
    new "O mundo de antes"
    old "Mémoire politique"
    new "Memória política"
    old "Julian présente l'avant-Kami comme une preuve que la circulation libre peut exister."
    new "Julian apresenta o mundo anterior a Kami como prova de que a livre circulação pode existir."
    old "Entendu auprès de Julian avant la cafétéria."
    new "Ouvido de Julian antes da cafeteria."
    old "L'énoncé précis"
    new "A redação exata"
    old "Texte du vote"
    new "Texto da votação"
    old "La formulation exacte devient décisive : elle engage plus qu'une simple autorisation d'échange."
    new "A redação exata é decisiva: ela implica mais do que uma simples autorização de troca."
    old "Déduit pendant la discussion à la cafétéria."
    new "Deduzido durante a conversa na cafeteria."
    old "Échanges discrets déjà actifs"
    new "Trocas discretas já ativas"
    old "Réseaux informels"
    new "Redes informais"
    old "Des échanges informels existent déjà. Les nier ne les fait pas disparaître."
    new "Trocas informais já existem. Negá-las não fará com que desapareçam."
    old "Observé dans la salle de stockage."
    new "Observado no depósito."
    old "Choisissez un argument pour orienter le débat."
    new "Escolha um argumento para orientar o debate."
    old "Sécurité minimale contre la faim et le chaos."
    new "Proteção mínima contra a fome e o caos."
    old "Dépendance logistique et fragilité structurelle."
    new "Dependência logística e fragilidade estrutural."
    old "Texte exact, conséquences juridiques immédiates."
    new "Texto exato, consequências jurídicas imediatas."
    old "Ruptures passées et files de pénurie."
    new "Interrupções passadas e filas de escassez."
    old "Réseaux d'entraide clandestins déjà en place."
    new "Redes clandestinas de ajuda mútua já ativas."
    old "Mémoire d'un système ancien imparfait mais vivant."
    new "Memória de um sistema antigo, imperfeito, mas vivo."

    old "transport,"
    new "transporte,"
    old "la"
    new "a"
    old "et"
    new "e"
    old "l’échange"
    new "troca"
    old "de"
    new "de"
    old "marchandises."
    new "mercadorias."
    old "Le"
    new "O"
    old "système"
    new "sistema"
    old "actuel"
    new "atual"
    old "distribution"
    new "distribuição"
    old "denrées"
    new "alimentos"
    old "est"
    new "é"
    old "aboli."
    new "abolido."

    old "ENTRAÎNEMENT AUX HALTÈRES"
    new "TREINO COM HALTERES"
    old "Synchronise ton effort avec la zone verte pour valider chaque répétition."
    new "Sincronize seu esforço com a área verde para completar cada repetição."
    old "Correct."
    new "Correto."
    old "Raté..."
    new "Errou..."
    old "Combo x5"
    new "Combo x5"
    old "Zéro raté"
    new "Nenhum erro"
    old "4 frappes parfaites"
    new "4 acertos perfeitos"

    old "LA LIMITE DE TOMAS"
    new "O LIMITE DE TOMAS"
    old "Tomas vient de te demander d'arrêter."
    new "Tomas acabou de pedir para você parar."
    old "AUCUN MANDAT"
    new "SEM MANDATO"
    old "Personne ne t'a choisi pour les représenter."
    new "Ninguém escolheu você para representá-los."
    old "LE FOND DU TEXTE"
    new "O CONTEÚDO DO TEXTO"
    old "Parler plus fort ne rend pas le texte meilleur."
    new "Falar mais alto não melhora o texto."
    old "Je veux seulement que ce texte passe."
    new "Só quero que este texto seja aprovado."
    old "On devrait tous viser la même chose."
    new "Todos deveríamos buscar a mesma coisa."
    old "Je ne force personne."
    new "Não estou forçando ninguém."
    old "Je leur donne seulement un cap."
    new "Só estou dando uma direção."
    old "Ils restent libres de me suivre."
    new "Eles continuam livres para me seguir."
    old "Quelqu'un doit transformer cette hésitation"
    new "Alguém precisa transformar esta hesitação"
    old "en mouvement. J'assume de le faire."
    new "em ação. Eu assumo essa responsabilidade."
    old "Tomas hésite, c'est tout."
    new "Tomas está hesitando, só isso."
    old "Au fond, il attend que je le guide."
    new "No fundo, ele espera que eu o guie."
    old "Je lui évite de rester seul avec son choix."
    new "Estou evitando que ele enfrente sua escolha sozinho."
    old "Si je parle en premier au Conclave,"
    new "Se eu falar primeiro no Conclave,"
    old "les autres sauront enfin où regarder."
    new "os outros finalmente saberão para onde olhar."
    old "Ce n'est pas une question d'ego."
    new "Isto não é uma questão de ego."
    old "Les indécis m'ont choisi pour les représenter."
    new "Os indecisos me escolheram para representá-los."
    old "Je ne fais que prendre mes responsabilités."
    new "Só estou assumindo minhas responsabilidades."
    old "Vous pouvez trouver ma méthode agaçante."
    new "Vocês podem achar meu método irritante."
    old "Elle reste plus utile que votre silence."
    new "Ainda assim, ele é mais útil do que o silêncio de vocês."
    old "Quand le vote passera, personne ne reprochera"
    new "Quando a votação passar, ninguém culpará"
    old "à Julian d'avoir pris les devants."
    new "Julian por ter tomado a iniciativa."

    old "Représentante n°03 — Velkyn"
    new "Representante nº 03 — Velkyn"
    old "Représentant n°04 — Solen"
    new "Representante nº 04 — Solen"
    old "Représentante n°05 — Orée"
    new "Representante nº 05 — Orée"
    old "Représentant n°06 — Miren"
    new "Representante nº 06 — Miren"
    old "Représentante n°08 — Civitas"
    new "Representante nº 08 — Civitas"
    old "Représentant n°09 — Archive"
    new "Representante nº 09 — Archive"
    old "Représentante n°10 — Aster"
    new "Representante nº 10 — Aster"
    old "Représentant n°11 — Forge"
    new "Representante nº 11 — Forge"
    old "Représentante n°02 — Apex"
    new "Representante nº 02 — Apex"
    old "Représentant n°07 — Limen"
    new "Representante nº 07 — Limen"
    old "Représentante n°12 — Serment"
    new "Representante nº 12 — Serment"
    old "Médiateur — District Harmonie"
    new "Mediador — Distrito Harmonie"
    old "Ah, je dois commencer ?? Euh..."
    new "Ah, eu tenho que começar? Hum..."
    old "Abolir la distribution risque de"
    new "Abolir a distribuição pode"
    old "condamner les plus fragiles."
    new "condenar os mais vulneráveis."
    old "Le marché libre va"
    new "O livre mercado vai"
    old "récompenser ceux"
    new "recompensar aqueles"
    old "qui se bougent vraiment."
    new "que realmente se esforçam."
    old "Ceux qui se bougent, oui."
    new "Quem se esforça, sim."
    old "Mais ceux qui échouent"
    new "Mas quem fracassa,"
    old "on les verra aussi."
    new "também será visto."
    old "L’échec existe déjà."
    new "O fracasso já existe."
    old "Au moins là,"
    new "Pelo menos assim,"
    old "il aura un sens."
    new "ele terá um sentido."
    old "J’aime pas vraiment ça."
    new "Eu não gosto muito disso."
    old "Mais rester figés,"
    new "Mas ficar parados,"
    old "j’aime encore moins."
    new "eu gosto menos ainda."
    old "Statistiquement…"
    new "Estatisticamente..."
    old "ne rien changer"
    new "não mudar nada"
    old "c’est déjà tout perdre."
    new "já significa perder tudo."
    old "Alors essayons !"
    new "Então vamos tentar!"
    old "Moi, j’ai envie de voir"
    new "Eu quero ver"
    old "ce que ça peut donner."
    new "no que isso pode dar."
    old "Un test mal cadré peut"
    new "Um teste mal planejado pode"
    old "coûter plus cher que"
    new "custar mais do que"
    old "ce qu'on connait déjà."
    new "aquilo que já conhecemos."
    old "Alors cadrons-le."
    new "Então vamos planejá-lo bem."
    old "Mais ne faisons pas"
    new "Mas não vamos"
    old "semblant d’ignorer le reste."
    new "fingir que ignoramos o resto."
    old "Le reste ?!"
    new "O resto?!"
    old "Le reste, c’est des vies !"
    new "O resto são vidas!"
    old "Pas un foutu paramètre !"
    new "Não um maldito parâmetro!"
    old "Si on veut protéger des vies,"
    new "Se queremos proteger vidas,"
    old "il faut tout changer."
    new "precisamos mudar tudo."
    old "Ca commence par ça."
    new "E começa por isto."
    old "On doit bouger, oui."
    new "Precisamos avançar, sim."
    old "Mais étape par étape."
    new "Mas passo a passo."
    old "Doucement."
    new "Devagar."
    old "Je vous l’avais dit."
    new "Eu avisei."
    old "On finit toujours"
    new "No fim, todos sempre"
    old "par me rejoindre."
    new "acabam do meu lado."
    old "Ton besoin d’avoir raison"
    new "Sua necessidade de ter razão"
    old "n’a rien à voir avec"
    new "não tem nada a ver com"
    old "notre discussion."
    new "a nossa discussão."
    old "Je crois bien que"
    new "Acho que"
    old "nous sommes d’accord."
    new "estamos de acordo."
    old "Il faut du changement."
    new "Precisamos de mudança."
    old "Kami : Deux minutes. Vous êtes déjà en retard sur mes calculs."
    new "Kami: Dois minutos. Você já está atrasado em relação aos meus cálculos."
    old "Kami : 120 secondes, et toujours ce chaos. Charmant."
    new "Kami: 120 segundos e ainda este caos. Encantador."
    old "Kami : Vous sentez la pression ? Moi, j'appelle ça une statistique."
    new "Kami: Está sentindo a pressão? Eu chamo isso de estatística."
    old "Kami : Une minute. J'espère que vous aimez finir dans la panique."
    new "Kami: Um minuto. Espero que goste de terminar em pânico."
    old "Kami : 60 secondes. Je lance déjà les paris sur votre échec."
    new "Kami: 60 segundos. Já estou aceitando apostas no seu fracasso."
    old "Kami : Tic tac. C'est là que les erreurs deviennent irréversibles."
    new "Kami: Tic-tac. É agora que os erros se tornam irreversíveis."
    old "Kami : 30 secondes. Même mes protocoles ont plus de sang-froid."
    new "Kami: 30 segundos. Até meus protocolos mantêm mais a calma."
    old "Kami : Trente secondes. Vous devriez déjà avoir terminé."
    new "Kami: Trinta segundos. Você já deveria ter terminado."
    old "Kami : Plus que 30 secondes. Essayez de ne pas tout saboter."
    new "Kami: Restam 30 segundos. Tente não sabotar tudo."
    old "Kami : 10 secondes. Oui, c'est exactement aussi catastrophique que prévu."
    new "Kami: 10 segundos. Sim, está exatamente tão catastrófico quanto o previsto."
    old "Kami : Dix secondes. Respirez... enfin non, perdez plutôt du temps."
    new "Kami: Dez segundos. Respire... ou melhor, continue perdendo tempo."
    old "Kami : 10 secondes. Le stress vous va si bien."
    new "Kami: 10 segundos. O estresse combina tanto com você."
    old "— CONCLAVE —"
    new "— CONCLAVE —"
    old "Day [day_label]"
    new "Dia [day_label]"
    old "Temps libre"
    new "Tempo livre"
    old "DIFFUSION"
    new "TRANSMISSÃO"
    old "DOSSIER DE VOTE"
    new "DOSSIÊ DE VOTAÇÃO"
    old "CHAPITRES"
    new "CAPÍTULOS"
    old "COMPLÉTION DU CHAPITRE"
    new "CONCLUSÃO DO CAPÍTULO"
    old "ARGUMENTS  [arguments_done] / [arguments_total]"
    new "ARGUMENTOS  [arguments_done] / [arguments_total]"
    old "SUCCÈS  [successes_done] / [successes_total]"
    new "CONQUISTAS  [successes_done] / [successes_total]"
    old "Le pourcentage réunit les arguments découverts\net les succès liés à ce chapitre."
    new "A porcentagem combina os argumentos descobertos\ne as conquistas deste capítulo."
    old "SA FORMULATION"
    new "REDAÇÃO"
    old "ARGUMENTS DÉBLOQUÉS"
    new "ARGUMENTOS DESBLOQUEADOS"
    old "[dossier_prop_unlocked_count(sel_prop)] / [dossier_prop_total(sel_prop)] DÉBLOQUÉS"
    new "[dossier_prop_unlocked_count(sel_prop)] / [dossier_prop_total(sel_prop)] DESBLOQUEADOS"
    old "ⓘ  Les arguments recueillis vous aideront à préparer vos positions et anticiper les votes."
    new "ⓘ  Os argumentos coletados ajudam a preparar suas posições e antecipar as votações."
    old "Obtenu auprès de :"
    new "Obtido com:"
    old "Argument non débloqué"
    new "Argumento bloqueado"
    old "Continuez vos discussions, explorez les lieux et observez les autres représentants pour débloquer cet argument."
    new "Continue conversando, explore os lugares e observe os outros representantes para desbloquear este argumento."
    old "VOTE EN COURS"
    new "VOTAÇÃO EM ANDAMENTO"
    old "CHOISISSEZ L’ISSUE DU VOTE"
    new "ESCOLHA O RESULTADO DA VOTAÇÃO"
    old "DÉPOUILLEMENT DES VOTES"
    new "APURAÇÃO DOS VOTOS"
    old "Les votes sont secrets - les résultats seuls comptent."
    new "Os votos são secretos — apenas os resultados importam."
    old "AMENDEMENT N°1"
    new "EMENDA Nº 1"
    old "COMPTAGE DES VOTES"
    new "CONTAGEM DOS VOTOS"
    old "Bulletin [vote_phase3_tally_index] / [total_votes]"
    new "Cédula [vote_phase3_tally_index] / [total_votes]"
    old "BULLETIN DÉPOUILLÉ"
    new "CÉDULA APURADA"
    old "RÈGLE D’UNANIMITÉ"
    new "REGRA DE UNANIMIDADE"
    old "Si une seule personne vote contre, l’amendement est immédiatement refusé. L’abstention ne bloque pas l’adoption."
    new "Se uma única pessoa votar contra, a emenda será rejeitada imediatamente. A abstenção não impede a aprovação."
    old "Voix"
    new "Votos"
    old "FINAL_REPRESENTATIVES = (\"NOAM\", \"LYSA\")\n\nfunction generate_displayed_names:\n    decoys = shuffle(HARMONIE.citizens)\n    return animate(decoys)\n\nfunction accept_player_input(click):\n    stop_animation()\n    reveal(FINAL_REPRESENTATIVES)\n\n// La liste déroulante n'est qu'une façade.\n// Sélection terminée avant le début de la séance."
    new "FINAL_REPRESENTATIVES = (\"NOAM\", \"LYSA\")\n\nfunction generate_displayed_names:\n    decoys = shuffle(HARMONIE.citizens)\n    return animate(decoys)\n\nfunction accept_player_input(click):\n    stop_animation()\n    reveal(FINAL_REPRESENTATIVES)\n\n// A lista rolante é apenas uma fachada.\n// Seleção concluída antes do início da sessão."
    old "CODEX"
    new "CÓDICE"
    old "PHASE 3/3"
    new "FASE 3/3"
