translate portuguese strings:

    # Minijogo do rascunho (textos gerados por dados Python).
    old "Toute personne"
    new "Toda pessoa"
    old "doit"
    new "deve"
    old "intervenir"
    new "intervir"
    old "lorsqu'une autre personne"
    new "quando outra pessoa"
    old "est en danger."
    new "está em perigo."
    old "immédiatement"
    new "imediatamente"
    old "peut"
    new "pode"
    old "s'il l'ose"
    new "se tiver coragem"
    old "porter assistance"
    new "prestar assistência"
    old "après autorisation"
    new "após autorização"
    old "si nécessaire"
    new "se necessário"
    old "à une autre personne"
    new "a outra pessoa"
    old "quand c'est permis"
    new "quando permitido"
    old "peut-être"
    new "talvez"
    old "en danger"
    new "em perigo"
    old "sans autorisation préalable."
    new "sem autorização prévia."
    old "dans la limite"
    new "dentro do limite"
    old "sauf refus"
    new "salvo recusa"
    old "si toléré"
    new "se tolerado"

    old "« Toute personne doit intervenir lorsqu'une autre personne est en danger. »"
    new "“Toda pessoa deve intervir quando outra pessoa está em perigo.”"
    old "Doit. Une obligation. Je force la main de tout le monde, d'un seul mot."
    new "Deve. Uma obrigação. Com uma única palavra, forço a mão de todo mundo."
    old "Et si quelqu'un intervient mal ? Si à cause de « doit », on condamne celui qui a hésité ?"
    new "E se alguém intervier mal? E se, por causa de “deve”, condenarmos quem hesitou?"
    old "Non. « Doit », c'est trop. Ça punit autant que ça protège."
    new "Não. “Deve” é demais. Pune tanto quanto protege."
    old "Le mot part. La trace, elle, reste."
    new "A palavra some. A marca fica."
    old "« Immédiatement »... et si c'est trop tard pour bien faire ? Je le retire."
    new "“Imediatamente”... e se já for tarde demais para agir direito? Vou tirar."
    old "« ...peut intervenir... »"
    new "“...pode intervir...”"
    old "Intervenir. Ça sonne comme se jeter dans le feu. Comme un héros."
    new "Intervir. Parece se jogar no fogo. Como um herói."
    old "Personne n'est un héros, ici. On lira ça comme le droit de tout casser au nom du secours."
    new "Ninguém aqui é herói. Vão ler isso como o direito de destruir tudo em nome do resgate."
    old "Encore un mot rayé. La phrase respire un peu moins fort."
    new "Mais uma palavra riscada. A frase respira um pouco mais baixo."
    old "« S'il l'ose »... je ne vais pas leur demander du courage en plus. Non."
    new "“Se tiver coragem”... não vou exigir coragem deles também. Não."
    old "« ...peut porter assistance lorsqu'une autre personne est en danger. »"
    new "“...pode prestar assistência quando outra pessoa está em perigo.”"
    old "« Lorsque ». Comme s'il fallait attendre le bon moment. Attendre l'autorisation du danger lui-même."
    new "“Quando.” Como se fosse preciso esperar o momento certo. Esperar a autorização do próprio perigo."
    old "J'ajoute « après autorisation », machinalement. Ma main écrit ce que la peur dicte."
    new "Acrescento “após autorização” sem pensar. Minha mão escreve o que o medo dita."
    old "...Non. Si on attend l'autorisation, la personne est déjà par terre. Je barre ça aussi."
    new "...Não. Se esperarmos autorização, a pessoa já estará no chão. Risco isso também."
    old "Trop de conditions. Chaque condition est une porte pour dire non."
    new "Condições demais. Cada condição é uma porta para dizer não."
    old "Je gomme la condition. Mes doigts sont gris."
    new "Apago a condição. Meus dedos estão cinzentos."
    old "« Après autorisation ». Voilà. C'est exactement le mot qui tue les gens poliment. Dehors."
    new "“Após autorização.” Pronto. É exatamente assim que se mata alguém com educação. Fora."
    old "« Si nécessaire », qui décide de ça ? Pas moi. Je l'écarte."
    new "“Se necessário”, quem decide isso? Eu não. Vou descartar."
    old "« ...porter assistance à une autre personne est en danger. »"
    new "“...prestar assistência a outra pessoa está em perigo.”"
    old "Ça se lit de travers, maintenant. Tant pis, personne ne relira ma calligraphie."
    new "Agora ficou estranho. Tanto faz, ninguém vai reler minha caligrafia."
    old "« Est en danger. » Lourd. Je veux juste : en danger. Court. Qu'on ne puisse pas l'esquiver."
    new "“Está em perigo.” Pesado. Quero apenas: em perigo. Curto. Impossível de contornar."
    old "La feuille est presque illisible. Moi aussi."
    new "A folha está quase ilegível. Eu também."
    old "« Quand c'est permis »... et si ça ne l'est jamais ? Je raye."
    new "“Quando permitido”... e se nunca for? Vou riscar."
    old "« Peut-être ». Le mot le plus lâche que je connaisse. Dehors."
    new "“Talvez.” A palavra mais covarde que conheço. Fora."
    old "« Toute personne peut porter assistance à une autre personne en danger sans autorisation préalable. »"
    new "“Toda pessoa pode prestar assistência a outra pessoa em perigo sem autorização prévia.”"
    old "Voilà. C'est laid. C'est raturé. Mais ça tient debout."
    new "Pronto. É feio. Está cheio de rasuras. Mas se sustenta."
    old "« Dans la limite »... la limite de quoi ? Non."
    new "“Dentro do limite”... limite de quê? Não."
    old "« Sauf refus ». Toujours une porte de sortie. Je n'en veux plus."
    new "“Salvo recusa.” Sempre uma saída. Não quero mais nenhuma."
    old "« Si toléré ». Non. Plus de permission à mendier."
    new "“Se tolerado.” Não. Chega de implorar por permissão."
    old "Alors. Ma phrase. Une seule ligne, et qu'on n'en parle plus."
    new "Certo. Minha frase. Uma única linha, e não se fala mais nisso."
    old "Les mots sont là, éparpillés autour. Fais-les glisser sur la feuille pour former une phrase."
    new "As palavras estão espalhadas. Arraste-as para a folha para formar uma frase."
    old "Déjà ? Mes mains vont plus lentement que cette horloge."
    new "Já? Minhas mãos são mais lentas que esse relógio."
    old "Ma main cherche la gomme toute seule. Attrape-la, frotte le mot cerclé jusqu'à ce qu'il disparaisse."
    new "Minha mão procura a borracha sozinha. Pegue-a e esfregue a palavra circulada até ela desaparecer."
    old "Je pourrais encore. Enlever « sans autorisation ». Trouver plus doux, plus prudent."
    new "Eu ainda poderia. Tirar “sem autorização”. Encontrar algo mais suave, mais prudente."
    old "Continuer jusqu'à ce que la phrase ne veuille plus rien dire. Jusqu'à ce qu'elle ne gêne plus personne."
    new "Continuar até a frase não significar mais nada. Até não incomodar ninguém."
    old "La gomme est déjà dans ma main."
    new "A borracha já está na minha mão."
    old "Non."
    new "Não."
    old "Je pose la gomme."
    new "Eu largo a borracha."
    old "Pour une fois, je n'efface pas."
    new "Desta vez, eu não apago."
    old "Je repose la gomme sans m'en servir."
    new "Largo a borracha sem usá-la."
    old "Je plie la feuille en deux. De travers, évidemment."
    new "Dobro a folha ao meio. Torto, é claro."

    old "Ecoute chaque argument"
    new "Ouça cada argumento"
    old "Chaque participant parle quelques secondes. La barre jaune indique le temps disponible."
    new "Cada participante fala por alguns segundos. A barra amarela mostra o tempo disponível."
    old "Interviens avec discernement"
    new "Intervenha com discernimento"
    old "Le buzzer sert a prendre la parole quand Noam apporte un vrai eclairage, pas a contredire tout le monde."
    new "Use o botão quando Noam puder acrescentar algo relevante, não para contradizer todo mundo."
    old "Reste coherent"
    new "Mantenha a coerência"
    old "Multiplier les objections affaiblit Noam : l'assemblee juge aussi la coherence de tes interventions."
    new "Objeções demais enfraquecem Noam: a assembleia também avalia a coerência das suas intervenções."

    old "VOTE POUR"
    new "VOTE A FAVOR"
    old "ABSTENTION"
    new "ABSTENÇÃO"
    old "VOTE CONTRE"
    new "VOTE CONTRA"
    old "Changer les règles"
    new "Mudar as regras"
    old "Laisser le système trancher"
    new "Deixar o sistema decidir"
    old "Maintenir le cadre"
    new "Manter as regras atuais"
    old "En attente du premier bulletin..."
    new "Aguardando a primeira cédula..."
    old "Dépouillement en cours..."
    new "Apuração em andamento..."
    old "Amendement refusé : au moins un vote contre."
    new "Emenda rejeitada: pelo menos um voto contra."
    old "Amendement adopté : aucun vote contre."
    new "Emenda aprovada: nenhum voto contra."
