translate portuguese strings:

    old "Couloir de la cafétéria"
    new "Corredor da cafeteria"
    old "Couloir du dortoir"
    new "Corredor do dormitório"
    old "Couloir de l'infirmerie"
    new "Corredor da enfermaria"
    old "Couloir de maintenance"
    new "Corredor da manutenção"
    old "Couloir du SAS"
    new "Corredor da câmara de ar"
    old "Exploration libre"
    new "Exploração livre"
    old "Accès indisponible"
    new "Acesso indisponível"
    old "Parler à Elen"
    new "Falar com Elen"
    old "Parler à Tomas"
    new "Falar com Tomas"
    old "Parler à Julian"
    new "Falar com Julian"
    old "Parler à Mara et Sael"
    new "Falar com Mara e Sael"
    old "Parler à Lysa et Elias"
    new "Falar com Lysa e Elias"
    old "Parler à Sael"
    new "Falar com Sael"
    old "Règlement du Conclave"
    new "Regulamento do Conclave"
    old "Représentant — Conclave"
    new "Representante — Conclave"
    old "Entrer dans la cafétéria"
    new "Entrar na cafeteria"
    old "Entrer dans la salle du canon"
    new "Entrar na sala do canhão"
    old "Entrer dans l'observatoire"
    new "Entrar no observatório"
    old "Entrer dans la salle de repos"
    new "Entrar na sala de descanso"
    old "Aller vers le dortoir"
    new "Ir para o dormitório"
    old "Aller vers la maintenance"
    new "Ir para a manutenção"
    old "Entrer dans la salle d'archive"
    new "Entrar na sala de arquivos"
    old "Entrer dans le Conclave"
    new "Entrar no Conclave"
    old "Entrer dans le dortoir"
    new "Entrar no dormitório"
    old "Aller vers la cafétéria"
    new "Ir para a cafeteria"
    old "Aller vers l'infirmerie"
    new "Ir para a enfermaria"
    old "Entrer dans le gymnase"
    new "Entrar na academia"
    old "Entrer dans l'infirmerie"
    new "Entrar na enfermaria"
    old "Aller vers le SAS"
    new "Ir para a câmara de ar"
    old "Entrer dans la maintenance"
    new "Entrar na manutenção"
    old "Entrer dans le SAS de livraison"
    new "Entrar na câmara de entrega"
    old "Entrer dans la salle de stockage"
    new "Entrar no depósito"
