translate portuguese strings:

    old "TUTORIEL"
    new "TUTORIAL"
    old "{} ANS"
    new "{} ANOS"
    old "%d / 5 tris"
    new "%d / 5 separações"
    old "Le pain va tomber de mon côté."
    new "O pão vai cair do meu lado."
    old "Quelqu'un peut me passer l'eau avant que Julian négocie avec elle ?"
    new "Alguém pode me passar a água antes que Julian negocie com ela?"
    old "La ration chaude, avant qu'elle devienne un concept."
    new "A ração quente, antes que vire um conceito."
    old "Laisse une part au centre. On va éviter le drame diplomatique."
    new "Deixe uma porção no centro. Vamos evitar um incidente diplomático."
    old "Iris lève son verre comme si elle venait de fonder un pays."
    new "Iris ergue o copo como se tivesse acabado de fundar um país."
    old "Le nom de Kami aspire l'air autour de la table."
    new "O nome de Kami suga o ar ao redor da mesa."
    old "Julian prend l'attaque comme une promotion."
    new "Julian recebe a provocação como uma promoção."
    old "La prudence est juste. Elle est aussi lourde."
    new "A prudência é justa. Também é pesada."
    old "Les verres se lèvent. Le silence devient presque une présence invitée."
    new "Os copos se erguem. O silêncio quase se torna um convidado."
    old "Julian proteste trop vite pour être crédible."
    new "Julian protesta rápido demais para ser convincente."
    old "La règle est simple. Tout le monde l'accepte."
    new "A regra é simples. Todos aceitam."
    old "Lysa te regarde, puis accepte cette petite désobéissance."
    new "Lysa olha para você e aceita essa pequena desobediência."
    old "La table retombe dans le réel."
    new "A mesa volta à realidade."
    old "Mauvaise image. Les épaules se tendent."
    new "Imagem ruim. Os ombros ficam tensos."
    old "Julian mime une blessure politique grave."
    new "Julian encena uma grave ferida política."
    old "Il se redresse comme si c'était sérieux. C'est ce qui sauve la blague."
    new "Ele se endireita como se fosse sério. É isso que salva a piada."
    old "Le repas continue. Sans éclat, mais sans casse."
    new "A refeição continua. Sem brilho, mas sem estragos."
    old "La formule lui arrache presque un sourire."
    new "A frase quase arranca um sorriso dela."
    old "Elle te laisse faire. C'est déjà un accord."
    new "Ela deixa você fazer. Isso já é um acordo."
    old "Elle se ferme aussitôt. Mauvais angle."
    new "Ela se fecha imediatamente. Abordagem errada."
    old "Pendant une minute, personne ne dit son nom."
    new "Por um minuto, ninguém diz o nome dela."
    old "La table respire encore un peu."
    new "A mesa respira por mais um pouco."
    old "La blague tient juste assez longtemps pour devenir utile."
    new "A piada dura o bastante para se tornar útil."
    old "Le calme reste là, moins brillant, mais intact."
    new "A calma permanece, menos brilhante, mas intacta."
    old "Le calme se fend. Pas beaucoup. Assez."
    new "A calma racha. Não muito. O bastante."
    old "NORD"
    new "NORTE"
    old "SUD"
    new "SUL"
    old "EST"
    new "LESTE"
    old "OUEST"
    new "OESTE"
    old "{} // VALEUR {} SÉLECTIONNÉE"
    new "{} // VALOR {} SELECIONADO"
    old "{} // CALIBRATION REFUSÉE — SIGNAL INSTABLE"
    new "{} // CALIBRAÇÃO RECUSADA — SINAL INSTÁVEL"
    old "{} // FLUX STABILISÉ"
    new "{} // FLUXO ESTABILIZADO"

    old "SYSTEM"
    new "SISTEMA"
    old "KAMI.CORE  /  INTERFACE LOCALE"
    new "KAMI.CORE  /  INTERFACE LOCAL"
    old "NAVIGATION  ↑ ↓   //   CONFIRMER  ENTRÉE"
    new "NAVEGAÇÃO  ↑ ↓   //   CONFIRMAR  ENTER"
    old "KAMI.CORE // DOSSIERS DES REPRÉSENTANTS"
    new "KAMI.CORE // DOSSIÊS DOS REPRESENTANTES"
    old "REPRÉSENTANT·E DE"
    new "REPRESENTANTE DE"
    old "GARDE-ROBE"
    new "GUARDA-ROUPA"
    old "Les choix équipés sont sauvegardés de façon permanente et appliqués aux sprites en jeu."
    new "As escolhas equipadas são salvas permanentemente e aplicadas aos sprites no jogo."
    old "TENUES"
    new "TRAJES"
    old "VERROUILLÉE — disponible dans la Boutique"
    new "BLOQUEADO — disponível na Loja"
    old "ÉQUIPÉE"
    new "EQUIPADO"
    old "ÉQUIPER"
    new "EQUIPAR"
    old "ACCESSOIRES"
    new "ACESSÓRIOS"
    old "VERROUILLÉ — disponible dans la Boutique"
    new "BLOQUEADO — disponível na Loja"
    old "RETIRER"
    new "REMOVER"
    old "FERMER"
    new "FECHAR"
    old "Médiateur"
    new "Mediador"
    old "Habitante"
    new "Moradora"
    old "Habitant"
    new "Morador"
    old "Ouvrier"
    new "Operário"
    old "Archiviste"
    new "Arquivista"
    old "Ingénieur"
    new "Engenheiro"
    old "Gardien"
    new "Guardião"
    old "Harmonie"
    new "Harmonia"
    old "Axiome"
    new "Axioma"
    old "Archive"
    new "Arquivo"
    old "Orbite"
    new "Órbita"
    old "Limen"
    new "Limen"
    old "14 avril"
    new "14 de abril"
    old "3 septembre"
    new "3 de setembro"
    old "19 janvier"
    new "19 de janeiro"
    old "27 juin"
    new "27 de junho"
    old "8 novembre"
    new "8 de novembro"
    old "22 février"
    new "22 de fevereiro"
    old "5 octobre"
    new "5 de outubro"
    old "16 mai"
    new "16 de maio"
    old "30 décembre"
    new "30 de dezembro"
    old "11 août"
    new "11 de agosto"
    old "7 mars"
    new "7 de março"
    old "24 juillet"
    new "24 de julho"
    old "Comprendre avant de trancher."
    new "Entender antes de decidir."
    old "Une promesse sans procédure n'est qu'un bruit."
    new "Uma promessa sem procedimento é apenas ruído."
    old "Tenir, c'est déjà gagner du temps."
    new "Resistir já é ganhar tempo."
    old "Un repas stable vaut mieux qu'un grand discours."
    new "Uma refeição garantida vale mais que um grande discurso."
    old "Les chiffres mentent moins que nous."
    new "Os números mentem menos que nós."
    old "Le silence est aussi un signal."
    new "O silêncio também é um sinal."
    old "Si ce n'est pas consigné, c'est déjà perdu."
    new "Se não foi registrado, já está perdido."
    old "On compte les vivants, pas les slogans."
    new "Contamos os vivos, não os slogans."
    old "On ne négocie pas avec une turbine en panne."
    new "Não se negocia com uma turbina quebrada."
    old "Le cadre protège de l'arbitraire."
    new "As regras protegem contra o arbítrio."
    old "Le danger n'attend pas les votes."
    new "O perigo não espera votações."
    old "Je vois ce qui entre. Et ce qui disparaît."
    new "Eu vejo o que entra. E o que desaparece."
    old "ÉCLATS DE DÉSIR"
    new "FRAGMENTOS DE DESEJO"
    old "IRIS : TENUE 2"
    new "IRIS: TRAJE 2"
    old "RYN : TENUE 2"
    new "RYN: TRAJE 2"
    old "LYSA : ACCESSOIRE 1"
    new "LYSA: ACESSÓRIO 1"
    old "PRÉVISUALISER"
    new "PRÉ-VISUALIZAR"
    old "OBTENU"
    new "OBTIDO"
    old "OBTENIR"
    new "OBTER"
    old "RÉQUISITIONS DE KAMI"
    new "REQUISIÇÕES DE KAMI"
    old "OFFRES TEMPORAIRES"
    new "OFERTAS TEMPORÁRIAS"
    old "CODE PROMO"
    new "CÓDIGO PROMOCIONAL"
    old "FIN DANS 06 J 14 H"
    new "TERMINA EM 06 D 14 H"
    old "Les réquisitions non obtenues disparaîtront à la fin du cycle."
    new "As requisições não obtidas desaparecerão no fim do ciclo."
    old "PRÉVISUALISATION"
    new "PRÉ-VISUALIZAÇÃO"
    old "Corps, bras, bouche et yeux sont tirés au hasard. La tenue ou l'accessoire sélectionné reste fixe."
    new "Corpo, braços, boca e olhos são sorteados. O traje ou acessório selecionado permanece fixo."
    old "ALÉATOIRE"
    new "ALEATÓRIO"
    old "Saisissez un code pour créditer des récompenses persistantes."
    new "Digite um código para receber recompensas permanentes."
    old "VALIDER"
    new "VALIDAR"
    old "Réquisition introuvable"
    new "Requisição não encontrada"
    old "Objet déjà obtenu"
    new "Item já obtido"
    old "Éclats de désir insuffisants"
    new "Fragmentos de Desejo insuficientes"
    old "Réquisition validée"
    new "Requisição validada"
    old "{}{} Éclats de désir"
    new "{}{} Fragmentos de Desejo"
    old "+{} Éclats de désir"
    new "+{} Fragmentos de Desejo"
    old "Encore humain"
    new "Ainda humano"
    old "Un hasard bien cadré"
    new "Uma coincidência bem enquadrada"

    old "Je termine de ranger les caisses."
    new "Termino de organizar as caixas."
    old "Puis je me rends à la cafétéria."
    new "Depois vou para a cafeteria."
    old "Le repas se déroule sans accroc pendant de longues minutes."
    new "A refeição segue sem problemas por longos minutos."
    old "Une bonne heure plus tard"
    new "Uma boa hora depois"
    old "Après m'être longuement calmé"
    new "Depois de levar um bom tempo para me acalmar"
    old "Après plusieurs heures"
    new "Várias horas depois"
    old "Début du chapitre 2"
    new "Início do Capítulo 2"
    old "Fin du chapitre 2"
    new "Fim do Capítulo 2"

    old "CAFÉTÉRIA"
    new "CAFETERIA"
    old "INFIRMERIE"
    new "ENFERMARIA"
    old "STOCKAGE"
    new "DEPÓSITO"
    old "STOCKAGE • BONUS"
    new "DEPÓSITO • BÔNUS"
    old "ATTRAPEZ"
    new "PEGUE"
    old "Cliquez et maintenez un objet qui défile sur le tapis."
    new "Clique e segure um objeto que passa pela esteira."
    old "TRIEZ"
    new "SEPARE"
    old "Glissez-le au-dessus de la caisse correspondant à sa catégorie."
    new "Arraste-o sobre a caixa correspondente à sua categoria."
    old "ACCÉLÉREZ"
    new "ACELERE"
    old "Cinq tris justes d'affilée accélèrent le tapis et donnent +5."
    new "Cinco separações corretas seguidas aceleram a esteira e dão +5."
    old "BONUS"
    new "BÔNUS"
    old "Les objets de stockage sont plus rares et valent 0 point."
    new "Os itens de depósito são mais raros e valem 0 pontos."
    old "TRI DES LIVRAISONS"
    new "SEPARAÇÃO DE ENTREGAS"
    old "MINI-JEU  •  TRI DES LIVRAISONS"
    new "MINIJOGO  •  SEPARAÇÃO DE ENTREGAS"
    old "ATTRAPEZ • GLISSEZ • DÉPOSEZ AU-DESSUS DE LA BONNE CAISSE"
    new "PEGUE • ARRASTE • SOLTE SOBRE A CAIXA CERTA"
    old "SCORE CALCULÉ"
    new "PONTUAÇÃO CALCULADA"
    old "SÉRIE"
    new "SEQUÊNCIA"
    old "CADENCE"
    new "RITMO"
    old "DÉFILEMENT  >>>"
    new "FLUXO  >>>"
    old "RÈGLES"
    new "REGRAS"
    old "• Bonne caisse :  +1 point\n• Mauvaise caisse :  -1 point et cadence -1\n• Stockage correct :  0 point\n• 5 tris justes : cadence +1\n• Score : points × cadence"
    new "• Caixa correta:  +1 ponto\n• Caixa errada:  -1 ponto e ritmo -1\n• Depósito correto:  0 pontos\n• 5 acertos: ritmo +1\n• Pontuação: pontos × ritmo"
    old "BILAN EN DIRECT"
    new "RELATÓRIO AO VIVO"
    old "Corrects"
    new "Corretos"
    old "Erreurs"
    new "Erros"
    old "Bonus neutres"
    new "Bônus neutros"
    old "Objets passés"
    new "Itens perdidos"
    old "PROCHAINE ACCÉLÉRATION"
    new "PRÓXIMA ACELERAÇÃO"
    old "REPRENDRE"
    new "RETOMAR"
    old "PAUSE"
    new "PAUSA"
    old "TRI EN PAUSE"
    new "SEPARAÇÃO PAUSADA"
    old "Le chronomètre et le tapis sont arrêtés."
    new "O cronômetro e a esteira estão parados."
    old "STOCKAGE BONUS  •  +0"
    new "BÔNUS DE DEPÓSITO  •  +0"
    old "TRI CORRECT  •  +1"
    new "SEPARAÇÃO CORRETA  •  +1"
    old "ACCÉLÉRATION  •  MULTIPLICATEUR x%.2f"
    new "ACELERAÇÃO  •  MULTIPLICADOR x%.2f"
    old "ERREUR  •  -1 POINT  •  CADENCE -1"
    new "ERRO  •  -1 PONTO  •  RITMO -1"
    old "MAUVAISE CAISSE  •  -1 POINT"
    new "CAIXA ERRADA  •  -1 PONTO"
    old "Points bruts"
    new "Pontos brutos"
    old "Multiplicateur final"
    new "Multiplicador final"
    old "Score final"
    new "Pontuação final"
    old "Tris corrects"
    new "Separações corretas"
    old "Meilleure série"
    new "Melhor sequência"
    old "Aucune erreur"
    new "Nenhum erro"
    old "Atteindre la cadence x1.42"
    new "Alcançar ritmo x1.42"

    old "PLATEAU EN CIRCULATION"
    new "BANDEJA EM CIRCULAÇÃO"
    old "Le plateau a survécu au repas."
    new "A bandeja sobreviveu à refeição."
    old "Pain"
    new "Pão"
    old "Eau"
    new "Água"
    old "Ration"
    new "Ração"
    old "Partage"
    new "Compartilhar"
    old "sec"
    new "seco"
    old "stable"
    new "estável"
    old "chaud"
    new "quente"
    old "centre"
    new "centro"
    old "ton"
    new "tom"
    old "piste"
    new "faixa"
    old "Rythme de table"
    new "Ritmo da mesa"
    old "Ratés [j701_plate_errors]"
    new "Erros [j701_plate_errors]"
    old "Le plateau glisse de main en main. Suis la demande avant que la conversation déraille."
    new "A bandeja passa de mão em mão. Siga o pedido antes que a conversa descarrile."
    old "Bon geste. Le repas continue sans accroc."
    new "Bom movimento. A refeição continua sem problemas."
    old "Mauvais objet. Quelqu'un rattrape le plateau au dernier moment."
    new "Item errado. Alguém segura a bandeja no último instante."
    old "Trop lent. La demande se perd dans le bruit de la table."
    new "Lento demais. O pedido se perde no barulho da mesa."
    old "DISCUSSION"
    new "DISCUSSÃO"
    old "Table"
    new "Mesa"
    old "blague"
    new "piada"
    old "relance"
    new "deixa"
    old "calme"
    new "calma"
    old "partage"
    new "partilha"
    old "chemin"
    new "caminho"
    old "Réponds vite. Trop hésiter, c'est déjà laisser le malaise entrer."
    new "Responda rápido. Hesitar demais já deixa o mal-estar entrar."
    old "Noam hésite. La table continue sans lui, un peu moins légère."
    new "Noam hesita. A mesa continua sem ele, um pouco menos leve."
    old "Je veux que ça DUUURE... Si on a enfin une journée sans voix divine, je refuse qu'on la passe à fixer les murs."
    new "Quero que isso DUUURE... Se finalmente temos um dia sem voz divina, me recuso a passá-lo olhando para as paredes."
    old "Alors impose une minute de fête officielle."
    new "Então decrete um minuto oficial de comemoração."
    old "Tu crois vraiment qu'elle est partie ?"
    new "Você realmente acha que ela foi embora?"
    old "Julian peut faire le discours, il adore s'écouter."
    new "Julian pode fazer o discurso. Ele adora se ouvir."
    old "On devrait quand même rester prudents."
    new "Ainda deveríamos ter cuidado."
    old "Minute de fête officielle ? J'aime. Il nous faut un rituel idiot, tout de suite."
    new "Um minuto oficial de comemoração? Gostei. Precisamos de um ritual idiota agora."
    old "Lever les verres à la santé du silence."
    new "Erguer os copos à saúde do silêncio."
    old "Déclarer Julian mascotte temporaire."
    new "Declarar Julian mascote temporário."
    old "Proposer une minute sans parler de Kami."
    new "Propor um minuto sem falar de Kami."
    old "Partie ? Non. C'est justement ça qui me gêne. Elle ne disparaît pas. Elle attend."
    new "Foi embora? Não. É justamente isso que me incomoda. Ela não desaparece. Ela espera."
    old "Alors on lui vole six minutes."
    new "Então roubamos seis minutos dela."
    old "Tu as raison, ça sent mauvais."
    new "Você tem razão. Tem algo errado."
    old "Peut-être qu'elle nous écoute paniquer."
    new "Talvez ela esteja ouvindo nosso pânico."
    old "Je peux improviser un discours historique. Court, brillant, indispensable."
    new "Posso improvisar um discurso histórico. Curto, brilhante, indispensável."
    old "Trois mots maximum."
    new "No máximo três palavras."
    old "Vas-y, président de la table."
    new "Vai em frente, presidente da mesa."
    old "Non. On mange."
    new "Não. Vamos comer."
    old "Merci. Je sais que je casse l'ambiance, mais je n'arrive pas à trouver ça normal."
    new "Obrigada. Sei que estou estragando o clima, mas não consigo achar isso normal."
    old "Tu ne casses rien. Tu vérifies les murs."
    new "Você não está estragando nada. Está verificando as paredes."
    old "Alors laisse-moi casser l'ambiance à ta place."
    new "Então deixe que eu estrague o clima por você."
    old "Tu stresses pour rien."
    new "Você está se preocupando à toa."
    old "CANON // SYNCHRONISATION DES FLUX"
    new "CÂNON // SINCRONIZAÇÃO DOS FLUXOS"
    old "Isole la dernière valeur stable de chaque flux régional."
    new "Isole o último valor estável de cada fluxo regional."
    old "SIGNAL MONDIAL INSTABLE"
    new "SINAL GLOBAL INSTÁVEL"
    old "SIGNAL MONDIAL STABILISÉ"
    new "SINAL GLOBAL ESTABILIZADO"
    old "SIGNAL PARTIEL // %d / 4"
    new "SINAL PARCIAL // %d / 4"
    old "FLUX STABILISÉ"
    new "FLUXO ESTABILIZADO"
    old "CALIBRER"
    new "CALIBRAR"
    old "ANALYSE TERMINÉE"
    new "ANÁLISE CONCLUÍDA"
    old "EXÉCUTIONS RECENSÉES — DERNIÈRES 24 HEURES"
    new "EXECUÇÕES REGISTRADAS — ÚLTIMAS 24 HORAS"
    old "TOTAL MONDIAL : 0"
    new "TOTAL GLOBAL: 0"
    old "DERNIÈRE EXÉCUTION ENREGISTRÉE : HIER — 18 H 42"
    new "ÚLTIMA EXECUÇÃO REGISTRADA: ONTEM — 18:42"
    old "QUITTER LE CANON"
    new "SAIR DO CÂNON"
    old "Stabilise chaque flux pour reconstituer le bilan mondial."
    new "Estabilize cada fluxo para reconstruir o relatório global."
    old "[j701_console_locked_count()] / 4 FLUX STABILISÉS"
    new "[j701_console_locked_count()] / 4 FLUXOS ESTABILIZADOS"
    old "NETTOYER LE BUREAU"
    new "LIMPAR A MESA"
    old "Balaye les particules avant qu'elles se multiplient. Le dessin n'apparaît nulle part."
    new "Varra as partículas antes que se multipliquem. O desenho não aparece em lugar nenhum."
    old "Nettoyé [j701_clean_score]/12"
    new "Limpo [j701_clean_score]/12"
    old "Trace révélée"
    new "Traço revelado"
    old "Balaye les poussières avant qu'elles se multiplient."
    new "Varra a poeira antes que ela se multiplique."
    old "La poussière éclate en silence."
    new "A poeira se desfaz em silêncio."
    old "Le parasite se désagrège sous le balai."
    new "A interferência se desfaz sob a vassoura."
    old "La poussière se divise. Le bureau refuse de rester propre."
    new "A poeira se divide. A mesa se recusa a ficar limpa."

    old "PHASE D'ENQUÊTE"
    new "FASE DE INVESTIGAÇÃO"
    old "5 TOURS  /  10 PISTES  /  UNE SEULE NUIT"
    new "5 TURNOS  /  10 PISTAS  /  UMA ÚNICA NOITE"
    old "Choisis où consacrer ton temps. Les pistes abandonnées seront perdues."
    new "Escolha onde investir seu tempo. As pistas abandonadas serão perdidas."
    old "DOSSIER 07-A  //  CHOISIR UN LIEU"
    new "DOSSIÊ 07-A  //  ESCOLHER UM LOCAL"
    old "LE CONTENU DES SALLES RESTE INCONNU TANT QUE TU NE L'EXAMINES PAS"
    new "O CONTEÚDO DAS SALAS PERMANECE DESCONHECIDO ATÉ VOCÊ EXAMINÁ-LO"
    old "TOUR [j701_investigation_turn + 1] / [J701_INVESTIGATION_MAX_TURNS]"
    new "TURNO [j701_investigation_turn + 1] / [J701_INVESTIGATION_MAX_TURNS]"
    old "Entrer dans une salle est gratuit. Seul un indice collecté consomme un tour."
    new "Entrar em uma sala é grátis. Apenas coletar uma pista consome um turno."
    old "<  RETOUR AU PLAN"
    new "<  VOLTAR AO MAPA"
    old "FRAGMENT DE PREUVE OBTENU"
    new "FRAGMENTO DE PROVA OBTIDO"
    old "DOSSIER PROVISOIRE"
    new "DOSSIÊ PROVISÓRIO"
    old "5 fragments récupérés  //  5 pistes abandonnées"
    new "5 fragmentos recuperados  //  5 pistas abandonadas"
    old "REJOINDRE LE DÉBRIEF  >"
    new "IR PARA A REUNIÃO  >"
    old "POINT D'INTÉRÊT"
    new "PONTO DE INTERESSE"
    old "POINTS D'INTÉRÊT"
    new "PONTOS DE INTERESSE"
    old "PLUS RIEN À EXAMINER"
    new "NADA MAIS PARA EXAMINAR"
    old "Reprendre les témoignages"
    new "Rever os depoimentos"
    old "Reconstituer le prélèvement"
    new "Reconstituir a retirada"
    old "Chercher ce qui a été fabriqué"
    new "Procurar o que foi fabricado"
    old "Interroger les images"
    new "Investigar as imagens"
    old "SAS DE LIVRAISON"
    new "ECLUSA DE ENTREGA"
    old "Suivre le trajet du matériel"
    new "Rastrear o trajeto do material"
    old "Interroger Elias"
    new "Interrogar Elias"
    old "Examiner la table"
    new "Examinar a mesa"
    old "Inspecter les emplacements vides"
    new "Inspecionar os espaços vazios"
    old "Consulter le boîtier de porte"
    new "Consultar o terminal da porta"
    old "Regarder sous l'établi"
    new "Olhar sob a bancada"
    old "Étudier le plan de travail"
    new "Estudar a superfície de trabalho"
    old "Surprendre Kael"
    new "Surpreender Kael"
    old "Accéder aux logs de sécurité"
    new "Acessar os registros de segurança"
    old "Suivre les marques"
    new "Seguir as marcas"
    old "Écouter le terminal"
    new "Escutar o terminal"
    old "LA DERNIÈRE VISITE"
    new "A ÚLTIMA VISITA"
    old "Elias a manipulé les quatre objets hier soir. À 23 h 47, ils étaient encore tous à leur place."
    new "Elias manuseou os quatro objetos ontem à noite. Às 23:47, todos ainda estavam em seus lugares."
    old "LA GRUE D'ARGENT"
    new "O TSURU DE PRATA"
    old "Un origami en emballage de ration était pris dans une roue du chariot. Elen en plie souvent, mais les laisse sur toutes les tables."
    new "Um origami feito com embalagem de ração estava preso na roda do carrinho. Elen costuma dobrá-los, mas os deixa em todas as mesas."
    old "LE POIDS FANTÔME"
    new "O PESO FANTASMA"
    old "Les batteries ont été remplacées par des poches d'eau du même poids afin de tromper le capteur de l'étagère."
    new "As baterias foram trocadas por bolsas de água do mesmo peso para enganar o sensor da prateleira."
    old "LE REÇU SANS NOM"
    new "O RECIBO SEM NOME"
    old "Le terminal a bien autorisé un retrait à 02 h 14, mais la case réservée à l'identité contient seulement un caractère impossible."
    new "O terminal autorizou uma retirada às 02:14, mas o campo de identidade contém apenas um caractere impossível."
    old "LE CHEVEU COUPÉ"
    new "O CABELO CORTADO"
    old "Un cheveu brun et assez court était coincé dans l'établi. Son extrémité est tranchée net et il ne porte aucune racine."
    new "Um cabelo castanho e curto estava preso na bancada. Sua ponta foi cortada com precisão e não há raiz."
    old "LE PLAN EN NÉGATIF"
    new "O PROJETO EM NEGATIVO"
    old "La limaille magnétique dessine la silhouette d'un adaptateur fabriqué ici, emporté ensuite, et dont le plan a été soigneusement effacé."
    new "A limalha magnética revela o contorno de um adaptador fabricado aqui e levado depois, cujo projeto foi cuidadosamente apagado."
    old "LA REQUÊTE DE KAEL"
    new "A CONSULTA DE KAEL"
    old "Kael tente seul d'entrer dans la base des caméras et masque sa requête lorsque Noam approche."
    new "Kael tenta acessar sozinho o banco de câmeras e esconde sua consulta quando Noam se aproxima."
    old "LE LOG DE 02 H 34"
    new "O REGISTRO DAS 02:34"
    old "Les logs de sécurité indiquent que la porte de la maintenance s'est ouverte à 02 h 34, sans enregistrer l'identité de l'utilisateur."
    new "Os registros de segurança mostram que a porta da manutenção abriu às 02:34 sem registrar a identidade do usuário."
    old "LES TRACES VERTICALES"
    new "AS MARCAS VERTICAIS"
    old "Les marques du chariot quittent le sol et continuent sur une porte. La cargaison a été fixée à un plateau magnétique."
    new "As marcas do carrinho saem do chão e continuam por uma porta. A carga foi presa a uma plataforma magnética."
    old "L'ÉCHO IMPOSSIBLE"
    new "O ECO IMPOSSÍVEL"
    old "Le micro du sas a enregistré deux bips de la même porte séparés de sept secondes, alors que son verrou exige douze secondes."
    new "O microfone da eclusa registrou dois bipes da mesma porta com sete segundos de intervalo, embora a trava exija doze segundos."
