translate portuguese strings:

    old "Tous"
    new "Todos"
    old "Jours"
    new "Dias"
    old "Votes"
    new "Votações"
    old "Routes"
    new "Rotas"
    old "Scènes importantes"
    new "Cenas importantes"
    old "Développement / Debug"
    new "Desenvolvimento / Debug"
    old "En cours"
    new "Em andamento"
    old "Terminé"
    new "Concluído"
    old "Accès autorisé"
    new "Acesso autorizado"
    old "Nœud narratif verrouillé"
    new "Nó narrativo bloqueado"
    old "Données non découvertes"
    new "Dados não descobertos"
    old "Statut inconnu"
    new "Estado desconhecido"
    old "Kami refuse l'accès à ce fragment. Continuez la chronologie pour l'identifier."
    new "Kami nega acesso a este fragmento. Continue a cronologia para identificá-lo."
    old "Résumé à compléter."
    new "Resumo pendente."
    old "En cours / disponible"
    new "Em andamento / disponível"
    old "Route alternative"
    new "Rota alternativa"
    old "Verrouillé"
    new "Bloqueado"

    old "Jour 0 — Sélection"
    new "Dia 0 — Seleção"
    old "Kami interrompt une réunion ordinaire et impose le Conclave orbital comme nouveau centre de décision."
    new "Kami interrompe uma reunião comum e impõe o Conclave orbital como novo centro decisório."
    old "Acceptation forcée du protocole Kami's Desires."
    new "Aceitação forçada do protocolo Kami's Desires."
    old "Noam est extrait vers le Conclave."
    new "Noam é levado ao Conclave."
    old "Jour 1 — Réveil au Conclave"
    new "Dia 1 — Despertar no Conclave"
    old "Les représentants découvrent le Conclave, ses salles et les règles d'unanimité imposées par Kami."
    new "Os representantes descobrem o Conclave, suas salas e as regras de unanimidade impostas por Kami."
    old "Premiers repères, premières alliances, premières méfiances."
    new "Primeiras referências, primeiras alianças, primeiras desconfianças."
    old "Le cycle des amendements est lancé."
    new "O ciclo de emendas começa."
    old "Jour 2 — Installation"
    new "Dia 2 — Instalação"
    old "Le premier amendement sur le commerce interdistrict est annoncé. Les intérêts de chaque district remontent."
    new "A primeira emenda sobre o comércio entre distritos é anunciada. Os interesses de cada distrito vêm à tona."
    old "Observer les positions avant le premier vote."
    new "Observar as posições antes da primeira votação."
    old "Le débat sur le commerce devient inévitable."
    new "O debate sobre o comércio se torna inevitável."
    old "Jour 3 — Premier débat"
    new "Dia 3 — Primeiro debate"
    old "Le Conclave approche du vote sur le commerce. Les tensions politiques deviennent impossibles à cacher."
    new "O Conclave se aproxima da votação sobre o comércio. As tensões políticas já não podem ser ocultadas."
    old "Soutien, opposition ou prudence face à l'amendement."
    new "Apoio, oposição ou prudência diante da emenda."
    old "Le vote peut ouvrir une nouvelle route ou maintenir le statu quo."
    new "A votação pode abrir uma nova rota ou manter o status quo."
    old "Débat — Texte fragmenté"
    new "Debate — Texto fragmentado"
    old "Débat I"
    new "Debate I"
    old "L'amendement est présenté sous une forme instable. Les représentants tentent de reconstituer le sens politique du texte."
    new "A emenda aparece de forma instável. Os representantes tentam reconstruir seu sentido político."
    old "Identifier les arguments utiles au vote."
    new "Identificar os argumentos relevantes para a votação."
    old "Le rapport de forces se précise."
    new "A correlação de forças fica mais clara."
    old "Vote — Commerce libre"
    new "Votação — Livre comércio"
    old "Le Conclave vote sur l'autorisation du commerce, du transport et du stockage des marchandises."
    new "O Conclave vota a autorização do comércio, transporte e armazenamento de mercadorias."
    old "Voter pour, voter contre, ou laisser l'abstention agir."
    new "Votar a favor, votar contra ou deixar a abstenção decidir."
    old "Le résultat divise la chronologie en deux routes."
    new "O resultado divide a cronologia em duas rotas."
    old "Route — Statu quo"
    new "Rota — Status quo"
    old "Le commerce échoue. Le Conclave conserve l'ordre existant, mais la frustration politique s'accumule."
    new "O comércio fracassa. O Conclave mantém a ordem existente, mas a frustração política se acumula."
    old "Refus ou blocage de l'amendement commerce."
    new "Rejeição ou bloqueio da emenda comercial."
    old "Jour 4 suit la route de l'échec du vote."
    new "O Dia 4 segue a rota da votação fracassada."
    old "Route — Commerce adopté"
    new "Rota — Comércio aprovado"
    old "Le commerce est adopté. Nexus et Orbite s'organisent, tandis que Limen vacille."
    new "O comércio é aprovado. Nexus e Orbite se organizam enquanto Limen vacila."
    old "Adoption de l'amendement commerce."
    new "Aprovação da emenda comercial."
    old "Jour 4 suit la route du commerce ouvert."
    new "O Dia 4 segue a rota do comércio aberto."
